### ISSUE TITLE
spacewalk-common-channels internal exception

### ISSUE THREAD

**Issue by megamaced** [uyuni-project/uyuni#1203]
Running latest RPMs from Uyuni/Master

Can't seem to add any channels via spacewalk-common-channels

```
sudo /usr/bin/spacewalk-common-channels -u admin -p PASSWORD -a x86_64 'opensuse_leap42_3'
ERROR: opensuse_leap42_3-x86_64: redstone.xmlrpc.XmlRpcFault: unhandled internal exception: null
```

```
[2019-07-30 12:36:05,662] ERROR - REQUESTED FROM: ::1 CALL: channel.software.getDetails(admin, opensuse_leap42_3-x86_64) CALLER: (admin) TIME: 0.009 seconds
redstone.xmlrpc.XmlRpcFault: No such channel: opensuse_leap42_3-x86_64
        at com.redhat.rhn.frontend.xmlrpc.BaseHandler.invoke(BaseHandler.java:174)
        at redstone.xmlrpc.XmlRpcDispatcher.dispatch(XmlRpcDispatcher.java:123)
        at com.redhat.rhn.frontend.xmlrpc.RhnXmlRpcServer.execute(RhnXmlRpcServer.java:54)
        at com.redhat.rhn.frontend.xmlrpc.XmlRpcServlet.doPost(XmlRpcServlet.java:162)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.opensymphony.module.sitemesh.filter.PageFilter.parsePage(PageFilter.java:142)
        at com.opensymphony.module.sitemesh.filter.PageFilter.doFilter(PageFilter.java:58)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.redhat.rhn.frontend.servlets.LocalizedEnvironmentFilter.doFilter(LocalizedEnvironmentFilter.java:71)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.redhat.rhn.frontend.servlets.EnvironmentFilter.doFilter(EnvironmentFilter.java:103)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.redhat.rhn.frontend.servlets.SessionFilter.doFilter(SessionFilter.java:55)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.redhat.rhn.frontend.servlets.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:97)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:394)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:834)
[2019-07-30 12:36:05,700] INFO  - REQUESTED FROM: ::1 CALL: channel.software.create(admin, opensuse_leap42_3-x86_64, openSUSE Leap 42.3 (x86_64), openSUSE Leap 42.3 (x86_64), channel-x86_64, , sha256, {fingerprint=22C0 7BA5 3417 8CD0 2EFE  22AA B88B 2FD4 3DBD C284, id=3DBDC284, url=http://download.opensuse.org/distribution/leap/42.3/repo/oss/suse/repodata/repomd.xml.key}) CALLER: (admin) TIME: 0.027 seconds
[2019-07-30 12:36:05,714] ERROR - REQUESTED FROM: ::1 CALL: channel.software.createRepo(admin, External - openSUSE Leap 42.3 (x86_64), , http://download.opensuse.org/distribution/leap/42.3/repo/oss/suse/) CALLER: (admin) TIME: 0.007 seconds
redstone.xmlrpc.XmlRpcFault: unhandled internal exception: null
        at com.redhat.rhn.frontend.xmlrpc.BaseHandler.invoke(BaseHandler.java:186)
        at redstone.xmlrpc.XmlRpcDispatcher.dispatch(XmlRpcDispatcher.java:123)
        at com.redhat.rhn.frontend.xmlrpc.RhnXmlRpcServer.execute(RhnXmlRpcServer.java:54)
        at com.redhat.rhn.frontend.xmlrpc.XmlRpcServlet.doPost(XmlRpcServlet.java:162)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.opensymphony.module.sitemesh.filter.PageFilter.parsePage(PageFilter.java:142)
        at com.opensymphony.module.sitemesh.filter.PageFilter.doFilter(PageFilter.java:58)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.redhat.rhn.frontend.servlets.LocalizedEnvironmentFilter.doFilter(LocalizedEnvironmentFilter.java:71)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.redhat.rhn.frontend.servlets.EnvironmentFilter.doFilter(EnvironmentFilter.java:103)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.redhat.rhn.frontend.servlets.SessionFilter.doFilter(SessionFilter.java:55)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.redhat.rhn.frontend.servlets.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:97)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:394)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by juliogonzalez** [comment]
Confirmed. I can reproduce on the CI instance, not just for Leap 42.3, but for Leap 15.0 and 15.1 as well.

It seems the channel gets created, but something fails:
```
uyuni-master-srv:~ # sudo /usr/bin/spacewalk-common-channels -u admin -p admin -a x86_64 'opensuse_leap15_0'
ERROR: opensuse_leap15_0-x86_64: redstone.xmlrpc.XmlRpcFault: unhandled internal exception: null
uyuni-master-srv:~ # sudo /usr/bin/spacewalk-common-channels -u admin -p admin -a x86_64 opensuse_leap15_0
WARNING: opensuse_leap15_0-x86_64: redstone.xmlrpc.XmlRpcFault: The channel name 'openSUSE Leap 15.0 (x86_64)' is already in use, please enter a different name
```

This is from `rhn_web_api.log`:
```
[2019-07-30 22:13:16,389] ERROR - REQUESTED FROM: ::1 CALL: channel.software.getDetails(admin, opensuse_leap15_0-x86_64) CALLER: (admin) TIME: 0.008 seconds
redstone.xmlrpc.XmlRpcFault: No such channel: opensuse_leap15_0-x86_64
```

Nothing strange at `rhn_server_xmlrpc.log`.

@cbbayburt we'll need to have a look tomorrow, to get this fixed for 4.0.2.

Somehow this seems to be related to RPM channels (I am able to reproduce this for CentOS as well channels), as I can also reproduce this problem at an instance where I could test adding the Ubuntu channels without any issue.

Maybe something related to GPG?

**Comment by juliogonzalez** [comment]
I can see the channels I added yesterday at the WebUI. For example:

![image](https://user-images.githubusercontent.com/4226070/62191707-5549f800-b374-11e9-87cc-fcb175c6b414.png)

**Comment by juliogonzalez** [comment]
Adding Debian works, adding Fedora does not:
```
uyuni-server:~ # spacewalk-common-channels debian-10-pool-amd64
SUSE Manager username: admin
SUSE Manager password: 

uyuni-server:~ # spacewalk-common-channels fedora28
SUSE Manager username: admin
SUSE Manager password: 
ERROR: fedora28-i386: redstone.xmlrpc.XmlRpcFault: unhandled internal exception: null
```

**Comment by juliogonzalez** [comment]
Adding fedora27, this is the output of running `tail /var/log/tomcat* and /var/log/rhn*`: 
[log.txt](https://github.com/uyuni-project/uyuni/files/3450409/log.txt)

**Comment by cbbayburt** [comment]
```
Connecting to http://localhost/rpc/api
Base channel 'openSUSE Leap 42.3 (x86_64)' - creating...
* label=opensuse_leap42_3-x86_64, summary=openSUSE Leap 42.3 (x86_64), arch=x86_64, repo_type=, checksum=sha256
ERROR: opensuse_leap42_3-x86_64: redstone.xmlrpc.XmlRpcFault: unhandled internal exception: null
```

The verbose output shows that the `repo_type` is sent empty to the API for RPM channels. This is causing the problem at repository creation. The channel gets created, but the code crashes when trying to create the repository.

I'll post a patch for `spacewalk-common-channels` soon.

We'll need more explanatory error messages as well.

**Comment by cbbayburt** [comment]
I've opened https://github.com/uyuni-project/uyuni/pull/1208 for the fix.

There's one more thing which worries me. The code goes through the list of available channels and checks if any of them exists. It does this check by calling `software.channel.getDetails`. If this call returns an error, then it means the channel does not exist.

However, his method logs a stack trace to the API log if the channel cannot be found. So the first error in the API log above (`redstone.xmlrpc.XmlRpcFault: No such channel: opensuse_leap42_3-x86_64`) is actually part of the normal execution and should not be logged at all.

I'll create an additional issue to fix the error messages.

**Comment by juliogonzalez** [comment]
Just for reference, verified on my test server:
```
uyuni-server:~ # sudo /usr/bin/spacewalk-common-channels -u admin -p admin -a x86_64 'opensuse_leap42_3'
uyuni-server:~ # 
``` 
Thanks again @cbbayburt :-)
