### ISSUE TITLE
Uyuni 4.0.2 Could not connect to search server.

### ISSUE THREAD

**Issue by hunter86bg** [uyuni-project/uyuni#1248]
This is a fresh install of Uyuni 4.0.2
The rhn-search.service dies immediately with: 
```
Aug 07 06:39:50 uyuni systemd[1]: Started Spacewalk search engine.
Aug 07 06:39:50 uyuni rhn-search[28354]: Sourcing config file...
Aug 07 06:39:51 uyuni rhn-search[28354]: Exception in thread "Thread-0" java.lang.NoClassDefFoundError: org/apache/lucene/queryParser/ParseException
Aug 07 06:39:51 uyuni rhn-search[28354]:         at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
Aug 07 06:39:51 uyuni rhn-search[28354]:         at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
Aug 07 06:39:51 uyuni rhn-search[28354]:         at java.base/java.lang.Class.getDeclaredConstructors(Class.java:2357)
Aug 07 06:39:51 uyuni rhn-search[28354]:         at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$3.run(ConstructorInjectionComponentAdapter.java:286)
Aug 07 06:39:51 uyuni rhn-search[28354]:         at java.base/java.security.AccessController.doPrivileged(Native Method)
Aug 07 06:39:51 uyuni rhn-search[28354]:         at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getConstructors(ConstructorInjectionComponentAdapter.java:284)
Aug 07 06:39:51 uyuni rhn-search[28354]:         at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getSortedMatchingConstructors(ConstructorInjectionComponentAdapter.java:264)
Aug 07 06:39:51 uyuni rhn-search[28354]:         at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getGreediestSatisfiableConstructor(ConstructorInjectionComponentAdapter.java:148)
Aug 07 06:39:51 uyuni rhn-search[28354]:         at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:210)
Aug 07 06:39:51 uyuni rhn-search[28354]:         at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
Aug 07 06:39:51 uyuni rhn-search[28354]:         at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
Aug 07 06:39:51 uyuni rhn-search[28354]:         at org.picocontainer.defaults.DecoratingComponentAdapter.getComponentInstance(DecoratingComponentAdapter.java:60)
Aug 07 06:39:51 uyuni rhn-search[28354]:         at org.picocontainer.defaults.CachingComponentAdapter.getComponentInstance(CachingComponentAdapter.java:58)
Aug 07 06:39:51 uyuni rhn-search[28354]:         at org.picocontainer.defaults.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:393)
Aug 07 06:39:51 uyuni rhn-search[28354]:         at org.picocontainer.defaults.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:374)
Aug 07 06:39:51 uyuni rhn-search[28354]:         at org.picocontainer.defaults.BasicComponentParameter.resolveInstance(BasicComponentParameter.java:77)
Aug 07 06:39:51 uyuni rhn-search[28354]:         at org.picocontainer.defaults.ComponentParameter.resolveInstance(ComponentParameter.java:114)
Aug 07 06:39:51 uyuni rhn-search[28354]:         at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getConstructorArguments(ConstructorInjectionComponentAdapter.java:257)
Aug 07 06:39:51 uyuni rhn-search[28354]:         at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:217)
Aug 07 06:39:51 uyuni rhn-search[28354]:         at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
Aug 07 06:39:51 uyuni rhn-search[28354]:         at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
Aug 07 06:39:51 uyuni rhn-search[28354]:         at org.picocontainer.defaults.DecoratingComponentAdapter.getComponentInstance(DecoratingComponentAdapter.java:60)
Aug 07 06:39:51 uyuni rhn-search[28354]:         at org.picocontainer.defaults.CachingComponentAdapter.getComponentInstance(CachingComponentAdapter.java:58)
Aug 07 06:39:51 uyuni rhn-search[28354]:         at org.picocontainer.defaults.DefaultPicoContainer$OrderedComponentAdapterLifecycleManager.start(DefaultPicoContainer.java:644)
Aug 07 06:39:51 uyuni rhn-search[28354]:         at org.picocontainer.defaults.DefaultPicoContainer.start(DefaultPicoContainer.java:456)
Aug 07 06:39:51 uyuni rhn-search[28354]:         at com.redhat.satellite.search.ContainerRunner.run(ContainerRunner.java:42)
Aug 07 06:39:51 uyuni rhn-search[28354]:         at java.base/java.lang.Thread.run(Thread.java:834)
Aug 07 06:39:51 uyuni rhn-search[28354]: Caused by: java.lang.ClassNotFoundException: org.apache.lucene.queryParser.ParseException
Aug 07 06:39:51 uyuni rhn-search[28354]:         at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
Aug 07 06:39:51 uyuni rhn-search[28354]:         at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
Aug 07 06:39:51 uyuni rhn-search[28354]:         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
Aug 07 06:39:51 uyuni rhn-search[28354]:         ... 27 more
```
```
uyuni:~ # bash -x /usr/sbin/rhn-search
+ echo 'Sourcing config file...'
Sourcing config file...
+ . /usr/share/rhn/config-defaults/rhn_search_daemon.conf
++ SEARCH_LIBRARY_PATH=/usr/lib:/usr/lib64:/usr/lib/gcj/postgresql-jdbc:/usr/lib64/gcj/postgresql-jdbc
++ SEARCH_RHN_CLASSPATH=/usr/share/rhn/classes:/usr/share/nutch-core:/usr/share/nutch-core/conf
++ SEARCH_RHN_JARS=/usr/share/rhn/lib/spacewalk-asm.jar:/usr/share/rhn/lib/rhn.jar:/usr/share/rhn/lib/java-branding.jar
++ SEARCH_JARS='/usr/share/rhn/search/lib/*'
++ SEARCH_INIT_MEMORY=32
++ SEARCH_MAX_MEMORY=96
+ SEARCH_CLASSPATH='/usr/share/rhn/search/lib/*:/usr/share/rhn/classes:/usr/share/nutch-core:/usr/share/nutch-core/conf:/usr/share/rhn/lib/spacewalk-asm.jar:/usr/share/rhn/lib/rhn.jar:/usr/share/rhn/lib/java-branding.jar'
+ SEARCH_PARAMS='-Dfile.encoding=UTF-8 -Xms32m -Xmx96m'
+ JAVACMD='/usr/bin/java -Djava.library.path=/usr/lib:/usr/lib64:/usr/lib/gcj/postgresql-jdbc:/usr/lib64/gcj/postgresql-jdbc -classpath /usr/share/rhn/search/lib/*:/usr/share/rhn/classes:/usr/share/nutch-core:/usr/share/nutch-core/conf:/usr/share/rhn/lib/spacewalk-asm.jar:/usr/share/rhn/lib/rhn.jar:/usr/share/rhn/lib/java-branding.jar -Dfile.encoding=UTF-8 -Xms32m -Xmx96m'
+ [[ 0 -eq 0 ]]
+ /usr/bin/java -Djava.library.path=/usr/lib:/usr/lib64:/usr/lib/gcj/postgresql-jdbc:/usr/lib64/gcj/postgresql-jdbc -classpath '/usr/share/rhn/search/lib/*:/usr/share/rhn/classes:/usr/share/nutch-core:/usr/share/nutch-core/conf:/usr/share/rhn/lib/spacewalk-asm.jar:/usr/share/rhn/lib/rhn.jar:/usr/share/rhn/lib/java-branding.jar' -Dfile.encoding=UTF-8 -Xms32m -Xmx96m com.redhat.satellite.search.Main
Exception in thread "Thread-0" java.lang.NoClassDefFoundError: org/apache/lucene/index/CorruptIndexException
        at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
        at java.base/java.lang.Class.getDeclaredConstructors(Class.java:2357)
        at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$3.run(ConstructorInjectionComponentAdapter.java:286)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getConstructors(ConstructorInjectionComponentAdapter.java:284)
        at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getSortedMatchingConstructors(ConstructorInjectionComponentAdapter.java:264)
        at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getGreediestSatisfiableConstructor(ConstructorInjectionComponentAdapter.java:148)
        at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:210)
        at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
        at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
        at org.picocontainer.defaults.DecoratingComponentAdapter.getComponentInstance(DecoratingComponentAdapter.java:60)
        at org.picocontainer.defaults.CachingComponentAdapter.getComponentInstance(CachingComponentAdapter.java:58)
        at org.picocontainer.defaults.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:393)
        at org.picocontainer.defaults.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:374)
        at org.picocontainer.defaults.BasicComponentParameter.resolveInstance(BasicComponentParameter.java:77)
        at org.picocontainer.defaults.ComponentParameter.resolveInstance(ComponentParameter.java:114)
        at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getConstructorArguments(ConstructorInjectionComponentAdapter.java:257)
        at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:217)
        at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
        at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
        at org.picocontainer.defaults.DecoratingComponentAdapter.getComponentInstance(DecoratingComponentAdapter.java:60)
        at org.picocontainer.defaults.CachingComponentAdapter.getComponentInstance(CachingComponentAdapter.java:58)
        at org.picocontainer.defaults.DefaultPicoContainer$OrderedComponentAdapterLifecycleManager.start(DefaultPicoContainer.java:644)
        at org.picocontainer.defaults.DefaultPicoContainer.start(DefaultPicoContainer.java:456)
        at com.redhat.satellite.search.ContainerRunner.run(ContainerRunner.java:42)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: org.apache.lucene.index.CorruptIndexException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 27 more
```
```
uyuni:~ # systemctl status rhn-search
● rhn-search.service - Spacewalk search engine
   Loaded: loaded (/usr/lib/systemd/system/rhn-search.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Wed 2019-08-07 08:15:44 EEST; 6s ago
  Process: 20375 ExecStart=/usr/sbin/rhn-search (code=exited, status=0/SUCCESS)
 Main PID: 20375 (code=exited, status=0/SUCCESS)
```
Another interesting fact is that the exit code of the systemd service is '0'.

**Comment by mcalmer** [comment]
Please check if you have all packages installed. In this case the class should be part of the "lucene" and "lucene-queryparser" package.

**Comment by hunter86bg** [comment]
The only installed is:
```
uyuni:~ # rpm -qa | grep -i lucene
lucene-6.6.0-lp151.2.2.noarch
```

I have installed 'lucene-queryparser' but the issue is still existing:
```
uyuni:~ # zypper install lucene-queryparser
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following NEW package is going to be installed:
  lucene-queryparser

1 new package to install.
Overall download size: 350.0 KiB. Already cached: 0 B. After the operation, additional 394.1 KiB will be used.
Continue? [y/n/v/...? shows all options] (y): y
Retrieving package lucene-queryparser-6.6.0-lp151.2.2.noarch                                                                                                                                            (1/1), 350.0 KiB (394.1 KiB unpacked)
Retrieving: lucene-queryparser-6.6.0-lp151.2.2.noarch.rpm ...............................................................................................................................................................[done (133.3 KiB/s)]
Checking for file conflicts: ..........................................................................................................................................................................................................[done]
(1/1) Installing: lucene-queryparser-6.6.0-lp151.2.2.noarch ...........................................................................................................................................................................[done]
uyuni:~ # systemctl restart rhn-search
uyuni:~ # systemctl status rhn-search
● rhn-search.service - Spacewalk search engine
   Loaded: loaded (/usr/lib/systemd/system/rhn-search.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Wed 2019-08-07 12:25:38 EEST; 3s ago
  Process: 4420 ExecStart=/usr/sbin/rhn-search (code=exited, status=0/SUCCESS)
 Main PID: 4420 (code=exited, status=0/SUCCESS)

Aug 07 12:25:38 uyuni rhn-search[4420]:         at org.picocontainer.defaults.CachingComponentAdapter.getComponentInstance(CachingComponentAdapter.java:58)
Aug 07 12:25:38 uyuni rhn-search[4420]:         at org.picocontainer.defaults.DefaultPicoContainer$OrderedComponentAdapterLifecycleManager.start(DefaultPicoContainer.java:644)
Aug 07 12:25:38 uyuni rhn-search[4420]:         at org.picocontainer.defaults.DefaultPicoContainer.start(DefaultPicoContainer.java:456)
Aug 07 12:25:38 uyuni rhn-search[4420]:         at com.redhat.satellite.search.ContainerRunner.run(ContainerRunner.java:42)
Aug 07 12:25:38 uyuni rhn-search[4420]:         at java.base/java.lang.Thread.run(Thread.java:834)
Aug 07 12:25:38 uyuni rhn-search[4420]: Caused by: java.lang.ClassNotFoundException: org.apache.lucene.analysis.Analyzer
Aug 07 12:25:38 uyuni rhn-search[4420]:         at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
Aug 07 12:25:38 uyuni rhn-search[4420]:         at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
Aug 07 12:25:38 uyuni rhn-search[4420]:         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
Aug 07 12:25:38 uyuni rhn-search[4420]:         ... 27 more
uyuni:~ # bash -x /usr/sbin/rhn-search
+ echo 'Sourcing config file...'
Sourcing config file...
+ . /usr/share/rhn/config-defaults/rhn_search_daemon.conf
++ SEARCH_LIBRARY_PATH=/usr/lib:/usr/lib64:/usr/lib/gcj/postgresql-jdbc:/usr/lib64/gcj/postgresql-jdbc
++ SEARCH_RHN_CLASSPATH=/usr/share/rhn/classes:/usr/share/nutch-core:/usr/share/nutch-core/conf
++ SEARCH_RHN_JARS=/usr/share/rhn/lib/spacewalk-asm.jar:/usr/share/rhn/lib/rhn.jar:/usr/share/rhn/lib/java-branding.jar
++ SEARCH_JARS='/usr/share/rhn/search/lib/*'
++ SEARCH_INIT_MEMORY=32
++ SEARCH_MAX_MEMORY=96
+ SEARCH_CLASSPATH='/usr/share/rhn/search/lib/*:/usr/share/rhn/classes:/usr/share/nutch-core:/usr/share/nutch-core/conf:/usr/share/rhn/lib/spacewalk-asm.jar:/usr/share/rhn/lib/rhn.jar:/usr/share/rhn/lib/java-branding.jar'
+ SEARCH_PARAMS='-Dfile.encoding=UTF-8 -Xms32m -Xmx96m'
+ JAVACMD='/usr/bin/java -Djava.library.path=/usr/lib:/usr/lib64:/usr/lib/gcj/postgresql-jdbc:/usr/lib64/gcj/postgresql-jdbc -classpath /usr/share/rhn/search/lib/*:/usr/share/rhn/classes:/usr/share/nutch-core:/usr/share/nutch-core/conf:/usr/share/rhn/lib/spacewalk-asm.jar:/usr/share/rhn/lib/rhn.jar:/usr/share/rhn/lib/java-branding.jar -Dfile.encoding=UTF-8 -Xms32m -Xmx96m'
+ [[ 0 -eq 0 ]]
+ /usr/bin/java -Djava.library.path=/usr/lib:/usr/lib64:/usr/lib/gcj/postgresql-jdbc:/usr/lib64/gcj/postgresql-jdbc -classpath '/usr/share/rhn/search/lib/*:/usr/share/rhn/classes:/usr/share/nutch-core:/usr/share/nutch-core/conf:/usr/share/rhn/lib/spacewalk-asm.jar:/usr/share/rhn/lib/rhn.jar:/usr/share/rhn/lib/java-branding.jar' -Dfile.encoding=UTF-8 -Xms32m -Xmx96m com.redhat.satellite.search.Main
Exception in thread "Thread-0" java.lang.NoClassDefFoundError: org/apache/lucene/queryParser/ParseException
        at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
        at java.base/java.lang.Class.getDeclaredConstructors(Class.java:2357)
        at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$3.run(ConstructorInjectionComponentAdapter.java:286)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getConstructors(ConstructorInjectionComponentAdapter.java:284)
        at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getSortedMatchingConstructors(ConstructorInjectionComponentAdapter.java:264)
        at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getGreediestSatisfiableConstructor(ConstructorInjectionComponentAdapter.java:148)
        at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:210)
        at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
        at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
        at org.picocontainer.defaults.DecoratingComponentAdapter.getComponentInstance(DecoratingComponentAdapter.java:60)
        at org.picocontainer.defaults.CachingComponentAdapter.getComponentInstance(CachingComponentAdapter.java:58)
        at org.picocontainer.defaults.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:393)
        at org.picocontainer.defaults.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:374)
        at org.picocontainer.defaults.BasicComponentParameter.resolveInstance(BasicComponentParameter.java:77)
        at org.picocontainer.defaults.ComponentParameter.resolveInstance(ComponentParameter.java:114)
        at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getConstructorArguments(ConstructorInjectionComponentAdapter.java:257)
        at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:217)
        at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
        at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
        at org.picocontainer.defaults.DecoratingComponentAdapter.getComponentInstance(DecoratingComponentAdapter.java:60)
        at org.picocontainer.defaults.CachingComponentAdapter.getComponentInstance(CachingComponentAdapter.java:58)
        at org.picocontainer.defaults.DefaultPicoContainer$OrderedComponentAdapterLifecycleManager.start(DefaultPicoContainer.java:644)
        at org.picocontainer.defaults.DefaultPicoContainer.start(DefaultPicoContainer.java:456)
        at com.redhat.satellite.search.ContainerRunner.run(ContainerRunner.java:42)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: org.apache.lucene.queryParser.ParseException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 27 more
```

**Comment by mcalmer** [comment]
Ahh, we ship our own lucene. In the repo below:

https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable/images/repo/Uyuni-Server-4.0-POOL-x86_64-Media1

we ship lucene-2.4.1 (much older but working). Try to install this one instead of 6.6.0 .

**Comment by mcalmer** [comment]
We better at a version to the dependency to prevent this in future.

**Comment by stdevel** [comment]
Hello,
I'm able to reproduce this with the same error.

The workaround is - as mentioned by @mcalmer - quite easy:
```
# zypper install --oldpackage lucene-2.4.1-lp151.2.1
```

**Comment by hunter86bg** [comment]
Yep. It works with the package from Uyuni Stable as follows:
```
uyuni:~ # zypper install --oldpackage  lucene-2.4.1-lp151.2.1.noarch
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following package is going to be downgraded:
  lucene

The following package is going to change vendor:
  lucene  openSUSE -> obs://build.opensuse.org/systemsmanagement:Uyuni

1 package to downgrade, 1 to change vendor.
Overall download size: 926.3 KiB. Already cached: 0 B. After the operation, 2.4 MiB will be freed.
Continue? [y/n/v/...? shows all options] (y): y
Retrieving package lucene-2.4.1-lp151.2.1.noarch                                                                  (1/1), 926.3 KiB (  1.0 MiB unpacked)
Retrieving: lucene-2.4.1-lp151.2.1.noarch.rpm .....................................................................................[done (866.8 KiB/s)]
Checking for file conflicts: ....................................................................................................................[done]
(1/1) Installing: lucene-2.4.1-lp151.2.1.noarch .................................................................................................[done]
  
uyuni:~ # systemctl restart rhn-search
uyuni:~ # systemctl status rhn-search
● rhn-search.service - Spacewalk search engine
   Loaded: loaded (/usr/lib/systemd/system/rhn-search.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2019-08-07 18:07:40 EEST; 3s ago
 Main PID: 1216 (rhn-search)
    Tasks: 78 (limit: 4915)
   CGroup: /system.slice/rhn-search.service
           ├─1216 /bin/sh /usr/sbin/rhn-search
           └─1217 /usr/bin/java -Djava.library.path=/usr/lib:/usr/lib64:/usr/lib/gcj/postgresql-jdbc:/usr/lib64/gcj/postgresql-jdbc -classpath /usr/sh>

Aug 07 18:07:43 uyuni rhn-search[1216]: Update to version 56.0.3051.104 (changes since 56.0.3051.99):
Aug 07 18:07:43 uyuni rhn-search[1216]: * DNA-69051 [Mac] Crash at opera:hints::HintManager::RemoveObserver
Aug 07 18:07:43 uyuni rhn-search[1216]: * DNA-73192 Promotion Banner Update
Aug 07 18:07:43 uyuni rhn-search[1216]: Update to version 56.0.3051.99 (changes since 56.0.3051.31):
Aug 07 18:07:43 uyuni rhn-search[1216]: * DNA-72644 extension desktop capture does not work properly
Aug 07 18:07:43 uyuni rhn-search[1216]: * DNA-73176 cannot see full license text on opera://about/credits
Aug 07 18:07:43 uyuni rhn-search[1216]: * DNA-73285 [Linux] no tab separator
Aug 07 18:07:43 uyuni rhn-search[1216]: * DNA-73335 Crash at -[ZoomButton setAddressBarModel:]
Aug 07 18:07:43 uyuni rhn-search[1216]: * DNA-73492 Coupon toolbar
Aug 07 18:07:43 uyuni rhn-search[1216]: , synopsis=Recommended update for opera, orgId=null, advisoryRel=1, solution= , advisoryType=Bug Fix Advisory,>
```

**Comment by megamaced** [comment]
I also had this issue on a Master/convert to stable rpm build,  but a simple systemctl restart  rhn-search.service resolved it for me. No further action was necessary

**Comment by stdevel** [comment]
Is this really fixed? Was doing a new installation today and ended up with the following package version:
```
# rpm -qa|grep lucene
lucene-6.6.0-lp151.2.2.noarch
```

And ``rhn-search`` was not starting:
```
# systemctl status rhn-search
● rhn-search.service - Spacewalk search engine
   Loaded: loaded (/usr/lib/systemd/system/rhn-search.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Wed 2019-12-18 11:57:45 CET; 4s ago
  Process: 20801 ExecStart=/usr/sbin/rhn-search (code=exited, status=0/SUCCESS)
 Main PID: 20801 (code=exited, status=0/SUCCESS)

Dec 18 11:57:45 uyuni rhn-search[20801]:         at org.picocontainer.defaults.CachingComponentAdapter.getComponentInstance(CachingComponentAdapt>Dec 18 11:57:45 uyuni rhn-search[20801]:         at org.picocontainer.defaults.DefaultPicoContainer$OrderedComponentAdapterLifecycleManager.start>Dec 18 11:57:45 uyuni rhn-search[20801]:         at org.picocontainer.defaults.DefaultPicoContainer.start(DefaultPicoContainer.java:456)
Dec 18 11:57:45 uyuni rhn-search[20801]:         at com.redhat.satellite.search.ContainerRunner.run(ContainerRunner.java:42)
Dec 18 11:57:45 uyuni rhn-search[20801]:         at java.base/java.lang.Thread.run(Thread.java:834)
Dec 18 11:57:45 uyuni rhn-search[20801]: Caused by: java.lang.ClassNotFoundException: org.apache.lucene.queryParser.ParseException
Dec 18 11:57:45 uyuni rhn-search[20801]:         at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
Dec 18 11:57:45 uyuni rhn-search[20801]:         at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
Dec 18 11:57:45 uyuni rhn-search[20801]:         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
Dec 18 11:57:45 uyuni rhn-search[20801]:         ... 27 more
```

The fix was again to install the older version:
```
# zypper install --oldpackage lucene-2.4.1-lp151.2.1
```

Uyuni packages are as follows:
```
# rpm -qa|grep ^uyuni
uyuni-docs_en-4.0-400.8.1.uyunimaster.noarch
uyuni-docs_en-pdf-4.0-400.8.1.uyunimaster.noarch
uyuni-build-keys-web-12.0.1-400.4.1.uyunimaster.noarch
uyuni-doc-indexes-4.0-400.9.3.uyunimaster.noarch
uyuni-build-keys-12.0.1-400.4.1.uyunimaster.noarch
```
