### ISSUE TITLE
Cobblerd fails to start due to legacy version of /etc/cobblerd/modules.conf parameters

### ISSUE THREAD

**Issue by petepascente** [uyuni-project/uyuni#1632]
Cobber daemon fails to load on fresh install of Uyuni release 4.0.2 on OpenSUSE LEAP 15.1 4.12.14-lp151.27-default. Journactl output shows: 
``` Traceback (most recent call last):                                                                           
   File "/usr/bin/cobblerd", line 75, in main                                                                 
     api = cobbler_api.CobblerAPI(is_cobblerd=True)                                                           
   File "/usr/lib/python3.6/site-packages/cobbler/api.py", line 125, in __init__                              
     "authn_configfile"                                                                                       
   File "/usr/lib/python3.6/site-packages/cobbler/api.py", line 911, in get_module_from_file                  
     return module_loader.get_module_from_file(section, name, fallback)                                       
   File "/usr/lib/python3.6/site-packages/cobbler/module_loader.py", line 140, in get_module_from_file        
     raise CX(_("Failed to load module for %s/%s") % (category, field))                                       
 cobbler.cexceptions.CX: 'Failed to load module for authentication/module'                                    
```

This appears to be due to /etc/cobbler.modules.conf containing format for older versions of cobbler. For example - 
```[authentication]
## disabled by spacewalk-setup-cobbler ## module = authentication.configfile
module = authn_spacewalk
```
Where as of cobbler 3.0.1 this should look like: 
```
[authentication]
## disabled by spacewalk-setup-cobbler ## module = authentication.configfile
module = authentication.spacewalk
```

Changing these values manually allows cobblerd to start. 

Came across this script for migrating legacy values https://github.com/cobbler/cobbler/blob/master/scripts/settings-migration-v1-to-v2.sh

**Comment by sbluhm** [comment]
@petepascente , is this still relevant?
