### ISSUE TITLE
cobbler: syntax error near unexpected token `'spacewalk/redhat_register''

### ISSUE THREAD

**Issue by hunter86bg** [uyuni-project/uyuni#1656]
Hi All,

I'm experimenting with uyuni's cobler's capabilities and it seems that machine (rhel 7.7) fails to register to the uyuni.
The /root/ks-rhn-post.log shows only the following:
```
[root@localhost ~]# cat ks-rhn-post.log 
/tmp/ks-script-2X5Xzx: line 121: syntax error near unexpected token `'spacewalk/redhat_register''
/tmp/ks-script-2X5Xzx: line 121: `$SNIPPET('spacewalk/redhat_register')'
```

The original kickstart is:

```
[root@localhost ~]# cat original-ks.cfg
# Kickstart config file generated by Uyuni Config Management
# Profile Label : rhel76-locked
# Date Created  : 2019-11-28 14:16:52.528832

install
text
network --bootproto=dhcp
url --url http://10.10.10.1/ks/dist/org/1/rhel77
lang en_US
keyboard us
zerombr
clearpart --all
bootloader --location mbr
timezone --utc Europe/Sofia
auth --enableshadow --passalgo=sha256
rootpw --iscrypted <removed>
selinux --enforcing
reboot
firewall --enabled
skipx
autopart
shutdown
repo --name=rhel-7-server-rpms-v7_6-2019-08-01 --baseurl=http://10.10.10.1/ks/dist/child/rhel-7-server-rpms-v7_6-2019-08-01/rhel77
repo --name=rhel-7-uyuni-clients-2019-08-01 --baseurl=http://10.10.10.1/ks/dist/child/rhel-7-uyuni-clients-2019-08-01/rhel77
autopart --type=lvm

%packages 
perl
wget
rhn-setup
rhn-check
rhn-client-tools
%end

%pre
# Error: no snippet data for kickstart_start




echo "Saving RHN keys..." > /dev/ttyS0
SYSTEM_ID=/etc/sysconfig/rhn/systemid
rhn_keys_found=no

mkdir -p /tmp/rhn

drives=$(list-harddrives | awk '{print $1}')
for disk in $drives; do
    DISKS="$DISKS $(fdisk -l /dev/$disk | grep -v "swap\|LVM\|Extended" | awk '/^\/dev/{print $1}')"
done

# Try to find the keys on ordinary partitions
for disk in $DISKS; do
    name=test-$(basename $disk)
    mkdir -p /tmp/$name
    mount $disk /tmp/$name
    [ $? -eq 0 ] || continue # Skip to the next partition if the mount fails

    # Copy current RHN host keys out to be reused
    if [ -f /tmp/${name}$SYSTEM_ID ]; then
        cp -a /tmp/${name}$SYSTEM_ID /tmp/rhn
        rhn_keys_found="yes"
        umount /tmp/$name
        break
    fi
    umount /tmp/$name
    rm -r /tmp/$name
done

# Try LVM if that didn't work
if [ "$rhn_keys_found" = "no" ]; then
    lvm lvmdiskscan
    vgs=$(lvm vgs | tail -n +2 | awk '{ print $1 }')
    for vg in $vgs; do
        # Activate any VG we found
        lvm vgchange -ay $vg
    done
    
    lvs=$(lvm lvs | tail -n +2 | awk '{ print "/dev/" $2 "/" $1 }')
    for lv in $lvs; do
        tmpdir=$(mktemp -d findkeys.XXXXXX)
        mkdir -p /tmp/${tmpdir}
        mount $lv /tmp/${tmpdir} || continue # Skip to next volume if this fails

        # Let's see if the keys are in there
        if [ -f /tmp/${tmpdir}$SYSTEM_ID ]; then
            cp -a /tmp/${tmpdir}$SYSTEM_ID /tmp/rhn/
            rhn_keys_found="yes"
            umount /tmp/${tmpdir}
            break # We're done!
        fi
        umount /tmp/${tmpdir}
        rm -r /tmp/${tmpdir}
    done
    
    # And clean up..
    for vg in $vgs; do
        lvm vgchange -an $vg
    done
fi


%end

%post --nochroot
mkdir /mnt/sysimage/tmp/ks-tree-copy
if [ -d /oldtmp/ks-tree-shadow ]; then
cp -fa /oldtmp/ks-tree-shadow/* /mnt/sysimage/tmp/ks-tree-copy
elif [ -d /tmp/ks-tree-shadow ]; then
cp -fa /tmp/ks-tree-shadow/* /mnt/sysimage/tmp/ks-tree-copy
fi
cp /etc/resolv.conf /mnt/sysimage/etc/resolv.conf
cp -f /tmp/ks-pre.log* /mnt/sysimage/root/ || :

cp `awk '{ if ($1 ~ /%include/) {print $2}}' /tmp/ks.cfg` /tmp/ks.cfg /mnt/sysimage/root
%end

%post --nochroot --interpreter /bin/bash
### Learning how variables work
/bin/echo "TEST" > /root/TEST-post-kickstart
%end

%post --nochroot
if [ -f /usr/bin/python3 ]; then
    interpreter=/usr/bin/python3
else
    interpreter=/usr/bin/python
fi

cat << EOF | ${interpreter}

try:  # python 2
    import xmlrpclib
except ImportError:  # python 3
    import xmlrpc.client as xmlrpclib
import os.path

try:
    system_id = "/tmp/rhn/systemid"
    if os.path.exists(system_id):
        client =  xmlrpclib.Server("http://10.10.10.1/rpc/api")
        client.system.delete_system(open(system_id).read())
except:
    # xml rpc due to  a old/bad system id
    # we don't care about those
    # we'll register those as new. 
    pass

EOF

%end

%post --log /root/ks-rhn-post.log
# --Begin Uyuni command section--
cat > /tmp/ssl-key-1 <<'EOF'
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            be:bd:7c:08:eb:9f:c0:56
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = BG, ST = Sofia, L = Sofia, O = MyHOME, OU = Hall, CN = uyuni.localdomain.com
        Validity
            Not Before: Aug 21 22:27:17 2019 GMT
            Not After : Aug 18 22:27:17 2029 GMT
        Subject: C = BG, ST = Sofia, L = Sofia, O = MyHOME, OU = Hall, CN = uyuni.localdomain.com
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:c2:b4:d0:31:97:2c:91:9e:c7:f4:cb:8d:9c:ee:
                    15:f2:1d:41:aa:83:86:a8:44:cc:1b:ee:38:d5:d5:
                    bf:be:5d:b7:93:31:ce:f4:26:4f:d2:ee:e5:16:38:
                    d7:76:98:4a:2e:d9:2a:5c:5e:5e:c2:8c:27:4d:b0:
                    c6:3e:be:6f:6f:a2:49:17:d9:74:7b:6a:a2:38:be:
                    f4:db:72:f8:8d:1d:af:6f:45:4b:49:5f:3f:d7:94:
                    2e:82:9d:4a:35:0f:e9:de:08:61:36:99:47:7b:c3:
                    f6:99:75:fc:e5:d3:a9:d1:35:25:19:c2:72:04:91:
                    1e:6c:7e:01:4f:c3:3c:48:25:44:c4:20:72:33:6b:
                    f1:6a:2a:de:37:d0:fa:e3:c2:45:d4:aa:02:3a:6d:
                    2b:da:c8:a7:74:1d:3e:97:f7:04:88:b5:73:a1:de:
                    d4:11:01:3e:6b:e6:7c:59:3a:4e:bc:91:bb:a1:e0:
                    0a:7a:74:85:dd:bb:37:bc:c2:65:40:4a:ef:5b:36:
                    8e:28:92:4e:13:91:32:ad:40:86:9e:00:2c:99:7e:
                    c9:05:00:b0:1a:ad:b8:ea:69:9f:2e:50:df:36:85:
                    bb:6a:5a:73:dc:2f:6a:2e:b7:4c:30:4f:23:4e:02:
                    92:b0:69:f5:96:f8:04:94:96:80:98:c8:0f:93:14:
                    68:ef
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Basic Constraints: 
                CA:TRUE
            X509v3 Key Usage: 
                Digital Signature, Key Encipherment, Certificate Sign
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication, TLS Web Client Authentication
            Netscape Comment: 
                RHN SSL Tool Generated Certificate
            X509v3 Subject Key Identifier: 
                30:AE:F0:09:FB:5D:9D:D8:5E:92:53:14:B7:B5:69:11:44:B8:4C:1D
            X509v3 Authority Key Identifier: 
                keyid:30:AE:F0:09:FB:5D:9D:D8:5E:92:53:14:B7:B5:69:11:44:B8:4C:1D
                DirName:/C=BG/ST=Sofia/L=Sofia/O=MyHOME/OU=Hall/CN=uyuni.localdomain.com
                serial:BE:BD:7C:08:EB:9F:C0:56

    Signature Algorithm: sha256WithRSAEncryption
         64:12:e7:07:4c:a4:bf:c1:5f:92:a8:88:89:17:dc:4a:89:9d:
         19:56:94:62:15:c3:7e:46:08:ed:83:f3:7e:ce:99:c2:38:cb:
         ad:35:d5:53:bb:fe:7b:b5:0c:ff:b0:d1:01:7b:5a:36:32:f2:
         34:6b:65:db:a3:59:a8:b4:d9:1b:c2:ee:63:7c:0c:11:f8:eb:
         e8:db:b0:c3:3e:6f:de:89:f7:d6:3d:f6:44:06:a1:6d:87:0a:
         31:d3:59:46:ff:d5:f2:fe:4f:27:fa:3e:97:d8:e9:ec:04:07:
         92:63:56:ad:8a:1c:c4:86:04:6f:04:bc:0f:85:b1:37:e1:11:
         5c:d9:63:94:93:75:8f:9e:1b:75:f3:b6:d7:89:38:5e:bd:07:
         f6:80:88:50:ef:98:97:75:bc:a9:01:a3:02:36:4d:fe:50:eb:
         ac:20:b6:5c:02:0a:6f:c9:f4:1d:99:8e:30:d8:46:e9:10:62:
         88:ba:f2:c3:e9:e5:46:11:e5:91:4d:78:ef:da:42:0e:81:4d:
         b6:bd:82:a8:e7:7a:ed:0f:38:4e:a1:2c:99:10:98:1a:2e:0a:
         85:0c:04:12:ff:51:76:30:67:98:f6:21:4c:da:df:37:96:4e:
         d9:46:75:fd:e0:53:0b:7d:92:c0:cd:fe:3f:fe:72:ee:a9:16:
         0d:3b:d1:44
-----BEGIN CERTIFICATE-----
MIIEkTCCA3mgAwIBAgIJAL69fAjrn8BWMA0GCSqGSIb3DQEBCwUAMG0xCzAJBgNV
BAYTAkJHMQ4wDAYDVQQIDAVTb2ZpYTEOMAwGA1UEBwwFU29maWExDzANBgNVBAoM
Bk15SE9NRTENMAsGA1UECwwESGFsbDEeMBwGA1UEAwwVdXl1bmkubG9jYWxkb21h
aW4uY29tMB4XDTE5MDgyMTIyMjcxN1oXDTI5MDgxODIyMjcxN1owbTELMAkGA1UE
BhMCQkcxDjAMBgNVBAgMBVNvZmlhMQ4wDAYDVQQHDAVTb2ZpYTEPMA0GA1UECgwG
TXlIT01FMQ0wCwYDVQQLDARIYWxsMR4wHAYDVQQDDBV1eXVuaS5sb2NhbGRvbWFp
bi5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDCtNAxlyyRnsf0
y42c7hXyHUGqg4aoRMwb7jjV1b++XbeTMc70Jk/S7uUWONd2mEou2SpcXl7CjCdN
sMY+vm9vokkX2XR7aqI4vvTbcviNHa9vRUtJXz/XlC6CnUo1D+neCGE2mUd7w/aZ
dfzl06nRNSUZwnIEkR5sfgFPwzxIJUTEIHIza/FqKt430PrjwkXUqgI6bSvayKd0
HT6X9wSItXOh3tQRAT5r5nxZOk68kbuh4Ap6dIXduze8wmVASu9bNo4okk4TkTKt
QIaeACyZfskFALAarbjqaZ8uUN82hbtqWnPcL2out0wwTyNOApKwafWW+ASUloCY
yA+TFGjvAgMBAAGjggEyMIIBLjAMBgNVHRMEBTADAQH/MAsGA1UdDwQEAwICpDAd
BgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwMQYJYIZIAYb4QgENBCQWIlJI
TiBTU0wgVG9vbCBHZW5lcmF0ZWQgQ2VydGlmaWNhdGUwHQYDVR0OBBYEFDCu8An7
XZ3YXpJTFLe1aRFEuEwdMIGfBgNVHSMEgZcwgZSAFDCu8An7XZ3YXpJTFLe1aRFE
uEwdoXGkbzBtMQswCQYDVQQGEwJCRzEOMAwGA1UECAwFU29maWExDjAMBgNVBAcM
BVNvZmlhMQ8wDQYDVQQKDAZNeUhPTUUxDTALBgNVBAsMBEhhbGwxHjAcBgNVBAMM
FXV5dW5pLmxvY2FsZG9tYWluLmNvbYIJAL69fAjrn8BWMA0GCSqGSIb3DQEBCwUA
A4IBAQBkEucHTKS/wV+SqIiJF9xKiZ0ZVpRiFcN+Rgjtg/N+zpnCOMutNdVTu/57
tQz/sNEBe1o2MvI0a2Xbo1motNkbwu5jfAwR+Ovo27DDPm/eiffWPfZEBqFthwox
01lG/9Xy/k8n+j6X2OnsBAeSY1atihzEhgRvBLwPhbE34RFc2WOUk3WPnht187bX
iThevQf2gIhQ75iXdbypAaMCNk3+UOusILZcAgpvyfQdmY4w2EbpEGKIuvLD6eVG
EeWRTXjv2kIOgU22vYKo53rtDzhOoSyZEJgaLgqFDAQS/1F2MGeY9iFM2t83lk7Z
RnX94FMLfZLAzf4//nLuqRYNO9FE
-----END CERTIFICATE-----

EOF
# ssl-key1
cat /tmp/ssl-key-* > /usr/share/rhn/RHN-ORG-TRUSTED-SSL-CERT
perl -pe 's/RHNS-CA-CERT/RHN-ORG-TRUSTED-SSL-CERT/g' -i /etc/sysconfig/rhn/up2date

perl -npe 's|^(\s*(noSSLS\|s)erverURL\s*=\s*[^:]+://)[^/]*/|${1}uyuni.localdomain.com/|' -i /etc/sysconfig/rhn/up2date
mkdir -p /etc/sysconfig/rhn/allowed-actions/script
touch /etc/sysconfig/rhn/allowed-actions/script/run
mkdir -p /etc/sysconfig/rhn/allowed-actions/configfiles
touch /etc/sysconfig/rhn/allowed-actions/configfiles/all

# now copy from the ks-tree we saved in the non-chroot checkout
cp -fav /tmp/ks-tree-copy/* / 2>/dev/null
rm -Rf /tmp/ks-tree-copy
# --End Uyuni command section--

# begin cobbler snippet

# Start post_install_network_config generated code
# End post_install_network_config generated code

# set default MOTD
echo "Kickstarted on $(date +'%Y-%m-%d')" >> /etc/motd

$SNIPPET('spacewalk/redhat_register')
# end cobbler snippet

rhn_check
%end


%post


# Start koan environment setup
echo "export COBBLER_SERVER=10.10.10.1" > /etc/profile.d/cobbler.sh
echo "setenv COBBLER_SERVER 10.10.10.1" > /etc/profile.d/cobbler.csh
# End koan environment setup


# Error: no snippet data for kickstart_done


%end
```
I'm on latest uyuni stable.

**Comment by mcalmer** [comment]
Do you run uyuni "Stable" or "Master" ?

In "Master" we use cobbler 3.0.0 and snippet directories have changed.
Maybe a migration is not yet correctly done as "Master" is development playground.

**Comment by mcalmer** [comment]
Just saw, that you wrote you are on "uyuni stable" :-)

**Comment by mcalmer** [comment]
Can you paste the output of the following 2 commands please? 

```
$> ls -la /var/lib/rhn/kickstarts/snippets/
$> ls -la /var/lib/cobbler/snippets/
```

**Comment by hunter86bg** [comment]
Sure:

```
uyuni:/var/lib/rhn #  ls -la /var/lib/cobbler/snippets/
total 224
drwxr-xr-x 1 root   root    1614 Aug 22 01:22 .
drwxr-xr-x 1 root   root     246 Aug 22 01:27 ..
-rw-r--r-- 1 root   root    1023 Feb 22  2019 addons.xml
-rw-r--r-- 1 root   root    5557 Feb 22  2019 autoinstall_done
-rw-r--r-- 1 root   root    1848 Feb 22  2019 autoinstall_start
-rw-r--r-- 1 root   root     431 Feb 22  2019 cobbler_register
-rw-r--r-- 1 root   root     645 Feb 22  2019 download_config_files
-rw-r--r-- 1 root   root     865 Feb 22  2019 download_config_files_deb
-rw-r--r-- 1 root   root     821 Feb 22  2019 hosts.xml
-rw-r--r-- 1 root   root    1310 Feb 22  2019 kdump.xml
-rw-r--r-- 1 root   root    2563 Feb 22  2019 keep_cfengine_keys
-rw-r--r-- 1 root   root    5431 Feb 22  2019 keep_files
-rw-r--r-- 1 root   root    2609 Feb 22  2019 keep_rhn_keys
-rw-r--r-- 1 root   root    2564 Feb 22  2019 keep_rudder_keys
-rw-r--r-- 1 root   root    2534 Feb 22  2019 keep_rudder_uuid
-rw-r--r-- 1 root   root    2893 Feb 22  2019 keep_ssh_host_keys
-rw-r--r-- 1 root   root     191 Feb 22  2019 koan_environment
-rw-r--r-- 1 root   root     644 Feb 22  2019 late_apt_repo_config
-rw-r--r-- 1 root   root      40 Feb 22  2019 log_ks_post
-rw-r--r-- 1 root   root      62 Feb 22  2019 log_ks_post_nochroot
-rw-r--r-- 1 root   root     281 Feb 22  2019 log_ks_pre
-rw-r--r-- 1 root   root      46 Feb 22  2019 main_partition_select
-rw-r--r-- 1 root   root    4009 Feb 22  2019 network_config-rw-r--r-- 1 root   root    1974 Feb 22  2019 network_config_esx
-rw-r--r-- 1 root   root    2332 Feb 22  2019 network_config_esxi
-rw-r--r-- 1 root   root    8549 Feb 22  2019 networking.xml-rw-r--r-- 1 root   root     675 Feb 22  2019 partition_select
-rw-r--r-- 1 root   root     709 Feb 22  2019 post_anamon
-rw-r--r-- 1 root   root     840 Feb 22  2019 post_install_kernel_options
-rw-r--r-- 1 root   root   17277 Feb 22  2019 post_install_network_config
-rw-r--r-- 1 root   root   13349 Feb 22  2019 post_install_network_config_deb
-rw-r--r-- 1 root   root     204 Feb 22  2019 post_koan_add_reinstall_entry
-rw-r--r-- 1 root   root      69 Feb 22  2019 post_run_deb
-rw-r--r-- 1 root   root     195 Feb 22  2019 pre_anamon
-rw-r--r-- 1 root   root    6927 Feb 22  2019 pre_install_network_config
-rw-r--r-- 1 root   root     679 Feb 22  2019 pre_partition_select
-rw-r--r-- 1 root   root     628 Feb 22  2019 preseed_apt_repo_config
-rw-r--r-- 1 root   root     263 Feb 22  2019 proxy.xml
-rw-r--r-- 1 root   root      65 Feb 22  2019 puppet_install_if_enabled
-rw-r--r-- 1 root   root     644 Feb 22  2019 puppet_register_if_enabled
-rw-r--r-- 1 root   root     836 Jul 21 09:42 redhat_register
-rw-r--r-- 1 root   root     696 Feb 22  2019 restore_boot_device
-rw-r--r-- 1 root   root     620 Jul 21 09:42 rhn_certificate_based_register
-rw-r--r-- 1 root   root     656 Feb 22  2019 save_boot_device
drwxrwxr-x 1 tomcat tomcat   334 Aug 22 01:22 spacewalk
-rw-r--r-- 1 root   root     349 Jul 31 18:40 spacewalk_file_preservation
-rw-r--r-- 1 root   root     438 Feb 22  2019 suse_scriptwrapper.xml
uyuni:/var/lib/rhn #  ls -la /var/lib/rhn/kickstarts/snippets/
ls: cannot access '/var/lib/rhn/kickstarts/snippets/': No such file or directory
uyuni:/var/lib/rhn #  ls -la /var/lib/rhn/                  total 0
drwxr-xr-x 1 root root  48 Aug 22 01:21 .
drwxr-xr-x 1 root root 644 Dec  1 00:12 ..
drwxr-xr-x 1 root root 120 Aug 22 01:27 rhn-satellite-prep
drwxr-xr-x 1 root root  14 Aug 22 01:21 search
uyuni:/var/lib/rhn #
```

**Comment by hunter86bg** [comment]
In some old threads (I think Fedora) they mention that no Snipp substitution will be done  if the snip is having an issue.

I don't have a cobbler system entry due to another issue (which was already fixed as per  the people  in the cobbler  community):
```
uyuni:~ # cobbler system add --help
Traceback (most recent call last):                            File "/usr/bin/cobbler", line 35, in <module>
    sys.exit(app.main())                                      File "/usr/lib/python3.6/site-packages/cobbler/cli.py", line 745, in main
    rc = cli.run(sys.argv)                                    File "/usr/lib/python3.6/site-packages/cobbler/cli.py", line 358, in run                                                  self.object_command(object_type, object_action)
  File "/usr/lib/python3.6/site-packages/cobbler/cli.py", line 428, in object_command                                       network_interface_fields, settings, object_action)        File "/usr/lib/python3.6/site-packages/cobbler/cli.py", line 238, in add_options_from_fields
    _add_parser_option_from_field(parser, field, settings)
  File "/usr/lib/python3.6/site-packages/cobbler/cli.py", line 209, in _add_parser_option_from_field
    raise Exception("field %s default value (%s) is not listed in choices (%s)" % (name, default, str(choices)))
Exception: field redhat_management_key default value (<<inherit>>) is not listed in choices (str)
```

**Comment by mcalmer** [comment]
Ok, you use already cobbler 3.0.0. I forgot that we had already a release with it.

Please check what is in 

```
$> ls -la /var/lib/cobbler/snippets/spacewalk
```

I can see a redhat_register in snippets directly, but there should be one in spacewalk/ subdirectory as well.

There were some changes in cobbler and one very anoying was a rename of some variables and fields. We need to check step by step what is happening.

@SchoolGuy maybe this thread is also interesting for you.

**Comment by SchoolGuy** [comment]
Definitly... @mcalmer I will have a look tomorrow.

**Comment by hunter86bg** [comment]
It really does contain it:
```
uyuni:~ # ls -la /var/lib/cobbler/snippets/spacewalk
total 36
drwxrwxr-x 1 tomcat tomcat  334 Aug 22 01:22 .
drwxr-xr-x 1 root   root   1614 Aug 22 01:22 ..
-rw-r--r-- 1 tomcat tomcat   75 Aug  1 12:02 default_motd
-rw-r--r-- 1 tomcat tomcat 1706 Aug  1 12:02 keep_system_id
-rw-r--r-- 1 tomcat tomcat  611 Aug  1 12:02 post_delete_system
-rw-r--r-- 1 tomcat tomcat 1227 Aug  1 12:02 post_reactivation_key
-rw-r--r-- 1 tomcat tomcat 1034 Aug  1 12:02 redhat_register-rw-r--r-- 1 tomcat tomcat  597 Aug  1 12:02 sles_no_signature_checks
-rw-r--r-- 1 tomcat tomcat 3067 Aug  1 12:02 sles_register
-rw-r--r-- 1 tomcat tomcat 3196 Aug  1 12:02 sles_register_script
-rw-r--r-- 1 tomcat tomcat  426 Aug  1 12:02 wait_for_networkmanager_script
uyuni:~ # cd /var/lib/cobbler/snippets/spacewalk
uyuni:/var/lib/cobbler/snippets/spacewalk # cat redhat_register
# begin Red Hat management server registration
#if $redhat_management_type != "off" and $redhat_management_key != ""
mkdir -p /usr/share/rhn/
   #if $redhat_management_type == "site"
      #set $mycert_file = "RHN-ORG-TRUSTED-SSL-CERT"
      #set $mycert = "/usr/share/rhn/" + $mycert_file
wget http://$redhat_management_server/pub/RHN-ORG-TRUSTED-SSL-CERT -O $mycert
perl -Xnpe 's/RHNS-CA-CERT/$mycert_file/g' -i /etc/sysconfig/rhn/*
if [ -f /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release ]; then
    rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-releasefi
   #end if
   #if $redhat_management_type == "hosted"
      #set $mycert = "/usr/share/rhn/RHNS-CA-CERT"
   #end if
   #set $endpoint = "https://%s/XMLRPC" % $redhat_management_server
key=$redhat_management_key
if [ -f /tmp/key ]; then
    key=`cat /tmp/key`,\$key
fi

rhnreg_ks --serverUrl=$endpoint --sslCACert=$mycert --activationkey=\$key
#else
# not configured to register to any Red Hat management server (ok)
#end if
# end Red Hat management server registration
```

**Comment by SchoolGuy** [comment]
@hunter86bg Is it possible that you look in `/var/lib/cobbler/cobbler.log` and look for template rendering errors? (Don't paste the whole file, it may contain sensitive information and it will definitely be very very long.)

**Comment by hunter86bg** [comment]
Hm... It seems there is a warning:

```uyuni:/var/log/cobbler # cat cobbler.log
Thu Dec  5 11:02:00 2019 - INFO | find_items; ['distro']
Thu Dec  5 11:03:00 2019 - INFO | REMOTE find_items(distro); criteria({'uid': '368a60af9fd64b34a60a5b208fbe3a50'}); sort(None); user(?)
Thu Dec  5 11:03:00 2019 - INFO | find_items; ['distro']
Thu Dec  5 11:03:00 2019 - INFO | REMOTE generate_autoinstall; user(?)
Thu Dec  5 11:03:00 2019 - WARNING | errors were encountered rendering the template
Thu Dec  5 11:03:00 2019 - WARNING |
[{'code': 'VFFSL(SL,"zMBsm4BrjlSMNtrt",True)',
  'exc_val': NotFound("cannot find 'zMBsm4BrjlSMNtrt'",),
  'lineCol': (24, 22),
  'rawCode': '$zMBsm4BrjlSMNtrt',
  'time': 'Thu Dec  5 11:03:00 2019'},
 {'code': 'VFFSL(SL,"I",True)',
  'exc_val': NotFound("cannot find 'I'",),
  'lineCol': (24, 39),
  'rawCode': '$I',
  'time': 'Thu Dec  5 11:03:00 2019'},
 {'code': 'VFFSL(SL,"SNIPPET",False)(\'spacewalk/redhat_register\')',
  'exc_val': NotFound("cannot find 'redhat_management_type'",),
  'lineCol': (195, 1),
  'rawCode': "$SNIPPET('spacewalk/redhat_register')",
  'time': 'Thu Dec  5 11:03:00 2019'}]
Thu Dec  5 11:04:00 2019 - INFO | REMOTE find_items(distro); criteria({'uid': '368a60af9fd64b34a60a5b208fbe3a50'}); sort(None); user(?)
Thu Dec  5 11:04:00 2019 - INFO | find_items; ['distro']
Thu Dec  5 11:05:00 2019 - INFO | REMOTE find_items(distro); criteria({'uid': '368a60af9fd64b34a60a5b208fbe3a50'}); sort(None); user(?)
Thu Dec  5 11:05:00 2019 - INFO | find_items; ['distro']
Thu Dec  5 11:06:00 2019 - INFO | REMOTE find_items(distro); criteria({'uid': '368a60af9fd64b34a60a5b208fbe3a50'}); sort(None); user(?)
Thu Dec  5 11:06:00 2019 - INFO | find_items; ['distro']
Thu Dec  5 11:07:00 2019 - INFO | REMOTE find_items(distro); criteria({'uid': '368a60af9fd64b34a60a5b208fbe3a50'}); sort(None); user(?)
Thu Dec  5 11:07:00 2019 - INFO | find_items; ['distro']
Thu Dec  5 11:08:00 2019 - INFO | REMOTE find_items(distro); criteria({'uid': '368a60af9fd64b34a60a5b208fbe3a50'}); sort(None); user(?)
Thu Dec  5 11:08:00 2019 - INFO | find_items; ['distro']
Thu Dec  5 11:09:00 2019 - INFO | REMOTE find_items(distro); criteria({'uid': '368a60af9fd64b34a60a5b208fbe3a50'}); sort(None); user(?)
Thu Dec  5 11:09:00 2019 - INFO | find_items; ['distro']
Thu Dec  5 11:10:00 2019 - INFO | REMOTE find_items(distro); criteria({'uid': '368a60af9fd64b34a60a5b208fbe3a50'}); sort(None); user(?)
Thu Dec  5 11:10:00 2019 - INFO | find_items; ['distro']
Thu Dec  5 11:10:00 2019 - INFO | REMOTE find_items(profile); criteria({'uid': '0397ed6eb5d749b29df31e22152c766a'}); sort(None); user(?)
Thu Dec  5 11:10:00 2019 - INFO | find_items; ['profile']
Thu Dec  5 11:11:00 2019 - INFO | REMOTE find_items(distro); criteria({'uid': '368a60af9fd64b34a60a5b208fbe3a50'}); sort(None); user(?)
Thu Dec  5 11:11:00 2019 - INFO | find_items; ['distro']
Thu Dec  5 11:12:00 2019 - INFO | REMOTE find_items(distro); criteria({'uid': '368a60af9fd64b34a60a5b208fbe3a50'}); sort(None); user(?)
Thu Dec  5 11:12:00 2019 - INFO | find_items; ['distro']
<snip>
```

**Comment by SchoolGuy** [comment]
@hunter86g This is exactly the error you asked on Gitter. Just apply the commit I pasted you there and you should be fine!

**Comment by mcalmer** [comment]
`redhat_management_type` : it seems this variable is not found. Not sure if this cause the parsing error.
I checked cobbler 2.6 and 3.0. It is not defined anywhere. Also in the uyuni code it is not set.
Sounds a bit like it never worked.

Checking what it does, it seems that we can re-write the snippets and not use it.

**Comment by mcalmer** [comment]
@hunter86bg please check my pull request and try out if the changed snippet fix your problem.

https://github.com/uyuni-project/uyuni/blob/d0d2db327f29eb2e2f8e37bb4c55aea2a071e0fd/java/conf/cobbler/snippets/redhat_register

**Comment by hunter86bg** [comment]
> @hunter86g This is exactly the error you asked on Gitter. Just apply the commit I pasted you there and you should be fine!

Thanks, now the 'cobbler system add --help' works
