### ISSUE TITLE
Can't bootstrap minimal installations of Debian or Astra Linux CE

### ISSUE THREAD

**Issue by juliogonzalez** [uyuni-project/uyuni#1912]
As the `python3-apt` package is missing, and it's required (Ubuntu has it by default).

If you bootstrap from WebUI you will see:
```
Rendering SLS 'base:bootstrap' failed: Jinja error: argument of type 'StrictUndefined' is not iterable /var/tmp/.root_d52978_salt/running_data/var/cache/salt/minion/files/base/channels/disablelocalrepos.sls(12): --- [...] {% set repos = salt['pkg.list_repos']() %} {% for alias, data in repos.items() %} {% if grains['os_family'] == 'Debian' %} {% for entry in data %} {% if (repos_disabled.match_str in entry['file'])|string == repos_disabled.matching|string and entry.get('enabled', True) %} <====================== disable_repo_{{ repos_disabled.count }}: module.run: - name: pkg.mod_repo - repo: {{ "'" ~ entry.line ~ "'" }} - kwargs: [...] --- Traceback (most recent call last): File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 392, in render_jinja_tmpl output = template.render(**decoded_context) File "/usr/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render return original_render(self, *args, **kwargs) File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render return self.environment.handle_exception(exc_info, True) File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception reraise(exc_type, exc_value, tb) File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise raise value.with_traceback(tb) File "<template>", line 11, in top-level template code File "/var/tmp/.root_d52978_salt/running_data/var/cache/salt/minion/files/base/channels/disablelocalrepos.sls", line 12, in top-level template code {% if (repos_disabled.match_str in entry['file'])|string == repos_disabled.matching|string and entry.get('enabled', True) %} TypeError: argument of type 'StrictUndefined' is not iterable
```
Thanks to @meaksh we discovered that it is true that `entry['file']` is `StrictUndefined`.

`pkg.list_repos` (above at the sls file) REQUIRES `python3-apt` (or python-apt for old systems) installed BEFORE this step (disabling repos) can work.

Such packages are not installed at a minumal Debian 10 installation or at an Astra Linux CE installations, so such machines can't be onboarded unless `python3-apt` is installed in advance.

Maybe it's somehow easy to fix at the bootstrap scripts, but WebUI is another problem because  @meaksh and I couldn't fond a proper way of having the package installed because the way the code is written. Doesn't mean it can be done, but it could require an important rewrite of the bootstrap SLS files.

*NOTE*: This was not discovered in Ubuntu as the package is part of the `ubuntu-server` pattern.

**Comment by juliogonzalez** [comment]
To reproduce, adjust the software selection as follows:

![image](https://user-images.githubusercontent.com/4226070/77674647-33008c80-6f8c-11ea-8250-2d3a0acd33dc.png)

**Comment by juliogonzalez** [comment]
And then you don't get `python3-apt` as you can see:
![image](https://user-images.githubusercontent.com/4226070/77675517-537d1680-6f8d-11ea-884d-1bf42749a5da.png)

**Comment by paususe** [comment]
This can be fixed by salt-ssh'ing into the machine and installing the package via a state prior to onboarding, like we are talking for Ubuntu:
https://github.com/uyuni-project/uyuni-rfc/pull/30

**Comment by juliogonzalez** [comment]
I hit this again testing https://github.com/uyuni-project/uyuni/pull/2757

And we need also `ca-certficates` installed. Otherwise the bootstrap fails, installs this package, and then works if you launch it again.

**Comment by nodeg** [comment]
@juliogonzalez Same with this one. I think we can also close this.

**Comment by juliogonzalez** [comment]
Probably, as Debian works.
