### ISSUE TITLE
spacewalk-repo-sync traceback when adding --email

### ISSUE THREAD

**Issue by hunter86bg** [uyuni-project/uyuni#2142]
spacewalk-repo-sync tracebacks due to a missing option in the config file:
```
uyuni:~ # spacewalk-repo-sync -c ubuntu-18.04-pool-amd64 -t deb -f -n --email
07:51:32 ======================================
07:51:32 | Channel: ubuntu-18.04-pool-amd64
07:51:32 ======================================
07:51:32 Sync of channel started.
07:51:32 Repo URL: http://localhost/pub/repositories/empty-deb/?uniquekey=1804
07:51:32     Packages in repo:                 0
07:51:32     No new packages to sync.
07:51:32
07:51:32   Patches in repo: 0.
Generating bootstrap repos for all available products which had changes.
Nothing to do.
07:51:32 Sync completed.
07:51:32 Total time: 0:00:00
+++ sending log as an email +++
Traceback (most recent call last):
  File "/usr/bin/spacewalk-repo-sync", line 286, in <module>    sys.exit(abs(main() or 0))
  File "/usr/bin/spacewalk-repo-sync", line 279, in main
    reposync.send_mail()
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 115, in send_mail
    if CFG.default_mail_from:
  File "/usr/lib/python3.6/site-packages/spacewalk/common/rhnConfig.py", line 237, in __getattr__
    raise AttributeError(key)
AttributeError: default_mail_from
uyuni:~ #
```

In order to fix, you need to add the missing key in /etc/rhn/rhn.conf:
default_mail_from=uyuni@<Uyuni's FQDN>

**Comment by mcalmer** [comment]
There should be `web.default_mail_from` defined. I opened a PR to use that address.
Thanks for the report
