### ISSUE TITLE
Issues first bootstrapping minions: Add with SSH failed with salt permission denied.

### ISSUE THREAD

**Issue by NunoHiggs** [uyuni-project/uyuni#2312]
Hello all,

I’ve been trying to add several clients – centos 7  and leap 15.1 – to my 2020.05 Uyuni fresh implementation and I am getting on both errors using only ssh.
All of my adds are failing to bootstrap.

It seems to be related to this https://github.com/saltstack/salt/issues/38458.
Is there any workaround? 

I am trying to add a new server, bootstrap, using only ssh.

Thanks a lot for your help.
Nuno.

Error log:

2020-06-08 14:25:39,503 [py.warnings      :99  ][WARNING ][3878] /usr/share/susemanager/modules/pillar/suma_minion.py:83: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  ret.update(yaml.load(open('{0}.yml'.format(static_pillar_filename)).read()))

2020-06-08 14:25:39,508 [py.warnings      :99  ][WARNING ][3878] /usr/share/susemanager/modules/pillar/suma_minion.py:91: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  ret.update(yaml.load(open('{0}.yml'.format(global_pillar_filename)).read()))

2020-06-08 14:25:39,753 [salt.utils.templates:180 ][ERROR   ][3878] Rendering exception occurred
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 392, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 8, in top-level template code
  File "/usr/lib/python3.6/site-packages/jinja2/runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 2, in template
  File "/usr/lib/python3.6/site-packages/salt/utils/jinja.py", line 136, in get_source
    self.check_cache(_template)
  File "/usr/lib/python3.6/site-packages/salt/utils/jinja.py", line 97, in check_cache
    self.cache_file(template)
  File "/usr/lib/python3.6/site-packages/salt/utils/jinja.py", line 90, in cache_file
    self.file_client().get_file(saltpath, '', True, self.saltenv)
  File "/usr/lib/python3.6/site-packages/salt/fileclient.py", line 1053, in get_file
    hash_server, stat_server = self.hash_and_stat_file(path, saltenv)
  File "/usr/lib/python3.6/site-packages/salt/fileclient.py", line 1312, in hash_and_stat_file
    hash_result = self.hash_file(path, saltenv)
  File "/usr/lib/python3.6/site-packages/salt/fileclient.py", line 1305, in hash_file
    return self.__hash_and_stat_file(path, saltenv)
  File "/usr/lib/python3.6/site-packages/salt/fileclient.py", line 1297, in __hash_and_stat_file
    return self.channel.send(load)
  File "/usr/lib/python3.6/site-packages/salt/fileserver/__init__.py", line 906, in send
    return getattr(self.fs, cmd)(load)
  File "/usr/lib/python3.6/site-packages/salt/fileserver/__init__.py", line 681, in file_hash
    return self.__file_hash_and_stat(load)[0]
  File "/usr/lib/python3.6/site-packages/salt/fileserver/__init__.py", line 673, in __file_hash_and_stat
    return self.servers[fstr](load, fnd), stat_result
  File "/usr/lib/python3.6/site-packages/salt/fileserver/roots.py", line 280, in file_hash
    os.makedirs(cache_dir)
  File "/usr/lib64/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib64/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib64/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  [Previous line repeated 5 more times]
  File "/usr/lib64/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/var/tmp/.root_2c2911_salt/running_data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 169, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 441, in render_jinja_tmpl
    trace=tracestr)
salt.exceptions.SaltRenderError: Jinja error: [Errno 13] Permission denied: '/var/tmp/.root_2c2911_salt/running_data'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 392, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 8, in top-level template code
  File "/usr/lib/python3.6/site-packages/jinja2/runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 2, in template
  File "/usr/lib/python3.6/site-packages/salt/utils/jinja.py", line 136, in get_source
    self.check_cache(_template)
  File "/usr/lib/python3.6/site-packages/salt/utils/jinja.py", line 97, in check_cache
    self.cache_file(template)
  File "/usr/lib/python3.6/site-packages/salt/utils/jinja.py", line 90, in cache_file
    self.file_client().get_file(saltpath, '', True, self.saltenv)
  File "/usr/lib/python3.6/site-packages/salt/fileclient.py", line 1053, in get_file
    hash_server, stat_server = self.hash_and_stat_file(path, saltenv)
  File "/usr/lib/python3.6/site-packages/salt/fileclient.py", line 1312, in hash_and_stat_file
    hash_result = self.hash_file(path, saltenv)
  File "/usr/lib/python3.6/site-packages/salt/fileclient.py", line 1305, in hash_file
    return self.__hash_and_stat_file(path, saltenv)
  File "/usr/lib/python3.6/site-packages/salt/fileclient.py", line 1297, in __hash_and_stat_file
    return self.channel.send(load)
  File "/usr/lib/python3.6/site-packages/salt/fileserver/__init__.py", line 906, in send
    return getattr(self.fs, cmd)(load)
  File "/usr/lib/python3.6/site-packages/salt/fileserver/__init__.py", line 681, in file_hash
    return self.__file_hash_and_stat(load)[0]
  File "/usr/lib/python3.6/site-packages/salt/fileserver/__init__.py", line 673, in __file_hash_and_stat
    return self.servers[fstr](load, fnd), stat_result
  File "/usr/lib/python3.6/site-packages/salt/fileserver/roots.py", line 280, in file_hash
    os.makedirs(cache_dir)
  File "/usr/lib64/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib64/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib64/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  [Previous line repeated 5 more times]
  File "/usr/lib64/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/var/tmp/.root_2c2911_salt/running_data'

; line 2

---
{% macro includesls(osfullname, osrelease) -%}
{% include 'certs/{0}.sls'.format(osfullname + osrelease.replace('.', '_')) ignore missing -%}    <======================
{%- endmacro %}
{% if grains['os_family'] == 'Suse' %}
{% if grains['osfullname'] == 'openSUSE Tumbleweed' %}
{% set sls = includesls('Tumbleweed', '') -%}
{% else -%}
[...]
---
2020-06-08 14:25:39,754 [salt.state       :3516][CRITICAL][3878] Rendering SLS 'base:certs' failed: Jinja error: [Errno 13] Permission denied: '/var/tmp/.root_2c2911_salt/running_data'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 392, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 8, in top-level template code
  File "/usr/lib/python3.6/site-packages/jinja2/runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 2, in template
  File "/usr/lib/python3.6/site-packages/salt/utils/jinja.py", line 136, in get_source
    self.check_cache(_template)
  File "/usr/lib/python3.6/site-packages/salt/utils/jinja.py", line 97, in check_cache
    self.cache_file(template)
  File "/usr/lib/python3.6/site-packages/salt/utils/jinja.py", line 90, in cache_file
    self.file_client().get_file(saltpath, '', True, self.saltenv)
  File "/usr/lib/python3.6/site-packages/salt/fileclient.py", line 1053, in get_file
    hash_server, stat_server = self.hash_and_stat_file(path, saltenv)
  File "/usr/lib/python3.6/site-packages/salt/fileclient.py", line 1312, in hash_and_stat_file
    hash_result = self.hash_file(path, saltenv)
  File "/usr/lib/python3.6/site-packages/salt/fileclient.py", line 1305, in hash_file
    return self.__hash_and_stat_file(path, saltenv)
  File "/usr/lib/python3.6/site-packages/salt/fileclient.py", line 1297, in __hash_and_stat_file
    return self.channel.send(load)
  File "/usr/lib/python3.6/site-packages/salt/fileserver/__init__.py", line 906, in send
    return getattr(self.fs, cmd)(load)
  File "/usr/lib/python3.6/site-packages/salt/fileserver/__init__.py", line 681, in file_hash
    return self.__file_hash_and_stat(load)[0]
  File "/usr/lib/python3.6/site-packages/salt/fileserver/__init__.py", line 673, in __file_hash_and_stat
    return self.servers[fstr](load, fnd), stat_result
  File "/usr/lib/python3.6/site-packages/salt/fileserver/roots.py", line 280, in file_hash
    os.makedirs(cache_dir)
  File "/usr/lib64/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
 File "/usr/lib64/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib64/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  [Previous line repeated 5 more times]
  File "/usr/lib64/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/var/tmp/.root_2c2911_salt/running_data'

; line 2

---
{% macro includesls(osfullname, osrelease) -%}
{% include 'certs/{0}.sls'.format(osfullname + osrelease.replace('.', '_')) ignore missing -%}    <======================
{%- endmacro %}
{% if grains['os_family'] == 'Suse' %}
{% if grains['osfullname'] == 'openSUSE Tumbleweed' %}
{% set sls = includesls('Tumbleweed', '') -%}
{% else -%}
[...]
---
2020-06-08 14:25:39,757 [salt.client.ssh  :1170][ERROR   ][3878] An Exception occurred while executing state.apply: [Errno 13] Permission denied: '/var/tmp/.root_2c2911_salt/running_data'

**Comment by juliogonzalez** [comment]
@meaksh any idea? Is this maybe something fixed with salt 3000?

**Comment by meaksh** [comment]
@NunoHiggs - this seems just a permission problem (maybe from previous salt-ssh executions with different user).

Have you tried to remove `/var/tmp/.root_2c2911_salt/` directory from the SSH minion and try to bootstrap again?

**Comment by Shirocco88** [comment]
@NunoHiggs 
is this issue still existing i uyuni-2021.06 ?

**Comment by mcalmer** [comment]
I think this has already been fixed. Please open a new issue if you can reproduce this problem with a current version of Uyuni.
Thanks.
