### ISSUE TITLE
Client no registering properly, suseconfig not getting copied to client in cli bootstrap

### ISSUE THREAD

**Issue by ewenf-uindy** [uyuni-project/uyuni#2387]
I have a base suse server and a base centos client.  When I try to run the bootstrap.sh, I get 
* registering
./bootstrap.sh: line 810: /etc/salt/minion.d/susemanager.conf: No such file or directory
./bootstrap.sh: line 811: /etc/salt/minion.d/susemanager.conf: No such file or directory
./bootstrap.sh: line 812: /etc/salt/minion.d/susemanager.conf: No such file or directory
./bootstrap.sh: line 813: /etc/salt/minion.d/susemanager.conf: No such file or directory
./bootstrap.sh: line 814: /etc/salt/minion.d/susemanager.conf: No such file or directory
./bootstrap.sh: line 815: /etc/salt/minion.d/susemanager.conf: No such file or directory
./bootstrap.sh: line 818: /etc/salt/minion.d/susemanager.conf: No such file or directory
* removing TLS certificate used for bootstrap

so it looks like the susemanager.conf isn't getting copied to the dir correctly.  In working my way backwards, I copied the susemanager.conf to the salt dir and the bootstrap.sh ran successfully, but no machine was registered.

In more troubleshoot, I went to try to register the key in salt, only to discover the salt page on the uyuni server is hanging.  I checked the service status and all of them were green.  I then rebooted the box just to be on the safe side and got 

2020-07-02 09:14:08,187 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-1] ERROR com.redhat.rhn.frontend.servlets.SessionFilter - Error during transaction. Rolling back
java.lang.RuntimeException: com.suse.salt.netapi.exception.SaltException: java.net.ConnectException: Connection refused
	at com.suse.manager.webui.services.impl.SaltService.callSync(SaltService.java:376)
	at com.suse.manager.webui.services.impl.SaltService.callSync(SaltService.java:326)
	at com.suse.manager.webui.services.impl.SaltService.getFingerprints(SaltService.java:406)
	at com.suse.manager.webui.controllers.MinionsAPI.listKeys(MinionsAPI.java:113)
	at com.suse.manager.webui.utils.SparkApplicationHelper.lambda$withUser$1(SparkApplicationHelper.java:78)
	at spark.RouteImpl$1.handle(RouteImpl.java:72)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
	at spark.servlet.SparkFilter.doFilter(SparkFilter.java:173)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.redhat.rhn.frontend.servlets.AuthFilter.doFilter(AuthFilter.java:98)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.opensymphony.module.sitemesh.filter.PageFilter.parsePage(PageFilter.java:142)
	at com.opensymphony.module.sitemesh.filter.PageFilter.doFilter(PageFilter.java:58)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.redhat.rhn.frontend.servlets.LocalizedEnvironmentFilter.doFilter(LocalizedEnvironmentFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.redhat.rhn.frontend.servlets.EnvironmentFilter.doFilter(EnvironmentFilter.java:103)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.redhat.rhn.frontend.servlets.SessionFilter.doFilter(SessionFilter.java:55)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.redhat.rhn.frontend.servlets.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:97)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:433)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1591)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.suse.salt.netapi.exception.SaltException: java.net.ConnectException: Connection refused
	at com.suse.manager.webui.services.impl.SaltService.adaptException(SaltService.java:951)
	at com.suse.manager.webui.services.impl.SaltService.callSync(SaltService.java:370)
	... 46 more
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:173)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:147)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:350)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:221)
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)

in the apache error_log.

I am unsure what else to try or do to get the clients registered.

**Comment by ewenf-uindy** [comment]
This is two separate issue, one of which I solved.  Opening a new issue.
