### ISSUE TITLE
OL7 not pulling updates

### ISSUE THREAD

**Issue by ewenf-uindy** [uyuni-project/uyuni#2421]
When I install an Oracle Linux 7, the system shows no packages are needed/required for update.  I check the box with yum update and there are 200+ updates needed.  The only error message, that I know where to look for, is under the notifications tab saying '

Error | State apply failed | Error running state.apply on: uyuni-oracle7.test.uindy.edu
-- | -- | --

The server also shows no IP addresses.  It is using Salt.  The bootstrap.sh ran fine with no errors.  

**Server version**

Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2020.06-78.2.uyuni
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2020.06-78.2.uyuni.src
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.

The only thing I changed in the bootstrap.sh was the activation key.  Nothing was changed in the config file.

**Comment by lbenaglia** [comment]
I've the same issue with a CentOS 8 minion. If I try to run "salt '*' state.apply" from master I get the following error:

trliveuyuni:~ # salt '*' state.apply
centos8tmpl.online.gruppo24.net:
----------
          ID: mgrchannels_susemanagerplugin_dnf
    Function: file.managed
        Name: /usr/lib/python3.6/site-packages/dnf-plugins/susemanagerplugin.py
      Result: True
     Comment: File /usr/lib/python3.6/site-packages/dnf-plugins/susemanagerplugin.py is in the correct state
     Started: 11:34:04.963000
    Duration: 68.337 ms
     Changes:
----------
          ID: mgrchannels_susemanagerplugin_conf_dnf
    Function: file.managed
        Name: /etc/dnf/plugins/susemanagerplugin.conf
      Result: True
     Comment: File /etc/dnf/plugins/susemanagerplugin.conf is in the correct state
     Started: 11:34:05.031500
    Duration: 55.233 ms
     Changes:
----------
          ID: mgrchannels_repo
    Function: file.managed
        Name: /etc/yum.repos.d/susemanager:channels.repo
      Result: True
     Comment: File /etc/yum.repos.d/susemanager:channels.repo is in the correct state
     Started: 11:34:05.087428
    Duration: 42.749 ms
     Changes:
----------
          ID: mgrchannels_dnf_clean_all
    Function: cmd.run
        Name: /usr/bin/dnf clean all
      Result: True
     Comment: State was not run because none of the onchanges reqs changed
     Started: 11:34:05.131427
    Duration: 0.005 ms
     Changes:
----------
          ID: /etc/pki/ca-trust/source/anchors/RHN-ORG-TRUSTED-SSL-CERT
    Function: file.managed
      Result: True
     Comment: File /etc/pki/ca-trust/source/anchors/RHN-ORG-TRUSTED-SSL-CERT is in the correct state
     Started: 11:34:05.131504
    Duration: 21.652 ms
     Changes:
----------
          ID: update-ca-certificates
    Function: cmd.run
        Name: /usr/bin/update-ca-trust extract
      Result: True
     Comment: State was not run because none of the onchanges reqs changed
     Started: 11:34:05.153703
    Duration: 0.004 ms
     Changes:
----------
          ID: sync_states
    Function: mgrcompat.module_run
        Name: saltutil.sync_states
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3.6/site-packages/salt/utils/decorators/__init__.py", line 360, in _call_function
                  return self._function(*args, **kwargs)
              TypeError: _run() missing 1 required positional argument: 'name'

              During handling of the above exception, another exception occurred:

              Traceback (most recent call last):
                File "/usr/lib/python3.6/site-packages/salt/state.py", line 2154, in call
                  *cdata["args"], **cdata["kwargs"]
                File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2087, in wrapper
                  return f(*args, **kwargs)
                File "/var/cache/salt/minion/extmods/states/mgrcompat.py", line 85, in module_run
                  ret = module.run(**new_kwargs)
                File "/usr/lib/python3.6/site-packages/salt/utils/decorators/__init__.py", line 746, in _decorate
                  return self._call_function(kwargs)
                File "/usr/lib/python3.6/site-packages/salt/utils/decorators/__init__.py", line 363, in _call_function
                  self._function, self._orig_f_name
              TypeError: replace() argument 1 must be str, not function
     Started: 11:34:05.155814
    Duration: 3.731 ms
     Changes:
----------
          ID: pkg_installed
    Function: pkg.installed
      Result: True
     Comment: No packages to install provided
     Started: 11:34:06.052152
    Duration: 1.491 ms
     Changes:
----------
          ID: pkg_removed
    Function: pkg.removed
      Result: True
     Comment: All specified packages are already absent
     Started: 11:34:06.053896
    Duration: 717.082 ms
     Changes:
----------
          ID: pkg_latest
    Function: pkg.latest
      Result: True
     Comment: No packages to install provided
     Started: 11:34:06.771380
    Duration: 1.407 ms
     Changes:
----------
          ID: disable_spacewalksd
    Function: service.dead
        Name: rhnsd
      Result: True
     Comment: The named service rhnsd is not available
     Started: 11:34:06.773945
    Duration: 22.785 ms
     Changes:
----------
          ID: disable_spacewalk-update-status
    Function: service.dead
        Name: spacewalk-update-status
      Result: True
     Comment: The named service spacewalk-update-status is not available
     Started: 11:34:06.797006
    Duration: 13.772 ms
     Changes:
----------
          ID: disable_osad
    Function: service.dead
        Name: osad
      Result: True
     Comment: The named service osad is not available
     Started: 11:34:06.811034
    Duration: 13.546 ms
     Changes:
----------
          ID: remove_traditional_stack_all
    Function: pkg.removed
      Result: True
     Comment: All specified packages are already absent
     Started: 11:34:06.824828
    Duration: 8.234 ms
     Changes:
----------
          ID: remove_traditional_stack
    Function: pkg.removed
      Result: True
     Comment: All specified packages are already absent
     Started: 11:34:06.833203
    Duration: 673.392 ms
     Changes:
----------
          ID: remove_suse_register_info_rh
    Function: pkg.removed
        Name: suseRegisterInfo
      Result: True
     Comment: All specified packages are already absent
     Started: 11:34:07.506801
    Duration: 6.457 ms
     Changes:
----------
          ID: mgr_remove_management_key_grains
    Function: file.replace
        Name: /etc/salt/minion.d/susemanager.conf
      Result: True
     Comment: onlyif condition is false
     Started: 11:34:07.513375
    Duration: 16.663 ms
     Changes:
----------
          ID: mgr_remove_activation_key_grains
    Function: file.replace
        Name: /etc/salt/minion.d/susemanager.conf
      Result: True
     Comment: onlyif condition is false
     Started: 11:34:07.530263
    Duration: 16.397 ms
     Changes:
----------
          ID: mgr_salt_minion
    Function: pkg.installed
        Name: salt-minion
      Result: True
     Comment: All specified packages are already installed
     Started: 11:34:07.546877
    Duration: 20.007 ms
     Changes:
----------
          ID: mgr_salt_minion
    Function: service.running
        Name: salt-minion
      Result: True
     Comment: The service salt-minion is already running
     Started: 11:34:07.567006
    Duration: 32.112 ms
     Changes:

Summary for centos8tmpl.online.gruppo24.net
-------------
Succeeded: 19
Failed:     1
-------------
Total states run:     20
Total run time:    1.735 s
ERROR: Minions returned with non-zero exit code
trliveuyuni:~ #

I'm using Uyuni 2020.07 on a openSUSE Leap 15.2 VM.

**Comment by mcalmer** [comment]
@ewenf-uindy as this report is a bit older I have to ask if this is still a problem or if we can close this issue?

**Comment by ewenf-uindy** [comment]
this is resolved

---------------

Len Ewen

Systems Administrator 1

Information Technology

University of Indianapolis

(317) 788-3362

[image: UIndyIT.jpg]

Confidentiality Notice: This communication and/or its content are for the
sole use of the intended recipient, and may be privileged, confidential, or
otherwise protected from disclosure by law. If you are not the intended
recipient, please notify the sender and then delete all copies of it.
Unless you are the intended recipient, your use or dissemination of the
information contained in this communication may be illegal.
