### ISSUE TITLE
[repo sync 2020.09] Exception type <class 'spacewalk.server.importlib.importLib.InvalidPackageError'>

### ISSUE THREAD

**Issue by StefanSa** [uyuni-project/uyuni#2647]
# Additional Information
We have been seeing this error message on repo-sync since 2020.9.
Only the channel 'opensuse_leap15_2-x86_64' is affected.

```
2020/09/24 03:30:00 +02:00 Command: ['/usr/bin/spacewalk-repo-sync', '--channel', 'opensuse_leap15_2-x86_64', '--type', 'yum', '--non-interactive', '--latest']
2020/09/24 03:30:00 +02:00 Sync of channel started.
2020/09/24 03:30:19 +02:00 Repo URL: http://download.opensuse.org/distribution/leap/15.2/repo/oss/
2020/09/24 03:30:19 +02:00     Packages in repo:             38560
2020/09/24 03:31:31 +02:00     Packages already synced:      38491
2020/09/24 03:31:31 +02:00     Packages to sync:                 2
2020/09/24 03:31:31 +02:00     New packages to download:         2
2020/09/24 03:31:31 +02:00   Downloading packages:
2020/09/24 03:32:32 +02:00     1/2 : kicad-packages3D-5.1.5-lp152.1.1.noarch.rpm
2020/09/24 03:33:32 +02:00 ERROR: Download failed: http://download.opensuse.org/distribution/leap/15.2/repo/oss/noarch/system-user-root-20190513-lp152.1.100.noarch.rpm - [Errno 14] HTTP Error 504 - Gateway Timeout.
2020/09/24 03:33:32 +02:00     2/2 : system-user-root-20190513-lp152.1.100.noarch.rpm (failed)
2020/09/24 03:33:33 +02:00 Importing packages started.
2020/09/24 03:33:33 +02:00 
2020/09/24 03:33:33 +02:00   Importing packages to DB:
2020/09/24 03:33:34 +02:00   Package batch #1 of 1 completed...
2020/09/24 03:33:34 +02:00 Importing packages finished.
2020/09/24 03:33:34 +02:00 
2020/09/24 03:33:34 +02:00   Linking packages to the channel.
2020/09/24 03:33:34 +02:00 Unexpected error: <class 'spacewalk.server.importlib.importLib.InvalidPackageError'>
2020/09/24 03:33:35 +02:00 Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 592, in sync
    ret = self.import_packages(plugin, data['id'], url, is_non_local_repo)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 1107, in import_packages
    importer.run()
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/importLib.py", line 777, in run
    self.submit()
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/packageImport.py", line 126, in submit
    self.backend.lookupPackages(self.batch, self.checksums)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 822, in lookupPackages
    raise_with_tb(not_found[0], not_found[1])
  File "/usr/lib/python3.6/site-packages/uyuni/common/usix.py", line 77, in raise_with_tb
    raise value
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 814, in lookupPackages
    self.__lookupObjectCollection([package], 'rhnPackage')
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 2493, in __lookupObjectCollection
    raise InvalidPackageError(object, "Could not find object %s in table %s" % (object, tableName))
spacewalk.server.importlib.importLib.InvalidPackageError: Could not find object [<<class 'spacewalk.server.importlib.importLib.IncompletePackage'> instance; attributes={'package_id': None, 'name': 'kicad-packages3D', 'epoch': None, 'version': '5.1.5', 'release': 'lp152.1.1', 'arch': 'noarch', 'org_id': 1, 'package_size': None, 'last_modified': None, 'md5sum': None, 'channels': {141: 'opensuse_leap15_2-x86_64'}, 'checksum_list': None, 'checksum': 'fbb64b0589fe2aad9cf70bb93d0c09617def5ee35321f2c11cfab45801c92695', 'checksum_type': 'sha256', 'checksums': {'sha256': 'fbb64b0589fe2aad9cf70bb93d0c09617def5ee35321f2c11cfab45801c92695'}, 'name_id': 59199, 'evr_id': 28856, 'package_arch_id': 100, 'nevra_id': 124635, 'checksum_id': 8180811}] in table rhnPackage

```

## Version of Uyuni Server and Proxy (if used)
`zypper info Uyuni-Server-release` _and_ `zypper info Uyuni-Proxy-release` _(if used)_

```
zypper info Uyuni-Server-release
Repository-Daten werden geladen...
Installierte Pakete werden gelesen...


Informationen zu Paket Uyuni-Server-release:
--------------------------------------------
Repository         : Uyuni Server Stable
Name               : Uyuni-Server-release
Version            : 2020.09-98.2.uyuni
Arch               : x86_64
Anbieter           : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level      : Stufe 3
Installierte Größe : 1,4 KiB
Installiert        : Ja
Status             : aktuell
Quellpaket         : Uyuni-Server-release-2020.09-98.2.uyuni.src
Zusammenfassung    : Uyuni Server
Beschreibung       :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

**Comment by Shirocco88** [comment]
> 2020/09/24 03:33:32 +02:00 ERROR: Download failed: 
http://download.opensuse.org/distribution/leap/15.2/repo/oss/noarch/system-user-root-20190513-lp152.1.100.noarch.rpm - 
[Errno 14] HTTP Error 504 - Gateway Timeout.

This seems no uyuni problem;

@StefanSa 
What is the output of command "wget http://download.opensuse.org/distribution/leap/15.2/repo/oss/noarch/system-user-root-20190513-lp152.1.100.noarch.rpm" ?
Which OpenSuSE Mirror are you using ?

**Comment by StefanSa** [comment]
@Shirocco88 
the cause of the packet in question was the FW's IPS.
```
SERVER-WEBAPP /etc /passwd 
```
An exception in the IPS fixed the problem
