### ISSUE TITLE
prometheus fails to scrape for mgr-clients - can't unmarshal struct to slice

### ISSUE THREAD

**Issue by dvosburg** [uyuni-project/uyuni#2651]
# Additional Information

_The following information is very important in order to help us to help you. Omission of the following details cause delays or could receive no attention at all._

## Version of Uyuni Server and Proxy (if used)
`zypper info Uyuni-Server-release` _and_ `zypper info Uyuni-Proxy-release` _(if used)_
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2020.09-98.2.uyuni
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2020.09-98.2.uyuni.src
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.

## Details about issue
_Include as many details as you can. The procedure you are following,  the commands you are running, logs (specially from_ `/var/log/rhn/`_)..._
_In general: all that can help reproducing the issue or understanding it_

Prometheus formula deployed to openSUSE 15.2 client system, everything runs, server starts, mgr-clients scrape fails with this error:
Sep 24 23:06:03 tirian prometheus[6884]: level=error ts=2020-09-25T03:06:03.228Z caller=refresh.go:98 component="discovery manager scrape" discovery=uyuni msg="Unable to refresh target groups" err=" err="Unable to get systems combined formula data: error: type mismatch - can't unmarshal struct to slice"

No client system data is displayed in Targets.

**Comment by witekest** [comment]
I understand this happens during the upgrade to _Uyuni 2020.09_, right?
Could you please provide the versions of the packages before and after upgrade:
* `golang-github-prometheus-prometheus` (monitoring server)
* `prometheus-exporters-formula` (SUMA server)

**Comment by cavalheiro** [comment]
@dvosburg provided to me the current installed versions of Prometheus packages:
```

S  | Name                                   | Type    | Version           | Arch   | Repository
---+----------------------------------------+---------+-------------------+--------+---------------------------------------------------
i+ | golang-github-prometheus-alertmanager  | package | 0.21.0-22.1.uyuni | x86_64 | Uyuni Client Tools for openSUSE Leap 15.2 (x86_64)
i+ | golang-github-prometheus-node_exporter | package | 1.0.1-2.1.uyuni   | x86_64 | Uyuni Client Tools for openSUSE Leap 15.2 (x86_64)
i+ | golang-github-prometheus-prometheus    | package | 2.18.0-4.1.uyuni  | x86_64 | Uyuni Client Tools for openSUSE Leap 15.2 (x86_64)

**Comment by dvosburg** [comment]
Here are the prometheus packages on the Uyuni server:

```brie:~ # zypper se -si prometheus
Loading repository data...
Reading installed packages...

S | Name                                   | Type    | Version         | Arch   | Repository
--+----------------------------------------+---------+-----------------+--------+--------------------
i | golang-github-prometheus-node_exporter | package | 1.0.1-1.2.uyuni | x86_64 | Uyuni Server Stable
i | prometheus-client-java                 | package | 0.3.0-1.7.uyuni | noarch | Uyuni Server Stable
i | prometheus-exporters-formula           | package | 0.7.1-1.1.uyuni | noarch | Uyuni Server Stable
i | prometheus-formula                     | package | 0.2.1-2.1.uyuni | noarch | Uyuni Server Stable
i | prometheus-jmx_exporter                | package | 0.3.1-3.8.uyuni | noarch | Uyuni Server Stable
i | prometheus-jmx_exporter-tomcat         | package | 0.3.1-3.8.uyuni | noarch | Uyuni Server Stable
```

**Comment by witekest** [comment]
Could you please run Prometheus with debug log level `--log.level=debug` and share the logs, please?

**Comment by witekest** [comment]
Please also provide the runtime and build information obtained from _http://\<prometheus\>:9090/status_ .

**Comment by dvosburg** [comment]
Uptime | 2020-09-25 03:05:02.645968139 +0000 UTC
-- | --
/
Successful
2020-09-25 03:05:02 +0000 UTC
0
10918
2
 
 
15d

**Comment by dvosburg** [comment]
[Prometheus Time Series Collection and Processing Server.pdf](https://github.com/uyuni-project/uyuni/files/5319087/Prometheus.Time.Series.Collection.and.Processing.Server.pdf)

**Comment by dvosburg** [comment]
file:///home/don/prometheus-log-debug.txt

**Comment by dvosburg** [comment]
[prometheus-log-debug.txt](https://github.com/uyuni-project/uyuni/files/5319160/prometheus-log-debug.txt)

**Comment by dvosburg** [comment]
Workaround:  Issue resolved by UN-checking 'Enable reverse proxy' on the Prometheus Exporter formula settings.  Upgrade to 2020.09 had enabled it for all systems.

Looks like the new "feature" is causing problems.

**Comment by witekest** [comment]
I can see following error messages in reporter's `/var/log/rhn/rhn_web_api.log`:

```
[2020-09-30 00:00:03,338] INFO  - REQUESTED FROM: 10.3.0.21 CALL: formula.getCombinedFormulaDataByServerIds(uyuni, prometheus-exporters, [1000010009, 1000010008, 1000010010, 1000010012, 1000010002, 1000010004, 1000010007, 1000010000, 1000010014, 1000010006, 1000010013, 1000010003, 1000010001, 1000010005, 1000010011]) CALLER: (uyuni) TIME: 0.012 seconds
[2020-09-30 00:00:03,338] ERROR - postProcess error CALL: formula getCombinedFormulaDataByServerIds
java.lang.IllegalStateException: Stopwatch is not running. 
	at org.apache.commons.lang3.time.StopWatch.stop(StopWatch.java:255)
	at com.redhat.rhn.frontend.xmlrpc.LoggingInvocationProcessor.onException(LoggingInvocationProcessor.java:134)
	at redstone.xmlrpc.XmlRpcDispatcher.processException(XmlRpcDispatcher.java:268)
	at redstone.xmlrpc.XmlRpcDispatcher.dispatch(XmlRpcDispatcher.java:137)
	at com.redhat.rhn.frontend.xmlrpc.RhnXmlRpcServer.execute(RhnXmlRpcServer.java:54)
	at com.redhat.rhn.frontend.xmlrpc.XmlRpcServlet.doPost(XmlRpcServlet.java:165)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.opensymphony.module.sitemesh.filter.PageFilter.parsePage(PageFilter.java:142)
	at com.opensymphony.module.sitemesh.filter.PageFilter.doFilter(PageFilter.java:58)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.redhat.rhn.frontend.servlets.LocalizedEnvironmentFilter.doFilter(LocalizedEnvironmentFilter.java:70)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.redhat.rhn.frontend.servlets.EnvironmentFilter.doFilter(EnvironmentFilter.java:103)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.redhat.rhn.frontend.servlets.SessionFilter.doFilter(SessionFilter.java:55)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.redhat.rhn.frontend.servlets.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:97)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:432)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1591)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

The last occurence on 2020-10-04 12:23:21.

**Comment by witekest** [comment]
Still need to cherry-pick to `Manager-4.0`.
Also work in progress to make server side serialization more robust.

**Comment by witekest** [comment]
Fix provided in [prometheus-exporters-formula](https://github.com/SUSE/salt-formulas/pull/87). We decided [not to change server side serialization](https://github.com/uyuni-project/uyuni/pull/2729).
