### ISSUE TITLE
server error on attaching sources to content lifecycle project

### ISSUE THREAD

**Issue by ktsamis** [uyuni-project/uyuni#2906]
# Additional Information

I created a content lifecycle project because I want to manage a centos 8 salt-ssh minion with the appstream module. I created the project and tried to add Sources with this info:

```
Type
Channel
New Base Channel
CentOS 8 (ppc64le)
Choose the channel to be elected as the new base channel
Child Channels (3)
    CentOS 8 (ppc64le) (3)
Uyuni Client Tools for CentOS 8 (ppc64le) (Development)  
CentOS 8 AppStream (ppc64le)  
```
I selected all the available channels for centos 8 sources.
When I click Save I get `Server error, please check log files.` and I see the error below in `Details about issue` in the rhn_web_ui.log.

## Version of Uyuni Server and Proxy (if used)

`zypper info Uyuni-Server-release` _and_ `zypper info Uyuni-Proxy-release` _(if used)_
```Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-devel
Name           : Uyuni-Server-release
Version        : 2020.11-99.2.uyuni
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
```
No proxy used

## Details about issue
_Include as many details as you can. The procedure you are following,  the commands you are running, logs (specially from_ `/var/log/rhn/`_)..._
_In general: all that can help reproducing the issue or understanding it_

```2020-11-25 17:59:15,367 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-9] ERROR com.redhat.rhn.frontend.servlets.SessionFilter - Error during transaction. Rolling back
java.lang.RuntimeException: Cannot resolve modular dependencies. 'streams' (1)
        at com.redhat.rhn.domain.contentmgmt.modulemd.ModulemdApi.getPackagesForModules(ModulemdApi.java:106)
        at com.redhat.rhn.manager.contentmgmt.DependencyResolver.resolveModularDependencies(DependencyResolver.java:131)
        at com.redhat.rhn.manager.contentmgmt.DependencyResolver.resolveFilters(DependencyResolver.java:108)
        at com.redhat.rhn.domain.contentmgmt.validation.ModularDependencyValidator.validate(ModularDependencyValidator.java:80)
        at com.redhat.rhn.domain.contentmgmt.validation.ContentProjectValidator.lambda$validate$0(ContentProjectValidator.java:63)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at com.redhat.rhn.domain.contentmgmt.validation.ContentProjectValidator.validate(ContentProjectValidator.java:64)
        at com.suse.manager.webui.controllers.contentmanagement.mappers.ResponseMappers.mapProjectFromDB(ResponseMappers.java:158)
        at com.suse.manager.webui.controllers.contentmanagement.handlers.ControllerApiUtils.fullProjectJsonResponse(ControllerApiUtils.java:67)
        at com.suse.manager.webui.controllers.contentmanagement.handlers.ProjectSourcesApiController.updateContentSoftwareSources(ProjectSourcesApiController.java:91)
        at com.suse.manager.webui.utils.SparkApplicationHelper.lambda$withUser$1(SparkApplicationHelper.java:79)
        at spark.RouteImpl$1.handle(RouteImpl.java:72)
        at spark.http.matching.Routes.execute(Routes.java:61)
        at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
        at spark.servlet.SparkFilter.doFilter(SparkFilter.java:173)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.redhat.rhn.frontend.servlets.AuthFilter.doFilter(AuthFilter.java:98)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.opensymphony.module.sitemesh.filter.PageFilter.parsePage(PageFilter.java:142)
        at com.opensymphony.module.sitemesh.filter.PageFilter.doFilter(PageFilter.java:58)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.redhat.rhn.frontend.servlets.LocalizedEnvironmentFilter.doFilter(LocalizedEnvironmentFilter.java:70)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.redhat.rhn.frontend.servlets.EnvironmentFilter.doFilter(EnvironmentFilter.java:103)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.redhat.rhn.frontend.servlets.SessionFilter.doFilter(SessionFilter.java:55)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.redhat.rhn.frontend.servlets.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:97)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:432)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1591)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by ktsamis** [comment]
I can verify that this fixes the server error. Thanks @cbbayburt :1st_place_medal:
