### ISSUE TITLE
Uyuni 2021.01 for Tumbleweed bootstrap is lacking python38-distro package

### ISSUE THREAD

**Issue by afaerber** [uyuni-project/uyuni#3274]
# Additional Information

## Version of Uyuni Server
`zypper info Uyuni-Server-release`:
```
Repository     : Uyuni
Name           : Uyuni-Server-release
Version        : 2021.01-107.1.uyuni
Arch           : aarch64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2021.01-107.1.uyuni.src
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.

```

## Details about issue
Freshly installed Uyuni 2021.01 on aarch64 registering its first (up-to-date) Tumbleweed 20210203 aarch64 system failed during bootstrap in the web UI as follows:
```
Traceback (most recent call last):
File "/var/tmp/.root_74f0ca_salt/pyall/salt/version.py", line 15, in <module>
from platform import linux_distribution as _deprecated_linux_distribution
ImportError: cannot import name 'linux_distribution' from 'platform' (/usr/lib64/python3.8/platform.py)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/var/tmp/.root_74f0ca_salt/salt-call", line 27, in <module>
salt_call()
File "/var/tmp/.root_74f0ca_salt/pyall/salt/scripts.py", line 440, in salt_call
import salt.cli.call
File "/var/tmp/.root_74f0ca_salt/pyall/salt/cli/call.py", line 5, in <module>
import salt.utils.parsers
File "/var/tmp/.root_74f0ca_salt/pyall/salt/utils/parsers.py", line 29, in <module>
import salt.config as config
File "/var/tmp/.root_74f0ca_salt/pyall/salt/config/__init__.py", line 24, in <module>
import salt.utils.data
File "/var/tmp/.root_74f0ca_salt/pyall/salt/utils/data.py", line 17, in <module>
import salt.utils.dictupdate
File "/var/tmp/.root_74f0ca_salt/pyall/salt/utils/dictupdate.py", line 25, in <module>
from salt.utils.decorators.jinja import jinja_filter
File "/var/tmp/.root_74f0ca_salt/pyall/salt/utils/decorators/__init__.py", line 18, in <module>
import salt.utils.args
File "/var/tmp/.root_74f0ca_salt/pyall/salt/utils/args.py", line 21, in <module>
import salt.utils.versions
File "/var/tmp/.root_74f0ca_salt/pyall/salt/utils/versions.py", line 29, in <module>
import salt.version
File "/var/tmp/.root_74f0ca_salt/pyall/salt/version.py", line 22, in <module>
from distro import linux_distribution
ModuleNotFoundError: No module named 'distro'
```

After I installed `python38-distro` and re-tried the bootstrap, it completed okay and lists the system as registered.

Possibly a different issue: On the target system, all repos are disabled afterwards and `zypper dup` suggests to remove 345 packages.
@juliogonzalez @ggardet

**Comment by juliogonzalez** [comment]
Yes, openSUSE Tumbleweed is not supported right now as a client, and for openSUSE Leap aarch64 is not announced as stable.

However I wonder why that stracktrace is happening, instead of python38-distro being installed: @brejoc any idea?

**Comment by agraul** [comment]
This is unexpected, `python3-salt` should pull `python38-distro` in. @afaerber where did you get Salt from, official TW repo?
