### ISSUE TITLE
Debian 10 SSH registration broken on Uyuni 2021.04

### ISSUE THREAD

**Issue by phibid** [uyuni-project/uyuni#3624]
# Additional Information

Since the upgrade of Uyuni to 2021.04, I am not able to SSH register Debian 10 Buster servers anymore. Here is the complete stack trace from the log `/var/log/rhn/rhn_web_ui.log`

```
2021-04-26 22:02:16,054 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-3] ERROR com.suse.manager.webui.controllers.utils.AbstractMinionBootstrapper - States failed during bootstrap: pkg_|-install_gnupg_debian_|-i
nstall_gnupg_debian_|-latest(retcode=2): No information found for 'gnupg'.
mgrcompat_|-trust_suse_manager_tools_deb_gpg_key_|-pkg.add_repo_key_|-module_run(retcode=2): Module function pkg.add_repo_key executed
2021-04-26 22:02:16,057 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-3] ERROR com.redhat.rhn.frontend.xmlrpc.BaseHandler - Error calling method:
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.redhat.rhn.frontend.xmlrpc.BaseHandler.invoke(BaseHandler.java:143)
        at redstone.xmlrpc.XmlRpcDispatcher.dispatch(XmlRpcDispatcher.java:123)
        at com.redhat.rhn.frontend.xmlrpc.RhnXmlRpcServer.execute(RhnXmlRpcServer.java:53)
        at com.redhat.rhn.frontend.xmlrpc.XmlRpcServlet.doPost(XmlRpcServlet.java:164)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.opensymphony.module.sitemesh.filter.PageFilter.parsePage(PageFilter.java:142)
        at com.opensymphony.module.sitemesh.filter.PageFilter.doFilter(PageFilter.java:58)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.redhat.rhn.frontend.servlets.LocalizedEnvironmentFilter.doFilter(LocalizedEnvironmentFilter.java:69)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.redhat.rhn.frontend.servlets.EnvironmentFilter.doFilter(EnvironmentFilter.java:99)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.redhat.rhn.frontend.servlets.SessionFilter.doFilter(SessionFilter.java:55)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.redhat.rhn.frontend.servlets.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:97)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:432)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1591)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.redhat.rhn.frontend.xmlrpc.BootstrapException: [pkg_|-install_gnupg_debian_|-install_gnupg_debian_|-latest(retcode=2): No information found for 'gnupg'., mgrcompat_|-trust_suse_manager_tools_deb_gpg_key_|-pkg.add_repo_key_|-module_run(retcode=2): Module function pkg.add_repo_key executed]
        at com.redhat.rhn.frontend.xmlrpc.system.XmlRpcSystemHelper.bootstrap(XmlRpcSystemHelper.java:142)
        at com.redhat.rhn.frontend.xmlrpc.system.SystemHandler.bootstrap(SystemHandler.java:7318)
        ... 48 more  
```
Ubuntu does not seem to be affected.

## Version of Uyuni Server and Proxy (if used)

```
# zypper info Uyuni-Server-release
Loading repository data...
Reading installed packages...


Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2021.04-122.3.uyuni
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2021.04-122.3.uyuni.src
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

**Comment by Shirocco88** [comment]
@phibid 
it seams there is a problem installing gnupg package on your debian10 client:

Uyuni source code:
```
susemanager-utils/susemanager-sls/salt/bootstrap/init.sls 
SNIP
{%- include 'channels/debiankeyring.sls' %}
install_gnupg_debian:
  pkg.latest:
    - pkgs:
      - gnupg
```

please do the following checks before bootstrapping:
1.) check if your repo config is valid:
```
debian10:/# apt update
```
2.) check if package gnupg can be installed:
```
debian10:/# apt install gnupg
```
if all checks are OK, please bootstrap again.

**Comment by phibid** [comment]
Just made the test, and indeed, I was able to register a Debian 10 server after the installation of `gnupg`.
Will try to add this step in our preseed file.

I am not sure to understand why this package is now needed debian 10 for a salt-ssh registration of Debian 10.

This was not necesarry in the previous Uyuni version and we have not changed the used iso.

**Comment by Shirocco88** [comment]
@phibid : Are you using "salt-ssh" as communication protocol ?

the only code change I could see, is "Gpg key for ssh minion #3352"

**Comment by phibid** [comment]
Yes, I use salt-ssh, and yes the issue I have now is because of this MR then :-)

I guess that this issue could be close. Perhaps that a note in a doc could be added regarding the installation of `gnupg`, as a prerequesite of registrating a Debian server through salt-ssh ?

**Comment by Shirocco88** [comment]
IMHO it is a bug of #3352 "handle GPG keys when bootstrapping ssh minions (bsc#1181847)"
and it should be troubleshooted and fixed

susemanager-utils/susemanager-sls/salt/ssh_bootstrap/init.sls 
```
{%- elif grains['os_family'] == 'Debian' %}
install_gnupg_debian:
  pkg.latest:
    - pkgs:
      - gnupg
{%- endif %}
```

**Comment by brejoc** [comment]
@mcalmer Could you please take a look here?

**Comment by mcalmer** [comment]
```
[pkg_|-install_gnupg_debian_|-install_gnupg_debian_|-latest(retcode=2): No information found for 'gnupg'.,
 mgrcompat_|-trust_suse_manager_tools_deb_gpg_key_|-pkg.add_repo_key_|-module_run(retcode=2): Module function pkg.add_repo_key executed]
```

`add_repo_key` cannot be executed without gnupg beeing installed. So far so good. I wonder if the first state tried to install it, but failed. Best would be, if we could see the whole state execution result incl. the execution order.

What I can see from the state, the order should be right:

bootstrap/init.sls (same for ssh_bootstrap/init.sls)
```
{%- elif grains['os_family'] == 'Debian' %}
install_gnupg_debian:
  pkg.latest:
    - pkgs:
      - gnupg
{%- endif %}

{% include 'channels/gpg-keys.sls' %}
```
First install gnupg and then execute gpg-keys.sls which add the keys.
But it seems that installing gnupg failed. Maybe because the gpg key is not trusted. A funny chicken & egg problem.

**Comment by mcalmer** [comment]
@phibid can you try out the changes in https://github.com/uyuni-project/uyuni/pull/3747 . You can simply change the files in your installation. You can find them in `/usr/share/susemanager/salt/` .
Main changes you should try:

- remove this block https://github.com/uyuni-project/uyuni/pull/3747/files#diff-68a0a907825f39ffb331c90b1443426866064e23da0c3811a605fa80d8d34aeeL130-L141 from bootstrap/init.sls and from ssh_bootstrap/init.sls
- add https://github.com/uyuni-project/uyuni/pull/3747/files#diff-9ec0ed75fd38f7fc8b177892aa7104c24dbe2c4f996a328dca94489e04724505R41-R45 to channels/gpg-keys.sls

The change for RES can be ignored for now. I think you do not use Expanded Support Product.

Would be good if you could try out if this fixes bootstrapping Debian 10 and report the results here.

**Comment by phibid** [comment]
@mcalmer If I am not wrong, this not seems to work. I have followed your instructions, and trying to register a Debian 10 without gngpu package installed, I get this error:

```
[2021-05-14 17:00:32,201] ERROR - REQUESTED FROM: 10.64.4.94 CALL: system.bootstrap(admin, uyuni07v, 22, root, ******, 1-debian10_ssh, 1000010030, 1) CALLER: (admin) TIME: 29.705 seconds
redstone.xmlrpc.XmlRpcFault: [pkg_|-install_gnupg_debian_|-install_gnupg_debian_|-latest(retcode=2): No information found for 'gnupg'., mgrcompat_|-trust_suse_manager_tools_deb_gpg_key_|-pkg.add_repo_key_|-module_run(retcode=2): Module function pkg.add_repo_key executed]
```

**Comment by mcalmer** [comment]
I try to reproduce it here. To do this I would like to know what sources your debian client has set up and what keys are trusted.

Please provide the output of the following commands:
```
$> find /etc/apt/
$> cat /etc/apt/sources.list
$> cat /etc/apt/sources.list.d/*
```

**Comment by phibid** [comment]
Here it is, on a freshly installed VM, with no gnupg package installed and with no registration attempt done yet:

```
root@uyuni07v : ~ # find /etc/apt/
/etc/apt/
/etc/apt/preferences.d
/etc/apt/apt.conf.d
/etc/apt/apt.conf.d/00trustcdrom
/etc/apt/apt.conf.d/01autoremove-kernels
/etc/apt/apt.conf.d/70debconf
/etc/apt/apt.conf.d/01autoremove
/etc/apt/apt.conf.d/20listchanges
/etc/apt/sources.list.d
/etc/apt/sources.list
/etc/apt/listchanges.conf
/etc/apt/trusted.gpg.d
/etc/apt/trusted.gpg.d/debian-archive-stretch-automatic.gpg
/etc/apt/trusted.gpg.d/debian-archive-buster-security-automatic.gpg
/etc/apt/trusted.gpg.d/debian-archive-jessie-stable.gpg
/etc/apt/trusted.gpg.d/debian-archive-stretch-security-automatic.gpg
/etc/apt/trusted.gpg.d/debian-archive-stretch-stable.gpg
/etc/apt/trusted.gpg.d/debian-archive-buster-stable.gpg
/etc/apt/trusted.gpg.d/debian-archive-jessie-security-automatic.gpg
/etc/apt/trusted.gpg.d/debian-archive-buster-automatic.gpg
/etc/apt/trusted.gpg.d/debian-archive-jessie-automatic.gpg
/etc/apt/auth.conf.d
```
```
root@uyuni07v : ~ # cat /etc/apt/sources.list
# deb http://XX.XX.XX.XX/pub/dists/debian10/iso buster main

deb http://XX.XX.XX.XX/pub/dists/debian10/iso buster main
deb-src http://XX.XX.XX.XX/pub/dists/debian10/iso buster main
```

```
root@uyuni07v : ~ # cat /etc/apt/sources.list.d/*
cat: '/etc/apt/sources.list.d/*': No such file or directory
```

**Comment by mcalmer** [comment]
I was able to reproduce the problem. The installation order is correct with the patch, but it can only work when gnupg is found and can be installed. Currently we do not have it in the bootstrap repository so another source is required.

I can see that you have the ISO configured. But maybe it was not available when you tried it?

I will add gnupg and some of its dependencies to the bootstrap repo. I hope onboarding is successfull even without other package source been available.
