### ISSUE TITLE
Uyuni Bugreport - Uyuni 2021.04 - CloudLinux 8 salt-ssh errors

### ISSUE THREAD

**Issue by ppc6446** [uyuni-project/uyuni#3800]
# Additional Information

CloudLinux 8 does not have client tools available, so I tried using salt-ssh.  The system is registered in the Uyuni WebUI and showing the list of installed packages, but salt-ssh commands are failing with a python stack trace.

## Version of Uyuni Server and Proxy (if used)
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2021.04-122.3.uyuni
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2021.04-122.3.uyuni.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.

## Details about issue
```
salt@snip:~> salt-ssh "snail" cmd.run "uptime"
[ERROR   ] An un-handled exception from the multiprocessing process 'Process-1' was caught:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/process.py", line 760, in wrapped_run_func
    return run_func()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/salt/client/ssh/__init__.py", line 521, in handle_routine
    **target)
  File "/usr/lib/python3.6/site-packages/salt/client/ssh/__init__.py", line 937, in __init__
    self.shell = salt.client.ssh.shell.gen_shell(opts, **args)
  File "/usr/lib/python3.6/site-packages/salt/client/ssh/shell.py", line 65, in gen_shell
    shell = Shell(opts, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/client/ssh/shell.py", line 93, in __init__
    self.host = host.strip('[]')
AttributeError: 'NoneType' object has no attribute 'strip'
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/site-packages/salt/utils/process.py", line 771, in wrapped_run_func
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3.6/site-packages/salt/ext/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/salt/utils/process.py", line 760, in wrapped_run_func
    return run_func()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/salt/client/ssh/__init__.py", line 521, in handle_routine
    **target)
  File "/usr/lib/python3.6/site-packages/salt/client/ssh/__init__.py", line 937, in __init__
    self.shell = salt.client.ssh.shell.gen_shell(opts, **args)
  File "/usr/lib/python3.6/site-packages/salt/client/ssh/shell.py", line 65, in gen_shell
    shell = Shell(opts, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/client/ssh/shell.py", line 93, in __init__
    self.host = host.strip('[]')
AttributeError: 'NoneType' object has no attribute 'strip'
[ERROR   ] Target 'None' did not return any data, probably due to an error.
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: join() argument must be str or bytes, not 'NoneType'
Traceback (most recent call last):
  File "/usr/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/lib/python3.6/site-packages/salt/scripts.py", line 470, in salt_ssh
    client.run()
  File "/usr/lib/python3.6/site-packages/salt/cli/ssh.py", line 24, in run
    ssh.run()
  File "/usr/lib/python3.6/site-packages/salt/client/ssh/__init__.py", line 784, in run
    self.cache_job(jid, host, ret[host], fun)
  File "/usr/lib/python3.6/site-packages/salt/client/ssh/__init__.py", line 710, in cache_job
    'fun': fun})
  File "/usr/lib/python3.6/site-packages/salt/returners/local_cache.py", line 147, in returner
    hn_dir = os.path.join(jid_dir, load['id'])
  File "/usr/lib64/python3.6/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib64/python3.6/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'
Traceback (most recent call last):
  File "/usr/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/lib/python3.6/site-packages/salt/scripts.py", line 470, in salt_ssh
    client.run()
  File "/usr/lib/python3.6/site-packages/salt/cli/ssh.py", line 24, in run
    ssh.run()
  File "/usr/lib/python3.6/site-packages/salt/client/ssh/__init__.py", line 784, in run
    self.cache_job(jid, host, ret[host], fun)
  File "/usr/lib/python3.6/site-packages/salt/client/ssh/__init__.py", line 710, in cache_job
    'fun': fun})
  File "/usr/lib/python3.6/site-packages/salt/returners/local_cache.py", line 147, in returner
    hn_dir = os.path.join(jid_dir, load['id'])
  File "/usr/lib64/python3.6/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib64/python3.6/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'
```

To cross-check, a salt-ssh cmd.run uptime was run successfully from the same Uyuni server for an AlmaLinux client

**Comment by Shirocco88** [comment]
@ppc6446 
Which salt-minion package are you using ?
from saltstack ???

**Comment by Shirocco88** [comment]
@ppc6446
could you please check if salt proper:
 
salt-call --versions-report
salt-call --local grains.items

**Comment by ppc6446** [comment]
There is no salt on the CloudLinux 8 system, and none available in its repos.  

My hope using salt-ssh was that salt wouldn't need to be installed there because no client tools channel is available specifically for CloudLinux 8 yet.   As it appears to be EL8-compatible, the tools channel for AlmaLinux 8 et al should work for except for the name reported in /etc/os-release

**Comment by Shirocco88** [comment]
>> The CloudLinux8 system is registered in the Uyuni WebUI and showing the list of installed packages, but salt-ssh commands are failing with a python stack trace.

How did you onboard this CloudLinux8 System ?
via Web-UI bootstraping ?
did you patch /etc/os-release ?

**Comment by ppc6446** [comment]
Yes, it was onboarded by WebUI bootstrapping with `Manage system completely via SSH (will not install an agent)` checked

/etc/os-release on the client was left untouched:

```
cloudlinux# cat /etc/os-release
NAME="CloudLinux"
VERSION="8.3 (Pavel Belyayev)"
ID="cloudlinux"
ID_LIKE="rhel fedora centos"
VERSION_ID="8.3"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CloudLinux 8.3 (Pavel Belyayev)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:cloudlinux:cloudlinux:8.3:GA:server"
HOME_URL="https://www.cloudlinux.com/"
BUG_REPORT_URL="https://www.cloudlinux.com/support"
```

**Comment by Shirocco88** [comment]
is there "salt-call" on your CloudLinux8 available ?

if yes, then generate output:
salt-call --versions-report
salt-call --local grains.items

**Comment by ppc6446** [comment]
I installed the major release according to the saltstack.io docs:

```
sudo rpm --import https://repo.saltproject.io/py3/redhat/8/x86_64/3003/SALTSTACK-GPG-KEY.pub
curl -fsSL https://repo.saltproject.io/py3/redhat/8/x86_64/3003.repo | sudo tee /etc/yum.repos.d/salt.repo
yum clean expire-cache
sudo yum install salt-minion
```

```
cloudlinux# salt-call --versions-report
Salt Version:
          Salt: 3003

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov  6 2020, 09:39:16)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 19.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: cloudlinux 8.3 Pavel Belyayev
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-147.8.1.el8.lve.1.x86_64
        system: Linux
       version: CloudLinux 8.3 Pavel Belyayev

cloudlinux#  salt-call --local grains.items
local:
    ----------
    biosreleasedate:
        12/12/2018
    biosversion:
        6.00
    cpu_flags:
        - fpu
        - vme
        - de
        - pse
        - tsc
        - msr
        - pae
        - mce
        - cx8
        - apic
        - sep
        - mtrr
        - pge
        - mca
        - cmov
        - pat
        - pse36
        - clflush
        - mmx
        - fxsr
        - sse
        - sse2
        - ss
        - syscall
        - nx
        - pdpe1gb
        - rdtscp
        - lm
        - constant_tsc
        - arch_perfmon
        - nopl
        - xtopology
        - tsc_reliable
        - nonstop_tsc
        - cpuid
        - pni
        - pclmulqdq
        - ssse3
        - fma
        - cx16
        - pcid
        - sse4_1
        - sse4_2
        - x2apic
        - movbe
        - popcnt
        - tsc_deadline_timer
        - aes
        - xsave
        - avx
        - f16c
        - rdrand
        - hypervisor
        - lahf_lm
        - abm
        - cpuid_fault
        - invpcid_single
        - pti
        - ssbd
        - ibrs
        - ibpb
        - stibp
        - fsgsbase
        - tsc_adjust
        - bmi1
        - avx2
        - smep
        - bmi2
        - invpcid
        - xsaveopt
        - arat
        - md_clear
        - flush_l1d
        - arch_capabilities
    cpu_model:
        Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz
    cpuarch:
        x86_64
    cwd:
        /root
    disks:
        - sr0
    dns:
        ----------
        domain:
        ip4_nameservers:
            - 192.168.1.20
            - 192.168.2.8
        ip6_nameservers:
        nameservers:
            - 192.168.1.20
            - 192.168.2.8
        options:
        search:
            - localdomain
        sortlist:
    domain:
        localdomain
    fqdn:
        cloudlinux.localdomain
    fqdn_ip4:
        - 192.168.3.60
    fqdn_ip6:
        - ::1
    fqdns:
        - cloudlinux.localdomain
    gid:
        0
    gpus:
        |_
          ----------
          model:
              SVGA II Adapter
          vendor:
              vmware
    groupname:
        root
    host:
        cloudlinux
    hwaddr_interfaces:
        ----------
        ens192:
            00:50:56:77:88:55
        lo:
            00:00:00:00:00:00
    id:
        cloudlinux.localdomain
    init:
        systemd
    ip4_gw:
        192.168.3.1
    ip4_interfaces:
        ----------
        ens192:
            - 192.168.3.60
        lo:
            - 127.0.0.1
    ip6_gw:
        False
    ip6_interfaces:
        ----------
        ens192:
        lo:
            - ::1
    ip_gw:
        True
    ip_interfaces:
        ----------
        ens192:
            - 192.168.3.60
        lo:
            - 127.0.0.1
            - ::1
    ipv4:
        - 127.0.0.1
        - 192.168.3.60
    ipv6:
        - ::1
    kernel:
        Linux
    kernelparams:
        |_
          - BOOT_IMAGE
          - (hd0,msdos1)/vmlinuz-4.18.0-147.8.1.el8.lve.1.x86_64
        |_
          - root
          - /dev/mapper/cloudlinux-root
        |_
          - ro
          - None
        |_
          - resume
          - /dev/mapper/cloudlinux-swap
        |_
          - rd.lvm.lv
          - cloudlinux/root
        |_
          - rd.lvm.lv
          - cloudlinux/swap
    kernelrelease:
        4.18.0-147.8.1.el8.lve.1.x86_64
    kernelversion:
        #1 SMP Mon Jun 29 09:55:57 EDT 2020
    locale_info:
        ----------
        defaultencoding:
            UTF-8
        defaultlanguage:
            en_US
        detectedencoding:
            UTF-8
        timezone:
            EDT
    localhost:
        cloudlinux.localdomain
    lsb_distrib_codename:
        CloudLinux 8.3 (Pavel Belyayev)
    lsb_distrib_id:
        CloudLinux
    lsb_distrib_release:
        8.3
    lvm:
        ----------
        cloudlinux:
            - root
            - swap
            - tmp
    machine_id:
        40ba64ed025741c685a7337417ag1144
    manufacturer:
        VMware, Inc.
    master:
        salt
    mdadm:
    mem_total:
        3940
    nodename:
        cloudlinux.localdomain
    num_cpus:
        2
    num_gpus:
        1
    os:
        CloudLinux
    os_family:
        RedHat
    osarch:
        x86_64
    oscodename:
        CloudLinux 8.3 (Pavel Belyayev)
    osfinger:
        CloudLinux-8
    osfullname:
        CloudLinux
    osmajorrelease:
        8
    osrelease:
        8.3
    osrelease_info:
        - 8
        - 3
    path:
        /usr/share/Modules/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
    pid:
        5180
    productname:
        VMware Virtual Platform
    ps:
        ps -efHww
    pythonexecutable:
        /usr/bin/python3.6
    pythonpath:
        - /usr/bin
        - /usr/lib64/python36.zip
        - /usr/lib64/python3.6
        - /usr/lib64/python3.6/lib-dynload
        - /usr/lib64/python3.6/site-packages
        - /usr/lib/python3.6/site-packages
    pythonversion:
        - 3
        - 6
        - 8
        - final
        - 0
    saltpath:
        /usr/lib/python3.6/site-packages/salt
    saltversion:
        3003
    saltversioninfo:
        - 3003
    selinux:
        ----------
        enabled:
            False
        enforced:
            Disabled
    serialnumber:
        VMware-47 4c e4 3d 71 4b 44 cd-b5 a6 e2 44 4d 71 44 45
    server_id:
        44047747
    shell:
        /bin/bash
    ssds:
        - sda
    swap_total:
        2043
    systemd:
        ----------
        features:
            +PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=legacy
        version:
            239
    systempath:
        - /usr/share/Modules/bin
        - /usr/local/sbin
        - /usr/local/bin
        - /usr/sbin
        - /usr/bin
        - /root/bin
    uid:
        0
    username:
        root
    uuid:
        3de43c42-4b71-abab-a5b6-e2132d912345
    virtual:
        VMware
    zfs_feature_flags:
        False
    zfs_support:
        False
    zmqversion:
        4.3.4

```

**Comment by ppc6446** [comment]
I have been able to successfully schedule a reboot of the client system from the Uyuni WebUI even though salt-ssh commands issued for it the Uyuni server show a stack trace

**Comment by Shirocco88** [comment]
@ppc6446 
Why do you mix "salt.rpm" and "salt-ssh push" installation ?
also saltstack rpms aren't supported with uyuni server.

**Comment by ppc6446** [comment]
I had installed the salt minion after the output of salt-call was requested for the client.  When I first read that, I thought it was referring to a tarball from saltstack.io rather than one being pushed by the Uyuni system.

I removed the Saltstack RPMs and dependencies that had been installed from AppStream:

```
cloudlinux# dnf remove salt-minion salt zeromq gpg-pubkey-de57bfbe-53a9be98
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.

No match for argument: gpg-pubkey-de57bfbe-53a9be98
Dependencies resolved.
================================================================================
 Package             Arch   Version                 Repository             Size
================================================================================
Removing:
 salt                noarch 3003-1.el8              @salt-3003-repo        47 M
 salt-minion         noarch 3003-1.el8              @salt-3003-repo        72 k
 zeromq              x86_64 4.3.4-2.el8             @salt-3003-repo       1.0 M
Removing unused dependencies:
 libsodium           x86_64 1.0.18-2.el8            @cloudlinux-AppStream 399 k
 libunwind           x86_64 1.3.1-3.el8             @salt-3003-repo       205 k
 openpgm             x86_64 5.2.122-21.el8          @salt-3003-repo       431 k
 python3-babel       noarch 2.5.1-5.el8             @cloudlinux-AppStream  20 M
 python3-contextvars noarch 2.4-1.el8               @salt-3003-repo        27 k
 python3-distro      noarch 1.4.0-2.module_el8.3.0+6191+6b4b10ec
                                                    @cloudlinux-AppStream 150 k
 python3-immutables  x86_64 0.14-1.el8              @salt-3003-repo       247 k
 python3-jinja2      noarch 2.10.1-2.el8_0          @cloudlinux-AppStream 2.5 M
 python3-m2crypto    x86_64 0.35.2-5.el8            @salt-3003-repo       1.4 M
 python3-markupsafe  x86_64 0.23-19.el8             @cloudlinux-AppStream  76 k
 python3-msgpack     x86_64 0.6.2-1.el8             @salt-3003-repo       275 k
 python3-psutil      x86_64 5.4.3-10.el8            @cloudlinux-AppStream 1.9 M
 python3-pycurl      x86_64 7.43.0.2-4.el8          @cloudlinux-AppStream 770 k
 python3-pytz        noarch 2017.2-9.el8            @cloudlinux-AppStream 175 k
 python3-zmq         x86_64 19.0.0-1.el8            @salt-3003-repo       1.6 M
 yum-utils           noarch 4.0.17-5.el8            @cloudlinux-BaseOS     20 k

Transaction Summary
================================================================================
Remove  19 Packages

Freed space: 78 M
Is this ok [y/N]: y
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                        1/1
  Running scriptlet: salt-minion-3003-1.el8.noarch                          1/1
  Running scriptlet: salt-minion-3003-1.el8.noarch                         1/19
  Erasing          : salt-minion-3003-1.el8.noarch                         1/19
  Running scriptlet: salt-minion-3003-1.el8.noarch                         1/19
  Erasing          : salt-3003-1.el8.noarch                                2/19
  Erasing          : python3-contextvars-2.4-1.el8.noarch                  3/19
  Erasing          : python3-jinja2-2.10.1-2.el8_0.noarch                  4/19
  Erasing          : python3-babel-2.5.1-5.el8.noarch                      5/19
  Erasing          : python3-pytz-2017.2-9.el8.noarch                      6/19
  Erasing          : python3-distro-1.4.0-2.module_el8.3.0+6191+6b4b10e    7/19
  Erasing          : yum-utils-4.0.17-5.el8.noarch                         8/19
  Erasing          : python3-zmq-19.0.0-1.el8.x86_64                       9/19
  Erasing          : zeromq-4.3.4-2.el8.x86_64                            10/19
  Erasing          : openpgm-5.2.122-21.el8.x86_64                        11/19
  Erasing          : libsodium-1.0.18-2.el8.x86_64                        12/19
  Erasing          : libunwind-1.3.1-3.el8.x86_64                         13/19
  Erasing          : python3-markupsafe-0.23-19.el8.x86_64                14/19
  Erasing          : python3-immutables-0.14-1.el8.x86_64                 15/19
  Erasing          : python3-m2crypto-0.35.2-5.el8.x86_64                 16/19
  Erasing          : python3-msgpack-0.6.2-1.el8.x86_64                   17/19
  Erasing          : python3-psutil-5.4.3-10.el8.x86_64                   18/19
  Erasing          : python3-pycurl-7.43.0.2-4.el8.x86_64                 19/19
  Running scriptlet: python3-pycurl-7.43.0.2-4.el8.x86_64                 19/19
  Verifying        : libsodium-1.0.18-2.el8.x86_64                         1/19
  Verifying        : libunwind-1.3.1-3.el8.x86_64                          2/19
  Verifying        : openpgm-5.2.122-21.el8.x86_64                         3/19
  Verifying        : python3-babel-2.5.1-5.el8.noarch                      4/19
  Verifying        : python3-contextvars-2.4-1.el8.noarch                  5/19
  Verifying        : python3-distro-1.4.0-2.module_el8.3.0+6191+6b4b10e    6/19
  Verifying        : python3-immutables-0.14-1.el8.x86_64                  7/19
  Verifying        : python3-jinja2-2.10.1-2.el8_0.noarch                  8/19
  Verifying        : python3-m2crypto-0.35.2-5.el8.x86_64                  9/19
  Verifying        : python3-markupsafe-0.23-19.el8.x86_64                10/19
  Verifying        : python3-msgpack-0.6.2-1.el8.x86_64                   11/19
  Verifying        : python3-psutil-5.4.3-10.el8.x86_64                   12/19
  Verifying        : python3-pycurl-7.43.0.2-4.el8.x86_64                 13/19
  Verifying        : python3-pytz-2017.2-9.el8.noarch                     14/19
  Verifying        : python3-zmq-19.0.0-1.el8.x86_64                      15/19
  Verifying        : salt-3003-1.el8.noarch                               16/19
  Verifying        : salt-minion-3003-1.el8.noarch                        17/19
  Verifying        : yum-utils-4.0.17-5.el8.noarch                        18/19
  Verifying        : zeromq-4.3.4-2.el8.x86_64                            19/19
Installed products updated.

Removed:
  libsodium-1.0.18-2.el8.x86_64
  libunwind-1.3.1-3.el8.x86_64
  openpgm-5.2.122-21.el8.x86_64
  python3-babel-2.5.1-5.el8.noarch
  python3-contextvars-2.4-1.el8.noarch
  python3-distro-1.4.0-2.module_el8.3.0+6191+6b4b10ec.noarch
  python3-immutables-0.14-1.el8.x86_64
  python3-jinja2-2.10.1-2.el8_0.noarch
  python3-m2crypto-0.35.2-5.el8.x86_64
  python3-markupsafe-0.23-19.el8.x86_64
  python3-msgpack-0.6.2-1.el8.x86_64
  python3-psutil-5.4.3-10.el8.x86_64
  python3-pycurl-7.43.0.2-4.el8.x86_64
  python3-pytz-2017.2-9.el8.noarch
  python3-zmq-19.0.0-1.el8.x86_64
  salt-3003-1.el8.noarch
  salt-minion-3003-1.el8.noarch
  yum-utils-4.0.17-5.el8.noarch
  zeromq-4.3.4-2.el8.x86_64

Complete!
```

**Comment by ppc6446** [comment]
Regarding AlmaLinux - I got one of those systems set up first running with a standard salt installation and salt-ssh commands are also working with it, so salt-ssh is working under at least some circumstances on this Uyuni server.

CloudLinux is required for a specific offering for a particular use case

**Comment by Shirocco88** [comment]
Are the AlmaLinux Uyuni-Client-Tools (salt-minion) working for CloudLinux8 ?
AlmaLinux 8 (x86_64): https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS8-Uyuni-Client-Tools/CentOS_8/

**Comment by ppc6446** [comment]
I added that repository and registered the system using the WebUI.  The key is accepted in salt, but even after a few hours, it's not showing up in the Systems list.

I tried salt "cloudlinux.localdomain" test.ping and it gave this error:
    Minion did not return. [No response]
ERROR: Minions returned with non-zero exit code

Due to the network location of this system, salt-ssh would be more appropriate.  I was able to apply the high state from the WebUI when it was registered using the Push by SSH method for example.  The salt-ssh command at the command-line was failing, however.  Ideally, the salt-ssh command could be made to work since it was otherwise working as desired that way.

**Comment by Shirocco88** [comment]
@ppc6446 : We need more information;
Could you please test the bootstrap.sh method instead of Web-UI;

**Comment by ppc6446** [comment]
I wouldn't expect bootstrap.sh to work since this system doesn't have inbound access to Uyuni

**Comment by Shirocco88** [comment]
@ppc6446 : is there a firewall active between Uyuni-Server and CloudLinux8 Machine ?
do you open the required ports:  tcp/22, tcp/4505, tcp/4506 ?

**Comment by ppc6446** [comment]
The goal is for Uyuni to manage the system using outbound "Push by SSH" over only port 22 outbound to the VM.  The client is using the external CloudLinux repositories the CloudLinux RPMs and the external opensuse repository for the Uyuni client tools.

**Comment by paususe** [comment]
Adding CloudLinux 8 to Uyuni should be rather easy. Please watch my talk at openSUSE Conference on Saturday and submit a PR :)

*Enabling new client operating systems in Uyuni*
https://events.opensuse.org/conferences/oSVC21/program/proposals/3534

**Comment by ppc6446** [comment]
Thank you for the follow-up!  To clarify, client tools support on CloudLinux would not be helpful to our use case.  salt-ssh would be the ideal tool if it wouldn't throw a python stack trace.

**Comment by agraul** [comment]
@ppc6446 how did you set up you [Salt Roster target](https://docs.saltproject.io/en/latest/topics/ssh/roster.html#targets-data)? I can reproduce your backtrace with an incorrect config:

```
suma:~ # cat /etc/salt/roster 
# Sample salt-ssh config file
#web1:
#  host: 192.168.42.1 # The IP addr or DNS hostname
#  user: fred         # Remote executions will be executed as user fred
#  passwd: foobarbaz  # The password to use for login, if omitted, keys are used
#  sudo: True         # Whether to sudo to root, not enabled by default
#web2:
#  host: 192.168.42.2
test:
  user: root
  passwd: password
  host:
suma:~ # salt-ssh test cmd.run uptime
[ERROR   ] An un-handled exception from the multiprocessing process 'Process-1' was caught:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/process.py", line 895, in wrapped_run_func
    return run_func()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/salt/client/ssh/__init__.py", line 544, in handle_routine
    **target
  File "/usr/lib/python3.6/site-packages/salt/client/ssh/__init__.py", line 980, in __init__
    self.shell = salt.client.ssh.shell.gen_shell(opts, **args)
  File "/usr/lib/python3.6/site-packages/salt/client/ssh/shell.py", line 53, in gen_shell
    shell = Shell(opts, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/client/ssh/shell.py", line 83, in __init__
    self.host = host.strip("[]")
AttributeError: 'NoneType' object has no attribute 'strip'
[...]
```

The crucial point here is that the roster specifies an empty `host:`, which is parsed as `None`. `salt-ssh` expects a string, et voilà: backtrace.
