### ISSUE TITLE
Uyuni Question - Uyuni 2021.05 - Automatic patching

### ISSUE THREAD

**Issue by lumarel** [uyuni-project/uyuni#3859]
# Question
Hi!
I tried to use the "Automatic application of relevant patches" function, but I was unable to.

So my question is, how is this intended to be used?
I just end up with pending requests which are not applied.
(in my configuration I'm trying to apply patches to Ubuntu 20.04, Rocky Linux 8 and CentOS 7, if this makes any difference)

As well, I also looked through all the documentation, but everything I could find there is that this button exists.

And does this feature respect the maintenance schedules?

Sorry for the quite direct questions,
and thank you very much for your help!
Lukas

**Comment by digdilem** [comment]
The docs do seem to be missing information on this checkbox. 

"system -> Details -> Properties, there is a checkbox "Automatic application of relevant patches""

Relevant page; https://ata-oxy-uyuni01.atass.com/docs/en/uyuni/reference/systems/system-details/sd-properties.html

**Comment by Shirocco88** [comment]
@lumarel: could you please precise "Automatic application of relevant patches" function ?
are you looking for a replacement "ubuntu: unattended-upgrades" or "suse yast automatic online update"
https://documentation.suse.com/sles/15-SP1/html/SLES-all/cha-onlineupdate-you.html#sec-onlineupdate-you-automatically ?

**Comment by Shirocco88** [comment]
the feature "Automatic application of relevant patches" was implemented in 2018;
see uyuni-project/uyuni#64

**Comment by juliogonzalez** [comment]
And there's https://www.uyuni-project.org/uyuni-docs/en/uyuni/administration/maintenance-windows.html as way.

**Comment by juliogonzalez** [comment]
@digdilem did you create an issue for the doc already?

> The docs do seem to be missing information on this checkbox.
> 
> "system -> Details -> Properties, there is a checkbox "Automatic application of relevant patches""
> 
> Relevant page; https://ata-oxy-uyuni01.atass.com/docs/en/uyuni/reference/systems/system-details/sd-properties.html

I see: https://www.uyuni-project.org/uyuni-docs/en/uyuni/reference/systems/system-details/sd-properties.html

```
Auto Patch Update | Check to have available patches automatically applied. | Unchecked.
```
and `Auto Patch Update` is indeed the name of the checkbox:

![image](https://user-images.githubusercontent.com/4226070/127900069-1bda79c9-6e7c-4cbd-8583-fd45501b9f66.png)

**Comment by lumarel** [comment]
>
> 
> And there's https://www.uyuni-project.org/uyuni-docs/en/uyuni/administration/maintenance-windows.html as way.

@juliogonzalez I didn't see any information about the automatic patching there
For me it is more about, does the maintenance window also move the run time of the patch schedules into the maintenance window, or are they just created and then run in the maintenance window
up to now I tested this a little more and it looks like it would be the latter option

> I see: https://www.uyuni-project.org/uyuni-docs/en/uyuni/reference/systems/system-details/sd-properties.html
>
> Auto Patch Update | Check to have available patches automatically applied. | Unchecked.
>
> and Auto Patch Update is indeed the name of the checkbox:

But as I already mentioned, the patch install schedules never get out of the pending state
So I asked for the guidance here how this should work, as it didn't work like I thought it would (the button itself is already quite descriptive 🙂 )

**Comment by juliogonzalez** [comment]
If you use maintenance windows, you don't need to use `Auto Patch Update`. 

As you can see you need to define a calendar, the actions, and the clients assigned to the actions at the calendar

About `Auto Patch Update` scheduled and never getting updated, check https://www.uyuni-project.org/uyuni-docs/en/uyuni/administration/task-schedules.html and the schedule configured for `errata-queue-default`. Then check the logs at the time that action is running (use `tail -f` for the logs at `/var/log/rhn`, `/var/log/tomcat` and `/var/log/minion`), to see if you can see anything strange, and provide the results here.

**Comment by lumarel** [comment]
@juliogonzalez 
Okay then I misread that over and over again in the maintenance-windows documentation,
does that mean as soon as an maintenance window is applied, the patches are automatically scheduled in the MW, even if the checkbox is not set and no manual patch installation gets triggered?

I will check that tomorrow as soon as I have access to the systems again 👍🏻
Thank you very much for your help up to now!

**Comment by lumarel** [comment]
Good news, looks like the pending schedules issue has been resolved since the upgrade to 2021.06!

Only one more thing, I noticed that errata/patches are not cloned on an content lifecycle build, is this intentional? (so the errata information, not the packages)
I was not aware of this fact up to now.

**Comment by mcalmer** [comment]
@lumarel I just checked the code and it seems we do not really take care of maintenance windows in the automatic patch update feature yet. The code just run every 10 minutes and schedule any patch update which is available independent of maintenance windows setting.
When you check your logs, you might find a message which say, that an action was skipped because it was scheduled outside of a maintenance window. This would explain why the action stay in pending.

We need to look into it and schedule only when the system is inside of a maintenance window.

**Comment by lumarel** [comment]
@mcalmer Okay good that you already see points for improvement!
Back when I created this issue I tested both cases, enabling the `Auto Patch Update` with a set maintenance window as well as without one, both ended up in pending schedules, that was on 2021.05, so since the upgrade to 2021.06 it looks like this doesn't happen anymore 🎉

And right now in 2021.06 it is not possible to check the `Auto Patch Update` checkbox while a maintenance window is configured:
```
==> /var/log/rhn/rhn_web_ui.log <==
2021-08-03 10:43:11,412 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-702] WARN  org.apache.struts.action.RequestProcessor - Unhandled Exception thrown: class com.suse.manager.maintenance.NotInMaintenanceModeException
2021-08-03 10:43:11,413 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-702] ERROR com.redhat.rhn.frontend.servlets.SessionFilter - Error during transaction. Rolling back
javax.servlet.ServletException: com.suse.manager.maintenance.NotInMaintenanceModeException: Systems assigned to these schedules (Default Maintenace) do not have a maintenance window at Tue Aug 03 10:43:11 CEST 2021
        at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:535)
        at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:433)
        at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:237)
        at com.redhat.rhn.frontend.struts.RhnRequestProcessor.process(RhnRequestProcessor.java:104)
        at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1196)
        at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:432)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.redhat.rhn.frontend.servlets.AuthFilter.doFilter(AuthFilter.java:98)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.opensymphony.module.sitemesh.filter.PageFilter.parsePage(PageFilter.java:142)
        at com.opensymphony.module.sitemesh.filter.PageFilter.doFilter(PageFilter.java:58)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.redhat.rhn.frontend.servlets.LocalizedEnvironmentFilter.doFilter(LocalizedEnvironmentFilter.java:69)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.redhat.rhn.frontend.servlets.EnvironmentFilter.doFilter(EnvironmentFilter.java:99)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.redhat.rhn.frontend.servlets.SessionFilter.doFilter(SessionFilter.java:55)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.redhat.rhn.frontend.servlets.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:97)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:432)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1591)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.suse.manager.maintenance.NotInMaintenanceModeException: Systems assigned to these schedules (Default Maintenace) do not have a maintenance window at Tue Aug 03 10:43:11 CEST 2021
        at com.suse.manager.maintenance.MaintenanceManager.canActionBeScheduled(MaintenanceManager.java:633)
        at com.redhat.rhn.domain.action.server.ServerAction.setParentActionWithCheck(ServerAction.java:183)
        at com.redhat.rhn.domain.action.ActionFactory.addServerToAction(ActionFactory.java:270)
        at com.redhat.rhn.manager.action.ActionManager.addServerToAction(ActionManager.java:460)
        at com.redhat.rhn.manager.errata.ErrataManager.lambda$createErrataActions$33(ErrataManager.java:1979)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at com.redhat.rhn.manager.errata.ErrataManager.createErrataActions(ErrataManager.java:1979)
        at com.redhat.rhn.manager.errata.ErrataManager.lambda$computeActions$29(ErrataManager.java:1895)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
        at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1746)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at com.redhat.rhn.manager.errata.ErrataManager.applyErrata(ErrataManager.java:1846)
        at com.redhat.rhn.manager.errata.ErrataManager.applyErrata(ErrataManager.java:1680)
        at com.redhat.rhn.manager.errata.ErrataManager.applyErrata(ErrataManager.java:1660)
        at com.redhat.rhn.manager.action.ActionManager.scheduleAllErrataUpdate(ActionManager.java:1779)
        at com.redhat.rhn.frontend.action.systems.sdc.SystemDetailsEditAction.processSubmission(SystemDetailsEditAction.java:192)
        at com.redhat.rhn.frontend.action.systems.sdc.SystemDetailsEditAction.execute(SystemDetailsEditAction.java:110)
        at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:431)
        ... 47 more
```

The other way around it works after all tasks have been run.
But if this will have to be changed as you say it, this also shouldn't make any problems anymore.

**Comment by Shirocco88** [comment]
I checked the uyuni design docs for "maintenance windows" and "automatic package installations":

see https://github.com/uyuni-project/uyuni-rfc/blob/master/accepted/00073-maintenance-windows.md
>> When a system is not in "Maintenance Mode" no action can be executed. 
>> A "Maintenance Window" does nothing else than turning Maintenance Mode "on" when the window starts and "off" when it ends.

label			| name					| maintenance_mode_only
------------ | ------------- | -------------
packages.update		| Package Install			| Y
errata.update		| Patch Update				| Y
packages.autoupdate	| Automatic package installation	| Y

==> if your system is in maintenance mode, then "automatic package installations" is denied.

**Comment by lumarel** [comment]
I didn't know that there are design documents up to now, learned one more thing! Thank you!

Okay yes, this then means, that it is disallowed to run any of these 3 actions outside of a maintenance window, but inside it should work, and furthermore as I understand it, any automatically scheduled tasks which get created for a client with a maintenance window configured should be created inside of the window (and not fail because it couldn't be scheduled right now)

**Comment by Shirocco88** [comment]
> And right now in 2021.06 it is not possible to check the `Auto Patch Update` checkbox while a maintenance window is configured:

the last code change that I found was PR https://github.com/uyuni-project/uyuni/pull/2367  from 20.06.2020;

https://github.com/hustodemon/uyuni/blob/fa17acecc121934782f8ae9061cd995fa4c86e52/java/code/src/com/suse/manager/maintenance/MaintenanceManager.java#L482
    /**
     * Check if an action can be scheduled at given date for given systems.
     *
     * If some systems have a {@link MaintenanceSchedule} and are outside of their maintenance windows,
     * throw the {@link NotInMaintenanceModeException} that bears the offending schedules.
     *
     * @param systemIds the system IDs to check
     * @param action the action
     * @throws NotInMaintenanceModeException when some systems are outside of maintenance window
     */

**Comment by Shirocco88** [comment]
> in my configuration I'm trying to apply patches to Ubuntu 20.04, Rocky Linux 8 and CentOS 7, if this makes any difference

Patches are "packages with erratas".
One question: how did you add erratas to "Ubuntu 20.04, Rocky Linux 8 and CentOS 7" systems ?
I ask this because erratas are i a out-of-box uyuni installation only available for OpenSUSE and SLES repos.

**Comment by Shirocco88** [comment]
> Okay yes, this then means, that it is disallowed to run any of these 3 actions outside of a maintenance window, but inside it should work, and furthermore as I understand it, any automatically scheduled tasks which get created for a client with a maintenance window configured should be created inside of the window (and not fail because it couldn't be scheduled right now)

Please keep in mind: there is a difference between "applying patches" vs. "package upgrades" !!!

**Comment by lumarel** [comment]
> Patches are "packages with erratas".
> One question: How did you add erratas to "Ubuntu 20.04, Rocky Linux 8 and CentOS 7" packages ?
> I ask this because erratas are i a out-of-box uyuni installation only available for OpenSUSE and SLES packages.

It is different between all three OSs:
- Ubuntu 20.04: https://github.com/lumarel/spacewalk-ubuntu-errata
- CentOS 7: https://github.com/stevemeier/cefs
- Rocky Linux 8: The errata content is built into the repos, so it also is kind of "out of the box"

Ubuntu is a special case there, because the patch applying does not work up to now, because of the before mentioned problem, that the salt-minion doesn't understand erratas for the deb packages up to now: https://github.com/uyuni-project/uyuni/issues/2068

> could you please open a separate issue and add information to reproduce the problem.

Okay I will do that later 👌🏻

> Please keep in mind: there is a difference between "applying patches" vs. "package upgrades" !!!

And yes I'm aware of that, I intentionally only want to install patches, to interrupt the clients as little as possible.

**Comment by Shirocco88** [comment]
@lumarel : 
there is a new PR https://github.com/uyuni-project/uyuni/pull/4158 "Fix autoupdate with maintenance windows"

**Comment by lumarel** [comment]
@Shirocco88 Thank you for the notice!
I will have a look as soon as it gets in the next release 👍🏻

**Comment by lumarel** [comment]
I tested this feature quite extensively now!
Works really good now, so if a maintenance window is set and the `auto-errata-update` checkbox is set, it installs any available patches at the beginning of the maintenance window.

Thanks to all of you for helping here!
