### ISSUE TITLE
Uyuni Bugreport - Uyuni 2021.05 add amazon linux channels

### ISSUE THREAD

**Issue by eins** [uyuni-project/uyuni#3893]
Howdy uyuni devs and community.

I upgrade uyuni server to release 2021.05 and I wanted to add amazon linux channels first in order to add later amazon linux clients. 

I can't find the correct amazon linux channels, Do we have arm64 support too ?

https://www.uyuni-project.org/uyuni-docs/uyuni/client-configuration/clients-amazon.html

```
spacewalk-common-channels \
amazonlinux2-uyuni-client \
amazonlinux2-core
```

The list in the github docs is empty
https://github.com/uyuni-project/uyuni-docs/blob/uyuni-2021.05/modules/client-configuration/pages/clients-amazon.adoc

How can we improve this ?
spacewalk-repo-sync gave me an error but I sync  Amazon Linux 2 Core aarch64 from uyuni url 
Repositories --> Sync --> Sync Now

# Additional Information

## Version of Uyuni Server 
zypper info Uyuni-Server-release
Loading repository data...
Reading installed packages...

Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2021.05-123.2.uyuni
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : out-of-date (version 2020.09-98.2.uyuni installed)
Source package : Uyuni-Server-release-2021.05-123.2.uyuni.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.

## Details about issue
After I upgrade uyuni to version 2021.05 I can't add amazonlinux channels

**Comment by juliogonzalez** [comment]
Is the bug report about Amazon Linux for aarch64? Because the title does not specify it.

Yes, the aarch64 channels are [defined](https://github.com/uyuni-project/uyuni/blob/master/utils/spacewalk-common-channels.ini#L2767), but to add them you must specify the architecture, as otherwise `x86_64` is used by default

Use `-a` at `spacewalk-common-channels`for that.

That should work just fine, and then you just need to launch the repository sync with `spacewalk-repo-sync`.

You are mentioning and error, but didn't provide the actual error, so all I can think of is that you specified the wrong channel label. The channel labe include the architecture. Check the list (IIRC you can pass an argument to `spacewalk-repo-sync`.

Will Amazon Linux for aarch64 work fine? It should, but we don't know. And that's why we did not document it. Please give it a try and let us know :-)

If adding the channels and syncing them works as I explained, please close this bug. If other problems are found onboarding, or managing Amazon Linux 2 aarch64, create new bug reports.

**NOTE:** https://github.com/uyuni-project/uyuni-docs/blob/uyuni-2021.05/modules/client-configuration/pages/clients-amazon.adoc is not empty. That's how Github renders adoc, since you are looking at the source code. Hit the `Raw` button to see the real adoc code.

**Comment by eins** [comment]
@juliogonzalez thanks for the reply
I created a new issue in the uyuni-docs github repository
https://github.com/uyuni-project/uyuni-docs/issues/999

@juliogonzalez do I need to close this issue or do you want to wait for the uyuni-docs' issues #999 to be closed first ?

**Comment by juliogonzalez** [comment]
I closed the other one. At this moment the doc does not have any bug at all. Amazon Linux 2 for aarch64 is not supported, as stated at the release notes.

But as I told yesterday:

> Will Amazon Linux for aarch64 work fine? It should, but we don't know. And that's why we did not document it. Please give it a try and let us know :-)

As soon as users can confirm it works fine, or we can find to test it, it will be documented.

As for the problems you have, using `-a` is not enough by itself, you need to use it with an architecture. IIRC `-a aarch64` is the thing to do here.

And for syncing with `spacewalk-repo-sync`, I am quite sure you didn't specify the channel name including the architecture. The channel name does not match what you add via `spacewalk-common-channels`. IIRC its rather `channelname-architecture`.

So `spacewalk-repo-sync -p amazonlinux2-core-aarch64` should work. `-p` tells the script to sync that channel and all children (such as the client tools).

**Comment by Shirocco88** [comment]
@eins:  could you please verify, if the channels for amazon linux are installed correctly
"mgr-sync list channels"

**Comment by eins** [comment]
@juliogonzalez  @Shirocco88 
I ran this line 
```
spacewalk-common-channels -a  amazonlinux2-core amazonlinux2-uyuni-client
No channels matching your selection.
```

I can't bootstrap an ARM64 amazonlinuxv2 minion.
I had this error in the uyuni url

```
file_|-/etc/salt/minion.d/susemanager.conf_|-/etc/salt/minion.d/susemanager.conf_|-managed(retcode=2): Parent directory not present
service_|-salt-minion_|-salt-minion_|-running(retcode=2): One or more requisite failed: bootstrap./etc/salt/minion.d/susemanager.conf

```

I have arm64 repositories but something is wrong
```
mgr-create-bootstrap-repo -l
1. amazonlinux-2-aarch64-uyuni
2. amazonlinux-2-x86_64-uyuni
3. openSUSE-Leap-15.2-x86_64-uyuni
```
Shirocco88 told me in gitter to add  /var/log/rhn/rhn_web_ui.log output

```
        at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:189)
        at spark.servlet.SparkFilter.doFilter(SparkFilter.java:173)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.redhat.rhn.frontend.servlets.AuthFilter.doFilter(AuthFilter.java:98)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.opensymphony.module.sitemesh.filter.PageFilter.parsePage(PageFilter.java:142)
        at com.opensymphony.module.sitemesh.filter.PageFilter.doFilter(PageFilter.java:58)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.redhat.rhn.frontend.servlets.LocalizedEnvironmentFilter.doFilter(LocalizedEnvironmentFilter.java:69)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.redhat.rhn.frontend.servlets.EnvironmentFilter.doFilter(EnvironmentFilter.java:99)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.redhat.rhn.frontend.servlets.SessionFilter.doFilter(SessionFilter.java:55)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.redhat.rhn.frontend.servlets.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:97)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:432)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1591)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: Broken pipe
        at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
        at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
        at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:79)
        at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:50)
        at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:462)
        at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:138)
        at org.apache.tomcat.util.net.NioBlockingSelector.write(NioBlockingSelector.java:101)
        at org.apache.tomcat.util.net.NioSelectorPool.write(NioSelectorPool.java:152)
        at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.doWrite(NioEndpoint.java:1254)
        at org.apache.tomcat.util.net.SocketWrapperBase.doWrite(SocketWrapperBase.java:741)
        at org.apache.tomcat.util.net.SocketWrapperBase.flushBlocking(SocketWrapperBase.java:694)
        at org.apache.tomcat.util.net.SocketWrapperBase.flush(SocketWrapperBase.java:684)
        at org.apache.coyote.ajp.AjpProcessor.writeData(AjpProcessor.java:1260)
        at org.apache.coyote.ajp.AjpProcessor.access$600(AjpProcessor.java:58)
        at org.apache.coyote.ajp.AjpProcessor$SocketOutputBuffer.doWrite(AjpProcessor.java:1332)
        at org.apache.coyote.Response.doWrite(Response.java:601)
        at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:339)
        ... 52 more
2021-06-18 15:38:12,250 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-25] ERROR com.suse.manager.webui.controllers.utils.AbstractMinionBootstrapper - States failed during bootstrap: file_|-/etc/salt/minion.d/susemanager.conf_|-/etc/salt/minion.d/susemanager.conf_|-managed(retcode=2): Parent directory not present
service_|-salt-minion_|-salt-minion_|-running(retcode=2): One or more requisite failed: bootstrap./etc/salt/minion.d/susemanager.conf
2021-06-18 15:40:43,797 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-20] ERROR com.suse.manager.webui.controllers.utils.AbstractMinionBootstrapper - States failed during bootstrap: file_|-/etc/salt/minion.d/susemanager.conf_|-/etc/salt/minion.d/susemanager.conf_|-managed(retcode=2): Parent directory not present
service_|-salt-minion_|-salt-minion_|-running(retcode=2): One or more requisite failed: bootstrap./etc/salt/minion.d/susemanager.conf
2021-06-18 16:36:52,992 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-30] ERROR com.suse.manager.webui.controllers.utils.AbstractMinionBootstrapper - States failed during bootstrap: file_|-/etc/salt/minion.d/susemanager.conf_|-/etc/salt/minion.d/susemanager.conf_|-managed(retcode=2): Parent directory not present
service_|-salt-minion_|-salt-minion_|-running(retcode=2): One or more requisite failed: bootstrap./etc/salt/minion.d/susemanager.conf
2021-06-18 17:16:20,376 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-22] ERROR com.suse.manager.webui.controllers.utils.AbstractMinionBootstrapper - States failed during bootstrap: file_|-/etc/salt/minion.d/susemanager.conf_|-/etc/salt/minion.d/susemanager.conf_|-managed(retcode=2): Parent directory not present
service_|-salt-minion_|-salt-minion_|-running(retcode=2): One or more requisite failed: bootstrap./etc/salt/minion.d/susemanager.conf
                                                                                                                                           
```

**Comment by eins** [comment]
> @eins: could you please verify, if the channels for amazon linux are installed correctly
> "mgr-sync list channels"

```
mgr-sync list channels
No channels found.
```

**Comment by Shirocco88** [comment]
/var/log/rhn/rhn_web_ui.log
/etc/salt/minion.d/susemanager.conf_|-managed(retcode=2): Parent directory not present

What salt-minion version are you using ?
"rpm -qa | grep salt-minion"

**Comment by Shirocco88** [comment]
Which repositories are defined at the amozon linux client ?

**Comment by eins** [comment]
> rpm -qa | grep salt-minion"
```
rpm -qa | grep salt-minion
salt-minion-2015.5.10-2.el7.noarch
```
> Which repositories are defined at the amazon linux client ?
```
yum repolist
Loaded plugins: priorities, update-motd
216 packages excluded due to repository priority protections
repo id                                                  repo name                                                    status
SUSE-Manager-Bootstrap                                   SUSE-Manager-Bootstrap                                       14+65
!amzn2-core/2/aarch64                                    Amazon Linux 2 core repository                               16,353
amzn2extra-docker/2/aarch64                              Amazon Extras repo for docker                                36
epel/aarch64                                             Extra Packages for Enterprise Linux 7 - aarch64              12,799+189
repolist: 29,202
```

**Comment by Shirocco88** [comment]
salt-minion-2015.5.10-2.el7.noarch
==> this is the wrong version, you need uyuni salt-minion 3000

**Comment by eins** [comment]
> salt-minion-2015.5.10-2.el7.noarch
> ==> this is the wrong version, you need uyuni salt-minion 3000

yes indeed. it is to old.

For some reason yum wants to install the old salt-minion 
```
yum-config-manager --enable SUSE-Manager-Bootstrap
yum --enablerepo=SUSE-Manager-Bootstrap install salt-minion
Loaded plugins: priorities, update-motd
216 packages excluded due to repository priority protections
Resolving Dependencies
--> Running transaction check
---> Package salt-minion.noarch 0:2015.5.10-2.el7 will be installed
--> Processing Dependency: salt = 2015.5.10-2.el7 for package: salt-minion-2015.5.10-2.el7.noarch
--> Running transaction check
---> Package salt.noarch 0:2015.5.10-2.el7 will be installed
--> Finished Dependency Resolution

```

**Comment by Shirocco88** [comment]
Please disable or temp. remove the following repo:
epel/aarch64                                             Extra Packages for Enterprise Linux 7 - aarch64 

and reinstall salt-minion from "SUSE-Manager-Bootstrap" repo.

**Comment by Shirocco88** [comment]
could you test with Repo
https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS7-Uyuni-Client-Tools/CentOS_7/systemsmanagement:Uyuni:Stable:CentOS7-Uyuni-Client-Tools.repo
instead of EL7

**Comment by juliogonzalez** [comment]
@Shirocco88, is right, that salt version is not right, but here's the thing... I think you added the channels first, but didn't sync them. May you then added EPEL as a child of the amazon aarch64 core repo, the automatic bootstrap procedure tried to create the repo, and copied salt from EPEL, and that's what you get now, the old salt from EPEL.

If that's the case, it's easy to fix:
1. Sync all the aarch64 channels for amazon as I explained above
2. Force a recreation of the bootstrap repo from scratch: `mgr-create-bootstrap-repo -f`

That should recreate the bootstrap repo wih the right salt. Try to bootstrap again following the same procedures you would follow for x86_64.

**Comment by eins** [comment]
I sync all the aarch64 channels but the bootstrap failed. 
python-zmq-14.5.0-3.10 is to old.
output here:  https://gist.github.com/eins/f308c38b3e2651c9621b0024e31e232e

**Comment by juliogonzalez** [comment]
Disable EPEL before you bootstrap, or add the package from EPEL to ignores. `python2-zmq-14.7.0-8.el7.aarch64` is clearly incompatible with the python-zmq package our salt package requires as of today.

This is not exactly https://github.com/uyuni-project/uyuni/issues/1275, but still similar.

This problem should be fixed soon by the salt bundle we are preparing, so we basically won't need any extra dependencies

**Comment by juliogonzalez** [comment]
Can we close this issue?

**Comment by eins** [comment]
> Can we close this issue?

I think we can close this issue.
I used Uyuni 2021.05 back then when I had the issue. now I'm running Uyuni 2021.06.

I don´t know when the salt bundle will be ready but I can't wait for testing and using it with ARM64 minions
