### ISSUE TITLE
Uyuni Bugreport - Uyuni 2021-06: Apply patched on registered servers fail

### ISSUE THREAD

**Issue by phibid** [uyuni-project/uyuni#4164]
I am trying to apply a patch on the Uyuni proxies (i.e. salt-minion registered in Uyuni) through the GUI, the action is scheduled on taskomatic but immediately crashes  with the following error:

```
# cat /var/log/rhn/tasko/sat/minion-action-executor-bunch/minion-action-executor_4757595_err
2021-08-25 16:53:42,912 [DefaultQuartzScheduler_Worker-16] ERROR com.redhat.rhn.taskomatic.task.MinionActionExecutor  - Executing a task threw an exception: java.lang.NullPointerException
2021-08-25 16:53:42,912 [DefaultQuartzScheduler_Worker-16] ERROR com.redhat.rhn.taskomatic.task.MinionActionExecutor  - Message: null
2021-08-25 16:53:42,913 [DefaultQuartzScheduler_Worker-16] ERROR com.redhat.rhn.taskomatic.task.MinionActionExecutor  - Cause: null
2021-08-25 16:53:42,913 [DefaultQuartzScheduler_Worker-16] ERROR com.redhat.rhn.taskomatic.task.MinionActionExecutor  - Stack trace:java.lang.NullPointerException
        at com.suse.manager.webui.services.SaltServerActionService.callsForAction(SaltServerActionService.java:307)
        at com.suse.manager.webui.services.SaltServerActionService.executeForRegularMinions(SaltServerActionService.java:537)
        at com.suse.manager.webui.services.SaltServerActionService.execute(SaltServerActionService.java:515)
        at com.redhat.rhn.taskomatic.task.MinionActionExecutor.execute(MinionActionExecutor.java:125)
        at com.redhat.rhn.taskomatic.task.RhnJavaJob.execute(RhnJavaJob.java:89)
        at com.redhat.rhn.taskomatic.TaskoJob.execute(TaskoJob.java:198)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
```

**Comment by mcalmer** [comment]
As we have a duplicate I close this one
