### ISSUE TITLE
Uyuni Bugreport - Uyuni 2021.08 (taskomatic -  Invalid advisory status)

### ISSUE THREAD

**Issue by mrstigmata** [uyuni-project/uyuni#4304]
# Additional Information

_The following information is very important in order to help us to help you. Omission of the following details cause delays or could receive no attention at all._

## Version of Uyuni Server and Proxy (if used)
`zypper info Uyuni-Server-release` _and_ `zypper info Uyuni-Proxy-release` _(if used)_

Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2021.08-139.2.uyuni1
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2021.08-139.2.uyuni1.src
Summary        : Uyuni Server

## Details about issue
_Include as many details as you can. The procedure you are following,  the commands you are running, logs (specially from_ `/var/log/rhn/`_)..._
_In general: all that can help reproducing the issue or understanding it_

Taskomatic runs with these message in a loop. looks like the database schema doesn't fit to the metadata. 

/var/log/rhn/rhn_taskomatic_daemon.log
2021-10-06 13:47:00,044 [Thread-148] INFO  com.redhat.rhn.taskomatic.task.repomd.RepositoryWriter - Channel Modified Date:2021-10-06 12:14:46 CEST
2021-10-06 13:47:00,083 [Thread-148] INFO  com.redhat.rhn.taskomatic.task.repomd.RepositoryWriter - Generating new repository metadata for channel 'rhel-7-epel-7_x86_64'(sha256) 16039 packages, 4788 errata
2021-10-06 13:47:06,648 [Thread-148] INFO  com.redhat.rhn.taskomatic.task.repomd.RepositoryWriter - Processed 1000 packages
2021-10-06 13:47:13,081 [Thread-148] INFO  com.redhat.rhn.taskomatic.task.repomd.RepositoryWriter - Processed 2000 packages
2021-10-06 13:47:19,527 [Thread-148] INFO  com.redhat.rhn.taskomatic.task.repomd.RepositoryWriter - Processed 3000 packages
2021-10-06 13:47:26,001 [Thread-148] INFO  com.redhat.rhn.taskomatic.task.repomd.RepositoryWriter - Processed 4000 packages
2021-10-06 13:47:32,334 [Thread-148] INFO  com.redhat.rhn.taskomatic.task.repomd.RepositoryWriter - Processed 5000 packages
2021-10-06 13:47:38,597 [Thread-148] INFO  com.redhat.rhn.taskomatic.task.repomd.RepositoryWriter - Processed 6000 packages
2021-10-06 13:47:45,112 [Thread-148] INFO  com.redhat.rhn.taskomatic.task.repomd.RepositoryWriter - Processed 7000 packages
2021-10-06 13:47:51,456 [Thread-148] INFO  com.redhat.rhn.taskomatic.task.repomd.RepositoryWriter - Processed 8000 packages
2021-10-06 13:47:57,747 [Thread-148] INFO  com.redhat.rhn.taskomatic.task.repomd.RepositoryWriter - Processed 9000 packages
2021-10-06 13:48:00,038 [DefaultQuartzScheduler_Worker-14] WARN  com.redhat.rhn.taskomatic.task.ChannelRepodata - Maximum number of workers already put ... skipping.
2021-10-06 13:48:04,043 [Thread-148] INFO  com.redhat.rhn.taskomatic.task.repomd.RepositoryWriter - Processed 10000 packages
2021-10-06 13:48:10,222 [Thread-148] INFO  com.redhat.rhn.taskomatic.task.repomd.RepositoryWriter - Processed 11000 packages
2021-10-06 13:48:16,467 [Thread-148] INFO  com.redhat.rhn.taskomatic.task.repomd.RepositoryWriter - Processed 12000 packages
2021-10-06 13:48:22,921 [Thread-148] INFO  com.redhat.rhn.taskomatic.task.repomd.RepositoryWriter - Processed 13000 packages
2021-10-06 13:48:30,463 [Thread-148] INFO  com.redhat.rhn.taskomatic.task.repomd.RepositoryWriter - Processed 14000 packages
2021-10-06 13:48:37,623 [Thread-148] INFO  com.redhat.rhn.taskomatic.task.repomd.RepositoryWriter - Processed 15000 packages
2021-10-06 13:48:45,020 [Thread-148] INFO  com.redhat.rhn.taskomatic.task.repomd.RepositoryWriter - Processed 16000 packages
2021-10-06 13:48:47,706 [Thread-148] INFO  com.redhat.rhn.taskomatic.task.repomd.RepositoryWriter - Processed 16039 packages
2021-10-06 13:48:51,718 [Thread-148] ERROR com.redhat.rhn.common.db.datasource.CachedStatement - Error while processing cached statement sql: select e.id, e.advisory, e.advisory_name, e.advisory_type, e.advisory_rel,
       e.synopsis as advisory_synopsis, e.advisory_status,
       e.description, e.issue_date, e.update_date, e.errata_from
  from rhnErrata e
 where e.id in (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
com.redhat.rhn.common.MethodInvocationException: Something bad happened when calling setAdvisoryStatus
        at com.redhat.rhn.common.util.MethodUtil.callMethod(MethodUtil.java:209)
        at com.redhat.rhn.common.db.datasource.CachedStatement.addToObject(CachedStatement.java:802)
        at com.redhat.rhn.common.db.datasource.CachedStatement.processResultSet(CachedStatement.java:655)
        at com.redhat.rhn.common.db.datasource.CachedStatement.execute(CachedStatement.java:500)
        at com.redhat.rhn.common.db.datasource.CachedStatement.lambda$executeChecking$1(CachedStatement.java:451)
        at org.hibernate.jdbc.WorkExecutor.executeReturningWork(WorkExecutor.java:55)
        at org.hibernate.internal.SessionImpl$2.accept(SessionImpl.java:2401)
        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.coordinateWork(JdbcCoordinatorImpl.java:320)
        at org.hibernate.internal.SessionImpl.doWork(SessionImpl.java:2408)
        at org.hibernate.internal.SessionImpl.doReturningWork(SessionImpl.java:2404)
        at com.redhat.rhn.common.db.datasource.CachedStatement.doWithStolenConnection(CachedStatement.java:915)
        at com.redhat.rhn.common.db.datasource.CachedStatement.executeChecking(CachedStatement.java:449)
        at com.redhat.rhn.common.db.datasource.CachedStatement.executeElaboratorBatch(CachedStatement.java:388)
        at com.redhat.rhn.common.db.datasource.CachedStatement.executeElaboratorBatch(CachedStatement.java:415)
        at com.redhat.rhn.common.db.datasource.CachedStatement.executeElaborator(CachedStatement.java:364)
        at com.redhat.rhn.common.db.datasource.SelectMode.elaborate(SelectMode.java:129)
        at com.redhat.rhn.common.db.datasource.DataResult.elaborate(DataResult.java:158)
        at com.redhat.rhn.taskomatic.task.repomd.UpdateInfoWriter.getUpdateInfo(UpdateInfoWriter.java:60)
        at com.redhat.rhn.taskomatic.task.repomd.RpmRepositoryWriter.generateUpdateinfo(RpmRepositoryWriter.java:493)
        at com.redhat.rhn.taskomatic.task.repomd.RpmRepositoryWriter.writeRepomdFiles(RpmRepositoryWriter.java:261)
        at com.redhat.rhn.taskomatic.task.repomd.ChannelRepodataWorker.run(ChannelRepodataWorker.java:113)
        at EDU.oswego.cs.dl.util.concurrent.PooledExecutor$Worker.run(PooledExecutor.java:732)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.GeneratedMethodAccessor344.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.redhat.rhn.common.util.MethodUtil.callMethod(MethodUtil.java:202)
        ... 22 more
Caused by: com.redhat.rhn.frontend.xmlrpc.InvalidParameterException: Invalid advisory status
        at com.redhat.rhn.frontend.dto.ErrataOverview.lambda$setAdvisoryStatus$0(ErrataOverview.java:343)
        at java.base/java.util.Optional.orElseThrow(Optional.java:408)
        at com.redhat.rhn.frontend.dto.ErrataOverview.setAdvisoryStatus(ErrataOverview.java:343)
        ... 26 more
2021-10-06 13:48:51,719 [Thread-148] ERROR com.redhat.rhn.taskomatic.task.ChannelRepodata - com.redhat.rhn.common.MethodInvocationException: Something bad happened when calling setAdvisoryStatus

**Comment by mcalmer** [comment]
I think this is already fixed as EPEL used some unknown status entries for errata.
Please try with the latest uyuni version. In case it is still a problem, please open a new issue.

I will close this one-
