### ISSUE TITLE
rhnSQL.SQLError caught - Uyuni 2021.09

### ISSUE THREAD

**Issue by kluchoslaw** [uyuni-project/uyuni#4462]
Version        : 2021.09-141.3.uyuni1
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2021.09-141.3.uyuni1.src

Traditional Uyuni clients get "Fatal error in Python code occurred [[6]]" while applying errata from GUI. 
Probably something similar was solved in SUSE Manager 4.2 http://bugzilla.suse.com/show_bug.cgi?id=1188289 but I dont have permissions.
In /var/log/apache2/error.log there are visible errors below:
[Fri Nov 12 10:07:06.885191 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] SUSE Manager 31417 2021/11/12 10:07:06 +02:00: ('rhnSQL.SQLError caught', SQLStatementPrepareError(None, "<connection object at 0x7f10e90792b8; dsn: 'user=uyuni password=xxx dbname=uyuni', closed: 0>", '\\n        select distinct\\n               pn.name,\\n               pe.epoch,\\n               pe.version,\\n               pe.release,\\n               pa.label arch\\n        from\\n               rhnPackageName pn,\\n               rhnPackageEVR pe,\\n               rhnPackage p,\\n               rhnPackageArch pa,\\n               rhnChannelPackage cp,\\n               rhnServerChannel sc,\\n               rhnErrataPackage ep\\n        where\\n                   ep.errata_id = %(errata_id)s\\n               and ep.package_id = p.id\\n               and p.name_id = pn.id\\n               and p.evr_id = pe.id\\n               and p.package_arch_id = pa.id\\n               and sc.server_id = %(server_id)s\\n               and sc.channel_id = cp.channel_id\\n               and cp.package_id = p.id\\n        '))
[Fri Nov 12 10:07:06.887977 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] Exception reported from server-uyuni
[Fri Nov 12 10:07:06.887995 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] Time: Fri Nov 12 10:07:06 2021
[Fri Nov 12 10:07:06.888000 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] Exception type <class 'spacewalk.server.rhnSQL.sql_base.SQLStatementPrepareError'>
[Fri Nov 12 10:07:06.888003 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] Exception while handling function errata.getErrataInfo
[Fri Nov 12 10:07:06.888018 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] Request object information:
[Fri Nov 12 10:07:06.888022 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] URI: /XMLRPC
[Fri Nov 12 10:07:06.888026 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] Remote Host: test.corp.local
[Fri Nov 12 10:07:06.888029 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] Server Name: server-uyuni.corp.local:80
[Fri Nov 12 10:07:06.888033 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] Headers passed in:
[Fri Nov 12 10:07:06.888036 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tAccept-Encoding: identity
[Fri Nov 12 10:07:06.888039 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tCONTENT_LENGTH: 2458
[Fri Nov 12 10:07:06.888043 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tCONTENT_TYPE: text/xml
[Fri Nov 12 10:07:06.888047 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tCONTEXT_DOCUMENT_ROOT: /srv/www/htdocs
[Fri Nov 12 10:07:06.888051 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tCONTEXT_PREFIX: 
[Fri Nov 12 10:07:06.888055 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tDOCUMENT_ROOT: /srv/www/htdocs
[Fri Nov 12 10:07:06.888059 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tGATEWAY_INTERFACE: CGI/1.1
[Fri Nov 12 10:07:06.888063 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tHTTP_ACCEPT_ENCODING: identity
[Fri Nov 12 10:07:06.888067 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tHTTP_HOST: server-uyuni.corp.local
[Fri Nov 12 10:07:06.888070 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tHTTP_USER_AGENT: rhn.rpclib.py/2.8.62.8.6-8.module_el8.1.0+211+ad6c0bc78.module_el8.1.0+211+ad6c0bc7
[Fri Nov 12 10:07:06.888074 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tHTTP_X_CLIENT_VERSION: 1
[Fri Nov 12 10:07:06.888078 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tHTTP_X_INFO: RPC Processor (C) Red Hat, Inc (version 2.8.62.8.6-8.module_el8.1.0+211+ad6c0bc78.module_el8.1.0+211+ad6c0bc7)
[Fri Nov 12 10:07:06.888081 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tHTTP_X_RHN_CLIENT_CAPABILITY: caneatCheese(1)=1,osad.ping(1)=1,osad.rhn_check(1)=1,configfiles.mtime_upload(1)=1,configfiles.upload(1)=1,configfiles.deploy(1)=1,configfiles.diff(1)=1,configfiles.base64_enc(1)=1,script.run(1)=1,packages.runTransaction(1)=1,packages.rollBack(1)=1,packages.verify(1)=1,packages.extended_profile(2)=1,reboot.reboot(1)=1,packages.update(2)=2
[Fri Nov 12 10:07:06.888085 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tHTTP_X_RHN_TRANSPORT_CAPABILITY: follow-redirects=3
[Fri Nov 12 10:07:06.888090 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tHTTP_X_TRANSPORT_INFO: Extended Capabilities Transport (C) Red Hat, Inc (version 2.8.62.8.6-8.module_el8.1.0+211+ad6c0bc78.module_el8.1.0+211+ad6c0bc7)
[Fri Nov 12 10:07:06.888093 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tHTTP_X_UP2DATE_VERSION: 2.8.16-13.module_el8.1.0+211+ad6c0bc7
[Fri Nov 12 10:07:06.888097 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tHost: server-uyuni.corp.local
[Fri Nov 12 10:07:06.888100 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tPATH_INFO: 
[Fri Nov 12 10:07:06.888104 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tQUERY_STRING: 
[Fri Nov 12 10:07:06.888108 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tREMOTE_ADDR: 10.1.1.2
[Fri Nov 12 10:07:06.888113 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tREMOTE_PORT: 39856
[Fri Nov 12 10:07:06.888116 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tREQUEST_METHOD: POST
[Fri Nov 12 10:07:06.888119 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tREQUEST_SCHEME: http
[Fri Nov 12 10:07:06.888123 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tREQUEST_URI: /XMLRPC
[Fri Nov 12 10:07:06.888132 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tSCRIPT_FILENAME: /usr/share/rhn/wsgi/xmlrpc.py
[Fri Nov 12 10:07:06.888136 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tSCRIPT_NAME: /XMLRPC
[Fri Nov 12 10:07:06.888139 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tSCRIPT_URI: http://server-uyuni.corp.local/XMLRPC
[Fri Nov 12 10:07:06.888143 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tSCRIPT_URL: /XMLRPC
[Fri Nov 12 10:07:06.888146 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tSERVER_ADDR: 10.1.1.1
[Fri Nov 12 10:07:06.888150 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tSERVER_ADMIN: [no address given]
[Fri Nov 12 10:07:06.888153 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tSERVER_NAME: server-uyuni.corp.local
[Fri Nov 12 10:07:06.888157 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tSERVER_PORT: 80
[Fri Nov 12 10:07:06.888161 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tSERVER_PROTOCOL: HTTP/1.1
[Fri Nov 12 10:07:06.888165 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tSERVER_SIGNATURE: 
[Fri Nov 12 10:07:06.888169 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tSERVER_SOFTWARE: Apache
[Fri Nov 12 10:07:06.888172 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tUser-Agent: rhn.rpclib.py/2.8.62.8.6-8.module_el8.1.0+211+ad6c0bc78.module_el8.1.0+211+ad6c0bc7
[Fri Nov 12 10:07:06.888175 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tX-Client-Version: 1
[Fri Nov 12 10:07:06.888179 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tX-Info: RPC Processor (C) Red Hat, Inc (version 2.8.62.8.6-8.module_el8.1.0+211+ad6c0bc78.module_el8.1.0+211+ad6c0bc7)
[Fri Nov 12 10:07:06.888182 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tX-RHN-Client-Capability: caneatCheese(1)=1,osad.ping(1)=1,osad.rhn_check(1)=1,configfiles.mtime_upload(1)=1,configfiles.upload(1)=1,configfiles.deploy(1)=1,configfiles.diff(1)=1,configfiles.base64_enc(1)=1,script.run(1)=1,packages.runTransaction(1)=1,packages.rollBack(1)=1,packages.verify(1)=1,packages.extended_profile(2)=1,reboot.reboot(1)=1,packages.update(2)=2
[Fri Nov 12 10:07:06.888186 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tX-RHN-Transport-Capability: follow-redirects=3
[Fri Nov 12 10:07:06.888190 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tX-Transport-Info: Extended Capabilities Transport (C) Red Hat, Inc (version 2.8.62.8.6-8.module_el8.1.0+211+ad6c0bc78.module_el8.1.0+211+ad6c0bc7)
[Fri Nov 12 10:07:06.888193 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tX-Up2Date-Version: 2.8.16-13.module_el8.1.0+211+ad6c0bc7
[Fri Nov 12 10:07:06.888196 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tapache.version: (2, 4, 33)
[Fri Nov 12 10:07:06.888199 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tmod_wsgi.application_group: server-uyuni.corp.local|/xmlrpc
[Fri Nov 12 10:07:06.888202 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tmod_wsgi.callable_object: application
[Fri Nov 12 10:07:06.888205 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tmod_wsgi.enable_sendfile: 0
[Fri Nov 12 10:07:06.888208 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tmod_wsgi.handler_script: 
[Fri Nov 12 10:07:06.888213 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tmod_wsgi.ignore_activity: 0
[Fri Nov 12 10:07:06.888217 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tmod_wsgi.listener_host: 
[Fri Nov 12 10:07:06.888220 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tmod_wsgi.listener_port: 80
[Fri Nov 12 10:07:06.888223 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tmod_wsgi.path_info: 
[Fri Nov 12 10:07:06.888226 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tmod_wsgi.process_group: 
[Fri Nov 12 10:07:06.888229 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tmod_wsgi.request_handler: wsgi-script
[Fri Nov 12 10:07:06.888236 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tmod_wsgi.request_id: agCLyJOisNk
[Fri Nov 12 10:07:06.888239 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tmod_wsgi.request_start: 1636708026876010
[Fri Nov 12 10:07:06.888243 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tmod_wsgi.script_name: /XMLRPC
[Fri Nov 12 10:07:06.888247 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tmod_wsgi.script_reloading: 1
[Fri Nov 12 10:07:06.888250 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tmod_wsgi.script_start: 1636708026876186
[Fri Nov 12 10:07:06.888253 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tmod_wsgi.thread_id: 0
[Fri Nov 12 10:07:06.888257 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tmod_wsgi.thread_requests: 62
[Fri Nov 12 10:07:06.888260 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tmod_wsgi.total_requests: 62
[Fri Nov 12 10:07:06.888264 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \tmod_wsgi.version: (4, 5, 18)
[Fri Nov 12 10:07:06.888268 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \twsgi.errors: <_io.TextIOWrapper name='<wsgi.errors>' encoding='utf-8'>
[Fri Nov 12 10:07:06.888273 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \twsgi.file_wrapper: <class 'mod_wsgi.FileWrapper'>
[Fri Nov 12 10:07:06.888277 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \twsgi.input: <mod_wsgi.Input object at 0x7f10f22b42d0>
[Fri Nov 12 10:07:06.888281 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \twsgi.multiprocess: True
[Fri Nov 12 10:07:06.888285 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \twsgi.multithread: False
[Fri Nov 12 10:07:06.888290 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \twsgi.run_once: False
[Fri Nov 12 10:07:06.888294 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \twsgi.url_scheme: http
[Fri Nov 12 10:07:06.888297 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] \twsgi.version: (1, 0)
[Fri Nov 12 10:07:06.888300 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] Extra information about this error:
[Fri Nov 12 10:07:06.888305 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] SQL Error generated: (None, "<connection object at 0x7f10e90792b8; dsn: 'user=uyuni password=xxx dbname=uyuni', closed: 0>", '\\n        select distinct\\n               pn.name,\\n               pe.epoch,\\n               pe.version,\\n               pe.release,\\n               pa.label arch\\n        from\\n               rhnPackageName pn,\\n               rhnPackageEVR pe,\\n               rhnPackage p,\\n               rhnPackageArch pa,\\n               rhnChannelPackage cp,\\n               rhnServerChannel sc,\\n               rhnErrataPackage ep\\n        where\\n                   ep.errata_id = %(errata_id)s\\n               and ep.package_id = p.id\\n               and p.name_id = pn.id\\n               and p.evr_id = pe.id\\n               and p.package_arch_id = pa.id\\n               and sc.server_id = %(server_id)s\\n               and sc.channel_id = cp.channel_id\\n               and cp.package_id = p.id\\n        ')
[Fri Nov 12 10:07:06.888312 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] 
[Fri Nov 12 10:07:06.888315 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] Exception Handler Information
[Fri Nov 12 10:07:06.888320 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] Traceback (most recent call last):
[Fri Nov 12 10:07:06.888324 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856]   File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 299, in _execute_wrapper
[Fri Nov 12 10:07:06.888329 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856]     retval = function(*p, **kw)
[Fri Nov 12 10:07:06.888332 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856]   File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/sql_base.py", line 182, in _execute
[Fri Nov 12 10:07:06.888340 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856]     return self._execute_(args, kwargs)
[Fri Nov 12 10:07:06.888344 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856]   File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 322, in _execute_
[Fri Nov 12 10:07:06.888348 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856]     self._real_cursor.execute(self.sql, params)
[Fri Nov 12 10:07:06.888352 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] psycopg2.ProgrammingError: can't adapt type 'dict'
[Fri Nov 12 10:07:06.888358 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] 
[Fri Nov 12 10:07:06.888361 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] During handling of the above exception, another exception occurred:
[Fri Nov 12 10:07:06.888365 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] 
[Fri Nov 12 10:07:06.888368 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] Traceback (most recent call last):
[Fri Nov 12 10:07:06.888372 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856]   File "/usr/lib/python3.6/site-packages/spacewalk/server/apacheRequest.py", line 135, in call_function
[Fri Nov 12 10:07:06.888377 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856]     response = func(*params)
[Fri Nov 12 10:07:06.888382 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856]   File "/usr/share/rhn/server/handlers/xmlrpc/errata.py", line 223, in getErrataInfo
[Fri Nov 12 10:07:06.888385 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856]     h.execute(errata_id=errata_id, server_id=self.server_id)
[Fri Nov 12 10:07:06.888389 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856]   File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/sql_base.py", line 150, in execute
[Fri Nov 12 10:07:06.888393 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856]     return self._execute_wrapper(self._execute, *p, **kw)
[Fri Nov 12 10:07:06.888396 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856]   File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 309, in _execute_wrapper
[Fri Nov 12 10:07:06.888400 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856]     raise sql_base.SQLStatementPrepareError(str(self.dbh), e.pgerror, self.sql)
[Fri Nov 12 10:07:06.888404 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856] spacewalk.server.rhnSQL.sql_base.SQLStatementPrepareError: (None, "<connection object at 0x7f10e90792b8; dsn: 'user=uyuni password=xxx dbname=uyuni', closed: 0>", '\\n        select distinct\\n               pn.name,\\n               pe.epoch,\\n               pe.version,\\n               pe.release,\\n               pa.label arch\\n        from\\n               rhnPackageName pn,\\n               rhnPackageEVR pe,\\n               rhnPackage p,\\n               rhnPackageArch pa,\\n               rhnChannelPackage cp,\\n               rhnServerChannel sc,\\n               rhnErrataPackage ep\\n        where\\n                   ep.errata_id = %(errata_id)s\\n               and ep.package_id = p.id\\n               and p.name_id = pn.id\\n               and p.evr_id = pe.id\\n               and p.package_arch_id = pa.id\\n               and sc.server_id = %(server_id)s\\n               and sc.channel_id = cp.channel_id\\n               and cp.package_id = p.id\\n        ')
[Fri Nov 12 10:07:06.888413 2021] [wsgi:error] [pid 31417] [client 10.1.1.2:39856]

**Comment by kluchoslaw** [comment]
This was caused by old osad/jabber client. After upgrade it looks ok.
