### ISSUE TITLE
Uyuni Bugreport - Uyuni 2021.12 - Error importing CentOS Stream 9 packages

### ISSUE THREAD

**Issue by ppc6446** [uyuni-project/uyuni#4560]
# Additional Information

## Version of Uyuni Server and Proxy (if used)
```
# zypper info Uyuni-Server-release
Loading repository data...
Reading installed packages...


Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2021.12-160.4.uyuni1
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2021.12-160.4.uyuni1.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.

```
## Details about issue
spacewalk-repo-sync is failing to import CentOS Stream 9 packages with the message `value too long for type character varying(4000)` -

```
 # spacewalk-repo-sync -c centos9-stream-x86_64
16:49:28 ======================================
16:49:28 | Channel: centos9-stream-x86_64
16:49:28 ======================================
16:49:28 Sync of channel started.
Retrieving repository 'centos9-stream-x86_64' metadata ...................[done]
Building repository 'centos9-stream-x86_64' cache ........................[done]
All repositories have been refreshed.
16:49:30
16:49:30   Importing comps file a37577dc74011c2870ad2469ceda42a2c1c27cd6a7bced18255b4706d4461e2b-comps-BaseOS.x86_64.xml.
16:49:30   Renaming non-standard filename a37577dc74011c2870ad2469ceda42a2c1c27cd6a7bced18255b4706d4461e2b-comps-BaseOS.x86_64.xml to comps.x86_64.xml.
16:49:30 *** NOTE: Importing comps file for the channel 'centos9-stream-x86_64'. Previous comps will be discarded.
16:49:30 Repo URL: http://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os
16:49:30     Packages in repo:              1788
16:49:35     Packages already synced:          0
16:49:35     Packages to sync:              1788
16:49:35     New packages to download:        80
16:49:35   Downloading packages:
16:49:35 Downloading total 80 files from 1 queues.
16:49:35     1/80 : avahi-libs-0.8-11.el9.i686.rpm
16:49:35     2/80 : cups-libs-2.3.3op2-10.el9.i686.rpm
16:49:35     3/80 : avahi-libs-0.8-11.el9.x86_64.rpm
16:49:35     4/80 : cyrus-sasl-lib-2.1.27-17.el9.i686.rpm
16:49:36     5/80 : cryptsetup-libs-2.4.1-1.el9.x86_64.rpm
16:49:36     6/80 : elfutils-0.186-1.el9.x86_64.rpm
16:49:36     7/80 : elfutils-debuginfod-client-0.185-5.el9.i686.rpm
16:49:36     8/80 : cyrus-sasl-lib-2.1.27-17.el9.x86_64.rpm
16:49:36     9/80 : elfutils-libelf-0.186-1.el9.x86_64.rpm
16:49:36     10/80 : elfutils-libs-0.185-5.el9.i686.rpm
16:49:36     11/80 : glibc-langpack-bem-2.34-8.el9.x86_64.rpm
16:49:36     12/80 : glibc-langpack-bem-2.34-7.el9.x86_64.rpm
16:49:36     13/80 : glibc-langpack-bi-2.34-7.el9.x86_64.rpm
16:49:36     14/80 : glibc-langpack-bi-2.34-8.el9.x86_64.rpm
16:49:36     15/80 : binutils-2.35.2-9.el9.x86_64.rpm
16:49:36     16/80 : binutils-2.35.2-9.el9.i686.rpm
16:49:36     17/80 : glibc-langpack-gl-2.34-8.el9.x86_64.rpm
16:49:36     18/80 : glibc-langpack-gl-2.34-7.el9.x86_64.rpm
16:49:36     19/80 : glibc-langpack-he-2.34-7.el9.x86_64.rpm
16:49:36     20/80 : glibc-langpack-he-2.34-8.el9.x86_64.rpm
16:49:36     21/80 : glibc-langpack-mfe-2.34-7.el9.x86_64.rpm
16:49:36     22/80 : glibc-langpack-mfe-2.34-8.el9.x86_64.rpm
16:49:36     23/80 : glibc-langpack-mjw-2.34-7.el9.x86_64.rpm
16:49:36     24/80 : glibc-langpack-mjw-2.34-8.el9.x86_64.rpm
16:49:36     25/80 : glibc-langpack-sgs-2.34-7.el9.x86_64.rpm
16:49:36     26/80 : glibc-langpack-sgs-2.34-8.el9.x86_64.rpm
16:49:36     27/80 : glibc-langpack-sk-2.34-7.el9.x86_64.rpm
16:49:36     28/80 : glibc-langpack-sk-2.34-8.el9.x86_64.rpm
16:49:36     29/80 : glibc-langpack-yo-2.34-8.el9.x86_64.rpm
16:49:36     30/80 : glibc-langpack-yo-2.34-7.el9.x86_64.rpm
16:49:36     31/80 : glibc-minimal-langpack-2.34-7.el9.x86_64.rpm
16:49:36     32/80 : glibc-minimal-langpack-2.34-8.el9.x86_64.rpm
16:49:36     33/80 : ipset-libs-7.11-5.el9.i686.rpm
16:49:36     34/80 : ipset-libs-7.11-5.el9.x86_64.rpm
16:49:36     35/80 : iptables-utils-1.8.7-23.el9.x86_64.rpm
16:49:36     36/80 : iptables-utils-1.8.7-26.el9.x86_64.rpm
16:49:36     37/80 : libassuan-2.5.5-3.el9.i686.rpm
16:49:36     38/80 : libassuan-2.5.5-3.el9.x86_64.rpm
16:49:36     39/80 : libbasicobjects-0.1.1-51.el9.i686.rpm
16:49:36     40/80 : libbasicobjects-0.1.1-51.el9.x86_64.rpm
16:49:36     41/80 : libgcrypt-1.9.3-5.el9.i686.rpm
16:49:36     42/80 : libgcrypt-1.9.3-5.el9.x86_64.rpm
16:49:37     43/80 : libgomp-11.2.1-6.1.el9.i686.rpm
16:49:37     44/80 : libgomp-11.2.1-6.1.el9.x86_64.rpm
16:49:37     45/80 : libpkgconf-1.7.3-9.el9.i686.rpm
16:49:37     46/80 : libpkgconf-1.7.3-9.el9.x86_64.rpm
16:49:37     47/80 : libqmi-utils-1.30.2-1.el9.x86_64.rpm
16:49:37     48/80 : libquadmath-11.2.1-2.2.el9.i686.rpm
16:49:37     49/80 : libstdc++-11.2.1-6.1.el9.x86_64.rpm
16:49:37     50/80 : libstdc++-11.2.1-6.el9.i686.rpm
16:49:37     51/80 : kernel-core-5.14.0-16.el9.x86_64.rpm
16:49:37     52/80 : libtdb-1.4.3-10.el9.x86_64.rpm
16:49:37     53/80 : libteam-1.31-10.el9.i686.rpm
16:49:37     54/80 : lzop-1.04-8.el9.x86_64.rpm
16:49:37     55/80 : mailcap-2.1.49-5.el9.noarch.rpm
16:49:37     56/80 : kernel-core-5.14.0-17.el9.x86_64.rpm
16:49:38     57/80 : microdnf-3.8.0-3.el9.x86_64.rpm
16:49:38     58/80 : openssh-keycat-8.7p1-5.el9.x86_64.rpm
16:49:38     59/80 : openssh-server-8.6p1-7.el9.1.x86_64.rpm
16:49:38     60/80 : microcode_ctl-20210608-2.el9.noarch.rpm
16:49:38     61/80 : openssl-libs-3.0.0-3.el9.x86_64.rpm
16:49:38     62/80 : openssl-libs-3.0.0-4.el9.i686.rpm
16:49:38     63/80 : python3-dnf-4.7.0-2.el9.noarch.rpm
16:49:38     64/80 : python3-dnf-plugin-post-transaction-actions-4.0.21-2.el9.noarch.rpm
16:49:38     65/80 : python3-gpg-1.15.1-5.el9.x86_64.rpm
16:49:38     66/80 : python3-hawkey-0.63.0-4.el9.x86_64.rpm
16:49:38     67/80 : rpm-sign-libs-4.16.1.3-7.el9.x86_64.rpm
16:49:38     68/80 : rsync-3.2.3-9.el9.x86_64.rpm
16:49:38     69/80 : samba-winbind-4.14.5-103.el9.x86_64.rpm
16:49:38     70/80 : samba-winbind-modules-4.14.5-103.el9.i686.rpm
16:49:38     71/80 : subscription-manager-rhsm-certificates-1.29.18-2.el9.x86_64.rpm
16:49:38     72/80 : subscription-manager-rhsm-certificates-1.29.21-1.el9.x86_64.rpm
16:49:38     73/80 : kernel-debug-core-5.14.0-16.el9.x86_64.rpm
16:49:38     74/80 : wpa_supplicant-2.9-17.20211112.gitc8b94bc7b347.el9.x86_64.rpm
16:49:38     75/80 : systemd-249-9.el9.i686.rpm
16:49:38     76/80 : systemd-249-9.el9.x86_64.rpm
16:49:38     77/80 : wpa_supplicant-2.9-17.el9.x86_64.rpm
16:49:38     78/80 : yum-4.10.0-1.el9.noarch.rpm
16:49:38     79/80 : yum-4.7.0-2.el9.noarch.rpm
16:49:38     80/80 : kernel-debug-core-5.14.0-17.el9.x86_64.rpm
16:49:39
16:49:39   Importing packages to DB:
16:49:39   Package batch #1 of 90 completed...
16:49:39   Package batch #2 of 90 completed...
16:49:39   Package batch #3 of 90 completed...
16:49:39   Package batch #4 of 90 completed...
16:49:39   Package batch #5 of 90 completed...
16:49:39   Package batch #6 of 90 completed...
16:49:39   Package batch #7 of 90 completed...
16:49:39   Package batch #8 of 90 completed...
16:49:39   Package batch #9 of 90 completed...
16:49:39   Package batch #10 of 90 completed...
16:49:39   Package batch #11 of 90 completed...
16:49:39   Package batch #12 of 90 completed...
16:49:39   Package batch #13 of 90 completed...
16:49:39   Package batch #14 of 90 completed...
16:49:39   Package batch #15 of 90 completed...
16:49:39   Package batch #16 of 90 completed...
16:49:39   Package batch #17 of 90 completed...
16:49:39   Package batch #18 of 90 completed...
16:49:39   Package batch #19 of 90 completed...
16:49:39   Package batch #20 of 90 completed...
16:49:39   Package batch #21 of 90 completed...
16:49:39   Package batch #23 of 90 completed...
16:49:39   Package batch #22 of 90 completed...
16:49:39   Package batch #24 of 90 completed...
16:49:39   Package batch #25 of 90 completed...
16:49:39   Package batch #26 of 90 completed...
16:49:39   Package batch #27 of 90 completed...
16:49:39   Package batch #28 of 90 completed...
16:49:39   Package batch #29 of 90 completed...
16:49:39   Package batch #30 of 90 completed...
16:49:39   Package batch #31 of 90 completed...
16:49:39   Package batch #32 of 90 completed...
16:49:39   Package batch #33 of 90 completed...
16:49:39   Package batch #34 of 90 completed...
16:49:39   Package batch #35 of 90 completed...
16:49:39   Package batch #36 of 90 completed...
16:49:40   Package batch #37 of 90 completed...
16:49:40   Package batch #38 of 90 completed...
16:49:40   Package batch #39 of 90 completed...
16:49:40   Package batch #40 of 90 completed...
16:49:40   Package batch #41 of 90 completed...
16:49:40   Package batch #42 of 90 completed...
16:49:40   Package batch #43 of 90 completed...
16:49:40   Package batch #44 of 90 completed...
16:49:40   Package batch #45 of 90 completed...
16:49:40   Package batch #46 of 90 completed...
16:49:40   Package batch #47 of 90 completed...
16:49:40   Package batch #48 of 90 completed...
16:49:40   Package batch #49 of 90 completed...
16:49:40   Package batch #50 of 90 completed...
16:49:40   Package batch #51 of 90 completed...
16:49:40   Package batch #52 of 90 completed...
16:49:40   Package batch #53 of 90 completed...
16:49:40   Package batch #54 of 90 completed...
16:49:40   Package batch #55 of 90 completed...
16:49:40   Package batch #56 of 90 completed...
16:49:40   Package batch #57 of 90 completed...
16:49:40   Package batch #58 of 90 completed...
16:49:40   Package batch #61 of 90 completed...
16:49:40   Package batch #64 of 90 completed...
16:49:40   Package batch #62 of 90 completed...
16:49:40   Package batch #63 of 90 completed...
16:49:40   Package batch #65 of 90 completed...
16:49:40   Package batch #66 of 90 completed...
16:49:40   Package batch #68 of 90 completed...
16:49:40   Package batch #67 of 90 completed...
16:49:40   Package batch #72 of 90 completed...
16:49:40   Package batch #74 of 90 completed...
16:49:40   Package batch #71 of 90 completed...
16:49:40   Package batch #73 of 90 completed...
16:49:40   Package batch #75 of 90 completed...
16:49:40   Package batch #77 of 90 completed...
16:49:40   Package batch #78 of 90 completed...
16:49:40   Package batch #76 of 90 completed...
16:49:40   Package batch #79 of 90 completed...
16:49:40   Package batch #80 of 90 completed...
16:49:40   Package batch #81 of 90 completed...
16:49:40   Package batch #82 of 90 completed...
16:49:40 value too long for type character varying(4000)

16:49:40   Package batch #60 of 90 completed...
16:49:40   Package batch #83 of 90 completed...
16:49:40   Package batch #85 of 90 completed...
16:49:40   Package batch #84 of 90 completed...
16:49:40   Package batch #86 of 90 completed...
16:49:41   Package batch #87 of 90 completed...
16:49:41   Package batch #90 of 90 completed...
16:49:41   Package batch #89 of 90 completed...
16:49:41   Package batch #88 of 90 completed...
16:49:41 value too long for type character varying(4000)

16:49:41   Package batch #59 of 90 completed...
16:49:41 value too long for type character varying(4000)

16:49:41   Package batch #70 of 90 completed...
16:49:41 value too long for type character varying(4000)

16:49:41   Package batch #69 of 90 completed...
16:49:41
16:49:41   Linking packages to the channel.
16:49:41 Unexpected error: <class 'spacewalk.server.importlib.importLib.InvalidPackageError'>
16:49:41 Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 598, in sync
    ret = self.import_packages(plugin, data['id'], url, is_non_local_repo)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 1142, in import_packages
    importer.run()
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/importLib.py", line 778, in run
    self.submit()
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/packageImport.py", line 131, in submit
    self.backend.lookupPackages(self.batch, self.checksums)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 834, in lookupPackages
    raise_with_tb(not_found[0], not_found[1])
  File "/usr/lib/python3.6/site-packages/uyuni/common/usix.py", line 77, in raise_with_tb
    raise value
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 826, in lookupPackages
    self.__lookupObjectCollection([package], 'rhnPackage')
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 2506, in __lookupObjectCollection
    raise InvalidPackageError(object, "Could not find object %s in table %s" % (object, tableName))
spacewalk.server.importlib.importLib.InvalidPackageError: Could not find object [<<class 'spacewalk.server.importlib.importLib.IncompletePackage'> instance; attributes={'package_id': None, 'name': 'avahi-libs', 'epoch': None, 'version': '0.8', 'release': '11.el9', 'arch': 'i686', 'org_id': 1, 'package_size': None, 'last_modified': None, 'md5sum': None, 'channels': {175: 'centos9-stream-x86_64'}, 'checksum_list': None, 'checksum': 'c662fcdbc9628d195304f58279f8cf201dc87b4641587fda749da9a3c6844dd3', 'checksum_type': 'sha256', 'checksums': {'sha256': 'c662fcdbc9628d195304f58279f8cf201dc87b4641587fda749da9a3c6844dd3'}, 'name_id': 6734, 'evr_id': 142965, 'package_arch_id': 104, 'nevra_id': 248237, 'checksum_id': 10436020}] in table rhnPackage

16:49:41 Total time: 0:00:13
```

**Comment by juliogonzalez** [comment]
If the community wants to help with this, and someone wants to be a maintainer, it could be possible to reuse the EL9 client tools for CentOS Stream9, and see what happens.

The PR should not be that complicated, it would be like adding another EL9 clone (repos, susemanager-sls, bootstrap repo definitions...).

I can provide guidance, if needed.

But since this is a bug report, let close it.
