### ISSUE TITLE
Uyuni Bugreport - Uyuni 2021.12  spacewalk-repo-sync --channel opensuse_leap15_2-x86_64-updates

### ISSUE THREAD

**Issue by ALutz273** [uyuni-project/uyuni#4629]
# Additional Information

Would like to sync the repo. with "spacewalk-repo-sync". But get an error when importing 

## Version of Uyuni Server and Proxy (if used)
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2021.12-160.4.uyuni1
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2021.12-160.4.uyuni1.src
Summary        : Uyuni Server

cat /etc/os-release
NAME="openSUSE Leap"
VERSION="15.3"
ID="opensuse-leap"

Kernel 5.3.18-59.37-default 
## Details about issue
Package batch #976 of 1059 completed...
Package batch #977 of 1059 completed...
Package batch #978 of 1059 completed...
Package batch #979 of 1059 completed...
Package batch #980 of 1059 completed...
Package batch #981 of 1059 completed...
Package batch #982 of 1059 completed...
Package batch #983 of 1059 completed...
Package batch #984 of 1059 completed...
Package batch #992 of 1059 completed..
connection already closed
connection already closed
connection already closed
connection already closed
connection already closed
connection already closed
connection already closed
connection already closed
Unexpected error: <class 'psycopg2.InterfaceError'>
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 1333, in import_package_batch
    rhnSQL.closeDB()
  File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/__init__.py", line 141, in closeDB
    __DB.commit()
  File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 239, in commit
    self.dbh.commit()
psycopg2.InterfaceError: connection already closed
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 598, in sync
    ret = self.import_packages(plugin, data['id'], url, is_non_local_repo)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 1113, in import_packages
    affected_channels_batch, failed_packages_batch, all_packages, processed_batch = result.get()
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
psycopg2.InterfaceError: connection already closed

Traceback (most recent call last):
  File "/usr/bin/spacewalk-repo-sync", line 286, in <module>
    sys.exit(abs(main() or 0))
  File "/usr/bin/spacewalk-repo-sync", line 269, in main
    elapsed_time, channel_ret_code = sync.sync()
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 674, in sync
    rhnSQL.commit()
  File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/__init__.py", line 224, in commit
    return db.commit()
  File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 239, in commit
    self.dbh.commit()
psycopg2.OperationalError: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.

_In general: all that can help someone to reproduce the issue or understand it_

**Comment by ALutz273** [comment]
Have given the Uyuni-server more resources (CPU/RAM). After that the import worked!
