### ISSUE TITLE
Uyuni Bugreport - Uyuni 2022.01 Can't register server with IPv4 secondary interface

### ISSUE THREAD

**Issue by phibid** [uyuni-project/uyuni#4854]
When trying to register via salt-ssh a new server configured with a secondary interface (such as a VIP from Keepalived), I have the following error:

```
INFO: Connected to https://uyuni/rpc/api as admin
ERROR: redstone.xmlrpc.XmlRpcFault: [SaltSSHError(1, Traceback (most recent call last):, File "/var/tmp/.root_930115_salt/salt-call", line
 27, in <module>, salt_call(), File "/var/tmp/.root_930115_salt/py27/pyall/salt/scripts.py", line 452, in salt_call, client.run(),
File "/var/tmp/.root_930115_salt/py27/pyall/salt/cli/call.py", line 47, in run, caller = salt.cli.caller.Caller.factory(self.config), File 
"/var/tmp/.root_930115_salt/py27/pyall/salt/cli/caller.py", line 63, in factory, return ZeroMQCaller(opts, **kwargs), File "/var/tmp
/.root_930115_salt/py27/pyall/salt/cli/caller.py", line 312, in __init__, super(ZeroMQCaller, self).__init__(opts), File "/var/tmp
/.root_930115_salt/py27/pyall/salt/cli/caller.py", line 87, in __init__, self.minion = salt.minion.SMinion(opts), File "/var/tmp
/.root_930115_salt/py27/pyall/salt/minion.py", line 844, in __init__, opts['grains'] = salt.loader.grains(opts), File "/var/tmp
/.root_930115_salt/py27/pyall/salt/loader.py", line 819, in grains, ret = funcs[key](), File "/var/tmp/.root_930115_salt/py27/pyall
/salt/grains/core.py", line 2378, in ip6_interfaces, socket.inet_pton(socket.AF_INET6, secondary["address"]), socket.error: illegal IP 
address string passed to inet_pton)]
```

Network interface configuration of my server:

```
2: ens192: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:90:AA:be:5b:d3 brd ff:ff:ff:ff:ff:ff
    inet 10.4.3.7/27 brd 10.4.3.31 scope global noprefixroute ens192
       valid_lft forever preferred_lft forever
    inet 10.4.3.9/27 scope global secondary ens192
       valid_lft forever preferred_lft forever
    inet6 feaa::250:ccff:febe:5bd3/64 scope link 
       valid_lft forever preferred_lft forever
```

And indeed, in the salt thin file `/var/tmp/.root_930115_salt/py27/pyall/salt/grains/core.py`:

```
        for secondary in ifaces[face].get('secondary', []):
            if 'address' in secondary:
                try:
                    socket.inet_pton(socket.AF_INET6, secondary["address"])
                    iface_ips.append(secondary["address"])
                except OSError:
                    pass
        ret[face] = iface_ips
```

After a little bit of debugging, I could see that in my case , the `secondary` variable equal to:

```
'secondary': [{'broadcast': None, 'netmask': '255.255.255.224', 'label': 'ens192', 'type': 'inet', 'address': '10.4.3.9'}]}}
```

`secondary.address` is indeed not an IPv6 address, which explains the `illegal IP address string passed to inet_pton` error.

**Comment by phibid** [comment]
Ok, issue + commit already exists on Saltstack

https://github.com/saltstack/salt/issues/61370
https://github.com/saltstack/salt/commit/75c0cb7181d14f780b24ee5dd126f2836730053b

A condition has been added to prevent this:

```
if "address" in secondary and secondary.get("type") == "inet6":
```

Question is, when will this fix be included in the salt version provided by Uyuni ?

**Comment by vzhestkov** [comment]
@phibid have you checked if the issue is still present with using Salt SSH with the Salt Bundle?

**Comment by vzhestkov** [comment]
It seems we've addressed the issue already for `py27-compat-salt` different way: https://github.com/openSUSE/salt/commit/96e906ec612541fe6d4c2596481e027191447022

It looks like it should be fine now with either Salt Bundle or updated `py27-compat-salt`

**Comment by vzhestkov** [comment]
@phibid could you please check if the issue still exists?

**Comment by phibid** [comment]
I have just tested the registration of a server with an IP alias configured, and so far so good, no more issue.

Closing this issue. Thanks !
