### ISSUE TITLE
Bugreport - 2022.02 Error 500, not able to bootstrap new clients anymore

### ISSUE THREAD

**Issue by phibid** [uyuni-project/uyuni#4927]
Uyuni and proxies just updated to 2022.22, and since then , no way to bootstrap, through salt-ssh in my case) new servers:

```
# spacecmd -u "admin" -p "xx" -- system_bootstrap --hostname ubuntu2004 --ssh-password r00tm3 --activation-key 1-ubuntu2004_ssh --proxyid 1000010024 --saltssh
INFO: Spacewalk Username: admin
INFO: Connected to https://uyuni/rpc/api as admin
Bootstrapping 'ubuntu2004'. This may take a while.
ERROR: redstone.xmlrpc.XmlRpcFault: unhandled internal exception: com.suse.salt.netapi.exception.SaltException: Response code: 500
```

Complete strack trace in tomcat log:

```
01-Mar-2022 14:18:48.916 SEVERE [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-10] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [default] in context with path [/rhn] threw exception
        java.lang.RuntimeException: com.suse.salt.netapi.exception.SaltException: Response code: 500
                at com.suse.manager.webui.services.impl.SaltService.callSyncResult(SaltService.java:229)
                at com.suse.manager.webui.services.impl.SaltService.callSync(SaltService.java:238)
                at com.suse.manager.webui.services.impl.SaltService.getGrains(SaltService.java:448)
                at com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction.registerSSHMinion(RegisterMinionEventMessageAction.java:156)
                at com.suse.manager.webui.controllers.utils.SSHMinionBootstrapper.bootstrapInternal(SSHMinionBootstrapper.java:111)
                at com.suse.manager.webui.controllers.utils.AbstractMinionBootstrapper.bootstrap(AbstractMinionBootstrapper.java:100)
                at com.suse.manager.webui.controllers.MinionsAPI.bootstrapSSH(MinionsAPI.java:235)
                at com.suse.manager.webui.utils.SparkApplicationHelper.lambda$withRole$10(SparkApplicationHelper.java:382)
                at spark.RouteImpl$1.handle(RouteImpl.java:72)
                at spark.http.matching.Routes.execute(Routes.java:61)
                at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
                at spark.servlet.SparkFilter.doFilter(SparkFilter.java:173)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at com.redhat.rhn.frontend.servlets.AuthFilter.doFilter(AuthFilter.java:98)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at com.opensymphony.module.sitemesh.filter.PageFilter.parsePage(PageFilter.java:142)
                at com.opensymphony.module.sitemesh.filter.PageFilter.doFilter(PageFilter.java:58)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at com.redhat.rhn.frontend.servlets.LocalizedEnvironmentFilter.doFilter(LocalizedEnvironmentFilter.java:69)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at com.redhat.rhn.frontend.servlets.EnvironmentFilter.doFilter(EnvironmentFilter.java:99)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at com.redhat.rhn.frontend.servlets.SessionFilter.doFilter(SessionFilter.java:55)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at com.redhat.rhn.frontend.servlets.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:97)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
                at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
                at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:432)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1591)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.base/java.lang.Thread.run(Thread.java:829)
        Caused by: com.suse.salt.netapi.exception.SaltException: Response code: 500
                at com.suse.salt.netapi.client.impl.HttpAsyncClientImpl.createSaltException(HttpAsyncClientImpl.java:145)
                at com.suse.salt.netapi.client.impl.HttpAsyncClientImpl.access$000(HttpAsyncClientImpl.java:27)
                at com.suse.salt.netapi.client.impl.HttpAsyncClientImpl$1.completed(HttpAsyncClientImpl.java:121)
                at com.suse.salt.netapi.client.impl.HttpAsyncClientImpl$1.completed(HttpAsyncClientImpl.java:101)
                at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:123)
                at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:181)
                at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:442)
                at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:332)
                at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
                at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
                at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
                at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:121)
                at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
                at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
                at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
                at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
                at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
                at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
                ... 1 more
```

Tried with the command line and the GUI, same behaviour. From what I can see, any OS is impacted.

**Comment by phibid** [comment]
Somehow, all which is related with salt-ssh is broken. In the log, I can see this too:

```
2022-03-01 15:54:00,036 [Thread-2413] INFO  com.redhat.rhn.taskomatic.task.SSHPush - Executing actions for minion: server1
2022-03-01 15:54:00,040 [Thread-2413] INFO  com.redhat.rhn.taskomatic.task.SSHPush - Performing a check-in for: server1
2022-03-01 15:54:00,045 [DefaultQuartzScheduler_Worker-11] INFO  com.redhat.rhn.taskomatic.task.ErrataCacheTask - In the queue: 1
2022-03-01 15:54:00,120 [Thread-2413] ERROR com.redhat.rhn.taskomatic.task.SSHPush - com.suse.salt.netapi.exception.SaltException: Response code: 500
java.lang.RuntimeException: com.suse.salt.netapi.exception.SaltException: Response code: 500
        at com.suse.manager.webui.services.impl.SaltService.callSyncResult(SaltService.java:229)
        at com.suse.manager.webui.services.impl.SaltService.callSync(SaltService.java:238)
        at com.suse.manager.webui.services.impl.SaltService.ping(SaltService.java:251)
        at com.redhat.rhn.taskomatic.task.sshpush.SSHPushWorkerSalt.performCheckin(SSHPushWorkerSalt.java:334)
        at com.redhat.rhn.taskomatic.task.sshpush.SSHPushWorkerSalt.lambda$run$0(SSHPushWorkerSalt.java:113)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at com.redhat.rhn.taskomatic.task.sshpush.SSHPushWorkerSalt.run(SSHPushWorkerSalt.java:101)
        at EDU.oswego.cs.dl.util.concurrent.PooledExecutor$Worker.run(PooledExecutor.java:732)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.suse.salt.netapi.exception.SaltException: Response code: 500
        at com.suse.salt.netapi.client.impl.HttpAsyncClientImpl.createSaltException(HttpAsyncClientImpl.java:145)
        at com.suse.salt.netapi.client.impl.HttpAsyncClientImpl.access$000(HttpAsyncClientImpl.java:27)
        at com.suse.salt.netapi.client.impl.HttpAsyncClientImpl$1.completed(HttpAsyncClientImpl.java:121)
        at com.suse.salt.netapi.client.impl.HttpAsyncClientImpl$1.completed(HttpAsyncClientImpl.java:101)
        at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:123)
        at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:181)
        at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:442)
        at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:332)
        at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
        at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
        at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
        at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:121)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
        ... 1 more
```

And when trying to update for example a Ubuntu salt-ssh push client, it just become crazy trying to get the repos metadata:

```
Ign:83 https://uyuni:443/rhn/manager/download ubuntu-2004-amd64-multiverse-updates-uyuni/main amd64 c-n-f Metadata
Err:84 https://uyuni:443/rhn/manager/download ubuntu-2004-amd64-multiverse-security-uyuni/main i386 Packages
  404  404 [IP: 10.0.0.1 443]
Ign:85 https://uyuni:443/rhn/manager/download ubuntu-2004-amd64-multiverse-security-uyuni/main all Packages
Ign:86 https://uyuni:443/rhn/manager/download ubuntu-2004-amd64-multiverse-security-uyuni/main amd64 Packages
Ign:87 https://uyuni:443/rhn/manager/download ubuntu-2004-amd64-multiverse-security-uyuni/main Translation-en_US
Ign:88 https://uyuni:443/rhn/manager/download ubuntu-2004-amd64-multiverse-security-uyuni/main Translation-en
Ign:89 https://uyuni:443/rhn/manager/download ubuntu-2004-amd64-multiverse-security-uyuni/main all c-n-f Metadata
Ign:90 https://uyuni:443/rhn/manager/download ubuntu-2004-amd64-multiverse-security-uyuni/main amd64 c-n-f Metadata
Reading package lists... Done
E: Failed to fetch https://uyuni:443/rhn/manager/download/dists/ubuntu-2004-amd64-main-uyuni/main/binary-i386/Packages  404  404 [IP: 10.0.0.1 443]
E: Failed to fetch https://uyuni:443/rhn/manager/download/dists/ubuntu-20.04-pool-amd64-uyuni/main/binary-i386/Packages  404  404 [IP: 10.0.0.1 443]
E: Failed to fetch https://uyuni:443/rhn/manager/download/dists/ubuntu-2004-amd64-universe-uyuni/main/binary-amd64/Packages  404  404 [IP: 10.0.0.1 443]
E: Failed to fetch https://uyuni:443/rhn/manager/download/dists/ubuntu-2004-amd64-multiverse-uyuni/main/binary-i386/Packages  404  404 [IP: 10.0.0.1 443]
E: Failed to fetch https://uyuni:443/rhn/manager/download/dists/ubuntu-2004-amd64-main-updates-uyuni/main/binary-i386/Packages  404  404 [IP: 10.0.0.1 443]
E: Failed to fetch https://uyuni:443/rhn/manager/download/dists/ubuntu-2004-amd64-main-security-uyuni/main/binary-i386/Packages  404  404 [IP: 10.0.0.1 443]
E: Failed to fetch https://uyuni:443/rhn/manager/download/dists/ubuntu-2004-amd64-universe-updates-uyuni/main/binary-amd64/Packages  404  404 [IP: 10.0.0.1 443]
E: Failed to fetch https://uyuni:443/rhn/manager/download/dists/ubuntu-2004-amd64-universe-security-uyuni/main/binary-i386/Packages  404  404 [IP: 10.0.0.1 443]
E: Failed to fetch https://uyuni:443/rhn/manager/download/dists/ubuntu-2004-amd64-multiverse-updates-uyuni/main/binary-i386/Packages  404  404 [IP: 10.0.0.1 443]
E: Failed to fetch https://uyuni:443/rhn/manager/download/dists/ubuntu-2004-amd64-multiverse-security-uyuni/main/binary-i386/Packages  404  404 [IP: 10.0.0.1 443]
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Will rollback on 2021.12 ... I have still a test env with the same issues if you need me to test things.

**Comment by phibid** [comment]
@Thorfin Well, I am afraid that there is not an easy way to do so, and if there is, I am not aware about it.
In my case, I have rolled-back on the snapshot done before the update.

**Comment by Thorfin** [comment]
@phibid I feared as much, unfortunately I do not have a snapshot from before (although I do have one now... which is unhelpful)

**Comment by vzhestkov** [comment]
Are there any messages in `/var/log/salt/api` on the moment of bootstrapping. If not, could you please try to repeat with setting logging level for the master to `trace` (no need to restart salt-master service, but salt-api should be restarted after changing the logging level).

**Comment by phibid** [comment]
`ssh_push_port=int(prow.ssh_push_port or 22)` in `/usr/share/susemanager/modules/roster/uyuni.py` did the trick, I am now able to register a server without errors. Thanks Victor !

**Comment by vzhestkov** [comment]
But another important moment: this Traceback is not possible on bootstrap, only for the system which is already in registry, strange how such case could be missed on testing.
@phibid could you please check with the other fresh bootstrap (I mean which have not been registered and even tried to be registered before).

Thanks a lot for the reporting and providing the traceback :+1:

**Comment by vzhestkov** [comment]
Are you changing machine-id on or before bootstrapping?

**Comment by phibid** [comment]
Yes, I do

**Comment by kluchoslaw** [comment]
For cloned VMs I use this commands and work for me:
rm -f /etc/machine-id
rm -f /var/lib/dbus/machine-id
dbus-uuidgen --ensure
systemd-machine-id-setup

**Comment by vzhestkov** [comment]
@kluchoslaw It's ok if perform it before running bootstrap, but not if run it after starting salt-minion on the system.
