### ISSUE TITLE
Uyuni 2022.02: Badly formated Alma 8 repository prevent generation of susemanager repository

### ISSUE THREAD

**Issue by phibid** [uyuni-project/uyuni#4991]
When bootstraping an Almalinux 8 with `venv-salt-minion`, I can see this error twice in `/var/log/salt-ssh.log`:

```
configparser.DuplicateSectionError: While reading from '/etc/yum.repos.d/almalinux-resilientstorage.repo' [line 12]: section 'resilientstorage' already exists
2022-03-10 16:15:01,874 [salt.log.setup   :910 ][ERROR   ][20315] An un-handled exception was caught by salt's global exception handler:
DuplicateSectionError: While reading from '/etc/yum.repos.d/almalinux-resilientstorage.repo' [line 12]: section 'resilientstorage' already exists
Traceback (most recent call last):
  File "/var/tmp/.alma8_96d69d_salt/salt-call", line 27, in <module>
    salt_call()
  File "/var/tmp/.alma8_96d69d_salt/pyall/salt/scripts.py", line 449, in salt_call
    client.run()
  File "/var/tmp/.alma8_96d69d_salt/pyall/salt/cli/call.py", line 58, in run
    caller.run()
  File "/var/tmp/.alma8_96d69d_salt/pyall/salt/cli/caller.py", line 112, in run
    ret = self.call()
  File "/var/tmp/.alma8_96d69d_salt/pyall/salt/cli/caller.py", line 220, in call
    self.opts, data, func, args, kwargs
  File "/var/tmp/.alma8_96d69d_salt/pyall/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/var/tmp/.alma8_96d69d_salt/pyall/salt/modules/yumpkg.py", line 2722, in list_repos
    filerepos = _parse_repo_file(repopath)[1]
  File "/var/tmp/.alma8_96d69d_salt/pyall/salt/modules/yumpkg.py", line 3015, in _parse_repo_file
    parsed.read(filename)
  File "/usr/lib64/python3.6/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/lib64/python3.6/configparser.py", line 1066, in _read
    lineno)
configparser.DuplicateSectionError: While reading from '/etc/yum.repos.d/almalinux-resilientstorage.repo' [line 12]: section 'resilientstorage' already exists
```

And indeed, section `resilientstorage` label repositories appears several times in the public repo definitions, which not seems to be correct but ok:

```
root@alma8 : /etc/yum.repos.d # cat almalinux-resilientstorage.repo
# almalinux-resilientstorage.repo

[resilientstorage]
name=AlmaLinux $releasever - ResilientStorage
mirrorlist=https://mirrors.almalinux.org/mirrorlist/$releasever/resilientstorage
# baseurl=https://repo.almalinux.org/almalinux/$releasever/ResilientStorage/$basearch/os/
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux

## Sources
[resilientstorage]
name=AlmaLinux $releasever - ResilientStorage Source
mirrorlist=https://mirrors.almalinux.org/mirrorlist/$releasever/resilientstorage-source
# baseurl=https://repo.almalinux.org/almalinux/$releasever/ResilientStorage/Source/
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux

## Debuginfo
[resilientstorage]
name=AlmaLinux $releasever - ResilientStorage debuginfo
mirrorlist=https://mirrors.almalinux.org/mirrorlist/$releasever/resilientstorage-debuginfo
# baseurl=https://repo.almalinux.org/almalinux/$releasever/ResilientStorage/debug/$basearch/
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux
```

This has in fact consequences as it prevents for the susemanager repository to be generated.

**Comment by vzhestkov** [comment]
As far as I know it was fixed already on Alma side
