### ISSUE TITLE
Uyuni 2022.02: venv-salt-minion, package not refreshed on GUI on registered Ubuntu 20.04

### ISSUE THREAD

**Issue by phibid** [uyuni-project/uyuni#4996]
On a newly registered Ubuntu 20.04 server, I am unable to have the status of the available updates on the GUI, which is always green.

Forcing a package profile refresh, I can see this error on `rhn_web_ui.log` log:

```
2022-03-11 10:11:28,787 [salt-event-thread-2] ERROR com.suse.manager.webui.services.SaltServerActionService - Error processing Salt job return
java.util.NoSuchElementException: No value present
        at java.base/java.util.Optional.get(Optional.java:148)
        at com.suse.manager.utils.SaltUtils.createInstalledPackage(SaltUtils.java:1492)
        at com.suse.manager.utils.SaltUtils.lambda$createPackagesFromSalt$96(SaltUtils.java:1472)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1764)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at com.suse.manager.utils.SaltUtils.createPackagesFromSalt(SaltUtils.java:1475)
        at com.suse.manager.utils.SaltUtils.updatePackages(SaltUtils.java:1423)
        at com.suse.manager.utils.SaltUtils.lambda$handlePackageProfileUpdate$78(SaltUtils.java:1260)
        at com.redhat.rhn.common.hibernate.HibernateFactory.lambda$doWithoutAutoFlushing$0(HibernateFactory.java:753)
        at com.redhat.rhn.common.hibernate.HibernateFactory.doWithoutAutoFlushing(HibernateFactory.java:697)
        at com.redhat.rhn.common.hibernate.HibernateFactory.doWithoutAutoFlushing(HibernateFactory.java:752)
        at com.redhat.rhn.common.hibernate.HibernateFactory.doWithoutAutoFlushing(HibernateFactory.java:725)
        at com.suse.manager.utils.SaltUtils.handlePackageProfileUpdate(SaltUtils.java:1259)
        at com.suse.manager.utils.SaltUtils.lambda$updateServerAction$23(SaltUtils.java:560)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at com.suse.manager.utils.SaltUtils.updateServerAction(SaltUtils.java:559)
        at com.suse.manager.webui.services.SaltServerActionService.lambda$handleAction$168(SaltServerActionService.java:2691)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at com.suse.manager.webui.services.SaltServerActionService.lambda$handleAction$169(SaltServerActionService.java:2665)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at com.suse.manager.webui.services.SaltServerActionService.handleAction(SaltServerActionService.java:2658)
        at com.suse.manager.reactor.messaging.JobReturnEventMessageAction.lambda$execute$1(JobReturnEventMessageAction.java:121)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at com.suse.manager.reactor.messaging.JobReturnEventMessageAction.lambda$execute$2(JobReturnEventMessageAction.java:120)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at com.suse.manager.reactor.messaging.JobReturnEventMessageAction.execute(JobReturnEventMessageAction.java:119)
        at com.suse.manager.reactor.PGEventListener.lambda$notify$1(PGEventListener.java:75)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at com.suse.manager.reactor.PGEventListener.lambda$notify$2(PGEventListener.java:73)
        at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at com.suse.manager.reactor.PGEventListener.notify(PGEventListener.java:70)
        at com.suse.salt.netapi.event.AbstractEventStream.notifyListeners(AbstractEventStream.java:64)
        at com.suse.manager.reactor.PGEventStream.lambda$processEvents$7(PGEventStream.java:201)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
        at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at com.suse.manager.reactor.PGEventStream.processEvents(PGEventStream.java:195)
        at com.suse.manager.reactor.PGEventStream.lambda$notification$2(PGEventStream.java:179)
        at com.redhat.rhn.frontend.events.TransactionHelper.run(TransactionHelper.java:63)
        at com.redhat.rhn.frontend.events.TransactionHelper.handlingTransaction(TransactionHelper.java:47)
        at com.suse.manager.reactor.PGEventStream.lambda$notification$4(PGEventStream.java:178)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
2022-03-11 10:11:28,791 [salt-event-thread-2] ERROR com.suse.manager.reactor.PGEventListener - Unexpected exception while executing a MessageAction
java.util.NoSuchElementException: No value present
        at java.base/java.util.Optional.get(Optional.java:148)
        at com.suse.manager.utils.SaltUtils.createInstalledPackage(SaltUtils.java:1492)
        at com.suse.manager.utils.SaltUtils.lambda$createPackagesFromSalt$96(SaltUtils.java:1472)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1764)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at com.suse.manager.utils.SaltUtils.createPackagesFromSalt(SaltUtils.java:1475)
        at com.suse.manager.utils.SaltUtils.updatePackages(SaltUtils.java:1423)
        at com.suse.manager.utils.SaltUtils.lambda$handlePackageProfileUpdate$78(SaltUtils.java:1260)
        at com.redhat.rhn.common.hibernate.HibernateFactory.lambda$doWithoutAutoFlushing$0(HibernateFactory.java:753)
        at com.redhat.rhn.common.hibernate.HibernateFactory.doWithoutAutoFlushing(HibernateFactory.java:697)
        at com.redhat.rhn.common.hibernate.HibernateFactory.doWithoutAutoFlushing(HibernateFactory.java:752)
        at com.redhat.rhn.common.hibernate.HibernateFactory.doWithoutAutoFlushing(HibernateFactory.java:725)
        at com.suse.manager.utils.SaltUtils.handlePackageProfileUpdate(SaltUtils.java:1259)
        at com.suse.manager.utils.SaltUtils.lambda$updateServerAction$23(SaltUtils.java:560)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at com.suse.manager.utils.SaltUtils.updateServerAction(SaltUtils.java:559)
        at com.suse.manager.webui.services.SaltServerActionService.lambda$handleAction$168(SaltServerActionService.java:2691)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at com.suse.manager.webui.services.SaltServerActionService.lambda$handleAction$169(SaltServerActionService.java:2665)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at com.suse.manager.webui.services.SaltServerActionService.handleAction(SaltServerActionService.java:2658)
        at com.suse.manager.reactor.messaging.JobReturnEventMessageAction.lambda$execute$1(JobReturnEventMessageAction.java:121)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at com.suse.manager.reactor.messaging.JobReturnEventMessageAction.lambda$execute$2(JobReturnEventMessageAction.java:120)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at com.suse.manager.reactor.messaging.JobReturnEventMessageAction.execute(JobReturnEventMessageAction.java:119)
        at com.suse.manager.reactor.PGEventListener.lambda$notify$1(PGEventListener.java:75)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at com.suse.manager.reactor.PGEventListener.lambda$notify$2(PGEventListener.java:73)
        at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at com.suse.manager.reactor.PGEventListener.notify(PGEventListener.java:70)
        at com.suse.salt.netapi.event.AbstractEventStream.notifyListeners(AbstractEventStream.java:64)
        at com.suse.manager.reactor.PGEventStream.lambda$processEvents$7(PGEventStream.java:201)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
        at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at com.suse.manager.reactor.PGEventStream.processEvents(PGEventStream.java:195)
        at com.suse.manager.reactor.PGEventStream.lambda$notification$2(PGEventStream.java:179)
        at com.redhat.rhn.frontend.events.TransactionHelper.run(TransactionHelper.java:63)
        at com.redhat.rhn.frontend.events.TransactionHelper.handlingTransaction(TransactionHelper.java:47)
        at com.suse.manager.reactor.PGEventStream.lambda$notification$4(PGEventStream.java:178)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
2022-03-11 10:11:28,791 [salt-event-thread-2] ERROR com.redhat.rhn.frontend.events.TransactionHelper - com.suse.manager.reactor.PGEventListenerException
2022-03-11 10:11:28,792 [salt-event-thread-2] ERROR com.suse.manager.reactor.PGEventStream - Events [2274] were lost
```

I have tried to unregister-register it again, but no way. Apart of this issue on the GUI, the salt-minion seems to work as expected, as the susemanager repos are correctly generated and I can install updates with `apt`.

I have others Ubuntu 20.04 next to this server, and I have not noticed this issue, so not sure what exactly I am missing here.

**Comment by mcalmer** [comment]
Thanks for the report. Possible fix is on the way.
