### ISSUE TITLE
Shows Bootstrap Complete but Salt Keys Perpetually Loading; Nothing Registered

### ISSUE THREAD

**Issue by saltyollpheist** [uyuni-project/uyuni#5049]
# Problem description
Attempted bootstrap via **System** > **Bootstrapping** following documentation located [here](https://www.uyuni-project.org/uyuni-docs/en/uyuni/client-configuration/registration-webui.html). 
This results in error despite having SSL active and enabled on client and using a private key it should recognize. `rhn_web_ui.log` says `com.suse.salt.netapi.exception.SaltException:java.net.ConnectException: Connection refused` (full log details at bottom of this post).

So, I attempted registration using the `curl` method as detailed [here](https://www.uyuni-project.org/uyuni-docs/en/uyuni/client-configuration/registration-bootstrap.html#_connect_clients). Full output of this attempt is detailed below as well with obvious redactions for privacy. Upon completing this attempted method, it says `-bootstrap completely-`. I check the **Salt** > **Keys** page to see if anything needs to be accepted/activated as detailed in the documentation, but the **Salt** page just perpetually loads and never shows anything. Are there steps I'm missing personally? Are there steps missing from documentation much like the issue with [Ubuntu's Client Registration page](https://www.uyuni-project.org/uyuni-docs/en/uyuni/client-configuration/clients-ubuntu-old.html); (see [Closed Issue 5022](https://github.com/uyuni-project/uyuni/issues/5022) for reference)?

Any other info I can provide, I'll happily do so. Just need to know what `log` files to reference. 
## Version of Uyuni Server and Proxy (if used)

Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2022.01-165.2.uyuni1
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2022.01-165.2.uyuni1.src
Summary        : Uyuni Server

## Details about the issue

Output for rhn_web_ui.log directly after **System** > **Bootstrapping** attempt
---------------------------------------------
2022-03-22 04:22:07,078 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-3] ERROR com.redhat.rhn.frontend.servlets.SessionFilter - Error during transaction. Rolling back
java.lang.RuntimeException: com.suse.salt.netapi.exception.SaltException: java.net.ConnectException: Connection refused
	at com.suse.manager.webui.services.impl.SaltService.callSync(SaltService.java:401)
	at com.suse.manager.webui.services.impl.SaltService.callSync(SaltService.java:345)
	at com.suse.manager.webui.services.impl.SaltService.getKeys(SaltService.java:333)
	at com.suse.manager.webui.services.impl.SaltService.keyExists(SaltService.java:420)
	at com.suse.manager.webui.controllers.utils.AbstractMinionBootstrapper.validateBootstrap(AbstractMinionBootstrapper.java:365)
	at com.suse.manager.webui.controllers.utils.AbstractMinionBootstrapper.bootstrap(AbstractMinionBootstrapper.java:94)
	at com.suse.manager.webui.controllers.MinionsAPI.bootstrap(MinionsAPI.java:214)
	at com.suse.manager.webui.utils.SparkApplicationHelper.lambda$withRole$10(SparkApplicationHelper.java:382)
	at spark.RouteImpl$1.handle(RouteImpl.java:72)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
	at spark.servlet.SparkFilter.doFilter(SparkFilter.java:173)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.redhat.rhn.frontend.servlets.AuthFilter.doFilter(AuthFilter.java:98)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.opensymphony.module.sitemesh.filter.PageFilter.parsePage(PageFilter.java:142)
	at com.opensymphony.module.sitemesh.filter.PageFilter.doFilter(PageFilter.java:58)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.redhat.rhn.frontend.servlets.LocalizedEnvironmentFilter.doFilter(LocalizedEnvironmentFilter.java:69)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.redhat.rhn.frontend.servlets.EnvironmentFilter.doFilter(EnvironmentFilter.java:99)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.redhat.rhn.frontend.servlets.SessionFilter.doFilter(SessionFilter.java:55)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.redhat.rhn.frontend.servlets.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:97)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:432)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1591)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.suse.salt.netapi.exception.SaltException: java.net.ConnectException: Connection refused
	at com.suse.manager.webui.services.impl.SaltService.adaptException(SaltService.java:981)
	at com.suse.manager.webui.services.impl.SaltService.callSync(SaltService.java:395)
	... 49 more
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:171)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:145)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:348)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:221)
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
	... 1 more

Output of CLI after running curl -Sks https://REDACTED/pub/bootstrap/ubuntu180406lts.sh | /bin/bash
---------------------------------------------
root@REDACTED:~# curl -Sks https://REDACTED.REDACTED.REDACTED.REDACTED/pub/bootstrap/ubuntu180406lts.sh | /bin/bash
Uyuni Server Client bootstrap script v4.2

UPDATING RHN_REGISTER/UP2DATE CONFIGURATION FILES
-------------------------------------------------
* downloading necessary files
  client_config_update.py...
WARNING: cannot verify REDACTED.REDACTED.REDACTED.REDACTED's certificate, issued by ‘CN=REDACTED.REDACTED.REDACTED.REDACTED,OU=REDACTED.REDACTED,O=REDACTED,L=REDACTED,ST=REDACTED,C=US’:
  Unable to locally verify the issuer's authority.
2022-03-22 14:42:45 URL:https://REDACTED.REDACTED.REDACTED.REDACTED/pub/bootstrap/client_config_update.py [6331/6331] -> "client_config_update.py" [1]
FINISHED --2022-03-22 14:42:45--
Total wall clock time: 0.03s
Downloaded: 1 files, 6.2K in 0s (673 MB/s)
  ubuntu180406lts-overrides.txt...
WARNING: cannot verify REDACTED.REDACTED.REDACTED.REDACTED's certificate, issued by ‘CN=REDACTED.REDACTED.REDACTED.REDACTED,OU=REDACTED.REDACTED,O=REDACTED,L=REDACTED,ST=REDACTED,C=US’:
  Unable to locally verify the issuer's authority.
2022-03-22 14:42:45 URL:https://REDACTED.REDACTED.REDACTED.REDACTED/pub/bootstrap/ubuntu180406lts-overrides.txt [583/583] -> "ubuntu180406lts-overrides.txt" [1]
FINISHED --2022-03-22 14:42:45--
Total wall clock time: 0.008s
Downloaded: 1 files, 583 in 0s (76.9 MB/s)

PREPARE GPG KEYS AND CORPORATE PUBLIC CA CERT
-------------------------------------------------

* importing organizational GPG keys
WARNING: cannot verify REDACTED.REDACTED.REDACTED.REDACTED's certificate, issued by ‘CN=REDACTED.REDACTED.REDACTED.REDACTED,OU=REDACTED.REDACTED,O=REDACTED,L=REDACTED,ST=REDACTED,C=US’:
  Unable to locally verify the issuer's authority.
2022-03-22 14:42:45 URL:https://REDACTED.REDACTED.REDACTED.REDACTED/pub/ubuntu-gpg-pubkey-3B4FE6ACC0B21F32.key [1660/1660] -> "ubuntu-gpg-pubkey-3B4FE6ACC0B21F32.key" [1]
FINISHED --2022-03-22 14:42:45--
Total wall clock time: 0.008s
Downloaded: 1 files, 1.6K in 0s (219 MB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
gnupg is already the newest version (2.2.4-1ubuntu1.4).
gnupg set to manually installed.
The following packages were automatically installed and are no longer required:
  linux-headers-4.15.0-169 linux-headers-4.15.0-169-generic linux-image-4.15.0-169-generic
  linux-modules-4.15.0-169-generic linux-modules-extra-4.15.0-169-generic
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
REDACTED

* attempting to install corporate public CA cert
WARNING: cannot verify REDACTED.REDACTED.REDACTED.REDACTED's certificate, issued by ‘CN=REDACTED.REDACTED.REDACTED.REDACTED,OU=REDACTED.REDACTED,O=REDACTED,L=REDACTED,ST=REDACTED,C=US’:
  Unable to locally verify the issuer's authority.
2022-03-22 14:42:47 URL:https://REDACTED.REDACTED.REDACTED.REDACTED/pub/RHN-ORG-TRUSTED-SSL-CERT [5297/5297] -> "RHN-ORG-TRUSTED-SSL-CERT" [1]
FINISHED --2022-03-22 14:42:47--
Total wall clock time: 0.009s
Downloaded: 1 files, 5.2K in 0s (645 MB/s)
* update certificates
Updating certificates in /etc/ssl/certs...
1 added, 0 removed; done.
Running hoREDACTEDs in /etc/ca-certificates/update.d...
done.

CLEANING UP OLD SUSE MANAGER REPOSITORIES
-------------------------------------------------

CHECKING THE REGISTRATION STACK
-------------------------------------------------
* check for necessary packages being installed...
* client codebase is ubuntu-18.4
2022-03-22 14:42:47 URL:https://REDACTED.REDACTED.REDACTED.REDACTED/pub/repositories/ubuntu/18/4/bootstrap/dists/bootstrap/Release [2329/2329] -> "Release" [1]
FINISHED --2022-03-22 14:42:47--
Total wall clock time: 0.009s
Downloaded: 1 files, 2.3K in 0s (301 MB/s)
 adding client software repository at https://REDACTED.REDACTED.REDACTED.REDACTED/pub/repositories/ubuntu/18/4/bootstrap
2022-03-22 14:42:47 URL:https://REDACTED.REDACTED.REDACTED.REDACTED/pub/repositories/ubuntu/18/4/bootstrap/venv-enabled-amd64.txt [140/140] -> "venv-enabled-amd64.txt" [1]
FINISHED --2022-03-22 14:42:47--
Total wall clock time: 0.008s
Downloaded: 1 files, 140 in 0s (19.3 MB/s)
Bootstrap repo 'https://REDACTED.REDACTED.REDACTED.REDACTED/pub/repositories/ubuntu/18/4/bootstrap' contains salt bundle.
Ign:1 https://REDACTED.REDACTED.REDACTED.REDACTED/pub/repositories/ubuntu/18/4/bootstrap bootstrap InRelease
Get:2 https://REDACTED.REDACTED.REDACTED.REDACTED/pub/repositories/ubuntu/18/4/bootstrap bootstrap Release [2,329 B]
Ign:3 https://REDACTED.REDACTED.REDACTED.REDACTED/pub/repositories/ubuntu/18/4/bootstrap bootstrap Release.gpg
Get:4 https://REDACTED.REDACTED.REDACTED.REDACTED/pub/repositories/ubuntu/18/4/bootstrap bootstrap/main amd64 Packages [20.7 kB]
Hit:5 http://us.archive.ubuntu.com/ubuntu bionic InRelease
Hit:6 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:7 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:8 http://us.archive.ubuntu.com/ubuntu bionic-security InRelease
Fetched 23.0 kB in 1s (37.5 kB/s)
Reading package lists... Done
* going to install missing packages...
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  linux-headers-4.15.0-169 linux-headers-4.15.0-169-generic linux-image-4.15.0-169-generic
  linux-modules-4.15.0-169-generic linux-modules-extra-4.15.0-169-generic
Use 'apt autoremove' to remove them.
The following NEW packages will be installed:
  venv-salt-minion
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 19.0 MB of archives.
After this operation, 98.2 MB of additional disk space will be used.
Get:1 https://REDACTED.REDACTED.REDACTED.REDACTED/pub/repositories/ubuntu/18/4/bootstrap bootstrap/main amd64 venv-salt-minion amd64 3002.2-41.7.uyuni [19.0 MB]
Fetched 19.0 MB in 1s (21.9 MB/s)
Selecting previously unselected package venv-salt-minion.
(Reading database ... 138569 files and directories currently installed.)
Preparing to unpack .../venv-salt-minion_3002.2-41.7.uyuni_amd64.deb ...
Unpacking venv-salt-minion (3002.2-41.7.uyuni) ...
Setting up venv-salt-minion (3002.2-41.7.uyuni) ...
Reading package lists... Done
Building dependency tree
Reading state information... Done
venv-salt-minion is already the newest version (3002.2-41.7.uyuni).
The following packages were automatically installed and are no longer required:
  linux-headers-4.15.0-169 linux-headers-4.15.0-169-generic linux-image-4.15.0-169-generic
  linux-modules-4.15.0-169-generic linux-modules-extra-4.15.0-169-generic
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

REGISTRATION
------------
* registering
Using activation key: 1-ubuntu_18_04_06_lts_amd64
* removing TLS certificate used for bootstrap
  (will be re-added via salt state)
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hoREDACTEDs in /etc/ca-certificates/update.d...
done.
* starting salt daemon and enabling it during boot
-bootstrap complete-

**Comment by mcalmer** [comment]
This connection refused happen on the server, where tomcat try to open a connection to salt-api. 
Is salt-api process running?
Is there something in the logs /var/log/salt/api or master ?
Please also check the journal (aka /var/log/messages) if something notable happened there. Maybe an Out of Memory or something like this?

**Comment by mcalmer** [comment]
No response. Closing

**Comment by tjmullicani** [comment]
@saltyollpheist @mcalmer #5105 I just encountered this exact error, and it was due to a mis-configuration on my part. I had accidentally removed the **127.0.0.1 localhost** line from /etc/hosts, which caused the server to perform localhost lookups on the loopback IPv6 address (::1), instead of the loopback IPv4 address (127.0.0.1). It looks like the salt-api is only binding to the loopback IPv4 address, which explains the connection refused error. Adding **127.0.0.1 localhost** back to /etc/hosts fixed the issue for me.

```console
uyuni-test:~ # cat /etc/hosts | grep -v '^#'
::1             localhost ipv6-localhost ipv6-loopback
fe00::0         ipv6-localnet
ff00::0         ipv6-mcastprefix
ff02::1         ipv6-allnodes
ff02::2         ipv6-allrouters
ff02::3         ipv6-allhosts
```console

```console
uyuni-test:~ # ss -an | grep -i listen | grep tcp
tcp   LISTEN    0      1000                                      0.0.0.0:4505                        0.0.0.0:*
tcp   LISTEN    0      1000                                      0.0.0.0:4506                        0.0.0.0:*
tcp   LISTEN    0      5                                       127.0.0.1:25151                       0.0.0.0:*
tcp   LISTEN    0      128                                       0.0.0.0:22                          0.0.0.0:*
tcp   LISTEN    0      30                                      127.0.0.1:9080                        0.0.0.0:*
tcp   LISTEN    0      834                                       0.0.0.0:5432                        0.0.0.0:*
tcp   LISTEN    0      100                                         [::1]:25                             [::]:*
tcp   LISTEN    0      4096                                            *:443                               *:*
tcp   LISTEN    0      1                                           [::1]:8005                           [::]:*
tcp   LISTEN    0      100                                         [::1]:8009                           [::]:*
tcp   LISTEN    0      100                            [::ffff:127.0.0.1]:8009                              *:*
tcp   LISTEN    0      50                             [::ffff:127.0.0.1]:2828                              *:*
tcp   LISTEN    0      50                                          [::1]:2829                           [::]:*
tcp   LISTEN    0      4096                                            *:80                                *:*
tcp   LISTEN    0      100                            [::ffff:127.0.0.1]:8080                              *:*
tcp   LISTEN    0      100                                         [::1]:8050                           [::]:*
tcp   LISTEN    0      128                                          [::]:22                             [::]:*
tcp   LISTEN    0      834                                          [::]:5432                           [::]:*
```
