### ISSUE TITLE
v2022.03, python error - exited with error code 1: Unable to find code tree

### ISSUE THREAD

**Issue by StefanSa** [uyuni-project/uyuni#5194]
# Problem description
After upgrading to v2022.03 we see the following error with spacewalk-repo-sync.

```
Command '[/usr/bin/spacewalk-repo-sync, --channel, fusioninventory_agent-2.6-15.3, --type, yum, --non-interactive]' exited with error code 1: Unable to find code tree.
Path not correct? ['/usr/bin', '/usr/lib/python36.zip', '/usr/lib64/python3.6', '/usr/lib64/python3.6/lib-dynload', '/usr/lib64/python3.6/site-packages', '/usr/lib64/python3.6/site-packages/PIL', '/usr/lib64/python3.6/_import_failed', '/usr/lib/python3.6/site-packages']
```
At first look, no problems are apparent as far as python is concerned.
```
# python3 --version
Python 3.6.15
# python3 -m pip --version
pip 20.0.2 from /usr/lib/python3.6/site-packages/pip (python 3.6)

# python3 -E
Python 3.6.15 (default, Sep 23 2021, 15:41:43) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

## Version of Uyuni Server and Proxy (if used)

`zypper info Uyuni-Server-release`
```
Repository-Daten werden geladen...
Installierte Pakete werden gelesen...


Informationen zu Paket Uyuni-Server-release:
--------------------------------------------
Repository         : Uyuni Server Stable
Name               : Uyuni-Server-release
Version            : 2022.03-172.4.uyuni1
Arch               : x86_64
Anbieter           : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level      : Stufe 3
Installierte Größe : 1,4 KiB
Installiert        : Ja
Status             : aktuell
Quellpaket         : Uyuni-Server-release-2022.03-172.4.uyuni1.src
Zusammenfassung    : Uyuni Server
Beschreibung       :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

**Comment by lumarel** [comment]
As mentioned in Gitter, you might have to check which python3 modules the spacewalk-repo-sync service is unable to find:
https://github.com/uyuni-project/uyuni/blob/Uyuni-2022.03/python/spacewalk/satellite_tools/spacewalk-repo-sync

**Comment by StefanSa** [comment]
That seems to be the problem:
```
>>> from spacewalk.satellite_tools import reposync
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 38, in <module>
    from rhn.stringutils import ustr
ModuleNotFoundError: No module named 'rhn.stringutils'
```

**Comment by StefanSa** [comment]
That was the solution:
```
zypper install python3-rhnlib-4.3.3-1.1.uyuni1.noarch
Repository-Daten werden geladen...
Installierte Pakete werden gelesen...
Paketabhängigkeiten werden aufgelöst...

Das folgende Paket wird aktualisiert:
  python3-rhnlib

Das folgende Paket wird den Anbieter ändern:
  python3-rhnlib  SUSE LLC <https://www.suse.com/> -> obs://build.opensuse.org/systemsmanagement:Uyuni
```
In reference to:
https://github.com/uyuni-project/uyuni/issues/4742

**Comment by juliogonzalez** [comment]
Seem the problem is that `python3-rhnlib` is incorrectly part of Leap 15.3:
```
juliogonzalez@juliogonzalez:~/Documents/development/git/suse/spacewalk/java (Uyuni-2022.04=)$ zypper info  python3-rhnlib
El repositorio 'Update repository with updates from SUSE Linux Enterprise 15' no está actualizado. Puede ejecutar 'zypper refresh' como usuario root para actualizarlo.
Cargando datos del repositorio...
Leyendo los paquetes instalados...


Información para paquete python3-rhnlib:
----------------------------------------
Repositorio           : Update repository with updates from SUSE Linux Enterprise 15
Nombre                : python3-rhnlib
Versión               : 4.2.6-150000.3.34.1
Arquitectura          : noarch
Proveedor             : SUSE LLC <https://www.suse.com/>
Tamaño de instalación : 237,7 KiB
Instalado             : No
Estado                : no se ha instalado
Paquete de fuentes    : rhnlib-4.2.6-150000.3.34.1.src
URL ascendente        : https://github.com/uyuni-project/uyuni
Resumen               : Python libraries for the Spacewalk project
Descripción           : 
```
I already have this reported for Leap 15.4, will need to ask the openSUSE Release Engineers to have a look for 15.3 as well.

My guess is you got that package installed at some point when uyuni still had 4.2.5 for this package (probably in June 2021), and you didn't notice the issue until now, when we did changes that break the compatibility with the old python3-rhnlib 4.2.6

**Comment by juliogonzalez** [comment]
Ok, the Leap 15.3 told me they blacklisted rnhlib, and the "Update repository with updates from SUSE Linux Enterprise 15" will not get more updates for Leap 15.3 either.

But packages that are released, can't be removed from the repository.

Given that any new setup is getting 4.3.X for `python3-rhnlib`, I think this problem is not reproducible anymore, unless the user uses `zypper up --allow-vendor-change` or `zypper dup` which is not the right way to update Uyuni for minor versions.

Can we close the bug @StefanSa ?

**Comment by StefanSa** [comment]
@juliogonzalez yes
