### ISSUE TITLE
Enhance rhnpush to handle Debian packages. Was: 3 Problems with creating custom channels for Ubuntu.

### ISSUE THREAD

**Issue by ppanon2022** [uyuni-project/uyuni#5212]
# Problem description

We've been trying to set up a custom channel for some 3rd party packages that we want to deploy across the organization. the idea is to load 3rd party rpm and deb packages with rhnpush so that they can then be installed with yum /dnf and apt-get. This is failing in a number of ways, some of which we were able to patch/work around, and another not so much.

## Version of Uyuni Server and Proxy (if used)

Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2022.03-172.4.uyuni1
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : out-of-date (version 2022.02-171.1.uyuni1 installed)
Source package : Uyuni-Server-release-2022.03-172.4.uyuni1.src

## Details about the issue

The first problem is that rhnpush doesn't support uploading .deb packages, and the staging directory on the server back-end has the wrong permissions preventing the creation of the temp file.  The following minor change allowed rhnpush to process .deb files as well

```
#diff -u /usr/lib/python3.6/site-packages/rhnpush/uploadLib.py.bak /usr/lib/python3.6/site-packages/rhnpush/uploadLib.py
--- /usr/lib/python3.6/site-packages/rhnpush/uploadLib.py.bak   2022-04-13 11:02:58.598147587 -0700 
+++ /usr/lib/python3.6/site-packages/rhnpush/uploadLib.py       2022-04-13 10:07:14.590320048 -0700
@@ -177,7 +177,7 @@

         for filename in listdir(self.options.dir):
             # only add packages
-            if filename[-3:] in ("rpm", "mpm"):
+            if filename[-3:] in ("rpm", "mpm", "deb"):
                 self.files.append(filename)

     def filter_excludes(self):
```

Next, we ran into some permission issues on the back end when running rhnpush. 

Exception Handler Information
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/spacewalk/server/apacheUploadServer.py", line 102, in _wrapper ret = function(req) File "/usr/share/rhn/upload_server/handlers/package_push/package_push.py", line 117, in handler self.file_checksum_type, self.file_checksum) File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnPackageUpload.py", line 281, in save_uploaded_package prefix='-'.join((nevra[0], nevra[2], nevra[3], nevra[4]))) File "/usr/lib64/python3.6/tempfile.py", line 551, in NamedTemporaryFile (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type) File "/usr/lib64/python3.6/tempfile.py", line 262, in _mkstemp_inner fd = _os.open(file, flags, 0o600)
PermissionError: [Errno 13] Permission denied: '/var/spacewalk/packages/1/stage/Newpackaget-8.3.0-X-amd64-debmdg_d6ri'

Turns out permissions on /var/spacewalk/packages/1/stage were root.root. Running
`chown wwwrun.www  /var/spacewalk/packages/1/stage `
to match the other dirs in  /var/spacewalk/packages/1 allowed the rhnpush to succeed.

The second problem has to do with package matching. One of the (3rd-party built) packages has a mixed case package name in the metadata. As you can see, using the mixed name of the package fails to match it in the package search on Ubuntu. Only using a lower case conversion of the name works. 

root@CARMD-EX-DWSBX1:/home/t1_ppanon@sierrawireless.local# apt-cache show nessusagent
Package: NessusAgent
Version: 8.3.0
Architecture: amd64
Maintainer: Debian
Conflicts: nessusd (<< 3.0)
Replaces: nessusd (<< 3.0)
Filename: ubuntu20-it_baseline-ubuntu-2004-amd64-itsec/getPackage/NessusAgent_8.3.0-X.amd64-deb.deb
Size: 16904902
SHA256: 4534e66bd3d85e31dba1c2db0d789395e9d453edd204819d82acae2f5166820e
Section: NoGroup
Priority: extra
Description: The Nessus Client Agent
Description-md5: 1c986ede11904b59f30b8d23d2104a8e

root@CARMD-EX-DWSBX1:/home/t1_ppanon@sierrawireless.local# apt-cache show NessusAgent
N: Unable to locate package NessusAgent
E: No packages found

This is a problem in that this search failure also applies to apt install commands.  Trying to install the package from the Uyuni system software tab will try to use the mixed case metadata name, and therefore also fails. While I haven't tried to add a newer version of the package to the channel to trigger an update, I expect that doing so also would result in a failed cache match. I'm not sure if this is an upstream apt bug or in the uyuni shim libraries.

**Comment by mcalmer** [comment]
rhnpush really only handle RPM packages. I made this an enhancement to make it handle also debian packages.

**Comment by ppanon2022** [comment]
Thank you very much for your work on the pull request so far. I tried to apply the additional changes it includes to my system manually. I'm finding that rhnpush is still failing with the Palo Alto Global Protect 6.0 deb package for Ubuntu/Debian. The official error message is
ERROR: GlobalProtect_UI_deb-6.0.1.1-6.deb: This file doesn't appear to be a package

I inserted a tb print into the relevant exception handler in rhnpush_main.py and got the following traceback

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/uyuni/common/rhn_deb.py", line 46, in __init__
    self.deb = debfile.DebFile(stream.name)
  File "/usr/lib/python3.6/site-packages/debian/debfile.py", line 427, in __init__
    ArFile.__init__(self, filename, mode, fileobj)
  File "/usr/lib/python3.6/site-packages/debian/arfile.py", line 93, in __init__
    self.__index_archive()
  File "/usr/lib/python3.6/site-packages/debian/arfile.py", line 100, in __index_archive
    self.__collect_members(fp)
  File "/usr/lib/python3.6/site-packages/debian/arfile.py", line 114, in __collect_members
    errors=self.__errors)
  File "/usr/lib/python3.6/site-packages/debian/arfile.py", line 257, in from_file
    raise IOError("Incorrect header length")
OSError: Incorrect header length

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/uyuni/common/rhn_deb.py", line 130, in read_header
    self.header = deb_Header(self.header_data)
  File "/usr/lib/python3.6/site-packages/uyuni/common/rhn_deb.py", line 49, in __init__
    raise_with_tb(InvalidPackageError(e), sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/uyuni/common/usix.py", line 76, in raise_with_tb
    raise value.with_traceback(tb)
  File "/usr/lib/python3.6/site-packages/uyuni/common/rhn_deb.py", line 46, in __init__
    self.deb = debfile.DebFile(stream.name)
  File "/usr/lib/python3.6/site-packages/debian/debfile.py", line 427, in __init__
    ArFile.__init__(self, filename, mode, fileobj)
  File "/usr/lib/python3.6/site-packages/debian/arfile.py", line 93, in __init__
    self.__index_archive()
  File "/usr/lib/python3.6/site-packages/debian/arfile.py", line 100, in __index_archive
    self.__collect_members(fp)
  File "/usr/lib/python3.6/site-packages/debian/arfile.py", line 114, in __collect_members
    errors=self.__errors)
  File "/usr/lib/python3.6/site-packages/debian/arfile.py", line 257, in from_file
    raise IOError("Incorrect header length")
uyuni.common.rhn_pkg.InvalidPackageError: Incorrect header length

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/rhnpush/rhnpush_main.py", line 502, in check_package_exists
    a_pkg.read_header()
  File "/usr/lib/python3.6/site-packages/uyuni/common/rhn_deb.py", line 133, in read_header
    raise_with_tb(InvalidPackageError(e), sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/uyuni/common/usix.py", line 76, in raise_with_tb
    raise value.with_traceback(tb)
  File "/usr/lib/python3.6/site-packages/uyuni/common/rhn_deb.py", line 130, in read_header
    self.header = deb_Header(self.header_data)
  File "/usr/lib/python3.6/site-packages/uyuni/common/rhn_deb.py", line 49, in __init__
    raise_with_tb(InvalidPackageError(e), sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/uyuni/common/usix.py", line 76, in raise_with_tb
    raise value.with_traceback(tb)
  File "/usr/lib/python3.6/site-packages/uyuni/common/rhn_deb.py", line 46, in __init__
    self.deb = debfile.DebFile(stream.name)
  File "/usr/lib/python3.6/site-packages/debian/debfile.py", line 427, in __init__
    ArFile.__init__(self, filename, mode, fileobj)
  File "/usr/lib/python3.6/site-packages/debian/arfile.py", line 93, in __init__
    self.__index_archive()
  File "/usr/lib/python3.6/site-packages/debian/arfile.py", line 100, in __index_archive
    self.__collect_members(fp)
  File "/usr/lib/python3.6/site-packages/debian/arfile.py", line 114, in __collect_members
    errors=self.__errors)
  File "/usr/lib/python3.6/site-packages/debian/arfile.py", line 257, in from_file
    raise IOError("Incorrect header length")
uyuni.common.rhn_pkg.InvalidPackageError: Incorrect header length

Looking at the package contents with the ar command gives
# ar t GlobalProtect_UI_deb-6.0.1.1-6.deb
debian-binary
control.tar.gz
data.tar.xz

so the executable ar doesn't seem to have a problem with that file. Is it a bug in the arfile.py module?

**Comment by ycedres** [comment]
Thank you for your feedback.
Could you please run `hexdump -C -n 100` on that deb file and paste the output here?

**Comment by ycedres** [comment]
Sorry for the late response. Sadly I cannot have that precise package to debug myself. From the output of `hexdump` that you pasted I don't understand why the header length for your `.deb` file is greater than 60, that is the check that the `debian` package is doing [here](https://salsa.debian.org/python-debian-team/python-debian/-/blob/master/lib/debian/arfile.py#L256). In fact it's [reading 60 bytes](https://salsa.debian.org/python-debian-team/python-debian/-/blob/master/lib/debian/arfile.py#L250) from the file 

I don't know if would be possible for you to somehow print that `buf` variable to try to sort out the problem.

**Comment by ppanon2022** [comment]
I did make it print the len(buf) and buf contents right after the read

~/PanGP> rhnpush -vvv -cubuntu-2004-amd64-itsec GlobalProtect_UI_deb-6.0.1.1-6.deb
Connecting to https://<servername>/APP
SUSE Manager username: <AdminAccount>
SUSE Manager password:
url is https://<servername>/PACKAGE-PUSH
Result codes: 200 OK
Computing checksum and package info. This may take some time ...
The length of buf is 60 bytes
Buffer: b'debian-binary   1651871518  0     0     100644  4         `\n'

The length of buf is 60 bytes
Buffer: b'control.tar.gz  1651871518  0     0     100644  3289      `\n'

The length of buf is 60 bytes
Buffer: b'data.tar.xz     1651871536  0     0     100644  8751056   `\n'

The length of buf is 1 bytes
Buffer: b'\n'

ERROR: GlobalProtect_UI_deb-6.0.1.1-6.deb: This file doesn't appear to be a package


So it looks as if it reads the first 3 entries fine, but then tries to read and extra entry which is empty and that is what makes it fail.

**Comment by ppanon2022** [comment]
Adding
         if buf == b'\n':
            return False
seems to allow it to work.

**Comment by ycedres** [comment]
That extra byte in the `.deb` file is obviously causing trouble. There should be just three iterations for the three components inside the `ar` file. This would need further research and maybe is out of scope of this issue as it seems to be a `python-debian` library problem (I assume this deb package can be installed using apt).

On the other hand, the issue you mentioned regarding mixed case in the metadata package is related to with not following the mandatory [syntax](https://www.debian.org/doc/debian-policy/ch-controlfields.html#package).

**Comment by ppanon2022** [comment]
Yes, there's no issue in installing this deb package using dpkg. There only issue right now is in getting the PGP public key to verify the package. Doesn't look like they have lots of people trying to do that. They usually have people run sha256 to check it and install the package with dpkg
