### ISSUE TITLE
cannot bootstrap new clients

### ISSUE THREAD

**Issue by ZsBT** [uyuni-project/uyuni#5230]
# Problem description

When bootstrapping, notification messages say:

Onboarding failed | Error registering minion id: XXXXXXXX

The issue is the same with brand-new systems, as well as previously deleted systems.

## Version of Uyuni Server and Proxy (if used)

Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2022.03-172.4.uyuni1
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date

### rhn_web_ui.log

```
2022-04-19 22:02:26,809 [salt-event-thread-1] ERROR com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction - Error registering minion id: *MINION*
org.hibernate.NonUniqueObjectException: A different object with the same identifier value was already associated with the session : [com.redhat.rhn.domain.server.ServerPath#com.redhat.rhn.domain.server.ServerPathId@6d9e7d3f[server=com.redhat.rhn.domain.server.MinionServer@b583bb0[id=1000010554,org=com.redhat.rhn.domain.org.Org@50355afe[id=1,name=*ORG*],name=*MINION*,description=<null>,machineId=efcdc5c84be060e9cabb30b2625e962f,minionId=*MINION*],proxyServer=com.redhat.rhn.domain.server.MinionServer@2eadc1ae[id=1000010022,org=com.redhat.rhn.domain.org.Org@50355afe[id=1,name=*ORG*],name=*MASTER*,description=<null>,machineId=fcfdcff8cc1e3340706864475ec6988b,minionId=*MASTER*]]]
        at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:183)
        at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:139)
        at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.saveWithGeneratedOrRequestedId(DefaultSaveOrUpdateEventListener.java:192)
        at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.entityIsTransient(DefaultSaveOrUpdateEventListener.java:177)
        at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.performSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:97)
        at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:73)
        at org.hibernate.internal.SessionImpl.fireSaveOrUpdate(SessionImpl.java:679)
        at org.hibernate.internal.SessionImpl.saveOrUpdate(SessionImpl.java:671)
        at org.hibernate.engine.spi.CascadingActions$5.cascade(CascadingActions.java:219)
        at org.hibernate.engine.internal.Cascade.cascadeToOne(Cascade.java:490)
        at org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:415)
        at org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:216)
        at org.hibernate.engine.internal.Cascade.cascadeCollectionElements(Cascade.java:523)
        at org.hibernate.engine.internal.Cascade.cascadeCollection(Cascade.java:455)
        at org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:418)
        at org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:216)
        at org.hibernate.engine.internal.Cascade.cascade(Cascade.java:149)
        at org.hibernate.event.internal.AbstractSaveEventListener.cascadeAfterSave(AbstractSaveEventListener.java:459)
        at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:295)
        at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:196)
        at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:139)
        at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.saveWithGeneratedOrRequestedId(DefaultSaveOrUpdateEventListener.java:192)
        at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.entityIsTransient(DefaultSaveOrUpdateEventListener.java:177)
        at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.performSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:97)
        at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:73)
        at org.hibernate.internal.SessionImpl.fireSaveOrUpdate(SessionImpl.java:679)
        at org.hibernate.internal.SessionImpl.saveOrUpdate(SessionImpl.java:671)
        at org.hibernate.internal.SessionImpl.saveOrUpdate(SessionImpl.java:666)
        at com.redhat.rhn.common.hibernate.HibernateFactory.saveObject(HibernateFactory.java:292)
        at com.redhat.rhn.common.hibernate.HibernateFactory.saveObject(HibernateFactory.java:304)
        at com.redhat.rhn.domain.server.ServerFactory.save(ServerFactory.java:670)
        at com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction.finalizeMinionRegistration(RegisterMinionEventMessageAction.java:502)
(...)
2022-04-19 22:02:26,809 [salt-event-thread-1] ERROR com.suse.manager.reactor.PGEventListener - Unexpected exception while executing a MessageAction
com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction$RegisterMinionException
        at com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction.finalizeMinionRegistration(RegisterMinionEventMessageAction.java:523)
        at com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction.lambda$registerMinion$7(RegisterMinionEventMessageAction.java:232)
        at com.suse.utils.Opt.consume(Opt.java:89)
        at com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction.lambda$registerMinion$9(RegisterMinionEventMessageAction.java:229)
        at com.suse.utils.Opt.consume(Opt.java:89)
        at com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction.lambda$registerMinion$18(RegisterMinionEventMessageAction.java:228)
        at com.suse.utils.Opt.consume(Opt.java:89)
        at com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction.registerMinion(RegisterMinionEventMessageAction.java:226)
        at com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction.lambda$registerMinion$5(RegisterMinionEventMessageAction.java:188)
        at com.suse.utils.Opt.consume(Opt.java:92)
        at com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction.lambda$registerMinion$6(RegisterMinionEventMessageAction.java:186)
        at com.suse.utils.Opt.consume(Opt.java:92)
        at com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction.registerMinion(RegisterMinionEventMessageAction.java:174)
        at com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction.execute(RegisterMinionEventMessageAction.java:143)
        at com.suse.manager.reactor.PGEventListener.lambda$notify$1(PGEventListener.java:75)
```

(real hostnames are replaced)

I've checked the database, there is no such minion record in table rhnserver that has the same id/digital_server_id/machine_id

**Comment by wombelix** [comment]
Even though you checked in the DB that no other Systems has the machine_id `efcdc5c84be060e9cabb30b2625e962f`, what happens when you re-create it on the client an try it again?

https://www.uyuni-project.org/uyuni-docs/en/uyuni/administration/tshoot-registerclones.html

**Comment by ZsBT** [comment]
The same happens with a new machine_id (double-checked with the grains item, as clients successfully register to salt). Also, when tried a "brand-new" (not cloned) minion. We have already ~300 minions successfully bootstrapped to the earlier Uyuni version.
Meantime I've tried to find the root cause by logging the PG statements but could not find a related store transaction:

https://share.andrews.hu/index.php/s/ERsSF5sGPmR4Apw

What I guess is something with the hibernate session handling, maybe a .clear(), merge() before .save() or .update().

**Comment by jhooge73** [comment]
Could you check if you have a salt minion running on your Uyuni server which has registered to your uyuni server. I've had the same issue on suse-manager. After deleting the suse manager server from its own systems list I could register clients again.

**Comment by wombelix** [comment]
> Could you check if you have a salt minion running on your Uyuni server which has registered to your uyuni server. I've had the same issue on suse-manager. After deleting the suse manager server from its own systems list I could register clients again.

Thanks for sharing! To be honest I never thought about registering Uyuni / SUMA to itself, but good to see what impact that would have.

> Now I have a lifecycle manager system that is unable to manage the lifecycle of the lifecycle managers. At least most of the minions start working. I leave this ticket open as I bet people would like to keep the OS of Uyuni server up to date.

What's wrong with just upgrading Uyuni from the command line every month when a new Version was released?

**Comment by ZsBT** [comment]
Closing the ticket as Uyuni should not be registered in Uyuni,  no further action is expected.
