### ISSUE TITLE
Uyuni 2022.03 fresh install failing with "There was a problem storing the SSL certificate.  Exit value: 11."

### ISSUE THREAD

**Issue by gabjef** [uyuni-project/uyuni#5237]
# Problem description

Installation of Uyuni 2022.03-172.4 is failing via both YAST and `/usr/lib/susemanager/bin/mgr-setup -s`

## Version of Uyuni Server and Proxy (if used)

Information for package Uyuni-Server-release:
```
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2022.03-172.4.uyuni1
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2022.03-172.4.uyuni1.src
Summary        : Uyuni Server
```

**Not using Uyuni proxy**

Contents of `/etc/os-release` :
```
NAME="openSUSE Leap"
VERSION="15.3"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.3"
PRETTY_NAME="openSUSE Leap 15.3"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.3"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
```

Output from `hostnamectl`:
```
   Static hostname: uyuni-lab-linux-mgmt.lab.tierpoint.com
Transient hostname: uyuni-lab-linux-mgmt
         Icon name: computer-vm
           Chassis: vm
        Machine ID: a95ebc4ab5cb4319bd01a99142fa3638
           Boot ID: ad482efcfd4d458e9cae1ca3aeb06384
    Virtualization: vmware
  Operating System: openSUSE Leap 15.3
       CPE OS Name: cpe:/o:opensuse:leap:15.3
            Kernel: Linux 5.3.18-150300.59.63-default
      Architecture: x86-64
```

## Details about the issue

Output from `/usr/lib/susemanager/bin/mgr-setup -s` (email/passwords replaced with x's):
```
Asserting correct java version...
/var/spacewalk already exists. Leaving it untouched.
Filesystem type for /var/cache is xfs - ok.
Open needed firewall ports...
running
Warning: ALREADY_ENABLED: suse-manager-server
success
success
Performing forced re-installation!
Shutting down spacewalk services...
Done.
Delete existing database...
Delete existing salt minion keys
CREATE ROLE
####   #####
admin-email = xxxxx.xxxxxxxx@tierpoint.com
ssl-set-org = Tierpoint
ssl-set-org-unit = OSA
ssl-set-city = St Louis
ssl-set-state = MO
ssl-set-country = US
ssl-set-cnames =
ssl-password = xxxxxxx
ssl-set-email = xxxxxxx@tierpoint.com
ssl-config-sslvhost = Y
ssl-ca-cert-expiration = 10
ssl-server-cert-expiration = 10
db-backend=postgresql
db-user=uyuni
db-password=xxxxxxx
db-name=uyuni
db-host=localhost
db-port=5432
db-protocol=TCP
report-db-backend=postgresql
report-db-name=reportdb
report-db-host=
report-db-port=
report-db-user=pythia_susemanager
report-db-password=
report-db-ca-cert=/etc/pki/trust/anchors/RHN-ORG-TRUSTED-SSL-CERT
enable-tftp=y

ssl-use-existing-certs = N
* Loading answer file: /root/spacewalk-answers.
** Database: Setting up database connection for PostgreSQL backend.
** Database: Populating database.
** Database: --clear-db option used.  Clearing database.
** Database: Shutting down spacewalk services that may be using DB.
** Database: Services stopped.  Clearing DB.
*** Progress: ###############################
* Configuring tomcat.
* Setting up users and groups.
* Performing initial configuration.
* Configuring apache SSL virtual host.
* Configuring jabberd.
* Creating SSL certificates.
** SSL: Generating CA certificate.
** SSL: Generating server certificate.
There was a problem storing the SSL certificate.  Exit value: 11.
Please examine /var/log/rhn/rhn_installation.log for more information.
ERROR: spacewalk-setup failed
```

From /var/log/rhn/rhn_installation.log (email/passwords replaced with #'s):
```
Installation log of Spacewalk
Command: /usr/bin/spacewalk-setup

db_port
db_password
hibernate.connection.driver_proto
db_name
db_backend
hibernate.connection.driver_class
db_host
hibernate.dialect
db_user
Shutting down spacewalk services...
Done.
** /etc/sysconfig//tomcat has been backed up to tomcat-swsave
** /etc/tomcat//tomcat.conf has been backed up to tomcat.conf-swsave
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored
Enabling spacewalk services...
Done
/var/lib/rhn/rhn-satellite-prep/etc/rhn/rhn.conf
/var/lib/rhn/rhn-satellite-prep/etc/rhn/rhn.conf.orig
/var/lib/rhn/rhn-satellite-prep/etc -> /etc
/var/lib/rhn/rhn-satellite-prep/etc/rhn -> /etc/rhn
/var/lib/rhn/rhn-satellite-prep/etc/rhn/rhn.conf -> /etc/rhn/rhn.conf
 * Making backup of /etc/rhn/rhn.conf to /etc/sysconfig/rhn/backup-2022-04-20-19:53/etc/rhn/rhn.conf
Generating private CA key: /root/ssl-build/RHN-ORG-PRIVATE-SSL-KEY
Rotated: RHN-ORG-PRIVATE-SSL-KEY --> RHN-ORG-PRIVATE-SSL-KEY.1
Rotated: rhn-ca-openssl.cnf --> rhn-ca-openssl.cnf.1

Generating public CA certificate: /root/ssl-build/RHN-ORG-TRUSTED-SSL-CERT
Using distinguishing variables:
    --set-country      = "US"
    --set-state        = "MO"
    --set-city         = "St Louis"
    --set-org          = "Tierpoint"
    --set-org-unit     = "OSA"
    --set-common-name  = "uyuni-lab-linux-mgmt.lab.tierpoint.com"
    --set-email        = ""
Rotated: RHN-ORG-TRUSTED-SSL-CERT --> RHN-ORG-TRUSTED-SSL-CERT.1
CA Cert for OS Images: Packaging /root/ssl-build/RHN-ORG-TRUSTED-SSL-CERT into /usr/share/susemanager/salt/images/rhn-org-trusted-ssl-cert-osimage-1.0-1.noarch.rpm
CA Cert for OS Images: Packaging /root/ssl-build/RHN-ORG-TRUSTED-SSL-CERT into /usr/share/susemanager/salt/images/rhn-org-trusted-ssl-cert-osimage-sle11-1.0-1.noarch.rpm

Generating the web server's SSL private key: /root/ssl-build/uyuni-lab-linux-mgmt.lab/server.key
Rotated: server.key --> server.key.1

Generating web server's SSL certificate request: /root/ssl-build/uyuni-lab-linux-mgmt.lab/server.csr
Using distinguished names:
    --set-country      = "US"
    --set-state        = "MO"
    --set-city         = "St Louis"
    --set-org          = "Tierpoint"
    --set-org-unit     = "OSA"
    --set-hostname     = "uyuni-lab-linux-mgmt.lab.tierpoint.com"
    --set-email        = "#######@tierpoint.com"
Rotated: server.csr --> server.csr.1
Rotated: rhn-ca-openssl.cnf --> rhn-ca-openssl.cnf.1

Generating/signing web server's SSL certificate: server.crt
Rotated: server.crt --> server.crt.1
ERROR: there was a problem trying to initialize the database:

Exception reported from uyuni-lab-linux-mgmt
Time: Wed Apr 20 19:53:34 2022
Exception type <class 'spacewalk.common.rhnException.rhnException'>

Exception Handler Information
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/rhn_ssl_dbstore.py", line 55, in processCommandline
    rhnSQL.initDB()
  File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/__init__.py", line 102, in initDB
    raise rhnException("Unsupported database backend", backend)
spacewalk.common.rhnException.rhnException: ('Unsupported database backend', None)
```

Contents of `setup_env.sh` (emails/passwords replaced with #'s):
```
export MANAGER_FORCE_INSTALL='1'
export ACTIVATE_SLP='n'
export MANAGER_ADMIN_EMAIL='####.#####@tierpoint.com'
export MANAGER_ENABLE_TFTP='y'
export MANAGER_IP='172.18.62.60'
export MANAGER_DB_PORT='5432'
export DB_BACKEND='postgresql'
export MANAGER_DB_HOST='localhost'
export MANAGER_DB_NAME='uyuni'
export MANAGER_DB_PROTOCOL='TCP'
export MANAGER_PASS='########'
export MANAGER_PASS2='#######'
export MANAGER_USER='uyuni'
export LOCAL_DB='1'
export CERT_CITY='St Louis'
export CERT_COUNTRY='US'
export CERT_EMAIL='#######@tierpoint.com'
export CERT_O='Tierpoint'
export CERT_OU='OSA'
export CERT_PASS='#######'
export CERT_PASS2='#######'
export CERT_STATE='MO'
```

Generated SSL cert dumped via `openssl x509 -in RHN-ORG-TRUSTED-SSL-CERT -noout -text`:
```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            27:38:dd:0d:21:c6:2e:f5:d0:c9:09:0e:a2:20:b5:18:3f:10:68:7a
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = US, ST = MO, L = St Louis, O = Tierpoint, OU = OSA, CN = uyuni-lab-linux-mgmt.lab.tierpoint.com
        Validity
            Not Before: Apr 21 00:09:56 2022 GMT
            Not After : Apr 18 00:09:56 2032 GMT
        Subject: C = US, ST = MO, L = St Louis, O = Tierpoint, OU = OSA, CN = uyuni-lab-linux-mgmt.lab.tierpoint.com
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    00:ae:f5:a5:80:c0:47:3f:50:2f:63:b4:ce:d7:7d:
                    da:37:6e:bc:34:44:d5:c9:2d:4e:fb:81:75:53:00:
                    f9:b4:b3:23:4e:5f:30:fb:f6:c6:0b:ec:0e:2f:b6:
                    68:f0:8e:ea:1f:74:17:1e:68:df:07:63:17:7f:15:
                    8f:06:da:a3:b9:ed:e9:8f:43:1b:1e:03:5a:02:50:
                    19:c8:97:15:9b:58:51:f7:76:63:16:3d:fc:5f:ee:
                    fa:c7:16:b0:e9:e4:06:2d:ed:15:b8:b5:10:28:e4:
                    a9:fb:2b:50:8d:cb:56:ab:62:08:1d:ab:8b:f6:04:
                    d4:23:8b:2b:22:0e:25:c7:da:b7:b2:f0:94:52:c1:
                    66:09:77:84:18:1e:e8:ab:19:be:e1:f2:6b:01:a6:
                    78:8c:96:57:50:10:5f:b2:01:2e:65:9d:0d:04:e5:
                    f5:cf:ed:35:bc:d5:1e:25:ef:94:3a:ab:d8:02:10:
                    e1:9a:c3:20:72:ac:fc:8f:80:e2:50:30:7b:80:d9:
                    d7:67:47:99:99:4d:24:6a:49:28:24:b6:1c:fe:c4:
                    0a:f2:9f:8d:4a:be:c1:09:5c:b4:0b:78:ca:8d:ea:
                    9b:37:4d:ac:99:a2:e1:ab:70:26:1f:b7:a1:c8:60:
                    bf:42:3a:fe:0c:75:39:09:22:83:d9:86:17:5f:44:
                    e0:c7
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Basic Constraints:
                CA:TRUE
            X509v3 Key Usage:
                Digital Signature, Key Encipherment, Certificate Sign
            X509v3 Extended Key Usage:
                TLS Web Server Authentication, TLS Web Client Authentication
            Netscape Comment:
                RHN SSL Tool Generated Certificate
            X509v3 Subject Key Identifier:
                F9:79:91:B2:82:53:9E:64:20:9D:38:B0:54:6C:E3:61:1F:75:F9:F5
            X509v3 Authority Key Identifier:
                keyid:F9:79:91:B2:82:53:9E:64:20:9D:38:B0:54:6C:E3:61:1F:75:F9:F5
                DirName:/C=US/ST=MO/L=St Louis/O=Tierpoint/OU=OSA/CN=uyuni-lab-linux-mgmt.lab.tierpoint.com
                serial:27:38:DD:0D:21:C6:2E:F5:D0:C9:09:0E:A2:20:B5:18:3F:10:68:7A

    Signature Algorithm: sha256WithRSAEncryption
         21:5e:3f:d2:df:c4:20:c8:70:9f:1a:f7:79:b8:8b:4e:ec:65:
         9a:34:93:e1:bb:c1:20:66:db:51:a3:fa:f4:10:37:63:32:01:
         5f:80:d5:8a:c0:93:da:b0:bb:cb:25:c3:6b:53:4c:49:9f:ee:
         18:81:d7:e3:27:d3:3d:cd:f8:82:9c:81:89:f3:3d:64:c8:1d:
         a8:89:17:8c:66:11:72:12:93:3d:5e:38:ce:f0:13:0b:d3:29:
         83:de:b2:1b:d3:e2:ff:51:a5:88:74:f7:d7:1e:41:26:d5:d1:
         f5:d8:a6:69:b3:ab:9f:26:48:f9:10:05:16:35:bd:5a:31:32:
         10:38:ef:90:dc:71:89:d7:e8:43:89:f3:14:9f:68:8e:09:2d:
         9f:14:a8:1e:fc:e7:fc:78:24:0c:c4:f3:3b:15:89:24:2e:4c:
         40:ad:95:a0:85:fd:68:30:94:47:97:87:ac:c6:98:53:5e:78:
         88:c7:c4:df:e2:5b:f8:d5:b9:ce:e4:8b:86:94:b5:7e:82:64:
         b7:f7:fb:b5:f8:68:b1:d7:52:73:fc:6f:7b:96:ad:fa:45:1d:
         c6:78:d5:ed:92:bf:78:f7:3f:03:64:27:9a:99:31:a7:f7:82:
         39:94:76:e9:0b:16:27:d6:eb:c6:1f:96:82:f5:37:a7:39:99:
         91:89:37:21
```
I can provide further detail as required.
Thanks!

**Comment by gabjef** [comment]
After some further digging it appears that the `db_*` configuration values in `/etc/rhn/rhn.conf` are not being set:

```
traceback_mail = jeff.gabel@tierpoint.com
mount_point = /var/spacewalk
kickstart_mount_point = /var/spacewalk
repomd_cache_mount_point = /var/cache

# Use proxy FQDN, or FQDN:port
server.satellite.http_proxy =
server.satellite.http_proxy_username =
server.satellite.http_proxy_password =
# no_proxy is a comma seperated list
# Either an exact match, or the previous character
# is a '.', so host is within the same domain.
# A leading '.' in the pattern is ignored.
server.satellite.no_proxy =

# Completely disable ISS.
# If set to 1, then no slave will be able to sync from this server
# this option does not affect ability to sync to this server from
# another spacewalk (or hosted).
disable_iss=0

db_backend =
db_user =
db_password =
db_name =
db_host =
db_port =
db_ssl_enabled =

report_db_backend = postgresql
report_db_user = pythia_susemanager
report_db_password = #######################
report_db_name = reportdb
report_db_host = uyuni-lab-linux-mgmt.lab.tierpoint.com
report_db_port = 5432
report_db_ssl_enabled = 1
report_db_sslrootcert = /etc/pki/trust/anchors/RHN-ORG-TRUSTED-SSL-CERT


server.nls_lang = english.UTF8

hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.connection.driver_class=org.postgresql.Driver
hibernate.connection.driver_proto=jdbc:postgresql


web.satellite = 1
web.satellite_install =

web.session_swap_secret_1 = 39568a0fdeae1a71034563d5719eb9aabb944d3d41976d7d1d44a8972545b5df
web.session_swap_secret_2 = 0bc960c7f23effc34791eae23c2afd3ee391982e890ba2eb1d638c82c4b0e64d
web.session_swap_secret_3 = d58d054a2dd44ca16b15b4f878a7d84ea4da72f4626d73e632bce9fd527600cf
web.session_swap_secret_4 = bfa749c016dd3a70e37f750ea3c55c25ce6a19e864b09385c06e6b25e7acc4cb

session_secret_1 = b023817ea423baa954517389cee0a4f867f85e13ff034ba1d8f4567ca4f3a5b9
session_secret_2 = 56c092d0981cf63e36966433c9f4f0921e6f2cad9b5cd31e9ecfea85315fe4d5
session_secret_3 = 42e669b9bedd7c98b5d3e1ee414ca5dcc8351351faa62e959c99b4c11ff372ea
session_secret_4 = 52ce579d5caf1f5e22f41a1bf18c6d85a0e39d75a147be35029b419392721a49

server.secret_key = 69f6cd6a8d92cc01426143c25fb36af1e68676c92cb9c11f299a92a326cdb1b8

encrypted_passwords = 1

web.restrict_mail_domains =

# OSA configuration #

server.jabber_server = uyuni-lab-linux-mgmt.lab.tierpoint.com
osa-dispatcher.jabber_server = uyuni-lab-linux-mgmt.lab.tierpoint.com

# set up SSL on the dispatcher
osa-dispatcher.osa_ssl_cert = /srv/www/htdocs/pub/RHN-ORG-TRUSTED-SSL-CERT

# system snapshots enabled
enable_snapshots = 1

#cobbler host name
cobbler.host = uyuni-lab-linux-mgmt.lab.tierpoint.com

# Maximum Java Heap Size (in MB)
# taskomatic.java.maxmemory=4096

web.default_mail_from = Uyuni (uyuni-lab-linux-mgmt.lab.tierpoint.com) <root@lab.tierpoint.com>
```
Everything else looks okay as far as I can tell.

**Comment by gabjef** [comment]
Closing this issue as it really ended up not being a fresh install after several failed run attempts.
Will open a new issue for a new failed deploy on green field...
