### ISSUE TITLE
Stracktraces at reposync for repositories that do not exist

### ISSUE THREAD

**Issue by juliogonzalez** [uyuni-project/uyuni#5631]
# Problem description

_The following information is very important in order to help us to understand your problem. Omission of the following details can cause delays or can receive no attention at all._

## Version of Uyuni Server and Proxy (if used)

Master (as of 2022 July 5th)

## Details about the issue

While testing Oracle 9, I added the Stable EL9 client tools, that do not exist yet (https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/EL9-Uyuni-Client-Tools/EL_9/ returns a 404).

However, besides an error about the repository being invalid, there are also a couple of stracktraces, that IMHO should not be there:
```
12:12:17 ======================================
12:12:17 | Channel: oraclelinux9-uyuni-client-x86_64
12:12:17 ======================================
12:12:17 Sync of channel started.
Recuperando los metadatos del repositorio 'oraclelinux9-uyuni-client-x86_64' ...........................................................................................................................................................................................[error]
12:12:19 RepoMDError: Cannot access repository.
El repositorio 'oraclelinux9-uyuni-client-x86_64' no es válido.
[oraclelinux9-uyuni-client-x86_64|https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/EL9-Uyuni-Client-Tools/EL_9/] No se han encontrado metadatos válidos en la URL especificada
Historial:
 - [oraclelinux9-uyuni-client-x86_64|https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/EL9-Uyuni-Client-Tools/EL_9/] Repository type can't be determined.

Compruebe si los URI definidos para este repositorio apuntan a un repositorio válido.
Se va a omitir el repositorio 'oraclelinux9-uyuni-client-x86_64' debido al error anterior.
No es posible actualizar los repositorios debido a errores.

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 610, in sync
    repo_checksum_type = plugin.get_md_checksum_type()
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_src.py", line 748, in get_md_checksum_type
    if self._md_exists('repomd'):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_src.py", line 697, in _md_exists
    self.setup_repo(self.repo)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_src.py", line 644, in setup_repo
    raise RepoMDError("Cannot access repository.\n{}".format(sstr(process.stderr)))
spacewalk.satellite_tools.repo_plugins.yum_src.RepoMDError: Cannot access repository.
El repositorio 'oraclelinux9-uyuni-client-x86_64' no es válido.
[oraclelinux9-uyuni-client-x86_64|https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/EL9-Uyuni-Client-Tools/EL_9/] No se han encontrado metadatos válidos en la URL especificada
Historial:
 - [oraclelinux9-uyuni-client-x86_64|https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/EL9-Uyuni-Client-Tools/EL_9/] Repository type can't be determined.

Compruebe si los URI definidos para este repositorio apuntan a un repositorio válido.
Se va a omitir el repositorio 'oraclelinux9-uyuni-client-x86_64' debido al error anterior.
No es posible actualizar los repositorios debido a errores.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/spacewalk-repo-sync", line 286, in <module>
    sys.exit(abs(main() or 0))
  File "/usr/bin/spacewalk-repo-sync", line 269, in main
    elapsed_time, channel_ret_code = sync.sync()
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 654, in sync
    self.sendErrorMail("RepoMDError: %s" % e)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 2367, in sendErrorMail
    rhnMail.send(headers, extra + body)
  File "/usr/lib/python3.6/site-packages/spacewalk/common/rhnMail.py", line 80, in send
    smtp.sendmail(sender, headers_recipients.to_addresses, msg)
  File "/usr/lib64/python3.6/smtplib.py", line 860, in sendmail
    msg = _fix_eols(msg).encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\xe1' in position 348: ordinal not in range(128)

**Comment by juliogonzalez** [comment]
Oddly enough, rerunning does not show the stacktraces again:

```
12:47:12 ======================================
12:47:12 | Channel: oraclelinux9-uyuni-client-x86_64
12:47:12 ======================================
12:47:12 Sync of channel started.
Retrieving repository 'oraclelinux9-uyuni-client-x86_64' metadata ......................................................................................................................................................................................................[error]
12:47:13 RepoMDError: Cannot access repository.
Repository 'oraclelinux9-uyuni-client-x86_64' is invalid.
[oraclelinux9-uyuni-client-x86_64|https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/EL9-Uyuni-Client-Tools/EL_9/] Valid metadata not found at specified URL                                                                                         
History:                                                                                                                                                                                                                                                                       
 - [oraclelinux9-uyuni-client-x86_64|https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/EL9-Uyuni-Client-Tools/EL_9/] Repository type can't be determined.                                                                                           

Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'oraclelinux9-uyuni-client-x86_64' because of the above error.
Could not refresh the repositories because of errors.

**Comment by Ripper66Six** [comment]
Dear Ladys and Gentlemen,

we have the same problem on a MongoDB6 repository for Ubuntu 20.04


2023-06-27 07:57:54,256 urlgrabber version  = 4.1.0
2023-06-27 07:57:54,256 trans function "_"  = <function _ at 0x7f52525e06a8>
07:57:54 ======================================
07:57:54 | Channel: mongodb6-ubuntu-20.04-x86_64
07:57:54 ======================================
07:57:54 Sync of channel started.
07:57:56 Unhandled error occurred: 'Packages'
07:57:56 Unexpected error: <class 'KeyError'>
07:57:56 Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 610, in sync
    http_headers=source_url["http_headers"])
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/deb_src.py", line 339, in __init__
    self.repo.verify()
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/deb_src.py", line 183, in verify
    if not repo.DpkgRepo(self.url, self._get_proxies(), self.gpg_verify).verify_packages_index():
  File "/usr/lib/python3.6/site-packages/spacewalk/common/repo.py", line 435, in verify_packages_index
    entry = self.get_release_index().get(name)
  File "/usr/lib/python3.6/site-packages/spacewalk/common/repo.py", line 77, in get
    return self[key]
KeyError: 'Packages'

**Comment by juliogonzalez** [comment]
@Ripper66Six this is a different stracktrace, so it should better be tracked on a separate issue, as it looks like a different issue, even if it happens with reposync and handling packages. Can you create one?

**Comment by Ripper66Six** [comment]
Hello @juliogonzalez,

I have deleted the entry and will provide this in a separate issue.

Kind regards

**Comment by admd** [comment]
As part of our effort to keep the Uyuni backlog manageable and focused on current priorities, we are closing older issues that have not seen recent activity. Due to significant changes in the codebase over time, many of these older reports may no longer be applicable or reproducible in the current version.

If this is still relevant and you are able to reproduce it on a recent version of Uyuni, please feel free to reopen this issue or create a new one with updated details.
