### ISSUE TITLE
Uyuni 2022.05: Unable to register client: "Got no result for grains.items on minion"

### ISSUE THREAD

**Issue by heiwu** [uyuni-project/uyuni#5669]
# Problem description

After bootstrapping a client and accepting salt key, uyuni is unable to register that client (create system profile)

## Version of Uyuni Server and Proxy (if used)

Client: `salt-minion-3004-150300.53.24.1.x86_64` (also tried `venv-salt-minion-3004-2.1.uyuni.x86_64`)
Server: `2022.05-180.1.uyuni1`

```
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2022.06-183.9.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : out-of-date (version 2022.05-180.1.uyuni1 installed)
Source package : Uyuni-Server-release-2022.06-183.9.uyuni2.src
Summary        : Uyuni Server
Description    : <cut>
```
## Details about the issue

Had to reinstall a sles15_sap sp3 client system. To avoid problems i deleted it from uyuni (gui) before.
After re-install was complete bootstrap script running on client (triggered by autoyast) was successful.
Accepting salt key in uyuni also worked, but then uyuni was unable to register the system (create profile).
Tried alternatives:
- bootstrapping from Uyuni GUI (salt agent and ssh), several times, with uninstalling salt, removing config from /etc, even re-generating machine uuid
- using venv instead of classic salt-minion
- using FQDN/shortname/IP
- using a different LAN Port, IP, Net, route

Related Thread in uyuni users mailinglist: https://lists.opensuse.org/archives/list/users@lists.uyuni-project.org/thread/3OQBLUUUN3NMY6YC2QMOND7UFHKPHZ7X/

Error in Uyuni WebGUI: `Onboarding failed | Error registering minion id: minion.hostna.me`

Errors in `/var/log/rhn/rhn_web_ui.log`:
```
2022-07-14 15:13:15,952 [salt-event-thread-3] WARN  com.suse.manager.webui.services.impl.SaltService - Got no result for grains.items on minion minion.hostna.me (minion did not respond in time)
2022-07-14 15:13:20,947 [salt-event-thread-3] ERROR com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction - Unable to find the server architecture for osfamily: '' and osarch: ''
2022-07-14 15:13:20,948 [salt-event-thread-3] ERROR com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction - Error registering minion id: minion.hostna.me
java.lang.IllegalArgumentException: Unable to get the server architecture
        at com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction.finalizeMinionRegistration(RegisterMinionEventMessageAction.java:487) ~[rhn.jar:?]
        at com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction.lambda$registerMinion$7(RegisterMinionEventMessageAction.java:234) ~[rhn.jar:?]
        at com.suse.utils.Opt.consume(Opt.java:89) ~[rhn.jar:?]
        at com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction.lambda$registerMinion$9(RegisterMinionEventMessageAction.java:231) ~[rhn.jar:?]
        at com.suse.utils.Opt.consume(Opt.java:89) ~[rhn.jar:?]
        at com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction.lambda$registerMinion$18(RegisterMinionEventMessageAction.java:230) ~[rhn.jar:?]
        at com.suse.utils.Opt.consume(Opt.java:89) ~[rhn.jar:?]
        at com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction.registerMinion(RegisterMinionEventMessageAction.java:228) ~[rhn.jar:?]
        at com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction.lambda$registerMinion$5(RegisterMinionEventMessageAction.java:190) ~[rhn.jar:?]
        at com.suse.utils.Opt.consume(Opt.java:92) ~[rhn.jar:?]
        at com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction.lambda$registerMinion$6(RegisterMinionEventMessageAction.java:188) ~[rhn.jar:?]
        at com.suse.utils.Opt.consume(Opt.java:92) ~[rhn.jar:?]
        at com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction.registerMinion(RegisterMinionEventMessageAction.java:176) ~[rhn.jar:?]
        at com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction.execute(RegisterMinionEventMessageAction.java:145) ~[rhn.jar:?]
        at com.suse.manager.reactor.PGEventListener.lambda$notify$1(PGEventListener.java:76) ~[rhn.jar:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?]
        at com.suse.manager.reactor.PGEventListener.lambda$notify$2(PGEventListener.java:74) ~[rhn.jar:?]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?]
        at com.suse.manager.reactor.PGEventListener.notify(PGEventListener.java:71) ~[rhn.jar:?]
        at com.suse.salt.netapi.event.AbstractEventStream.notifyListeners(AbstractEventStream.java:64) ~[salt-netapi-clientsalt-netapi-client.jar:?]
        at com.suse.manager.reactor.PGEventStream.lambda$processEvents$6(PGEventStream.java:202) ~[rhn.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357) ~[?:?]
        at java.util.stream.Sink$ChainedReference.end(Sink.java:258) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
        at com.suse.manager.reactor.PGEventStream.processEvents(PGEventStream.java:196) ~[rhn.jar:?]
        at com.suse.manager.reactor.PGEventStream.lambda$notification$1(PGEventStream.java:180) ~[rhn.jar:?]
        at com.redhat.rhn.frontend.events.TransactionHelper.run(TransactionHelper.java:63) ~[rhn.jar:?]
        at com.redhat.rhn.frontend.events.TransactionHelper.handlingTransaction(TransactionHelper.java:48) ~[rhn.jar:?]
        at com.suse.manager.reactor.PGEventStream.lambda$notification$3(PGEventStream.java:179) ~[rhn.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
2022-07-14 15:13:20,948 [salt-event-thread-3] ERROR com.suse.manager.reactor.PGEventListener - Unexpected exception while executing a MessageAction
com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction$RegisterMinionException: null
        at com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction.finalizeMinionRegistration(RegisterMinionEventMessageAction.java:531) ~[rhn.jar:?]
        at com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction.lambda$registerMinion$7(RegisterMinionEventMessageAction.java:234) ~[rhn.jar:?]
        at com.suse.utils.Opt.consume(Opt.java:89) ~[rhn.jar:?]
        at com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction.lambda$registerMinion$9(RegisterMinionEventMessageAction.java:231) ~[rhn.jar:?]
        at com.suse.utils.Opt.consume(Opt.java:89) ~[rhn.jar:?]
        at com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction.lambda$registerMinion$18(RegisterMinionEventMessageAction.java:230) ~[rhn.jar:?]
        at com.suse.utils.Opt.consume(Opt.java:89) ~[rhn.jar:?]
        at com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction.registerMinion(RegisterMinionEventMessageAction.java:228) ~[rhn.jar:?]
        at com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction.lambda$registerMinion$5(RegisterMinionEventMessageAction.java:190) ~[rhn.jar:?]
        at com.suse.utils.Opt.consume(Opt.java:92) ~[rhn.jar:?]
        at com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction.lambda$registerMinion$6(RegisterMinionEventMessageAction.java:188) ~[rhn.jar:?]
        at com.suse.utils.Opt.consume(Opt.java:92) ~[rhn.jar:?]
        at com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction.registerMinion(RegisterMinionEventMessageAction.java:176) ~[rhn.jar:?]
        at com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction.execute(RegisterMinionEventMessageAction.java:145) ~[rhn.jar:?]
        at com.suse.manager.reactor.PGEventListener.lambda$notify$1(PGEventListener.java:76) ~[rhn.jar:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?]
        at com.suse.manager.reactor.PGEventListener.lambda$notify$2(PGEventListener.java:74) ~[rhn.jar:?]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?]
        at com.suse.manager.reactor.PGEventListener.notify(PGEventListener.java:71) ~[rhn.jar:?]
        at com.suse.salt.netapi.event.AbstractEventStream.notifyListeners(AbstractEventStream.java:64) ~[salt-netapi-clientsalt-netapi-client.jar:?]
        at com.suse.manager.reactor.PGEventStream.lambda$processEvents$6(PGEventStream.java:202) ~[rhn.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357) ~[?:?]
        at java.util.stream.Sink$ChainedReference.end(Sink.java:258) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
        at com.suse.manager.reactor.PGEventStream.processEvents(PGEventStream.java:196) ~[rhn.jar:?]
        at com.suse.manager.reactor.PGEventStream.lambda$notification$1(PGEventStream.java:180) ~[rhn.jar:?]
        at com.redhat.rhn.frontend.events.TransactionHelper.run(TransactionHelper.java:63) ~[rhn.jar:?]
        at com.redhat.rhn.frontend.events.TransactionHelper.handlingTransaction(TransactionHelper.java:48) ~[rhn.jar:?]
        at com.suse.manager.reactor.PGEventStream.lambda$notification$3(PGEventStream.java:179) ~[rhn.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
2022-07-14 15:13:20,949 [salt-event-thread-3] ERROR com.redhat.rhn.frontend.events.TransactionHelper - com.suse.manager.reactor.PGEventListenerException
2022-07-14 15:13:20,950 [salt-event-thread-3] ERROR com.suse.manager.reactor.PGEventStream - Events [35291] were lost
```

Querying data from that system using salt on uyuni console (bash) as root works great:
```
# salt minion.hostna.me grains.items|grep -A1 osarch
    osarch:
        x86_64
```

Salt events captured on uyuni / salt master:
```
salt/auth       {
    "_stamp": "2022-07-14T13:12:58.957000",
    "act": "accept",
    "id": "minion.hostna.me",
    "pub": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1VSbSuSyFzD1L4mzK44J\nve8Jx3Pt1tDkWpII8/iFPDYFSCL07HmUChid/w2xas4nK9uMi4K/u3VFcyTXpuXi\n77nhH/1TCguStBtkKwmPH9tG6PVHlmBvd5YIXIq9fX5M5nqwvDGWakF9AK/sSgAA\nPgQLDJsd9kCkvtrALqtUJKst5QtpC5FNQeCPbIlpQRZBJGWUirBend1KD58C9aQ6\nOkISd7QmxnlfsL9WAjMoEXSnjqN6FG53Y282XNYBn5Q8InPqz7Bo8tuF2Z6zHlc2\n9JyTvAi3oW5ED4Ow1DDABdPtSDagDFzpHjk6n5MtEN9lnGpFniaESb2bhfyLpm7X\nvQIDAQAB\n-----END PUBLIC KEY-----\n",
    "result": true
}
minion/refresh/minion.hostna.me  {
    "Minion data cache refresh": "minion.hostna.me",
    "_stamp": "2022-07-14T13:12:59.105188"
}
salt/minion/minion.hostna.me/start       {
    "_stamp": "2022-07-14T13:13:09.352497",
    "cmd": "_minion_event",
    "data": "Minion minion.hostna.me started at Thu Jul 14 15:13:09 2022",
    "grains": {
        "machine_id": "551199a189a285553a1bb3d662d012dd",
        "susemanager": {
            "activation_key": "1-sles15sp3-sap-sandbox"
        }
    },
    "id": "minion.hostna.me",
    "pretag": null,
    "tag": "salt/minion/minion.hostna.me/start"
}
20220714131309544689    {
    "_stamp": "2022-07-14T13:13:09.545036",
    "minions": [
        "minion.hostna.me"
    ]
}
salt/job/20220714131309544689/new       {
    "_stamp": "2022-07-14T13:13:09.545557",
    "arg": [],
    "fun": "mgractionchains.resume",
    "jid": "20220714131309544689",
    "minions": [
        "minion.hostna.me"
    ],
    "missing": [],
    "tgt": "minion.hostna.me",
    "tgt_type": "glob",
    "user": "salt"
}
20220714131309617184    {
    "_stamp": "2022-07-14T13:13:09.617475",
    "minions": [
        "minion.hostna.me"
    ]
}
salt/job/20220714131309617184/new       {
    "_stamp": "2022-07-14T13:13:09.617967",
    "arg": [],
    "fun": "test.ping",
    "jid": "20220714131309617184",
    "minions": [
        "minion.hostna.me"
    ],
    "missing": [],
    "tgt": [
        "minion.hostna.me"
    ],
    "tgt_type": "list",
    "user": "admin"
}
salt/job/20220714131309544689/ret/minion.hostna.me       {
    "_stamp": "2022-07-14T13:13:09.670834",
    "cmd": "_return",
    "fun": "mgractionchains.resume",
    "fun_args": [],
    "id": "minion.hostna.me",
    "jid": "20220714131309544689",
    "metadata": {
        "suma-action-chain": true
    },
    "retcode": 0,
    "return": {},
    "success": true
}
salt/job/20220714131309617184/ret/minion.hostna.me       {
    "_stamp": "2022-07-14T13:13:09.741882",
    "cmd": "_return",
    "fun": "test.ping",
    "fun_args": [],
    "id": "minion.hostna.me",
    "jid": "20220714131309617184",
    "retcode": 0,
    "return": true,
    "success": true
}
20220714131309868274    {
    "_stamp": "2022-07-14T13:13:09.868617",
    "minions": [
        "minion.hostna.me"
    ]
}
salt/job/20220714131309868274/new       {
    "_stamp": "2022-07-14T13:13:09.869125",
    "arg": [],
    "fun": "saltutil.sync_grains",
    "jid": "20220714131309868274",
    "minions": [
        "minion.hostna.me"
    ],
    "missing": [],
    "tgt": [
        "minion.hostna.me"
    ],
    "tgt_type": "list",
    "user": "admin"
}
salt/job/20220714131309868274/ret/minion.hostna.me       {
    "_stamp": "2022-07-14T13:13:10.382469",
    "cmd": "_return",
    "fun": "saltutil.sync_grains",
    "fun_args": [],
    "id": "minion.hostna.me",
    "jid": "20220714131309868274",
    "retcode": 0,
    "return": [],
    "success": true
}
20220714131310718881    {
    "_stamp": "2022-07-14T13:13:10.719178",
    "minions": [
        "minion.hostna.me"
    ]
}
salt/job/20220714131310718881/new       {
    "_stamp": "2022-07-14T13:13:10.719676",
    "arg": [],
    "fun": "test.ping",
    "jid": "20220714131310718881",
    "minions": [
        "minion.hostna.me"
    ],
    "missing": [],
    "tgt": [
        "minion.hostna.me"
    ],
    "tgt_type": "list",
    "user": "admin"
}
20220714131314762241    {
    "_stamp": "2022-07-14T13:13:14.762526",
    "minions": [
        "minion.hostna.me"
    ]
}
salt/job/20220714131314762241/new       {
    "_stamp": "2022-07-14T13:13:14.763012",
    "arg": [
        "20220714131310718881"
    ],
    "fun": "saltutil.find_job",
    "jid": "20220714131314762241",
    "minions": [
        "minion.hostna.me"
    ],
    "missing": [],
    "tgt": [
        "minion.hostna.me"
    ],
    "tgt_type": "list",
    "user": "admin"
}
20220714131316191965    {
    "_stamp": "2022-07-14T13:13:16.192278",
    "minions": [
        "minion.hostna.me"
    ]
}
salt/job/20220714131316191965/new       {
    "_stamp": "2022-07-14T13:13:16.192763",
    "arg": [],
    "fun": "test.ping",
    "jid": "20220714131316191965",
    "minions": [
        "minion.hostna.me"
    ],
    "missing": [],
    "tgt": [
        "minion.hostna.me"
    ],
    "tgt_type": "list",
    "user": "admin"
}
20220714131320239868    {
    "_stamp": "2022-07-14T13:13:20.240216",
    "minions": [
        "minion.hostna.me"
    ]
}
salt/job/20220714131320239868/new       {
    "_stamp": "2022-07-14T13:13:20.240793",
    "arg": [
        "20220714131316191965"
    ],
    "fun": "saltutil.find_job",
    "jid": "20220714131320239868",
    "minions": [
        "minion.hostna.me"
    ],
    "missing": [],
    "tgt": [
        "minion.hostna.me"
    ],
    "tgt_type": "list",
    "user": "admin"
}
salt/job/20220714131310718881/ret/minion.hostna.me       {
    "_stamp": "2022-07-14T13:13:20.648287",
    "cmd": "_return",
    "fun": "test.ping",
    "fun_args": [],
    "id": "minion.hostna.me",
    "jid": "20220714131310718881",
    "retcode": 0,
    "return": true,
    "success": true
}
salt/job/20220714131314762241/ret/minion.hostna.me       {
    "_stamp": "2022-07-14T13:13:20.652867",
    "cmd": "_return",
    "fun": "saltutil.find_job",
    "fun_args": [
        "20220714131310718881"
    ],
    "id": "minion.hostna.me",
    "jid": "20220714131314762241",
    "retcode": 0,
    "return": {},
    "success": true
}
salt/job/20220714131316191965/ret/minion.hostna.me       {
    "_stamp": "2022-07-14T13:13:20.658460",
    "cmd": "_return",
    "fun": "test.ping",
    "fun_args": [],
    "id": "minion.hostna.me",
    "jid": "20220714131316191965",
    "retcode": 0,
    "return": true,
    "success": true
}
minion/refresh/minion.hostna.me  {
    "Minion data cache refresh": "minion.hostna.me",
    "_stamp": "2022-07-14T13:13:20.670603"
}
salt/job/20220714131320239868/ret/minion.hostna.me       {
    "_stamp": "2022-07-14T13:13:20.673717",
    "cmd": "_return",
    "fun": "saltutil.find_job",
    "fun_args": [
        "20220714131316191965"
    ],
    "id": "minion.hostna.me",
    "jid": "20220714131320239868",
    "retcode": 0,
    "return": {},
    "success": true
}
20220714131320697134    {
    "_stamp": "2022-07-14T13:13:20.697886",
    "minions": [
        "minion.hostna.me"
    ]
}
salt/job/20220714131320697134/new       {
    "_stamp": "2022-07-14T13:13:20.698353",
    "arg": [
        "master"
    ],
    "fun": "config.get",
    "jid": "20220714131320697134",
    "minions": [
        "minion.hostna.me"
    ],
    "missing": [],
    "tgt": [
        "minion.hostna.me"
    ],
    "tgt_type": "list",
    "user": "admin"
}
salt/job/20220714131320697134/ret/minion.hostna.me       {
    "_stamp": "2022-07-14T13:13:20.814600",
    "cmd": "_return",
    "fun": "config.get",
    "fun_args": [
        "master"
    ],
    "id": "minion.hostna.me",
    "jid": "20220714131320697134",
    "retcode": 0,
    "return": "minion.hostna.me",
    "success": true
}
```

So far i couldn't find anything interesting in client log.
Also didn't find anythin relatable in release Notes of Uyuni 2022.06

**Comment by mbussolotto** [comment]
Hi @heiwu , I'm wondering if the problem is really `minion did not respond in time` ... probably it's something else but can you try to increase timeout https://www.uyuni-project.org/uyuni-docs/en/uyuni/specialized-guides/large-deployments/tuning.html#java-salt-presence-ping-timeout ?

Thanks!
