### ISSUE TITLE
Package mgmt broken on clients registered through a proxy after upgrade to 2022.06

### ISSUE THREAD

**Issue by phibid** [uyuni-project/uyuni#5704]
I have just upgraded to Uyuni 2022.06 and all the upgrade process went well on the Uyuni as on the proxy servers.

However, I am now seeing that all the registered servers through the proxies have issues to get metadata and packages:

```
E: Failed to fetch https://uyuni_proxy:443/rhn/manager/download/ubuntu-2004-amd64-main-security-uyuni/getPackage/linux-image-5.4.0-122-generic_5.4.0-122.138.amd64-deb.deb  500  Internal Server Error [IP: 10.10.10.10 443]
E: Failed to fetch https://uyuni_proxy:443/rhn/manager/download/ubuntu-2004-amd64-main-security-uyuni/getPackage/linux-modules-extra-5.4.0-122-generic_5.4.0-122.138.amd64-deb.deb  500  Internal Server Error [IP: 10.10.10.10 443]
E: Failed to fetch https://uyuni_proxy:443/rhn/manager/download/ubuntu-2004-amd64-main-security-uyuni/getPackage/linux-generic_5.4.0.122.123-X.amd64-deb.deb  500  Internal Server Error [IP: 10.10.10.10 443]
E: Failed to fetch https://uyuni_proxy:443/rhn/manager/download/ubuntu-2004-amd64-main-security-uyuni/getPackage/linux-image-generic_5.4.0.122.123-X.amd64-deb.deb  500  Internal Server Error [IP: 10.10.10.10 443]
E: Failed to fetch https://uyuni_proxy:443/rhn/manager/download/ubuntu-2004-amd64-main-security-uyuni/getPackage/linux-headers-5.4.0-122_5.4.0-122.138.all-deb.deb  500  Internal Server Error [IP: 10.10.10.10 443]
E: Failed to fetch https://uyuni_proxy:443/rhn/manager/download/ubuntu-2004-amd64-main-security-uyuni/getPackage/linux-headers-5.4.0-122-generic_5.4.0-122.138.amd64-deb.deb  500  Internal Server Error [IP: 10.10.10.10 443]
E: Failed to fetch https://uyuni_proxy:443/rhn/manager/download/ubuntu-2004-amd64-main-security-uyuni/getPackage/linux-headers-generic_5.4.0.122.123-X.amd64-deb.deb  500  Internal Server Error [IP: 10.10.10.10 443]
E: Failed to fetch https://uyuni_proxy:443/rhn/manager/download/ubuntu-2004-amd64-main-updates-uyuni/getPackage/modemmanager_1.18.6-1~ubuntu20.04.1.amd64-deb.deb  500  Internal Server Error [IP: 10.10.10.10 443]
E: Failed to fetch https://uyuni_proxy:443/rhn/manager/download/ubuntu-2004-amd64-main-security-uyuni/getPackage/networkd-dispatcher_2.1-2~ubuntu20.04.3.all-deb.deb  500  Internal Server Error [IP: 10.10.10.10 443]
E: Failed to fetch https://uyuni_proxy:443/rhn/manager/download/ubuntu-2004-amd64-main-security-uyuni/getPackage/python3-jwt_1.7.1-2ubuntu2.1.all-deb.deb  500  Internal Server Error [IP: 10.10.10.10 443]
E: Failed to fetch https://uyuni_proxy:443/rhn/manager/download/ubuntu-2004-amd64-main-updates-uyuni/getPackage/sbsigntool_0.9.2-2ubuntu1.1.amd64-deb.deb  500  Internal Server Error [IP: 10.10.10.10 443]
E: Failed to fetch https://uyuni_proxy:443/rhn/manager/download/ubuntu-2004-amd64-main-updates-uyuni/getPackage/snapd_2.55.5+20.04-X.amd64-deb.deb  500  Internal Server Error [IP: 10.10.10.10 443]
E: Failed to fetch https://uyuni_proxy:443/rhn/manager/download/ubuntu-2004-amd64-uyuni-client/getPackage/venv-salt-minion_3004-2.4.uyuni.amd64-deb.deb  500  Internal Server Error [IP: 10.10.10.10 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

This affects, all the OS from what I can see, CentOS and Ubuntu. I can't see any errors on the Uyuni servers, which is strange, only the `TCP_MISS/500` on the squid logs from the Uyuni proxy:

```
1658745550.125     14 127.0.0.1 TCP_MISS/500 271 GET http://uyuni_proxy/rhn/manager/download/ubuntu-2004-amd64-main-security-uyuni/getPackage/git-man_1:2.25.1-1ubuntu3.5.all-deb.deb - HIER_DIRECT/10.10.10.10 text/xml
1658745550.237     15 127.0.0.1 TCP_MISS/500 271 GET http://uyuni_proxy/rhn/manager/download/ubuntu-2004-amd64-main-security-uyuni/getPackage/libcurl3-gnutls_7.68.0-1ubuntu2.12.amd64-deb.deb - HIER_DIRECT/10.10.10.10 text/xml
1658745550.352     15 127.0.0.1 TCP_MISS/500 271 GET http://uyuni_proxy/rhn/manager/download/ubuntu-2004-amd64-main-security-uyuni/getPackage/git_1:2.25.1-1ubuntu3.5.amd64-deb.deb - HIER_DIRECT/10.10.10.10 text/xml
1658745550.465     15 127.0.0.1 TCP_MISS/500 271 GET http://uyuni_proxy/rhn/manager/download/ubuntu-2004-amd64-main-security-uyuni/getPackage/libcom-err2_1.45.5-2ubuntu1.1.amd64-deb.deb - HIER_DIRECT/10.10.10.10 text/xml
1658745550.577     14 127.0.0.1 TCP_MISS/500 271 GET http://uyuni_proxy/rhn/manager/download/ubuntu-2004-amd64-main-security-uyuni/getPackage/python3-problem-report_2.20.11-0ubuntu27.24.all-deb.deb - HIER_DIRECT/10.10.10.10 text/xml
1658745550.686     15 127.0.0.1 TCP_MISS/500 271 GET http://uyuni_proxy/rhn/manager/download/ubuntu-2004-amd64-main-security-uyuni/getPackage/python3-apport_2.20.11-0ubuntu27.24.all-deb.deb - HIER_DIRECT/10.10.10.10 text/xml
1658745550.799     15 127.0.0.1 TCP_MISS/500 271 GET http://uyuni_proxy/rhn/manager/download/ubuntu-2004-amd64-main-security-uyuni/getPackage/apport_2.20.11-0ubuntu27.24.all-deb.deb - HIER_DIRECT/10.10.10.10 text/xml
```

**Comment by phibid** [comment]
In fact, the only logs I can see are located in `rhn_web_ui.log`:

```
2022-07-25 11:09:07,905 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-10] INFO  com.suse.manager.webui.controllers.DownloadController - 404 - File not found: /var/cache/rhn/repodata/ubuntu-2004-amd64-uyuni-client/Packages.zst
2022-07-25 11:09:08,432 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-3] INFO  com.suse.manager.webui.controllers.DownloadController - 404 - File not found: /var/cache/rhn/repodata/ubuntu-2004-amd64-universe-uyuni/Packages.zst
2022-07-25 11:09:09,017 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-8] INFO  com.suse.manager.webui.controllers.DownloadController - 404 - File not found: /var/cache/rhn/repodata/ubuntu-2004-amd64-multiverse-uyuni/Packages.zst
2022-07-25 11:09:09,549 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-4] INFO  com.suse.manager.webui.controllers.DownloadController - 404 - File not found: /var/cache/rhn/repodata/ubuntu-2004-amd64-main-updates-uyuni/Packages.zst
2022-07-25 11:09:10,075 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-7] INFO  com.suse.manager.webui.controllers.DownloadController - 404 - File not found: /var/cache/rhn/repodata/ubuntu-2004-amd64-main-security-uyuni/Packages.zst
2022-07-25 11:09:10,597 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-6] INFO  com.suse.manager.webui.controllers.DownloadController - 404 - File not found: /var/cache/rhn/repodata/ubuntu-2004-amd64-universe-updates-uyuni/Packages.zst
2022-07-25 11:09:11,125 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-1] INFO  com.suse.manager.webui.controllers.DownloadController - 404 - File not found: /var/cache/rhn/repodata/ubuntu-2004-amd64-universe-security-uyuni/Packages.zst
2022-07-25 11:09:11,653 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-9] INFO  com.suse.manager.webui.controllers.DownloadController - 404 - File not found: /var/cache/rhn/repodata/ubuntu-2004-amd64-multiverse-updates-uyuni/Packages.zst
2022-07-25 11:09:12,178 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-2] INFO  com.suse.manager.webui.controllers.DownloadController - 404 - File not found: /var/cache/rhn/repodata/ubuntu-2004-amd64-multiverse-security-uyuni/Packages.zst
2022-07-25 11:09:26,924 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-2] INFO  com.suse.manager.webui.controllers.DownloadController - 404 - File not found: /var/cache/rhn/repodata/epel7-centos7-x86_64/ebbdabaf650064db68dae3afff859d3e3568e022-primary.xml.gz
2022-07-25 11:09:26,948 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-8] INFO  com.suse.manager.webui.controllers.DownloadController - 404 - File not found: /var/cache/rhn/repodata/centos7-x86_64-updates/a14ee3487ec5781c28c47b409d1855cb10c5d32e-updateinfo.xml.gz
2022-07-25 11:09:26,949 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-6] INFO  com.suse.manager.webui.controllers.DownloadController - 404 - File not found: /var/cache/rhn/repodata/epel7-centos7-x86_64/66f40a30b4b3b52a0ec30354961f1105d53f4a58-updateinfo.xml.gz
2022-07-25 11:09:27,072 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-5] INFO  com.suse.manager.webui.controllers.DownloadController - 404 - File not found: /var/cache/rhn/repodata/epel7-centos7-x86_64/ebbdabaf650064db68dae3afff859d3e3568e022-primary.xml.gz
```

Strange ...

**Comment by phibid** [comment]
Ah, finally found the error in the error.log of the Apache of the Uyuni proxy:

```
[Mon Jul 25 11:44:13.961929 2022] [wsgi:error] [pid 5484] [client 10.10.10.10:46906] Extra information about this error:
[Mon Jul 25 11:44:13.962012 2022] [wsgi:error] [pid 5484] [client 10.10.10.10:46906] Unhandled exception type
[Mon Jul 25 11:44:13.962093 2022] [wsgi:error] [pid 5484] [client 10.10.10.10:46906]
[Mon Jul 25 11:44:13.962174 2022] [wsgi:error] [pid 5484] [client 10.10.10.10:46906] Exception Handler Information
[Mon Jul 25 11:44:13.962255 2022] [wsgi:error] [pid 5484] [client 10.10.10.10:46906] Traceback (most recent call last):
[Mon Jul 25 11:44:13.962337 2022] [wsgi:error] [pid 5484] [client 10.10.10.10:46906]   File "/usr/share/rhn/proxy/apacheServer.py", line 62, in __call__
[Mon Jul 25 11:44:13.962417 2022] [wsgi:error] [pid 5484] [client 10.10.10.10:46906]     ret = f(req)
[Mon Jul 25 11:44:13.962527 2022] [wsgi:error] [pid 5484] [client 10.10.10.10:46906]   File "/usr/share/rhn/proxy/apacheHandler.py", line 367, in handler
[Mon Jul 25 11:44:13.962550 2022] [wsgi:error] [pid 5484] [client 10.10.10.10:46906]     ret = handlerObj.handler()
[Mon Jul 25 11:44:13.962563 2022] [wsgi:error] [pid 5484] [client 10.10.10.10:46906]   File "/usr/share/rhn/proxy/redirect/rhnRedirect.py", line 92, in handler
[Mon Jul 25 11:44:13.962574 2022] [wsgi:error] [pid 5484] [client 10.10.10.10:46906]     self._connectToParent()  # part 1
[Mon Jul 25 11:44:13.962697 2022] [wsgi:error] [pid 5484] [client 10.10.10.10:46906]   File "/usr/share/rhn/proxy/rhnShared.py", line 145, in _connectToParent
[Mon Jul 25 11:44:13.962710 2022] [wsgi:error] [pid 5484] [client 10.10.10.10:46906]     self.responseContext.getConnection().connect()
[Mon Jul 25 11:44:13.962721 2022] [wsgi:error] [pid 5484] [client 10.10.10.10:46906]   File "/usr/lib/python3.6/site-packages/rhn/connections.py", line 209, in connect
[Mon Jul 25 11:44:13.962849 2022] [wsgi:error] [pid 5484] [client 10.10.10.10:46906]     self.sock = SSL.SSLSocket(sock, self.trusted_certs)
[Mon Jul 25 11:44:13.962862 2022] [wsgi:error] [pid 5484] [client 10.10.10.10:46906]   File "/usr/lib/python3.6/site-packages/rhn/SSL.py", line 63, in __init__
[Mon Jul 25 11:44:13.962873 2022] [wsgi:error] [pid 5484] [client 10.10.10.10:46906]     self.add_trusted_cert(f)
[Mon Jul 25 11:44:13.963000 2022] [wsgi:error] [pid 5484] [client 10.10.10.10:46906]   File "/usr/lib/python3.6/site-packages/rhn/SSL.py", line 89, in add_trusted_cert
[Mon Jul 25 11:44:13.963013 2022] [wsgi:error] [pid 5484] [client 10.10.10.10:46906]     raise ValueError("Unable to read certificate file %s" % file)
[Mon Jul 25 11:44:13.963129 2022] [wsgi:error] [pid 5484] [client 10.10.10.10:46906] ValueError: Unable to read certificate file /usr/share/rhn/RHN-ORG-TRUSTED-SSL-CERT
[Mon Jul 25 11:44:13.963170 2022] [wsgi:error] [pid 5484] [client 10.10.10.10:46906]
```

And indeed ....

```
uyuni_proxy:# ls -lrt /usr/share/rhn/RHN-ORG-TRUSTED-SSL-CERT
ls: cannot access '/usr/share/rhn/RHN-ORG-TRUSTED-SSL-CERT': No such file or directory
```

**Comment by phibid** [comment]
Ok, noticed that this symlink was missing:

```
lrwxrwxrwx 1 root root 47 May 20 18:29 /usr/share/rhn/RHN-ORG-TRUSTED-SSL-CERT -> /etc/pki/trust/anchors/RHN-ORG-TRUSTED-SSL-CERT
```

Created it again, and all working now. Not sure why this symlink disappeared to be honest.

**Comment by mcalmer** [comment]
I think i fixed the symlink already, but maybe it is part of 2022.07
