### ISSUE TITLE
Uyuni 2022.06: spacewalk-report can't find RHN-ORG-TRUSTED-SSL-CERT

### ISSUE THREAD

**Issue by phibid** [uyuni-project/uyuni#5718]
After the upgrade to Uyuni 2022.06, the tool `/usr/bin/spacewalk-report` does not work anymore  throwing this stack trace:

```
uyuni:~ # /usr/bin/spacewalk-report inventory
SQL error occurred, traceback follows...
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/__init__.py", line 53, in __init__DB
    my_db = __DB
NameError: name '__DB' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 185, in connect
    self.dbh = psycopg2.connect(" ".join("%s=%s" % (k, re.escape(str(v))) for k, v in list(dsndata.items())))
  File "/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "uyuni" (10.10.10.10), port 5432 failed: root certificate file "/etc/pki/trust/anchors/RHN-ORG-TRUSTED-SSL-CERT" does not exist
Either provide the file or change sslmode to disable server certificate verification.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 185, in connect
    self.dbh = psycopg2.connect(" ".join("%s=%s" % (k, re.escape(str(v))) for k, v in list(dsndata.items())))
  File "/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "uyuni" (10.10.10.10), port 5432 failed: root certificate file "/etc/pki/trust/anchors/RHN-ORG-TRUSTED-SSL-CERT" does not exist
Either provide the file or change sslmode to disable server certificate verification.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/spacewalk-report", line 268, in <module>
    rhnSQL.initDB(reportdb=options.use_reportdb)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/__init__.py", line 137, in initDB
    raise_with_tb(e, sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/uyuni/common/usix.py", line 77, in raise_with_tb
    raise value
  File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/__init__.py", line 126, in initDB
    __init__DB(backend, host, port, username, password, database, sslmode, sslrootcert)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/__init__.py", line 57, in __init__DB
    __DB.connect()
  File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 195, in connect
    return self.connect(reconnect=reconnect - 1)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 200, in connect
    "All attempts to connect to the database failed"), sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/uyuni/common/usix.py", line 76, in raise_with_tb
    raise value.with_traceback(tb)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 185, in connect
    self.dbh = psycopg2.connect(" ".join("%s=%s" % (k, re.escape(str(v))) for k, v in list(dsndata.items())))
  File "/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
spacewalk.server.rhnSQL.sql_base.SQLConnectError: (None, None, 'reportdb', 'All attempts to connect to the database failed')
```

The certificate is indeed not there anymore and is now called `LOCAL-RHN-ORG-TRUSTED-SSL-CERT`

```
uyuni:/etc/pki/trust/anchors # ls -lrt *RHN*
-rw-r--r-- 1 root root 5114 Apr  4  2020 LOCAL-RHN-ORG-TRUSTED-SSL-CERT
```

Creating a symlink to it called `RHN-ORG-TRUSTED-SSL-CERT` seems to do the trick. I have tried to find where exactly `/etc/pki/trust/anchors/RHN-ORG-TRUSTED-SSL-CERT` is defined, but no luck with that.

**Comment by phibid** [comment]
Well, no, the creation of the symlink does not solve the issue. It makes the stack trace disappear, but the output of the command execution is empty:

```
uyuni:~ # /usr/bin/spacewalk-report inventory
mgm_id,system_id,profile_name,hostname,ip_address,ipv6_address,registered_by,registration_time,last_checkin_time,kernel_version,packages_out_of_date,errata_out_of_date,software_channel,configuration_channel,entitlements,system_group,organization,virtual_host,architecture,is_virtualized,virt_type,hardware,minion_id,machine_id,synced_date
```

**Comment by mbussolotto** [comment]
> Well, no, the creation of the symlink does not solve the issue. It makes the stack trace disappear, but the output of the command execution is empty:

please consider that now `spacewalk-report` use the reportdb, and it sync data daily at midnight. So:
- you schedule `mgr-update-reporting-bunch` (or wait until midnight until some data are shown)
- otherwise if you want to use the "old" `spacewalk-report` you should use `--legacy`

> Creating a symlink to it called RHN-ORG-TRUSTED-SSL-CERT seems to do the trick. I have tried to find where exactly /etc/pki/trust/anchors/RHN-ORG-TRUSTED-SSL-CERT is defined, but no luck with that.

Of course is definitely a bug...is it a fresh installation or an upgrade?

Thanks!

**Comment by phibid** [comment]
@mbussolotto  Hi ! This is an upgrade.

**Comment by mbussolotto** [comment]
I guess this should fix the issue: https://github.com/uyuni-project/uyuni/pull/5620 .  It will be available from 2022.07

**Comment by mcalmer** [comment]
@phibid Can you check your  /etc/rhn/rhn.conf if some config option point to "/etc/pki/trust/anchors/RHN-ORG-TRUSTED-SSL-CERT" ?
Please tell us which one it is.

**Comment by phibid** [comment]
@mcalmer Ah ok, did not think to check at the rhn.conf:

```
uyuni:/etc/rhn # grep -ir  trusted rhn.conf
osa-dispatcher.osa_ssl_cert = /srv/www/htdocs/pub/RHN-ORG-TRUSTED-SSL-CERT
report_db_sslrootcert = /etc/pki/trust/anchors/RHN-ORG-TRUSTED-SSL-CERT
```

So, should I change this file or should I wait for [https://github.com/uyuni-project/uyuni/pull/5620](https://github.com/uyuni-project/uyuni/pull/5620) in 2022.07 ?

**Comment by mcalmer** [comment]
Please change `report_db_sslrootcert` . I think we changed it and forgot that uyuni may has now the old wrong value.
I think the pr will not help

**Comment by mbussolotto** [comment]
Hi @phibid,

Can you please provide your `/var/lib/pgsql/data/pg_hba.conf` ? Thanks!

**Comment by phibid** [comment]
Hi !

Here it is:

```
uyuni:~ # cat /var/lib/pgsql/data/pg_hba.conf
local   uyuni   admin   scram-sha-256
host    uyuni   admin   127.0.0.1/8     scram-sha-256
host    uyuni   admin   ::1/128 scram-sha-256
local   all     all     peer
host    all     all     127.0.0.1/32    ident
host    all     all     ::1/128 ident
local   replication     all     peer
host    replication     all     127.0.0.1/32    ident
host    replication     all     ::1/128 ident
local   replication     postgres        peer
local   reportdb        all     scram-sha-256   
host    reportdb        all     127.0.0.1/32    scram-sha-256
host    reportdb        all     ::1/128 scram-sha-256
host    reportdb        all     0.0.0.0/0       scram-sha-256
host    reportdb        all     ::/0    scram-sha-256
```

**Comment by mcalmer** [comment]
maybe move these 3 lines to the end of the file?

```
local   all     all     peer
host    all     all     127.0.0.1/32    ident
host    all     all     ::1/128 ident
```

**Comment by mbussolotto** [comment]
Changing `report_db_sslrootcert` and sorting `pg_hba.conf` should be done by provide `uyuni-setup-reportdb`, so I guess that during the upgrade we are not calling it at all.. I'll investigate on that
