### ISSUE TITLE
Replace ssl certificate at proxy -> ERROR: 'authorityKeyIdentifier'

### ISSUE THREAD

**Issue by mrstigmata** [uyuni-project/uyuni#5830]
# Problem description

_The following information is very important in order to help us to understand your problem. Omission of the following details can cause delays or can receive no attention at all._

## Version of Uyuni Server and Proxy (if used)

`zypper info Uyuni-Server-release` _and_ `zypper info Uyuni-Proxy-release` _(if used)_

`Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2022.08-185.2.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2022.08-185.2.uyuni2.src
Summary        : Uyuni Server`

`Information for package Uyuni-Proxy-release:
--------------------------------------------
Repository     : Uyuni Proxy Stable for openSUSE Leap 15.4 (x86_64)
Name           : Uyuni-Proxy-release
Version        : 2022.08-185.2.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Proxy-release-2022.08-185.2.uyuni2.src
Summary        : Uyuni Proxy`

## Details about the issue

we want to import a new proxy and uyuni server ssl certificate. the ssl certificate is created by our company ca.
we run that command:

` mgr-ssl-cert-setup -c -v -r root_ca.crt -i subca01.crt -s proxy01.pem -k proxy01-serverkey.pem`

the Output is the same at the Uyuni Proxy and the Uyuni Server:

`ERROR: 'authorityKeyIdentifier'`

Log file: /var/log/rhn/mgr-ssl-cert-setup.log

`2022/08/23 10:43:12 +02:00: /usr/lib/python3.6/site-packages/certs/mgr_ssl_cert_setup.py.processCommandline(105) - ['/usr/bin/mgr-ssl-cert-setup', '-v', '-c', '-r', 'root_ca.crt', '-i', 'subca01.crt', '-s', 'proxy01.pem', '-k', 'proxy01-serverkey.pem']
2022/08/23 10:43:13 +02:00: /usr/lib/python3.6/site-packages/certs/mgr_ssl_cert_setup.py.writeError(592) -
ERROR: 'authorityKeyIdentifier'

2022/08/23 10:43:13 +02:00: /usr/lib/python3.6/site-packages/certs/mgr_ssl_cert_setup.py.writeError(593) - Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/certs/mgr_ssl_cert_setup.py", line 597, in main
    ret = _main() or 0
  File "/usr/lib/python3.6/site-packages/certs/mgr_ssl_cert_setup.py", line 562, in _main
    getContainersSetup(files_content.root_ca, files_content.intermediate_cas, files_content.server_cert, files_content.server_key)
  File "/usr/lib/python3.6/site-packages/certs/mgr_ssl_cert_setup.py", line 542, in getContainersSetup
    checks(server_key_content,server_cert_content, certData)
  File "/usr/lib/python3.6/site-packages/certs/mgr_ssl_cert_setup.py", line 527, in checks
    checkCompleteCAChain(server_cert_content, certData)
  File "/usr/lib/python3.6/site-packages/certs/mgr_ssl_cert_setup.py", line 383, in checkCompleteCAChain
    issuerKeyId = certData[ihash]["authorityKeyIdentifier"]
KeyError: 'authorityKeyIdentifier'`

**Comment by mrstigmata** [comment]
@mcalmer perfect, thank you! workes for us. I was aible to install the new certificates via mgr-ssl-cert-setup without a problem
