### ISSUE TITLE
An error has occurred during salt execution: unable to parse json. 

### ISSUE THREAD

**Issue by ftigges-comdev** [uyuni-project/uyuni#5932]
# Problem description

While bootstrapping a new system the gui throw an error:
An error has occurred during salt execution: unable to parse json.

Error occurred after upgrading to 2022.08.

## Version of Uyuni Server 
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2022.08-185.2.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2022.08-185.2.uyuni2.src
Summary        : Uyuni Server
## Details about the issue
```

cat  /var/log/salt/api

2022-09-15 10:54:35,377 [salt.utils.templates:274 ][ERROR   ][16970] Rendering exception occurred
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 502, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 21, in top-level template code
  File "/var/tmp/.root_d6d5aa_salt/running_data/var/cache/venv-salt-minion/minion/files/base/channels/disablelocalrepos.sls", line 24, in top-level template code
    {% if (repos_disabled.match_str in alias)|string == repos_disabled.matching|string and data.get('enabled', True) in [True, '1'] %}
  File "/usr/lib/python3.6/site-packages/jinja2/sandbox.py", line 436, in call
    if not __self.is_safe_callable(__obj):
  File "/usr/lib/python3.6/site-packages/jinja2/sandbox.py", line 338, in is_safe_callable
    return not (getattr(obj, 'unsafe_callable', False) or
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 261, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 509, in render_jinja_tmpl
    raise SaltRenderError("Jinja variable {}{}".format(exc, out), buf=tmplstr)
salt.exceptions.SaltRenderError: Jinja variable 'str object' has no attribute 'get'
/var/tmp/.root_d6d5aa_salt/running_data/var/cache/venv-salt-minion/minion/files/base/channels/disablelocalrepos.sls(24):
---
[...]
        disabled: True
{% do repos_disabled.update({'count': repos_disabled.count + 1}) %}
{% endif %}
{% endfor %}
{% else %}
{% if (repos_disabled.match_str in alias)|string == repos_disabled.matching|string and data.get('enabled', True) in [True, '1'] %}    <======================
disable_repo_{{ alias }}:
  mgrcompat.module_run:
    - name: pkg.mod_repo
    - repo: {{ alias }}
    - kwargs:
[...]
---
2022-09-15 10:54:35,382 [salt.state       :4080][CRITICAL][16970] Rendering SLS 'base:bootstrap' failed: Jinja variable 'str object' has no attribute 'get'
/var/tmp/.root_d6d5aa_salt/running_data/var/cache/venv-salt-minion/minion/files/base/channels/disablelocalrepos.sls(24):
---
[...]
        disabled: True
{% do repos_disabled.update({'count': repos_disabled.count + 1}) %}
{% endif %}
{% endfor %}
{% else %}
{% if (repos_disabled.match_str in alias)|string == repos_disabled.matching|string and data.get('enabled', True) in [True, '1'] %}    <======================
disable_repo_{{ alias }}:
  mgrcompat.module_run:
    - name: pkg.mod_repo
    - repo: {{ alias }}
    - kwargs:
[...]
---
```

```
cat rhn_web_ui.log

2022-09-15 10:54:35,445 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-6] ERROR com.suse.manager.webui.controllers.bootstrap.AbstractMinionBootstrapper - Error during bootstrap: An error has occurred during salt execution: unable to parse json.
```

```
cat rhn_web_api.log

[2022-09-15 10:54:35,664] INFO  - REQUESTED FROM: 192.xxx.xxx.xxx CALL: systems.bootstrap(host="host.domain.xxx", activationKeys=["1-Alle_Suse"], password="XXXX", ignoreHostKeys=true, authMethod="password") CALLER: (XXXXX) TIME: 8.557 seconds
```

```
cat /usr/share/susemanager/salt/channels/disablelocalrepos.sls

# Disable all local repos matching or not matching the 'match_str'
# Default arguments: everything except *susemanager:*
{% if not repos_disabled is defined %}
{% set repos_disabled = {'match_str': 'susemanager:', 'matching': false} %}
{% endif %}
{% do repos_disabled.update({'count': 0}) %}

{% if salt['config.get']('disable_local_repos', True) %}
{% set repos = salt['pkg.list_repos']() %}
{% for alias, data in repos.items() %}
{% if grains['os_family'] == 'Debian' %}
{% for entry in data %}
{% if (repos_disabled.match_str in entry['file'])|string == repos_disabled.matching|string and entry.get('enabled', True) %} 
disable_repo_{{ repos_disabled.count }}:
  mgrcompat.module_run:
    - name: pkg.mod_repo
    - repo: {{ "'" ~ entry.line ~ "'" }}
    - kwargs:
        disabled: True
{% do repos_disabled.update({'count': repos_disabled.count + 1}) %}
{% endif %}
{% endfor %}
{% else %}



{% if (repos_disabled.match_str in alias)|string == repos_disabled.matching|string and data.get('enabled', True) in [True, '1'] %}



disable_repo_{{ alias }}:
  mgrcompat.module_run:
    - name: pkg.mod_repo
    - repo: {{ alias }}
    - kwargs:
        enabled: False
    - require:
{%- if grains.get('__suse_reserved_saltutil_states_support', False) %}
      - saltutil: sync_states
{%- else %}
      - mgrcompat: sync_states
{%- endif %}
{% do repos_disabled.update({'count': repos_disabled.count + 1}) %}
{% endif %}
{% endif %}
{% endfor %}
{% endif %}
```

**Comment by ftigges-comdev** [comment]
After enabling trace 
`echo "log_level_logfile: trace" > /etc/salt/master.d/logging.conf`

This message stands out.
`
Warning: the ECDSA host key for xxx.yyyy.zzz differs from the key for the IP address...
`
The message on the gui doesn't reflect that..
