### ISSUE TITLE
2022.11 - Webui claims all repos failing since Uyuni updated, but logs look fine.

### ISSUE THREAD

**Issue by digdilem** [uyuni-project/uyuni#6193]
### Problem description

Regular scheduled repo updates are all failing with the same error - according to the webui.   

However, logs in `/var/log/rhn/reposync` appear to show successful sync.

This only started after upgrade to 2022.11, repos were behaving fine before.

Please advise.

Screens from our Centos 7 Epel reposync

![image](https://user-images.githubusercontent.com/4052275/203570018-be785494-83e8-4cb7-95ad-53b4416f7885.png)

![image](https://user-images.githubusercontent.com/4052275/203569041-7d1f96bb-fe67-483e-8144-33817fc80743.png)

(Pasted below for seach friendliness)
```
Command '[/usr/bin/spacewalk-repo-sync, --channel, c7_epel, --type, yum, --non-interactive]' exited with error code 1: Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 299, in _execute_wrapper
retval = function(*p, **kw)
File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/sql_base.py", line 182, in _execute
return self._execute_(args, kwargs)
File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 322, in _execute_
self._real_cursor.execute(self.sql, params)
psycopg2.errors.UndefinedTable: missing FROM-clause entry for table "c"
LINE 4: coalesce(c.org_id, 1),
^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/bin/spacewalk-repo-sync", line 286, in
sys.exit(abs(main() or 0))
File "/usr/bin/spacewalk-repo-sync", line 269, in main
elapsed_time, channel_ret_code = sync.sync()
File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 705, in sync
self.update_servers()
File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 739, in update_servers
taskomatic.add_to_system_overview_update_queue(row["id"])
File "/usr/lib/python3.6/site-packages/spacewalk/server/taskomatic.py", line 103, in add_to_system_overview_update_queue
h.execute(sid=sid)
File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/sql_base.py", line 150, in execute
return self._execute_wrapper(self._execute, *p, **kw)
File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 309, in _execute_wrapper
raise sql_base.SQLStatementPrepareError(str(self.dbh), e.pgerror, self.sql)
spacewalk.server.rhnSQL.sql_base.SQLStatementPrepareError: ('ERROR: missing FROM-clause entry for table "c"\nLINE 4: coalesce(c.org_id, 1),\n ^\n', "", "\n INSERT INTO rhnTaskQueue (org_id, task_name, task_data, priority, earliest)\n VALUES (\n coalesce(c.org_id, 1),\n 'update_system_overview',\n %(sid)s,\n 0,\n current_timestamp\n )\n ")
```

Example /var/log/rhn/reposync log:
```
2022/11/23 12:35:01 +01:00 Command: ['/usr/bin/spacewalk-repo-sync', '--channel', 'c7_epel', '--type', 'yum', '--non-interactive']                                 
2022/11/23 12:35:01 +01:00 Sync of channel started.                                                                                                                
2022/11/23 12:35:07 +01:00
2022/11/23 12:35:07 +01:00   Importing comps file 6b79f3299e998e55c01aa3682f81e2bcb1678395aee04e6bdb115c3168cabc46-comps-Everything.x86_64.xml.
2022/11/23 12:35:07 +01:00   Renaming non-standard filename 6b79f3299e998e55c01aa3682f81e2bcb1678395aee04e6bdb115c3168cabc46-comps-Everything.x86_64.xml to comps.x86_64.xml.
2022/11/23 12:35:07 +01:00 *** NOTE: Importing comps file for the channel 'c7_epel'. Previous comps will be discarded.
2022/11/23 12:35:08 +01:00 Repo URL: https://dl.fedoraproject.org/pub/epel/7/x86_64/
2022/11/23 12:35:08 +01:00     Packages in repo:             13739
2022/11/23 12:35:43 +01:00     Packages already synced:      13735
2022/11/23 12:35:43 +01:00     Packages to sync:                 4
2022/11/23 12:35:43 +01:00     New packages to download:         4
2022/11/23 12:35:43 +01:00   Downloading packages:
2022/11/23 12:35:44 +01:00     1/4 : distribution-gpg-keys-1.79-1.el7.noarch.rpm
2022/11/23 12:35:44 +01:00     2/4 : drupal7-backup_migrate-3.10-1.el7.noarch.rpm
2022/11/23 12:35:44 +01:00     3/4 : tito-0.6.22-1.el7.noarch.rpm
2022/11/23 12:35:59 +01:00     4/4 : distribution-gpg-keys-copr-1.79-1.el7.noarch.rpm
2022/11/23 12:36:00 +01:00 Importing packages started.
2022/11/23 12:36:00 +01:00
2022/11/23 12:36:00 +01:00   Importing packages to DB:
2022/11/23 12:36:30 +01:00   Package batch #1 of 1 completed...
2022/11/23 12:36:30 +01:00 Importing packages finished.
2022/11/23 12:36:30 +01:00
2022/11/23 12:36:30 +01:00   Linking packages to the channel.
2022/11/23 12:36:30 +01:00     4 packages linked
2022/11/23 12:36:32 +01:00
2022/11/23 12:36:32 +01:00   Patches in repo: 4790.
2022/11/23 12:36:32 +01:00 Add Patch FEDORA-EPEL-2016-f74772a384
2022/11/23 12:36:32 +01:00 Add Patch FEDORA-EPEL-2022-724e9212ca
2022/11/23 12:36:32 +01:00 Add Patch FEDORA-EPEL-2022-a19a501da4
2022/11/23 12:36:33 +01:00 Add Patch FEDORA-EPEL-2022-a06d5c7af1
2022/11/23 12:36:33 +01:00 Add Patch FEDORA-EPEL-2022-b6e7cc561b
2022/11/23 12:36:33 +01:00 Add Patch FEDORA-EPEL-2018-ffb901cd33
2022/11/23 12:36:34 +01:00 Add Patch FEDORA-EPEL-2017-cb6ae5d6d4
2022/11/23 12:36:36 +01:00 Add Patch FEDORA-EPEL-2017-fe6485afd2
2022/11/23 12:36:37 +01:00 Add Patch FEDORA-EPEL-2016-fc4294ee35
2022/11/23 12:36:38 +01:00 Add Patch FEDORA-EPEL-2019-f5c0ca257e
2022/11/23 12:36:40 +01:00 Add Patch FEDORA-EPEL-2017-eb91ec0878
2022/11/23 12:36:40 +01:00 Add Patch FEDORA-EPEL-2016-f4b0b2cd84
2022/11/23 12:36:43 +01:00 Add Patch FEDORA-EPEL-2018-befecdd08e                                                                                                   
2022/11/23 12:36:46 +01:00     Syncing 4 new patch(es) to channel.                                                                                                 
2022/11/23 12:36:47 +01:00   Regenerating bootstrap repositories.                                                                                                  
2022/11/23 12:36:58 +01:00   Updating overview of 17 systems               
```

### Steps to reproduce

Wait for regular repo synchronisation to occur.  

Error bell gets highlighted:

![image](https://user-images.githubusercontent.com/4052275/203568360-ca18d6f3-6ce1-4531-a2c4-26e4d4e0355b.png)

### Uyuni version

```bash
2022.11
```

### Uyuni proxy version (if used)

```bash
N/A
```

**Comment by tacki** [comment]
I have the exact same issue with all installed repositories (CentOS 7, AlmaLinux 8, AlmaLinux9)

A manual sync on the console fails too:

```
# spacewalk-repo-sync -c almalinux9-x86_64
08:49:02 ======================================
08:49:02 | Channel: almalinux9-x86_64
08:49:02 ======================================
08:49:02 Sync of channel started.
Retrieving repository 'almalinux9-x86_64' metadata ...................................................................................................................................................................................................................................................................[done]
Building repository 'almalinux9-x86_64' cache ........................................................................................................................................................................................................................................................................[done]
All repositories have been refreshed.
08:49:05
08:49:05   Importing comps file 944d17156737e57054a0b425fcd38263438275c6f50c24e4766e1b43f256416a-comps.xml.
08:49:05   Renaming non-standard filename 944d17156737e57054a0b425fcd38263438275c6f50c24e4766e1b43f256416a-comps.xml to comps.xml.
08:49:05 *** NOTE: Importing comps file for the channel 'almalinux9-x86_64'. Previous comps will be discarded.
08:49:05 Repo URL: https://mirrors.almalinux.org/mirrorlist/9/baseos
08:49:05     Packages in repo:              1202
08:49:13     No new packages to sync.
08:49:13
08:49:13   Patches in repo: 56.
08:49:15     No new patch to sync.
08:49:15   Updating overview of 4 systems
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 299, in _execute_wrapper
    retval = function(*p, **kw)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/sql_base.py", line 182, in _execute
    return self._execute_(args, kwargs)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 322, in _execute_
    self._real_cursor.execute(self.sql, params)
psycopg2.errors.UndefinedTable: missing FROM-clause entry for table "c"
LINE 4:         coalesce(c.org_id, 1),
                         ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/spacewalk-repo-sync", line 286, in <module>
    sys.exit(abs(main() or 0))
  File "/usr/bin/spacewalk-repo-sync", line 269, in main
    elapsed_time, channel_ret_code = sync.sync()
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 705, in sync
    self.update_servers()
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 739, in update_servers
    taskomatic.add_to_system_overview_update_queue(row["id"])
  File "/usr/lib/python3.6/site-packages/spacewalk/server/taskomatic.py", line 103, in add_to_system_overview_update_queue
    h.execute(sid=sid)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/sql_base.py", line 150, in execute
    return self._execute_wrapper(self._execute, *p, **kw)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 309, in _execute_wrapper
    raise sql_base.SQLStatementPrepareError(str(self.dbh), e.pgerror, self.sql)
spacewalk.server.rhnSQL.sql_base.SQLStatementPrepareError: ('ERROR:  missing FROM-clause entry for table "c"\nLINE 4:         coalesce(c.org_id, 1),\n                         ^\n', "<connection object at 0x7fc862886a08; dsn: 'user=uyuni password=xxx dbname=uyuni', closed: 0>", "\n    INSERT INTO rhnTaskQueue (org_id, task_name, task_data, priority, earliest)\n    VALUES (\n        coalesce(c.org_id, 1),\n        'update_system_overview',\n        %(sid)s,\n        0,\n        current_timestamp\n    )\n    ")
```

**Comment by mcalmer** [comment]
@cbosdo maybe you want to have a look here?

**Comment by bigmike-19** [comment]
Hello, 

We are also experiencing the issue with the syncs failing, since upgrading to 2022.11:

 File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/sql_base.py", line 182, in _execute
    return self._execute_(args, kwargs)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 322, in _execute_
    self._real_cursor.execute(self.sql, params)
psycopg2.errors.UndefinedTable: missing FROM-clause entry for table "c"
LINE 4:         coalesce(c.org_id, 1),
                         ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/spacewalk-repo-sync", line 286, in <module>
    sys.exit(abs(main() or 0))
  File "/usr/bin/spacewalk-repo-sync", line 269, in main
    elapsed_time, channel_ret_code = sync.sync()
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 705, in sync
    self.update_servers()
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 739, in update_servers
    taskomatic.add_to_system_overview_update_queue(row["id"])
  File "/usr/lib/python3.6/site-packages/spacewalk/server/taskomatic.py", line 103, in add_to_system_overview_update_queue
    h.execute(sid=sid)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/sql_base.py", line 150, in execute
    return self._execute_wrapper(self._execute, *p, **kw)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 309, in _execute_wrapper
    raise sql_base.SQLStatementPrepareError(str(self.dbh), e.pgerror, self.sql)
spacewalk.server.rhnSQL.sql_base.SQLStatementPrepareError: ('ERROR:  missing FROM-clause entry for table "c"\nLINE 4:         coalesce(c.org_id, 1),\n                         ^\n', "<connection object at 0x7f19d4db6a08; dsn: 'user=uyuni password=xxx dbname=uyuni', closed: 0>", "\n    INSERT INTO rhnTaskQueue (org_id, task_name, task_data, priority, earliest)\n    VALUES (\n        coalesce(c.org_id, 1),\n        'update_system_overview',\n        %(sid)s,\n        0,\n        current_timestamp\n    )\n    ")

Thanks, 
Mike

**Comment by juliogonzalez** [comment]
For the reporters: did you see any problems during the call to `zypper up`?

If you migrated from < 2022.10, did you run the command to allow vendor changes, as specified at the release notes?

**Comment by digdilem** [comment]
Update: None that I noticed. Attached is my zypper.log
[uyuni-zypper-log.txt](https://github.com/uyuni-project/uyuni/files/10085060/uyuni-zypper-log.txt)
  in case it's useful and I did miss something

I run vendor changes when I updated to 2022.10

` 2022-11-02 12:16:34 zypper up --allow-vendor-change`

**Comment by juliogonzalez** [comment]
I can't find anything evident at the zypper log.... but I just remembered the schema migration runs during the server startup.

But I guess you didn't see any error there, so this could be a problem on one of the store procedures, not the migration itself.

**Comment by juliogonzalez** [comment]
BTW, I am curious: does this only happen with RHEL-like systems? So far I don't see anyone that reported the same on SLE-like or Debian-lile systems.

**Comment by juliogonzalez** [comment]
A patch with the fix for this problem will be released tomorrow, most likely in the morning (CET)

Stay tuned! :-)

**Comment by digdilem** [comment]
Good work all, look forwards to the fix

**Comment by digdilem** [comment]
Thanks for the patch, very quick response. 

I've applied that this morning and forced a manual sync and there were no immediate errors, so a tentative thumbs-up. 

However, I'd like to leave it over the weekend to pick all the scheduled syncs before closing this. 

Thanks!

**Comment by juliogonzalez** [comment]
Thanks @digdilem

For everyone else reading the bug, patch is now released: https://lists.opensuse.org/archives/list/announce@lists.uyuni-project.org/thread/C4H5RSOST43NUNXJS37B2I6DST4YBFJB/

**Comment by digdilem** [comment]
Pleased to report that after a weekend of schduled repo syncing, I had only one failure which was a perfectly legitimate network failure. This issue appears to be resolved, at least for us, so am closing this report - thanks for the prompt work.
