### ISSUE TITLE
reposync failing

### ISSUE THREAD

**Issue by oddyutza** [uyuni-project/uyuni#6228]
### Problem description

I've noticed that reposync is failing ( but it worked perfectly when the repo's were added a few daya ago )
log snippet 
07:56:58 Repo URL: http://archive.ubuntu.com/ubuntu/dists/focal-security/main/binary-amd64/
07:56:58     Packages in repo:             10173
07:57:24     No new packages to sync.
07:57:24 
07:57:24   Patches in repo: 0.
07:57:24   Updating overview of 10 systems
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 299, in _execute_wrapper
    retval = function(*p, **kw)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/sql_base.py", line 182, in _execute
    return self._execute_(args, kwargs)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 322, in _execute_
    self._real_cursor.execute(self.sql, params)
psycopg2.errors.UndefinedTable: missing FROM-clause entry for table "c"
LINE 4:         coalesce(c.org_id, 1),
                         ^

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/spacewalk-repo-sync", line 286, in <module>
    sys.exit(abs(main() or 0))
  File "/usr/bin/spacewalk-repo-sync", line 269, in main
    elapsed_time, channel_ret_code = sync.sync()
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 705, in sync
    self.update_servers()
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 739, in update_servers
    taskomatic.add_to_system_overview_update_queue(row["id"])
  File "/usr/lib/python3.6/site-packages/spacewalk/server/taskomatic.py", line 103, in add_to_system_overview_update_queue
    h.execute(sid=sid)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/sql_base.py", line 150, in execute
    return self._execute_wrapper(self._execute, *p, **kw)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 309, in _execute_wrapper
    raise sql_base.SQLStatementPrepareError(str(self.dbh), e.pgerror, self.sql)
spacewalk.server.rhnSQL.sql_base.SQLStatementPrepareError: ('ERROR:  missing FROM-clause entry for table "c"\nLINE 4:         coalesce(c.org_id, 1),\n                         ^\n', "<connection object at 0x7f47d118aa08; dsn: 'user=uyuni password=xxx dbname=uyuni', closed: 0>", "\n    INSERT INTO rhnTaskQueue (org_id, task_name, task_data, priority, earliest)\n    VALUES (\n        coalesce(c.org_id, 1),\n        'update_system_overview',\n        %(sid)s,\n        0,\n        current_timestamp\n    )\n    ")

postgresql
postgresql-server-14-150400.4.3.88.noarch

### Steps to reproduce

1.
2.
3.
...
1. add a repo
2. manual sync a repo - all ok ( only first time )
3. wait for cobbler to take action - failed
4. tray to sync again manually - failed

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2022.11-220400.193.4.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1,4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2022.11-220400.193.4.uyuni2.src
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

**Comment by gabardyne** [comment]
Hello,
Exact same error for me.
I've updated from 2022.05 to 2022.11

**Comment by oddyutza** [comment]
can be fixed by replacing /usr/lib/python3.6/site-packages/spacewalk/server/taskomatic.py with https://github.com/uyuni-project/uyuni/blob/master/python/spacewalk/server/taskomatic.py

**Comment by gabardyne** [comment]
Thanks!!
Works perfectly
