### ISSUE TITLE
After upgrade from 2022.08 to 2022.11, some repo syncs are throwing exceptions after completion

### ISSUE THREAD

**Issue by gabjef** [uyuni-project/uyuni#6297]
### Problem description

After upgrade from 2022.08 to 2022.11, some repo syncs are throwing exceptions
I have included a python stack trace example for CentOS 7
Repo syncs were working fine before the 2022.11 upgrade

### Steps to reproduce

1. Sync a repo

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2022.11-220400.193.4.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2022.11-220400.193.4.uyuni2.src
Summary        : Uyuni Server
```

### Uyuni proxy version (if used)

```bash
N/A
```

### Useful logs

```bash
Error syncing the channel: CentOS 7 (x86_64)
Command '[/usr/bin/spacewalk-repo-sync, --channel, centos7-x86_64, --type, yum, --non-interactive]' exited with error code 1: Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 299, in _execute_wrapper
retval = function(*p, **kw)
File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/sql_base.py", line 182, in _execute
return self._execute_(args, kwargs)
File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 322, in _execute_
self._real_cursor.execute(self.sql, params)
psycopg2.errors.UndefinedTable: missing FROM-clause entry for table "c"
LINE 4: coalesce(c.org_id, 1),
^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/bin/spacewalk-repo-sync", line 286, in
sys.exit(abs(main() or 0))
File "/usr/bin/spacewalk-repo-sync", line 269, in main
elapsed_time, channel_ret_code = sync.sync()
File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 705, in sync
self.update_servers()
File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 739, in update_servers
taskomatic.add_to_system_overview_update_queue(row["id"])
File "/usr/lib/python3.6/site-packages/spacewalk/server/taskomatic.py", line 103, in add_to_system_overview_update_queue
h.execute(sid=sid)
File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/sql_base.py", line 150, in execute
return self._execute_wrapper(self._execute, *p, **kw)
File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 309, in _execute_wrapper
raise sql_base.SQLStatementPrepareError(str(self.dbh), e.pgerror, self.sql)
spacewalk.server.rhnSQL.sql_base.SQLStatementPrepareError: ('ERROR: missing FROM-clause entry for table "c"\nLINE 4: coalesce(c.org_id, 1),\n ^\n', "", "\n INSERT INTO rhnTaskQueue (org_id, task_name, task_data, priority, earliest)\n VALUES (\n coalesce(c.org_id, 1),\n 'update_system_overview',\n %(sid)s,\n 0,\n current_timestamp\n )\n ")
```

**Comment by aaannz** [comment]
This seems like duplicate of https://github.com/uyuni-project/uyuni/issues/6228 and fixed by https://github.com/uyuni-project/uyuni/commit/6778f1ffe0870648d835e81f78843792ef373ce8

Can you config fix from the issue works for you?

**Comment by gabjef** [comment]
@aaannz Thanks for the response. Yes, that commit fixed this issue. Closing this issue.
