### ISSUE TITLE
Uyuni 2022.11: Reposync failed cause to missing FROM-clause

### ISSUE THREAD

**Issue by LordofAgents** [uyuni-project/uyuni#6312]
### Problem description

Hey all, 
since the update to Uyuni 2022.11, I am not able to sync Debian or openSUSE 15.4 Channel. I am not sure if the Database is broken or something else is wrong.
This error got already reported on Matrix by Gorf79, but he didnt opened an Bug Report.

### Steps to reproduce

1. Add e.g. opensuse Leap 15.4 Base Channel
2. `spacewalk-repo-sync --p opensuse_leap15_4-x86_64`

### Uyuni version

```bash
uyuni:~ # zypper info Uyuni-Server-release 
Loading repository data...
Reading installed packages...


Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2022.11-220400.193.4.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2022.11-220400.193.4.uyuni2.src
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

### Uyuni proxy version (if used)

```bash
Information for package Uyuni-Proxy-release:
--------------------------------------------
Repository     : Uyuni Proxy Stable for openSUSE Leap 15.4 (x86_64)
Name           : Uyuni-Proxy-release
Version        : 2022.11-220400.193.3.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Proxy-release-2022.11-220400.193.3.uyuni2.src
Summary        : Uyuni Proxy
Description    : 
    Uyuni Proxies extend large and/or geographically
    dispersed Uyuni environments to reduce load on the Uyuni
    Server, lower bandwidth needs, and provide faster local
    updates.
```

### Useful logs

```bash
spacewalk-repo-sync --p opensuse_leap15_4-x86_64
00:46:16 ======================================
00:46:16 | Channel: opensuse_leap15_4-x86_64
00:46:16 ======================================
00:46:16 Sync of channel started.
Retrieving repository 'opensuse_leap15_4-x86_64' metadata ...............................................................................................................................................[done]
Building repository 'opensuse_leap15_4-x86_64' cache ....................................................................................................................................................[done]All repositories have been refreshed.
00:46:30 Repo URL: http://download.opensuse.org/distribution/leap/15.4/repo/oss/
00:46:30     Packages in repo:             96026
00:48:10     No new packages to sync.
00:48:10 
00:48:10   Patches in repo: 0.
00:48:11 
00:48:11   Importing mediaproducts file products.
00:48:11 *** NOTE: Importing mediaproducts file for the channel 'opensuse_leap15_4-x86_64'. Previous mediaproducts will be discarded.
00:50:58   Updating overview of 13 systems
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 299, in _execute_wrapper
    retval = function(*p, **kw)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/sql_base.py", line 182, in _execute
    return self._execute_(args, kwargs)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 322, in _execute_
    self._real_cursor.execute(self.sql, params)
psycopg2.errors.UndefinedTable: missing FROM-clause entry for table "c"
LINE 4:         coalesce(c.org_id, 1),
                         ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/spacewalk-repo-sync", line 286, in <module>
    sys.exit(abs(main() or 0))
  File "/usr/bin/spacewalk-repo-sync", line 269, in main
    elapsed_time, channel_ret_code = sync.sync()
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 705, in sync
    self.update_servers()
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 739, in update_servers
    taskomatic.add_to_system_overview_update_queue(row["id"])
  File "/usr/lib/python3.6/site-packages/spacewalk/server/taskomatic.py", line 103, in add_to_system_overview_update_queue
    h.execute(sid=sid)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/sql_base.py", line 150, in execute
    return self._execute_wrapper(self._execute, *p, **kw)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 309, in _execute_wrapper
    raise sql_base.SQLStatementPrepareError(str(self.dbh), e.pgerror, self.sql)
spacewalk.server.rhnSQL.sql_base.SQLStatementPrepareError: ('ERROR:  missing FROM-clause entry for table "c"\nLINE 4:         coalesce(c.org_id, 1),\n                         ^\n', "<connection object at 0x7f07c3fc2a08; dsn: 'user=uyuni password=xxx dbname=uyuni', closed: 0>", "\n    INSERT INTO rhnTaskQueue (org_id, task_name, task_data, priority, earliest)\n    VALUES (\n        coalesce(c.org_id, 1),\n        'update_system_overview',\n        %(sid)s,\n        0,\n        current_timestamp\n    )\n    ")
```

### Additional information

This error doesmt seem to get logged in /var/log/rhn/reposync/channel.log, which is weird.

If you need any other information, just ask.

Thank you!

**Comment by MaxHerrmannSVA** [comment]
I've got the same error.
But only on those channels where the "System list refactor"-change would update the overview of some servers.

The repo sync itself still works.

**Comment by mbussolotto** [comment]
looks like a duplicate of https://github.com/uyuni-project/uyuni/issues/6297 . Can you please check if https://github.com/uyuni-project/uyuni/commit/6778f1ffe0870648d835e81f78843792ef373ce8 is working also for you? Thanks

**Comment by MaxHerrmannSVA** [comment]
The Sync is now working without any errors.
I guess we can also close the issue now.

Thank you!
