### ISSUE TITLE
salt-minion errors messages

### ISSUE THREAD

**Issue by Zayan1221** [uyuni-project/uyuni#6330]
# Question
AttributeError: 'dict' object has no attribute 'append'
Aug 03 11:46:21 nmscsponsqa01 salt-minion[16922]: [CRITICAL] The beacon errored:
Aug 03 11:46:21 nmscsponsqa01 salt-minion[16922]: Traceback (most recent call last):
Aug 03 11:46:21 nmscsponsqa01 salt-minion[16922]: File "/usr/lib/python3.6/site-packages/salt/minion.py", line 2954, in handle_beacons
Aug 03 11:46:21 nmscsponsqa01 salt-minion[16922]: beacons = self.process_beacons(self.functions)
Aug 03 11:46:21 nmscsponsqa01 salt-minion[16922]: File "/usr/lib/python3.6/site-packages/salt/minion.py", line 517, in process_beacons
Aug 03 11:46:21 nmscsponsqa01 salt-minion[16922]: b_conf, self.opts["grains"]
Aug 03 11:46:21 nmscsponsqa01 salt-minion[16922]: File "/usr/lib/python3.6/site-packages/salt/beacons/__init__.py", line 74, in process
Aug 03 11:46:21 nmscsponsqa01 salt-minion[16922]: b_config[mod].append({"_beacon_name": mod})
Aug 03 11:46:21 nmscsponsqa01 salt-minion[16922]: AttributeError: 'dict' object has no attribute 'append'
_What do you want to know about Uyuni?_

## Version of Uyuni Server and Proxy (if used)
2022.06
`zypper info Uyuni-Server-release` _and_ `zypper info Uyuni-Proxy-release` _(if used)_
uyunisuse:~ # zypper info Uyuni-Server-release
Retrieving repository 'OpenSUSE15 x64 base' metadata ...............................................................................................................................................[done]
Building repository 'OpenSUSE15 x64 base' cache ....................................................................................................................................................[done]
Loading repository data...
Warning: Repository 'Update repository of openSUSE Backports' appears to be outdated. Consider using a different mirror or server.
Warning: Repository 'Main Update Repository' appears to be outdated. Consider using a different mirror or server.
Reading installed packages...

Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2022.10-220400.191.2.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : out-of-date (version 2022.06-183.9.uyuni2 installed)
Source package : Uyuni-Server-release-2022.10-220400.191.2.uyuni2.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.

uyunisuse:~ # zypper info Uyuni-Proxy-release
Loading repository data...
Warning: Repository 'Update repository of openSUSE Backports' appears to be outdated. Consider using a different mirror or server.
Warning: Repository 'Main Update Repository' appears to be outdated. Consider using a different mirror or server.
Reading installed packages...

package 'Uyuni-Proxy-release' not found.
uyunisuse:~ #

**Comment by mbussolotto** [comment]
can you please try to update to the latest version? there's something that looks not ok:
```
Version : 2022.10-220400.191.2.uyuni2
```
but 
```
Status : out-of-date (version 2022.06-183.9.uyuni2 installed)
```

**Comment by Zayan1221** [comment]
I have tried to update the version, but the WebGUI does not come back online - 404 Error
