### ISSUE TITLE
Can not bootstrap salt client

### ISSUE THREAD

**Issue by bamorrow** [uyuni-project/uyuni#6368]
### Problem description

This is a new install of Uyuni.

Attempting to bootstrap a salt client fail with the message:
rhn_web_ui.log:2022-12-16 15:40:02,729 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-5] ERROR com.redhat.rhn.manager.action.ActionManager - Unable to run action on a system without either Salt or Management entitlement, id 1000010076

System never shows up in system list.

Traced it down to table rhnusergroupmembers are not being set.  If I actually add them system by a manual import of a row to this table, the systems will show up in the system list.  

### Steps to reproduce

1.
2.
3.
...

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2022.11-220400.193.4.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2022.11-220400.193.4.uyuni2.src
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

### Useful logs

```bash
rhn_web_ui.log:	at com.redhat.rhn.manager.action.ActionManager.checkSaltOrManagementEntitlement(ActionManager.java:1808) ~[rhn.jar:?]
rhn_web_ui.log:2022-12-16 15:40:02,722 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-5] ERROR com.suse.manager.reactor.messaging.RegistrationUtils - Error generating Salt files for minion 'xxxxxx.xxxxx.xxxxx':Config feature needs to be enabled on the server for handling Config Management. The provided server [com.redhat.rhn.domain.server.MinionServer@76488baf[id=1000010076,org=com.redhat.rhn.domain.org.Org@58746f5b[id=1,name=NSSL],name=xxxxxx.xxxxxx.xxxxxx,description=<null>,machineId=8a071dc2db0348e4843dae53450e3961,minionId=xxxxxx.xxxxxx.xxxxxx]] does not have have this enabled. Add provisioning capabilities to the system to enable this..
rhn_web_ui.log:2022-12-16 15:40:02,729 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-5] ERROR com.redhat.rhn.manager.action.ActionManager - Unable to run action on a system without either Salt or Management entitlement, id 1000010076
rhn_web_ui.log:com.redhat.rhn.manager.MissingEntitlementException: Management or Salt
rhn_web_ui.log:	at com.redhat.rhn.manager.action.ActionManager.checkSaltOrManagementEntitlement(ActionManager.java:1808) ~[rhn.jar:?]
```

**Comment by bamorrow** [comment]
Though I would add that I just the upgrade to 2022.12 version and have same issue

**Comment by bamorrow** [comment]
Is there any more info on this I need to provide to help find the cause?

**Comment by bamorrow** [comment]
Thought I would update this.  I tried the latest upgrade 2023.01 on this system and still had same issue. I decided just to blow that VM away and try again with a fresh install of 2023.01.  It seem to be working now.
