### ISSUE TITLE
Unexpected Error : After adding Uyuni Proxy 

### ISSUE THREAD

**Issue by theonlykl** [uyuni-project/uyuni#6393]
### Problem description

Adding a Uyuni Proxy results in the banner displayed below on login  : 

![image](https://user-images.githubusercontent.com/1879474/209483658-e0cc801b-b9aa-4a8d-b031-9fc5901ecc00.png)

Looking at the logs further it indicates the following: 

`2022-12-25 17:43:51,036 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-2] ERROR com.redhat.rhn.common.db.datasource.CachedStatement - Error while processing cached statement sql: SELECT  DISTINCT S.id,
                   S.name,
                   SI.server_id AS MGR_SERVER,
                   PI.server_id AS PROXY,
                   TO_CHAR(Sinfo.checkin, 'YYYY-MM-DD HH24:MI:SS') AS LAST_CHECKIN,
                   SO.SECURITY_ERRATA, SO.BUG_ERRATA, SO.ENHANCEMENT_ERRATA, SO.LOCKED,
                   SO.OUTDATED_PACKAGES, SO.SERVER_NAME, SO.SERVER_ADMINS, SO.GROUP_COUNT,
                   SO.MODIFIED, SO.CHANNEL_LABELS, SO.HISTORY_COUNT, SO.LAST_CHECKIN_DAYS_AGO,
                   SO.PENDING_UPDATES, SO.OS, SO.RELEASE, SO.SERVER_ARCH_NAME, SO.LAST_CHECKIN,
                  (SELECT 1
                     FROM rhnServerFeaturesView SFV
                    WHERE SFV.server_id = S.id
                      AND SFV.label = 'ftr_system_grouping') AS selectable
    FROM rhnServerInfo SInfo, rhnUserServerPerms USP, rhnServer S
    LEFT OUTER JOIN suseMgrServerInfo SI ON S.id = SI.server_id
    LEFT OUTER JOIN rhnProxyInfo PI ON S.id = PI.server_id
    LEFT OUTER JOIN rhnServerOverview SO ON S.id = SO.server_id
   WHERE  USP.user_id = ?
     AND  S.id = USP.server_id
     AND  Sinfo.server_id = S.id
     AND ((SELECT count (*) FROM rhnServerErrataTypeView setv WHERE setv.server_id = s.id) > 0)
   ORDER BY  SO.SECURITY_ERRATA DESC, SO.BUG_ERRATA DESC, SO.ENHANCEMENT_ERRATA DESC, S.name ASC`

If I remove the proxy this error goes away.   

### Steps to reproduce

1.  Build and attach a Uyuni Proxy following install guide. 
2. After add of proxy error is reported after every login to Uyuni (along with the error in the logs)
3. Only occurs after proxy add, if proxy is removed error goes away.   Reproducible on fresh install of 2022.12 and 2022.11 (have a older 2022.08 install, but havent had a need for a proxy there yet)

### Uyuni version

```bash
`
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : @System
Name           : Uyuni-Server-release
Version        : 2022.11-220400.193.4.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2022.11-220400.193.4.uyuni2.src
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.

`

**Also noticed it reports 2022.11, but i am fully updated to 2022.12
```

### Useful logs

```bash
`
2022-12-24 22:28:22,587 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-6] ERROR com.redhat.rhn.frontend.action.common.DownloadFile - //srv/www/htdocs/pub/distros/opensuse-leap-micro/driverupdate Not Found .. 404!
2022-12-24 22:30:34,799 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-4] ERROR com.redhat.rhn.frontend.action.common.DownloadFile - //srv/www/htdocs/pub/distros/opensuse-leap-micro/add_on_products.xml Not Found .. 404!
2022-12-24 22:30:34,822 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-5] ERROR com.redhat.rhn.frontend.action.common.DownloadFile - //srv/www/htdocs/pub/distros/opensuse-leap-micro/add_on_products Not Found .. 404!
2022-12-24 22:30:48,948 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-2] ERROR com.redhat.rhn.frontend.action.common.DownloadFile - //srv/www/htdocs/pub/distros/opensuse-leap-micro/suse/setup/slide/txt/en_US/directory.yast Not Found .. 404!
2022-12-24 22:30:48,976 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-10] ERROR com.redhat.rhn.frontend.action.common.DownloadFile - //srv/www/htdocs/pub/distros/opensuse-leap-micro/suse/setup/slide/pic/directory.yast Not Found .. 404!
2022-12-24 22:30:49,010 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-8] ERROR com.redhat.rhn.frontend.action.common.DownloadFile - //srv/www/htdocs/pub/distros/opensuse-leap-micro/docu/directory.yast Not Found .. 404!
2022-12-24 22:30:49,016 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-9] ERROR com.redhat.rhn.frontend.action.common.DownloadFile - //srv/www/htdocs/pub/distros/opensuse-leap-micro/docu/directory.yast Not Found .. 404!
2022-12-24 22:30:49,022 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-6] ERROR com.redhat.rhn.frontend.action.common.DownloadFile - //srv/www/htdocs/pub/distros/opensuse-leap-micro/docu/directory.yast Not Found .. 404!
2022-12-24 22:44:58,986 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-7] ERROR com.redhat.rhn.frontend.action.common.DownloadFile - //srv/www/htdocs/pub/distros/opensuse-leap-micro/content Not Found .. 404!
2022-12-24 22:45:03,905 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-8] ERROR com.redhat.rhn.frontend.action.common.DownloadFile - //srv/www/htdocs/pub/distros/opensuse-leap-micro/license.tar.gz Not Found .. 404!
2022-12-24 22:45:03,911 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-6] ERROR com.redhat.rhn.frontend.action.common.DownloadFile - //srv/www/htdocs/pub/distros/opensuse-leap-micro/media.1/info.txt Not Found .. 404!
2022-12-24 22:45:03,915 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-2] ERROR com.redhat.rhn.frontend.action.common.DownloadFile - //srv/www/htdocs/pub/distros/opensuse-leap-micro/part.info Not Found .. 404!
2022-12-24 22:45:03,920 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-1] ERROR com.redhat.rhn.frontend.action.common.DownloadFile - //srv/www/htdocs/pub/distros/opensuse-leap-micro/README.BETA Not Found .. 404!
2022-12-24 22:45:03,924 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-4] ERROR com.redhat.rhn.frontend.action.common.DownloadFile - //srv/www/htdocs/pub/distros/opensuse-leap-micro/driverupdate Not Found .. 404!
2022-12-24 22:46:27,832 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-9] ERROR com.redhat.rhn.frontend.action.common.DownloadFile - //srv/www/htdocs/pub/distros/opensuse-leap-micro/add_on_products.xml Not Found .. 404!
2022-12-24 22:46:27,871 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-7] ERROR com.redhat.rhn.frontend.action.common.DownloadFile - //srv/www/htdocs/pub/distros/opensuse-leap-micro/add_on_products Not Found .. 404!
2022-12-24 22:46:42,114 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-8] ERROR com.redhat.rhn.frontend.action.common.DownloadFile - //srv/www/htdocs/pub/distros/opensuse-leap-micro/suse/setup/slide/txt/en_US/directory.yast Not Found .. 404!
2022-12-24 22:46:42,145 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-6] ERROR com.redhat.rhn.frontend.action.common.DownloadFile - //srv/www/htdocs/pub/distros/opensuse-leap-micro/suse/setup/slide/pic/directory.yast Not Found .. 404!
2022-12-24 22:46:42,179 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-2] ERROR com.redhat.rhn.frontend.action.common.DownloadFile - //srv/www/htdocs/pub/distros/opensuse-leap-micro/docu/directory.yast Not Found .. 404!
2022-12-24 22:46:42,185 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-1] ERROR com.redhat.rhn.frontend.action.common.DownloadFile - //srv/www/htdocs/pub/distros/opensuse-leap-micro/docu/directory.yast Not Found .. 404!
2022-12-24 22:46:42,190 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-4] ERROR com.redhat.rhn.frontend.action.common.DownloadFile - //srv/www/htdocs/pub/distros/opensuse-leap-micro/docu/directory.yast Not Found .. 404!
com.redhat.rhn.common.util.MethodNotFoundException: Could not find method called: setProxy in class: com.redhat.rhn.frontend.dto.SystemOverview with params: [type: java.lang.Long, value: 1000010021]
	at com.redhat.rhn.common.util.MethodUtil.callMethod(MethodUtil.java:197) ~[rhn.jar:?]
	at com.redhat.rhn.common.db.datasource.CachedStatement.addToObject(CachedStatement.java:797) ~[rhn.jar:?]
	at com.redhat.rhn.common.db.datasource.CachedStatement.processResultSet(CachedStatement.java:660) ~[rhn.jar:?]
	at com.redhat.rhn.common.db.datasource.CachedStatement.execute(CachedStatement.java:505) ~[rhn.jar:?]
	at com.redhat.rhn.common.db.datasource.CachedStatement.lambda$executeChecking$1(CachedStatement.java:456) ~[rhn.jar:?]
	at org.hibernate.jdbc.WorkExecutor.executeReturningWork(WorkExecutor.java:55) [hibernate5_hibernate-core.jar:5.3.25.Final]
	at org.hibernate.internal.SessionImpl$2.accept(SessionImpl.java:2421) [hibernate5_hibernate-core.jar:5.3.25.Final]
	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.coordinateWork(JdbcCoordinatorImpl.java:306) [hibernate5_hibernate-core.jar:5.3.25.Final]
	at org.hibernate.internal.SessionImpl.doWork(SessionImpl.java:2428) [hibernate5_hibernate-core.jar:5.3.25.Final]
	at org.hibernate.internal.SessionImpl.doReturningWork(SessionImpl.java:2424) [hibernate5_hibernate-core.jar:5.3.25.Final]
	at com.redhat.rhn.common.db.datasource.CachedStatement.doWithStolenConnection(CachedStatement.java:909) [rhn.jar:?]
	at com.redhat.rhn.common.db.datasource.CachedStatement.executeChecking(CachedStatement.java:454) [rhn.jar:?]
	at com.redhat.rhn.common.db.datasource.CachedStatement.internalExecute(CachedStatement.java:337) [rhn.jar:?]
	at com.redhat.rhn.common.db.datasource.CachedStatement.execute(CachedStatement.java:273) [rhn.jar:?]
	at com.redhat.rhn.common.db.datasource.SelectMode.execute(SelectMode.java:96) [rhn.jar:?]
	at com.redhat.rhn.manager.BaseManager.makeDataResult(BaseManager.java:56) [rhn.jar:?]
	at com.redhat.rhn.manager.BaseManager.makeDataResult(BaseManager.java:76) [rhn.jar:?]
	at com.redhat.rhn.manager.system.SystemManager.mostCriticalSystems(SystemManager.java:1045) [rhn.jar:?]
	at com.redhat.rhn.frontend.action.renderers.CriticalSystemsRenderer.render(CriticalSystemsRenderer.java:46) [rhn.jar:?]
	at com.redhat.rhn.frontend.action.renderers.BaseFragmentRenderer.renderAsync(BaseFragmentRenderer.java:50) [rhn.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.directwebremoting.impl.CreatorModule$1.doFilter(CreatorModule.java:178) [dwr.jar:?]
	at org.directwebremoting.impl.CreatorModule.executeMethod(CreatorModule.java:184) [dwr.jar:?]
	at org.directwebremoting.impl.DefaultRemoter.execute(DefaultRemoter.java:353) [dwr.jar:?]
	at org.directwebremoting.impl.DefaultRemoter.execute(DefaultRemoter.java:306) [dwr.jar:?]
	at org.directwebremoting.dwrp.BaseCallHandler.handle(BaseCallHandler.java:110) [dwr.jar:?]
	at org.directwebremoting.servlet.UrlProcessor.handle(UrlProcessor.java:211) [dwr.jar:?]
	at org.directwebremoting.servlet.UrlProcessor.handle(UrlProcessor.java:185) [dwr.jar:?]
	at org.directwebremoting.servlet.DwrServlet.doPost(DwrServlet.java:144) [dwr.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) [tomcat-servlet-4.0-api.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-servlet-4.0-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:9.0.36]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.36]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-websocket.jar:9.0.36]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.36]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.36]
	at com.opensymphony.module.sitemesh.filter.PageFilter.parsePage(PageFilter.java:142) [sitemesh.jar:?]
	at com.opensymphony.module.sitemesh.filter.PageFilter.doFilter(PageFilter.java:58) [sitemesh.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.36]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.36]
	at com.redhat.rhn.frontend.servlets.LocalizedEnvironmentFilter.doFilter(LocalizedEnvironmentFilter.java:69) [rhn.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.36]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.36]
	at com.redhat.rhn.frontend.servlets.EnvironmentFilter.doFilter(EnvironmentFilter.java:100) [rhn.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.36]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.36]
	at com.redhat.rhn.frontend.servlets.SessionFilter.doFilter(SessionFilter.java:56) [rhn.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.36]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.36]
	at com.redhat.rhn.frontend.servlets.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:96) [rhn.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.36]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.36]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [catalina.jar:9.0.36]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.36]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [catalina.jar:9.0.36]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.36]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.36]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690) [catalina.jar:9.0.36]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.36]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.36]
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:432) [tomcat-coyote.jar:9.0.36]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.36]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-coyote.jar:9.0.36]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1591) [tomcat-coyote.jar:9.0.36]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.36]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.36]
	at java.lang.Thread.run(Thread.java:829) [?:?]
2022-12-25 17:43:51,036 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-2] ERROR com.redhat.rhn.common.db.datasource.CachedStatement - Error while processing cached statement sql: SELECT  DISTINCT S.id,
                   S.name,
                   SI.server_id AS MGR_SERVER,
                   PI.server_id AS PROXY,
                   TO_CHAR(Sinfo.checkin, 'YYYY-MM-DD HH24:MI:SS') AS LAST_CHECKIN,
                   SO.SECURITY_ERRATA, SO.BUG_ERRATA, SO.ENHANCEMENT_ERRATA, SO.LOCKED,
                   SO.OUTDATED_PACKAGES, SO.SERVER_NAME, SO.SERVER_ADMINS, SO.GROUP_COUNT,
                   SO.MODIFIED, SO.CHANNEL_LABELS, SO.HISTORY_COUNT, SO.LAST_CHECKIN_DAYS_AGO,
                   SO.PENDING_UPDATES, SO.OS, SO.RELEASE, SO.SERVER_ARCH_NAME, SO.LAST_CHECKIN,
                  (SELECT 1
                     FROM rhnServerFeaturesView SFV
                    WHERE SFV.server_id = S.id
                      AND SFV.label = 'ftr_system_grouping') AS selectable
    FROM rhnServerInfo SInfo, rhnUserServerPerms USP, rhnServer S
    LEFT OUTER JOIN suseMgrServerInfo SI ON S.id = SI.server_id
    LEFT OUTER JOIN rhnProxyInfo PI ON S.id = PI.server_id
    LEFT OUTER JOIN rhnServerOverview SO ON S.id = SO.server_id
   WHERE  USP.user_id = ?
     AND  S.id = USP.server_id
     AND  Sinfo.server_id = S.id
     AND ((SELECT count (*) FROM rhnServerErrataTypeView setv WHERE setv.server_id = s.id) > 0)
   ORDER BY  SO.SECURITY_ERRATA DESC, SO.BUG_ERRATA DESC, SO.ENHANCEMENT_ERRATA DESC, S.name ASC
com.redhat.rhn.common.util.MethodNotFoundException: Could not find method called: setProxy in class: com.redhat.rhn.frontend.dto.SystemOverview with params: [type: java.lang.Long, value: 1000010021]
	at com.redhat.rhn.common.util.MethodUtil.callMethod(MethodUtil.java:197) ~[rhn.jar:?]
	at com.redhat.rhn.common.db.datasource.CachedStatement.addToObject(CachedStatement.java:797) ~[rhn.jar:?]
	at com.redhat.rhn.common.db.datasource.CachedStatement.processResultSet(CachedStatement.java:660) ~[rhn.jar:?]
	at com.redhat.rhn.common.db.datasource.CachedStatement.execute(CachedStatement.java:505) ~[rhn.jar:?]
	at com.redhat.rhn.common.db.datasource.CachedStatement.lambda$executeChecking$1(CachedStatement.java:456) ~[rhn.jar:?]
	at org.hibernate.jdbc.WorkExecutor.executeReturningWork(WorkExecutor.java:55) [hibernate5_hibernate-core.jar:5.3.25.Final]
	at org.hibernate.internal.SessionImpl$2.accept(SessionImpl.java:2421) [hibernate5_hibernate-core.jar:5.3.25.Final]
	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.coordinateWork(JdbcCoordinatorImpl.java:306) [hibernate5_hibernate-core.jar:5.3.25.Final]
	at org.hibernate.internal.SessionImpl.doWork(SessionImpl.java:2428) [hibernate5_hibernate-core.jar:5.3.25.Final]
	at org.hibernate.internal.SessionImpl.doReturningWork(SessionImpl.java:2424) [hibernate5_hibernate-core.jar:5.3.25.Final]
	at com.redhat.rhn.common.db.datasource.CachedStatement.doWithStolenConnection(CachedStatement.java:909) [rhn.jar:?]
	at com.redhat.rhn.common.db.datasource.CachedStatement.executeChecking(CachedStatement.java:454) [rhn.jar:?]
	at com.redhat.rhn.common.db.datasource.CachedStatement.internalExecute(CachedStatement.java:337) [rhn.jar:?]
	at com.redhat.rhn.common.db.datasource.CachedStatement.execute(CachedStatement.java:273) [rhn.jar:?]
	at com.redhat.rhn.common.db.datasource.SelectMode.execute(SelectMode.java:96) [rhn.jar:?]
	at com.redhat.rhn.manager.BaseManager.makeDataResult(BaseManager.java:56) [rhn.jar:?]
	at com.redhat.rhn.manager.BaseManager.makeDataResult(BaseManager.java:76) [rhn.jar:?]
	at com.redhat.rhn.manager.system.SystemManager.mostCriticalSystems(SystemManager.java:1045) [rhn.jar:?]
	at com.redhat.rhn.frontend.action.renderers.CriticalSystemsRenderer.render(CriticalSystemsRenderer.java:46) [rhn.jar:?]
	at com.redhat.rhn.frontend.action.renderers.BaseFragmentRenderer.renderAsync(BaseFragmentRenderer.java:50) [rhn.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.directwebremoting.impl.CreatorModule$1.doFilter(CreatorModule.java:178) [dwr.jar:?]
	at org.directwebremoting.impl.CreatorModule.executeMethod(CreatorModule.java:184) [dwr.jar:?]
	at org.directwebremoting.impl.DefaultRemoter.execute(DefaultRemoter.java:353) [dwr.jar:?]
	at org.directwebremoting.impl.DefaultRemoter.execute(DefaultRemoter.java:306) [dwr.jar:?]
	at org.directwebremoting.dwrp.BaseCallHandler.handle(BaseCallHandler.java:110) [dwr.jar:?]
	at org.directwebremoting.servlet.UrlProcessor.handle(UrlProcessor.java:211) [dwr.jar:?]
	at org.directwebremoting.servlet.UrlProcessor.handle(UrlProcessor.java:185) [dwr.jar:?]
	at org.directwebremoting.servlet.DwrServlet.doPost(DwrServlet.java:144) [dwr.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) [tomcat-servlet-4.0-api.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-servlet-4.0-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:9.0.36]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.36]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-websocket.jar:9.0.36]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.36]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.36]
	at com.opensymphony.module.sitemesh.filter.PageFilter.parsePage(PageFilter.java:142) [sitemesh.jar:?]
	at com.opensymphony.module.sitemesh.filter.PageFilter.doFilter(PageFilter.java:58) [sitemesh.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.36]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.36]
	at com.redhat.rhn.frontend.servlets.LocalizedEnvironmentFilter.doFilter(LocalizedEnvironmentFilter.java:69) [rhn.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.36]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.36]
	at com.redhat.rhn.frontend.servlets.EnvironmentFilter.doFilter(EnvironmentFilter.java:100) [rhn.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.36]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.36]
	at com.redhat.rhn.frontend.servlets.SessionFilter.doFilter(SessionFilter.java:56) [rhn.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.36]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.36]
	at com.redhat.rhn.frontend.servlets.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:96) [rhn.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.36]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.36]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [catalina.jar:9.0.36]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.36]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [catalina.jar:9.0.36]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.36]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.36]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690) [catalina.jar:9.0.36]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.36]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.36]
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:432) [tomcat-coyote.jar:9.0.36]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.36]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-coyote.jar:9.0.36]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1591) [tomcat-coyote.jar:9.0.36]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.36]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.36]
	at java.lang.Thread.run(Thread.java:829) [?:?]

`
```

**Comment by theonlykl** [comment]
Closing this issue: 

I originally recreated this issue in three different environments.   Two of the three environments were still on 2022.11 (including the proxies).   Once i progressed through the upgrade cycles to patch everything to latest greatest (2022.12) this issue has gone away.   

Closing this ill keep a eye on things as I poke the proxies a bit more and report back if there are any issues.
