### ISSUE TITLE
Systems failed to run sync_states

### ISSUE THREAD

**Issue by samcoddington** [uyuni-project/uyuni#6530]
### Problem description

SLES and SLED hosts are failing to apply sync_states, which causes product.installed to fail.  We just upgraded from 2022.08 to 2022.12.  We were seeing this issue prior to the upgrade

### Steps to reproduce

1. Bootstrap system with bootstrap script
2. Accept salt key
3. Wait for initial apply states to run

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2022.11-220400.195.1.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2022.11-220400.195.1.uyuni2.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

### Uyuni proxy version (if used)

```bash
Information for package Uyuni-Proxy-release:
--------------------------------------------
Repository     : Uyuni Proxy Stable
Name           : Uyuni-Proxy-release
Version        : 2022.11-220400.195.1.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Proxy-release-2022.11-220400.195.1.uyuni2.src
Summary        : Uyuni Proxy
Description    :
    Uyuni Proxies extend large and/or geographically
    dispersed Uyuni environments to reduce load on the Uyuni
    Server, lower bandwidth needs, and provide faster local
    updates.
```

### Useful logs

```bash
ID: sync_states
    Function: saltutil.states
        Name: sync_states
      Result: false
     Comment: Failed to run sync_states: 'NoneType' object is not iterable
     Started: 20:16:50.165890
    Duration: 77.78
         SLS: util.syncstates
     Changed: {}
----------
          ID: null
    Function: product.installed
        Name: null
      Result: false
     Comment: One or more requisite failed: util.syncstates.sync_states
     Started: 20:16:50.348894
    Duration: 0.003
         SLS: channels
     Changed: {}
----------
          ID: null
    Function: product.installed
        Name: null
      Result: false
     Comment: One or more requisite failed: util.syncstates.sync_states
     Started: 20:16:50.371540
    Duration: 0.003
         SLS: packages
     Changed: {}
```

**Comment by samcoddington** [comment]
Could this be related to bootstrap repository creation failing?  I'm seeing a pacakge is missing 

`ERROR: package 'python3-ordered-set' not found`

This is happening with SLE 15.3 AND 15.4 bootstrap repositories.  I've confirmed our uyuni client tools repo is up to date.

**Comment by juliogonzalez** [comment]
Looks to me the bootstrap repo errors could be a bug created by https://github.com/uyuni-project/uyuni/commit/7dd5e34c8eda406748f65b7ac8b05c5e036d6bcd (ping @mcalmer)

I checked and:
- on SLES/SLED 15SP4, this package is part of the basesystem module, so that error creating the bootstrap repo should not happen.
- I can't see the package at all on SLES/SLED 15SP3

According to the PR for that commit, seems that package got added because it was needed for the traditional stack, but salt still needs it. I don't see the requirement for salt, so maybe it's a second/third level requirement.

I can't tell for sure if the bootstrap error is related. What's more, it's quite possible you are using already the salt bundle, and in that case the problem is for sure not created by the bootstrap repo creation error.

`rpm -qa|grep salt` on the client will tell you if the bundle is there or not.

But even so, that problem with the states should not happen, so you will need to provide logs from the Uyuni server (check for interesting stuff at `/var/log/rhn` and `/var/og/salt`) and the client (`/var/log/*salt* directories).

Maybe there will be more info about the error there, such as a stack trace that shows where the problem is really happening.

**Comment by samcoddington** [comment]
venv-salt-minion is getting installed on the clients when they bootstrap.  The only thing I'm seeing on the clients is the same kinds of errors 

```
2023-02-09T18:10:11.837850+00:00 hostname salt-minion[62895]: [ERROR   ] Failed to run saltutil.sync_states: 'NoneType' object is not iterable
2023-02-09T18:10:11.838327+00:00 hostname salt-minion[62895]: [ERROR   ] Failed to run sync_states: 'NoneType' object is not iterable
```

On the main Uyuni server, the only logs I see that might be related come from `/var/log/rhn/rhn_web_ui.log`.  This error is happening constantly, not just when trying to apply a state on a the above client.

```
2023-02-09 11:14:23,610 [salt-event-thread-8] ERROR com.suse.manager.webui.services.SaltServerActionService - Error processing Salt job return
java.lang.NullPointerException: null
	at com.suse.manager.reactor.utils.ValueMap.get(ValueMap.java:216) ~[rhn.jar:?]
	at com.suse.manager.reactor.utils.ValueMap.getValueAsString(ValueMap.java:78) ~[rhn.jar:?]
	at com.suse.manager.utils.SaltUtils.handlePackageProfileUpdate(SaltUtils.java:1411) ~[rhn.jar:?]
	at com.suse.manager.utils.SaltUtils.lambda$updateServerAction$25(SaltUtils.java:579) ~[rhn.jar:?]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at com.suse.manager.utils.SaltUtils.updateServerAction(SaltUtils.java:579) ~[rhn.jar:?]
	at com.suse.manager.webui.services.SaltServerActionService.lambda$handleAction$146(SaltServerActionService.java:2662) ~[rhn.jar:?]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at com.suse.manager.webui.services.SaltServerActionService.lambda$handleAction$147(SaltServerActionService.java:2640) ~[rhn.jar:?]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at com.suse.manager.webui.services.SaltServerActionService.handleAction(SaltServerActionService.java:2633) ~[rhn.jar:?]
	at com.suse.manager.reactor.messaging.JobReturnEventMessageAction.lambda$execute$4(JobReturnEventMessageAction.java:134) ~[rhn.jar:?]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at com.suse.manager.reactor.messaging.JobReturnEventMessageAction.lambda$execute$5(JobReturnEventMessageAction.java:133) ~[rhn.jar:?]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at com.suse.manager.reactor.messaging.JobReturnEventMessageAction.execute(JobReturnEventMessageAction.java:133) ~[rhn.jar:?]
	at com.suse.manager.reactor.PGEventListener.lambda$notify$1(PGEventListener.java:76) ~[rhn.jar:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?]
	at com.suse.manager.reactor.PGEventListener.lambda$notify$2(PGEventListener.java:74) ~[rhn.jar:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?]
	at com.suse.manager.reactor.PGEventListener.notify(PGEventListener.java:71) ~[rhn.jar:?]
	at com.suse.salt.netapi.event.AbstractEventStream.notifyListeners(AbstractEventStream.java:64) ~[salt-netapi-clientsalt-netapi-client.jar:?]
	at com.suse.manager.reactor.PGEventStream.lambda$processEvents$6(PGEventStream.java:206) ~[rhn.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357) ~[?:?]
	at java.util.stream.Sink$ChainedReference.end(Sink.java:258) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
	at com.suse.manager.reactor.PGEventStream.processEvents(PGEventStream.java:200) ~[rhn.jar:?]
	at com.suse.manager.reactor.PGEventStream.lambda$notification$1(PGEventStream.java:184) ~[rhn.jar:?]
	at com.redhat.rhn.frontend.events.TransactionHelper.run(TransactionHelper.java:63) ~[rhn.jar:?]
	at com.redhat.rhn.frontend.events.TransactionHelper.handlingTransaction(TransactionHelper.java:48) ~[rhn.jar:?]
	at com.suse.manager.reactor.PGEventStream.lambda$notification$3(PGEventStream.java:183) ~[rhn.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
2023-02-09 11:14:23,615 [salt-event-thread-8] ERROR com.suse.manager.reactor.PGEventListener - Unexpected exception while executing a MessageAction
java.lang.NullPointerException: null
	at com.suse.manager.reactor.utils.ValueMap.get(ValueMap.java:216) ~[rhn.jar:?]
	at com.suse.manager.reactor.utils.ValueMap.getValueAsString(ValueMap.java:78) ~[rhn.jar:?]
	at com.suse.manager.utils.SaltUtils.handlePackageProfileUpdate(SaltUtils.java:1411) ~[rhn.jar:?]
	at com.suse.manager.utils.SaltUtils.lambda$updateServerAction$25(SaltUtils.java:579) ~[rhn.jar:?]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at com.suse.manager.utils.SaltUtils.updateServerAction(SaltUtils.java:579) ~[rhn.jar:?]
	at com.suse.manager.webui.services.SaltServerActionService.lambda$handleAction$146(SaltServerActionService.java:2662) ~[rhn.jar:?]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at com.suse.manager.webui.services.SaltServerActionService.lambda$handleAction$147(SaltServerActionService.java:2640) ~[rhn.jar:?]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at com.suse.manager.webui.services.SaltServerActionService.handleAction(SaltServerActionService.java:2633) ~[rhn.jar:?]
	at com.suse.manager.reactor.messaging.JobReturnEventMessageAction.lambda$execute$4(JobReturnEventMessageAction.java:134) ~[rhn.jar:?]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at com.suse.manager.reactor.messaging.JobReturnEventMessageAction.lambda$execute$5(JobReturnEventMessageAction.java:133) ~[rhn.jar:?]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at com.suse.manager.reactor.messaging.JobReturnEventMessageAction.execute(JobReturnEventMessageAction.java:133) ~[rhn.jar:?]
	at com.suse.manager.reactor.PGEventListener.lambda$notify$1(PGEventListener.java:76) ~[rhn.jar:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?]
	at com.suse.manager.reactor.PGEventListener.lambda$notify$2(PGEventListener.java:74) ~[rhn.jar:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?]
	at com.suse.manager.reactor.PGEventListener.notify(PGEventListener.java:71) ~[rhn.jar:?]
	at com.suse.salt.netapi.event.AbstractEventStream.notifyListeners(AbstractEventStream.java:64) ~[salt-netapi-clientsalt-netapi-client.jar:?]
	at com.suse.manager.reactor.PGEventStream.lambda$processEvents$6(PGEventStream.java:206) ~[rhn.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357) ~[?:?]
	at java.util.stream.Sink$ChainedReference.end(Sink.java:258) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
	at com.suse.manager.reactor.PGEventStream.processEvents(PGEventStream.java:200) ~[rhn.jar:?]
	at com.suse.manager.reactor.PGEventStream.lambda$notification$1(PGEventStream.java:184) ~[rhn.jar:?]
	at com.redhat.rhn.frontend.events.TransactionHelper.run(TransactionHelper.java:63) ~[rhn.jar:?]
	at com.redhat.rhn.frontend.events.TransactionHelper.handlingTransaction(TransactionHelper.java:48) ~[rhn.jar:?]
	at com.suse.manager.reactor.PGEventStream.lambda$notification$3(PGEventStream.java:183) ~[rhn.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
2023-02-09 11:14:23,616 [salt-event-thread-8] ERROR com.redhat.rhn.frontend.events.TransactionHelper - com.suse.manager.reactor.PGEventListenerException
2023-02-09 11:14:23,617 [salt-event-thread-8] ERROR com.suse.manager.reactor.PGEventStream - Events [226755] were lost
```

**Comment by samcoddington** [comment]
Upgraded to 2023.01 today and it fixed the missing python3-ordered-set for SLE 15.3 and 15.4.  The issue is still happening for me on SLE 15.2 bootstrap repo creation.  The issue I was having with sync_states not running is still happening.  It doesn't seem to have been related to missing bootstrap repo package.

**Comment by samcoddington** [comment]
Could these salt state errors be related to mis-matched python versions?  Clients are using the venv-salt-minion bundle which is 3.10.x, but our main uyuni server (and proxies) are using the default system python which is 3.6.x.  When uyuni migrated to the venv-salt-minion bundle was there a python upgrade that we missed somewhere?  I've been looking through the release notes and haven't seen anything that mentions a python upgrade

**Comment by juliogonzalez** [comment]
> IIRC that error can be ignored for now. The problem is that bootstrap repository definition was not updated at the same time that the salt-minion package and its dependencies were removed from the Uyuni Client Tools repos.

@agraul, we removed `salt-minion` only from SLE12 and CentOS7.

This report is about SLE15, isn't it?

**Comment by juliogonzalez** [comment]
> > > IIRC that error can be ignored for now. The problem is that bootstrap repository definition was not updated at the same time that the salt-minion package and its dependencies were removed from the Uyuni Client Tools repos.
> > 
> > 
> > @agraul, we removed `salt-minion` only from SLE12 and CentOS7.
> > This report is about SLE15, isn't it?
> 
> @juliogonzalez you're right. No idea why the package is not available for repo sync then.

Check https://maintenance.suse.de/maintained/?q=python3-ordered-set, it's only available on SP4 or newer.

Check with your squad, I seem to remember this package was only required on newer Python versions. If so, you need to prepare a fix to make it optional on the bootstrap repo definition.

**Comment by samcoddington** [comment]
the python3-ordered-set issue I think is secondary here.  The salt errors are happening on both previously and newly bootstrapped hosts, all are SLE 15.3 or 15.4.  The errors are beginning to very a bit,  

This is from a previously bootstrapped 15.4 host that had been working.

```
Mar 13 15:09:06 <hostname> salt-minion[2658]: [ERROR   ] Failed to run sync_modules: 'NoneType' object is not iterable
Mar 13 15:09:06 <hostname> salt-minion[2658]: [ERROR   ] Failed to run saltutil.sync_states: 'NoneType' object is not iterable
Mar 13 15:09:06 <hostname> salt-minion[2658]: [ERROR   ] Failed to run sync_states: 'NoneType' object is not iterable
Mar 13 15:09:06 <hostname> salt-minion[2658]: [ERROR   ] Failed to run saltutil.sync_grains: 'NoneType' object is not iterable
Mar 13 15:09:06 <hostname> salt-minion[2658]: [ERROR   ] Failed to run sync_grains: 'NoneType' object is not iterable
Mar 13 15:09:06 <hostname> salt-minion[2658]: [ERROR   ] Failed to run saltutil.sync_beacons: 'NoneType' object is not iterable
Mar 13 15:09:06 <hostname> salt-minion[2658]: [ERROR   ] Failed to run sync_beacons: 'NoneType' object is not iterable
```

And this is the log from a newly build 15.3 system we just bootstrapped
```
Mar 10 18:51:53 <hostname> salt-minion[9268]: [ERROR   ] Failed to run saltutil.sync_modules: 'NoneType' object is not iterable
Mar 10 18:51:53 <hostname> salt-minion[9268]: [ERROR   ] Failed to run sync_modules: 'NoneType' object is not iterable
Mar 10 18:51:53 <hostname> salt-minion[9268]: [ERROR   ] Failed to run saltutil.sync_states: 'NoneType' object is not iterable
Mar 10 18:51:53 <hostname> salt-minion[9268]: [ERROR   ] Failed to run sync_states: 'NoneType' object is not iterable
Mar 10 18:51:54 <hostname> salt-minion[9268]: [ERROR   ] Failed to run saltutil.sync_grains: 'NoneType' object is not iterable
Mar 10 18:51:54 <hostname> salt-minion[9268]: [ERROR   ] Failed to run sync_grains: 'NoneType' object is not iterable
Mar 10 18:51:54 <hostname> salt-minion[9268]: [ERROR   ] Failed to run saltutil.sync_beacons: 'NoneType' object is not iterable
Mar 10 18:51:54 <hostname> salt-minion[9268]: [ERROR   ] Failed to run sync_beacons: 'NoneType' object is not iterable
Mar 10 18:51:55 <hostname> salt-minion[9268]: [ERROR   ] State 'mgrcompat.module_run' was not found in SLS 'util.systeminfo_full'
Mar 10 18:51:55 <hostname> salt-minion[9268]: Reason: 'mgrcompat.module_run' is not available.
Mar 10 18:51:55 <hostname> salt-minion[9268]: [ERROR   ] State 'mgrcompat.module_run' was not found in SLS 'util.systeminfo_full'
Mar 10 18:51:55 <hostname> salt-minion[9268]: Reason: 'mgrcompat.module_run' is not available.
Mar 10 18:51:55 <hostname> salt-minion[9268]: [ERROR   ] State 'mgrcompat.module_run' was not found in SLS 'util.systeminfo_full'
Mar 10 18:51:55 <hostname> salt-minion[9268]: Reason: 'mgrcompat.module_run' is not **available.**
```

**Comment by samcoddington** [comment]
Any more ideas on this?  I spun up a second uyuni instance and it just seems to work, no salt issues.  We would like to try and fix our prod instance since setting everything back up on a new server isn't ideal.

**Comment by agraul** [comment]
@samcoddington can you upload debug logs from the SP4 system that had been working before? You can set the log level by adding a config file to `/etc/venv-salt-minion/minion.d` that contains `log_level_logfile: debug` followed by restarting venv-salt-minion. You could use e.g. https://paste.opensuse.org/ or any other pastebin.

**Comment by samcoddington** [comment]
Sure, here's the output from doing that, https://paste.opensuse.org/pastes/693679c668a1

**Comment by samcoddington** [comment]
We ended up rebuilding our uyuni system from scratch, and the issue went away for a couple months.  New issue opened https://github.com/uyuni-project/uyuni/issues/7251

**Comment by avshiliaev** [comment]
Closing as stale and (probably) resolved. Feel free to reopen
