### ISSUE TITLE
Stack trace on USN-5054-2

### ISSUE THREAD

**Issue by phibid** [uyuni-project/uyuni#6548]
### Problem description

Since the 2023-01-26, we are receiving lots of Uyuni taskomatic notification per mail with this information:

```
Taskomatic bunch repo-sync-bunch was scheduled to run within the single-repo-sync-bunch-13 schedule.
Subtask repo-sync failed.
For more information check null.
```

Checking at the log, I have noticed those stack traces which seems to be related:

```
2023-01-30 03:40:19,643 [DefaultQuartzScheduler_Worker-5] ERROR com.redhat.rhn.taskomatic.task.RepoSyncTask - Message: For input string: "5054-2"
2023-01-30 03:40:19,643 [DefaultQuartzScheduler_Worker-5] ERROR com.redhat.rhn.taskomatic.task.RepoSyncTask - Cause:
2023-01-30 03:40:19,643 [DefaultQuartzScheduler_Worker-5] ERROR com.redhat.rhn.taskomatic.task.RepoSyncTask - Stack trace:java.lang.NumberFormatException: For input string: "5054-2"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Long.parseLong(Long.java:692)
        at java.base/java.lang.Long.parseLong(Long.java:817)
        at com.redhat.rhn.manager.content.ubuntu.UbuntuErrataManager.lambda$processUbuntuErrata$24(UbuntuErrataManager.java:280)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1764)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at com.redhat.rhn.manager.content.ubuntu.UbuntuErrataManager.lambda$processUbuntuErrata$26(UbuntuErrataManager.java:316)
        at com.redhat.rhn.common.util.TimeUtils.logTime(TimeUtils.java:48)
        at com.redhat.rhn.manager.content.ubuntu.UbuntuErrataManager.processUbuntuErrata(UbuntuErrataManager.java:233)
        at com.redhat.rhn.manager.content.ubuntu.UbuntuErrataManager.processUbuntuErrataByIds(UbuntuErrataManager.java:206)
        at com.redhat.rhn.manager.content.ubuntu.UbuntuErrataManager.sync(UbuntuErrataManager.java:197)
        at com.redhat.rhn.taskomatic.task.RepoSyncTask.execute(RepoSyncTask.java:118)
        at com.redhat.rhn.taskomatic.task.RhnJavaJob.execute(RhnJavaJob.java:105)
        at com.redhat.rhn.taskomatic.TaskoJob.execute(TaskoJob.java:155)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
```

This is strange because if really the cause is the errata generation/efresh, then I understand that 5054-2 mentioned in the stack trace correspond to this USN: https://ubuntu.com/security/notices/USN-5054-2 which is an old one (3 September 2021).

### Steps to reproduce

Not sure when it occurs to be honest as now the reposync scheduled is controlled by Uyuni

### Uyuni version

```bash
# zypper info Uyuni-server-release
Loading repository data...
Warning: Repository 'Update repository of openSUSE Backports' appears to be outdated. Consider using a different mirror or server.
Warning: Repository 'Main Update Repository' appears to be outdated. Consider using a different mirror or server.
Reading installed packages...


Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2022.11-220400.193.4.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2022.11-220400.193.4.uyuni2.src
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

**Comment by mcalmer** [comment]
Duplicate of https://github.com/uyuni-project/uyuni/issues/6534

**Comment by teonitro** [comment]
Hello, 

After also discovered all this bug in the uuyuni release 2023.01 i have updated  the uyuni on the lastest stable as uyuni 2023.03 but i don't any traces in taskomatic logs file from importing ubuntu erratas database. 
I don't see also no patch present starting by USN* in command line  : spacecmd errata_list
So i would like to know how to check the ubuntu errata import ? 

kind regards

**Comment by mcalmer** [comment]
We do not import them with the "USN" prefix. There are scripts out there which were used before we had this feature.
To not conflict with this, we used different names and just used the number for now.
If the channel is of type debian and we check all the packages against the packages in the json file and generate the errata. This should happen automatically at the end of a repo-sync.

**Comment by teonitro** [comment]
hello @mcalmer, 
Thanks for your response. 
After typing this command line to clear cache and have all erratas `spacecmd clear_caches ; spacecmd errata_list`, i can't see any Ubuntu erratas with only errata number after a repos-sync `spacewalk-repo-sync -p ubuntu-20.04-pool-amd64-uyuni`
I have put in DEBUG lever the taskomatic daemon  and no trace concerning importing ubuntu database. 
thanks in advance for your support.

**Comment by teonitro** [comment]
Hello, 
Finally i can see now the news erratas from ubuntu database. I think that was a refresh problem or taskomatic workers not available to do the import task. 
regards,
