### ISSUE TITLE
Upgrade to version 2023.01 Notification message empty

### ISSUE THREAD

**Issue by rchekhina** [uyuni-project/uyuni#6556]
### Problem description

HI,

I have upgraded Uyuni from version 2022.12 to 2023.01 and now the Notification Message page is empty:

![image](https://user-images.githubusercontent.com/78473404/215981458-e2fee7f9-2a10-4aaf-9536-2ccf9e12c451.png)

Best regards.

### Steps to reproduce

1. upgrade from version 2022.12 to 2023.01
2.
3.
...

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2023.01-220400.196.2.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2023.01-220400.196.2.uyuni2.src
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

**Comment by saquib-akhtar** [comment]
488.bundle.js:1 
        
       Uncaught (in promise) TypeError: First argument must be a string
    at a (488.bundle.js:1:3419)
    at NotificationMessages.buildSummary (244.bundle.js:1:32719)
    at Object.cell (244.bundle.js:1:39751)
    at _ (244.bundle.js:1:15401)
    at am (main.bundle.js?cb=20230127150645:2:174970)
    at Vi (main.bundle.js?cb=20230127150645:2:227019)
    at _o (main.bundle.js?cb=20230127150645:2:214293)
    at zo (main.bundle.js?cb=20230127150645:2:214221)
    at So (main.bundle.js?cb=20230127150645:2:214084)
    at fo (main.bundle.js?cb=20230127150645:2:211071)

**Comment by saquib-akhtar** [comment]
10.243.108.138 - - [06/Feb/2023:00:16:32 +0200] "GET /rhn/manager/notification-messages HTTP/1.1" 200 34974
10.243.108.138 - - [06/Feb/2023:00:16:33 +0200] "POST /rhn/manager/frontend-log HTTP/1.1" 200 16
10.243.108.138 - - [06/Feb/2023:00:16:33 +0200] "GET /rhn/manager/notification-messages/data-unread HTTP/1.1" 200 21595
127.0.0.1 - - [06/Feb/2023:00:16:34 +0200] "GET /rhn/websocket/notifications HTTP/1.1" 101 -

HTTP response went ok for request but there is internal JAVA error as shown above which crashes the page.

**Comment by greinick** [comment]
Same issue with my installation after the upgrade.

**Comment by csabaz** [comment]
Hi, I have the same problem.

**Comment by mackdk** [comment]
If you are currently experiencing this issue could you please run on the server the following command:

```
echo "SELECT nm.id, un.user_id, nm.type, nm.data, nm.created FROM suseusernotification un INNER JOIN susenotificationmessage nm ON un.message_id = nm.id WHERE nm.type = 'SubscriptionWarning' AND data = '{}';" | spacewalk-sql --select-mode-direct -
```

If you have get any row as result, could you please post it here? Thanks.

**Comment by saquib-akhtar** [comment]
spacewalk:~ # echo "SELECT nm.id, un.user_id, nm.type, nm.data, nm.created FROM suseusernotification un INNER JOIN susenotificationmessage nm ON un.message_id = nm.id WHERE nm.type = 'SubscriptionWarning' AND data = '{}';" | spacewalk-sql --select-mode-direct -
  id   | user_id |        type         | data |          created
-------+---------+---------------------+------+----------------------------
 43649 |       7 | SubscriptionWarning | {}   | 2023-01-17 09:51:00.173+02
 43649 |       9 | SubscriptionWarning | {}   | 2023-01-17 09:51:00.173+02
 43650 |       7 | SubscriptionWarning | {}   | 2023-01-17 10:52:00.131+02
 43650 |       9 | SubscriptionWarning | {}   | 2023-01-17 10:52:00.131+02
 43767 |       7 | SubscriptionWarning | {}   | 2023-01-18 09:51:00.177+02
 43767 |       9 | SubscriptionWarning | {}   | 2023-01-18 09:51:00.177+02
 43768 |       7 | SubscriptionWarning | {}   | 2023-01-18 10:52:00.143+02
 43768 |       9 | SubscriptionWarning | {}   | 2023-01-18 10:52:00.143+02
 43886 |       7 | SubscriptionWarning | {}   | 2023-01-19 09:51:00.182+02
 43886 |       9 | SubscriptionWarning | {}   | 2023-01-19 09:51:00.182+02
 43887 |       7 | SubscriptionWarning | {}   | 2023-01-19 10:52:00.119+02
 43887 |       9 | SubscriptionWarning | {}   | 2023-01-19 10:52:00.119+02
 44005 |       7 | SubscriptionWarning | {}   | 2023-01-20 09:51:00.15+02
 44005 |       9 | SubscriptionWarning | {}   | 2023-01-20 09:51:00.15+02
 44006 |       7 | SubscriptionWarning | {}   | 2023-01-20 10:52:00.123+02
 44006 |       9 | SubscriptionWarning | {}   | 2023-01-20 10:52:00.123+02
 44124 |       7 | SubscriptionWarning | {}   | 2023-01-21 09:51:00.166+02
 44124 |       9 | SubscriptionWarning | {}   | 2023-01-21 09:51:00.166+02
 44125 |       7 | SubscriptionWarning | {}   | 2023-01-21 10:52:00.12+02
 44125 |       9 | SubscriptionWarning | {}   | 2023-01-21 10:52:00.12+02
 44378 |       7 | SubscriptionWarning | {}   | 2023-01-23 09:51:00.178+02
 44378 |       9 | SubscriptionWarning | {}   | 2023-01-23 09:51:00.178+02
 45583 |       7 | SubscriptionWarning | {}   | 2023-02-02 09:51:00.189+02
 45583 |       9 | SubscriptionWarning | {}   | 2023-02-02 09:51:00.189+02
 44379 |       7 | SubscriptionWarning | {}   | 2023-01-23 10:52:00.162+02
 44379 |       9 | SubscriptionWarning | {}   | 2023-01-23 10:52:00.162+02
 45584 |       7 | SubscriptionWarning | {}   | 2023-02-02 10:52:00.167+02
 45584 |       9 | SubscriptionWarning | {}   | 2023-02-02 10:52:00.167+02
 44497 |       7 | SubscriptionWarning | {}   | 2023-01-24 09:51:00.183+02
 44497 |       9 | SubscriptionWarning | {}   | 2023-01-24 09:51:00.183+02
 45702 |       7 | SubscriptionWarning | {}   | 2023-02-03 09:51:00.24+02
 45702 |       9 | SubscriptionWarning | {}   | 2023-02-03 09:51:00.24+02
 44252 |       7 | SubscriptionWarning | {}   | 2023-01-22 09:51:00.149+02
 44252 |       9 | SubscriptionWarning | {}   | 2023-01-22 09:51:00.149+02
 44498 |       7 | SubscriptionWarning | {}   | 2023-01-24 10:52:00.229+02
 44498 |       9 | SubscriptionWarning | {}   | 2023-01-24 10:52:00.229+02
 44616 |       7 | SubscriptionWarning | {}   | 2023-01-25 09:51:00.181+02
 44616 |       9 | SubscriptionWarning | {}   | 2023-01-25 09:51:00.181+02
 45703 |       7 | SubscriptionWarning | {}   | 2023-02-03 10:52:00.176+02
 45703 |       9 | SubscriptionWarning | {}   | 2023-02-03 10:52:00.176+02
 45822 |       7 | SubscriptionWarning | {}   | 2023-02-04 09:51:00.221+02
 45822 |       1 | SubscriptionWarning | {}   | 2023-02-04 09:51:00.221+02
 45822 |       9 | SubscriptionWarning | {}   | 2023-02-04 09:51:00.221+02
 44253 |       7 | SubscriptionWarning | {}   | 2023-01-22 10:52:00.114+02
 44253 |       9 | SubscriptionWarning | {}   | 2023-01-22 10:52:00.114+02
 44617 |       7 | SubscriptionWarning | {}   | 2023-01-25 10:52:00.148+02
 44617 |       9 | SubscriptionWarning | {}   | 2023-01-25 10:52:00.148+02
 44735 |       7 | SubscriptionWarning | {}   | 2023-01-26 09:51:00.181+02
 44735 |       9 | SubscriptionWarning | {}   | 2023-01-26 09:51:00.181+02
 45823 |       7 | SubscriptionWarning | {}   | 2023-02-04 10:52:00.161+02
 45823 |       1 | SubscriptionWarning | {}   | 2023-02-04 10:52:00.161+02
 45823 |       9 | SubscriptionWarning | {}   | 2023-02-04 10:52:00.161+02
 44736 |       7 | SubscriptionWarning | {}   | 2023-01-26 10:52:00.138+02
 44736 |       9 | SubscriptionWarning | {}   | 2023-01-26 10:52:00.138+02
 44854 |       7 | SubscriptionWarning | {}   | 2023-01-27 09:51:00.194+02
 44854 |       9 | SubscriptionWarning | {}   | 2023-01-27 09:51:00.194+02
 44973 |       7 | SubscriptionWarning | {}   | 2023-01-28 09:51:00.202+02
 44973 |       9 | SubscriptionWarning | {}   | 2023-01-28 09:51:00.202+02
 44855 |       7 | SubscriptionWarning | {}   | 2023-01-27 10:52:00.137+02
 44855 |       9 | SubscriptionWarning | {}   | 2023-01-27 10:52:00.137+02
 44974 |       7 | SubscriptionWarning | {}   | 2023-01-28 10:52:00.142+02
 44974 |       9 | SubscriptionWarning | {}   | 2023-01-28 10:52:00.142+02
 45098 |       7 | SubscriptionWarning | {}   | 2023-01-29 09:51:00.144+02
 45098 |       9 | SubscriptionWarning | {}   | 2023-01-29 09:51:00.144+02
 45099 |       7 | SubscriptionWarning | {}   | 2023-01-29 10:52:00.112+02
 45099 |       9 | SubscriptionWarning | {}   | 2023-01-29 10:52:00.112+02
 45950 |       7 | SubscriptionWarning | {}   | 2023-02-05 09:51:00.151+02
 45950 |       1 | SubscriptionWarning | {}   | 2023-02-05 09:51:00.151+02
 45950 |       9 | SubscriptionWarning | {}   | 2023-02-05 09:51:00.151+02
 45951 |       7 | SubscriptionWarning | {}   | 2023-02-05 10:52:00.117+02
 45951 |       1 | SubscriptionWarning | {}   | 2023-02-05 10:52:00.117+02
 45951 |       9 | SubscriptionWarning | {}   | 2023-02-05 10:52:00.117+02
 45226 |       7 | SubscriptionWarning | {}   | 2023-01-30 09:51:00.255+02
 45226 |       9 | SubscriptionWarning | {}   | 2023-01-30 09:51:00.255+02
 45227 |       7 | SubscriptionWarning | {}   | 2023-01-30 10:52:00.19+02
 45227 |       9 | SubscriptionWarning | {}   | 2023-01-30 10:52:00.19+02
 45345 |       7 | SubscriptionWarning | {}   | 2023-01-31 09:51:00.187+02
 45345 |       9 | SubscriptionWarning | {}   | 2023-01-31 09:51:00.187+02
 45464 |       7 | SubscriptionWarning | {}   | 2023-02-01 09:51:00.195+02
 45464 |       9 | SubscriptionWarning | {}   | 2023-02-01 09:51:00.195+02
 45346 |       7 | SubscriptionWarning | {}   | 2023-01-31 10:52:00.192+02
 45346 |       9 | SubscriptionWarning | {}   | 2023-01-31 10:52:00.192+02
 45465 |       7 | SubscriptionWarning | {}   | 2023-02-01 10:52:00.179+02
 45465 |       9 | SubscriptionWarning | {}   | 2023-02-01 10:52:00.179+02
 43529 |       7 | SubscriptionWarning | {}   | 2023-01-16 09:51:00.14+02
 43529 |       9 | SubscriptionWarning | {}   | 2023-01-16 09:51:00.14+02
 43530 |       7 | SubscriptionWarning | {}   | 2023-01-16 10:52:00.13+02
 43530 |       9 | SubscriptionWarning | {}   | 2023-01-16 10:52:00.13+02
(88 rows)

**Comment by saquib-akhtar** [comment]
This shows me list of complete subscription warnings in DB till now
That means some issue with frontend JAVA Call

**Comment by mackdk** [comment]
The problem is mostly in the backend, actually. It should not create a notification with empty data. From what I knew, it should have been already fixed by https://github.com/uyuni-project/uyuni/pull/6513. When did you perform the upgrade to 2023.01? Anyway, to fix the issue (at least temporarly) you can remove the wrong notification with the following command on the server:

```
echo "DELETE FROM suseusernotification WHERE message_id IN (SELECT id FROM susenotificationmessage WHERE type = 'SubscriptionWarning' AND data = '{}');" | spacewalk-sql --select-mode-direct -
```

**Comment by saquib-akhtar** [comment]
> The problem is mostly in the backend, actually. It should not create a notification with empty data. From what I knew, it should have been already fixed by #6513. When did you perform the upgrade to 2023.01? Anyway, to fix the issue (at least temporarly) you can remove the wrong notification with the following command on the server:
> 
> ```
> echo "DELETE FROM suseusernotification WHERE message_id IN (SELECT id FROM susenotificationmessage WHERE type = 'SubscriptionWarning' AND data = '{}');" | spacewalk-sql --select-mode-direct -
> ```

So, this was the complete issue & because backend was creating empty notification then front-end JAVA was crashing basically WAR running the complete portal. Now as soon as I cleared above NULL notifications subscription page starts working again & perfectly fine.

**Comment by saquib-akhtar** [comment]
spacewalk:~ # echo "DELETE FROM suseusernotification WHERE message_id IN (SELECT id FROM susenotificationmessage WHERE type = 'SubscriptionWarning' AND data = '{}');" | spacewalk-sql --select-mode-direct -
DELETE 88
spacewalk:~ #
spacewalk:~ #
spacewalk:~ # echo "SELECT nm.id, un.user_id, nm.type, nm.data, nm.created FROM suseusernotification un INNER JOIN susenotificationmessage nm ON un.message_id = nm.id WHERE nm.type = 'SubscriptionWarning' AND data = '{}';" | spacewalk-sql --select-mode-direct -
 id | user_id | type | data | created
----+---------+------+------+---------
(0 rows)

**Comment by saquib-akhtar** [comment]
This marks the solution of this Bug now.

**Comment by mackdk** [comment]
> This marks the solution of this Bug now.

We still have to see if the offending line is recreated. The check for subscriptions is performed daily. If you see the problem again, it means we still have something to fix in the backend.

**Comment by saquib-akhtar** [comment]
> > This marks the solution of this Bug now.
> 
> We still have to see if the offending line is recreated. The check for subscriptions is performed daily. If you see the problem again, it means we still have something to fix in the backend.

Now since last above query was run by me to clear unwanted subscription alert with empty data there has no further such alerts or mails and the subscription portal works perfectly fine.
