### ISSUE TITLE
pkg.add_repo_key seems to be broken for Salt SSH transactional minions

### ISSUE THREAD

**Issue by juliogonzalez** [uyuni-project/uyuni#6560]
Saw while testing openSUSE Leap Micro 5.3 on Uyuni.

I tried to onboard that OS as regular minion. Worked fine.

However, as Salt SSH minion, the minion is bootstrapped, and salt-ssh runs there and is able to connect to the master.

But while running `Apply states [certs, channels, packages, transactional_reboot.config, util.systeminfo] scheduled by admin`, `pkg_add_repo_key` fails:

```
          ID: https_//download.opensuse.org/distribution/leap-micro/5.3/product/repo/Leap-Micro-5.3-x86_64-Media1/gpg-pubkey-3dbdc284-53674dd4.asc
    Function: mgrcompat.run
        Name: pkg.add_repo_key
      Result: false
     Comment: Module function pkg.add_repo_key executed
     Started: 12:27:38.318021
    Duration: 90.608
         SLS: channels.gpg-keys
     Changed: ret: false
              
----------
          ID: file_///etc/pki/rpm-gpg/uyuni-tools-gpg-pubkey-0d20833e.key
    Function: mgrcompat.run
        Name: pkg.add_repo_key
      Result: false
     Comment: Module function pkg.add_repo_key executed
     Started: 12:27:38.408929
    Duration: 19.515
         SLS: channels.gpg-keys
     Changed: ret: false
              
```
At the minion itself, I see:

![image](https://user-images.githubusercontent.com/4226070/216052012-0395c75c-505e-43e7-883f-36f794734b45.png)

So it seems that `pkg.add_repo_key` is not working correctly, but only for Salt SSH.

**Comment by juliogonzalez** [comment]
Something tells me `pkg.*` is not working in "transactional mode at all", as I can't install patches either:
```
          ID: mgr_regular_patches
    Function: pkg.installed
        Name: mgr_regular_patches
      Result: false
     Comment: An exception occurred in this state: Traceback (most recent call last):
  File "/var/tmp/venv-salt-minion/lib64/python3.10/site-packages/salt/state.py", line 2214, in call
    ret = self.states[cdata["full"]](
  File "/var/tmp/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/var/tmp/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1203, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/var/tmp/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1218, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/var/tmp/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1251, in wrapper
    return f(*args, **kwargs)
  File "/var/tmp/venv-salt-minion/lib/python3.10/site-packages/salt/states/pkg.py", line 2415, in patch_installed
    pkg_ret = __salt__["pkg.install"](
  File "/var/tmp/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/var/tmp/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1203, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/var/tmp/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1218, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/var/tmp/venv-salt-minion/lib/python3.10/site-packages/salt/modules/zypperpkg.py", line 1804, in install
    __zypper__(
  File "/var/tmp/venv-salt-minion/lib/python3.10/site-packages/salt/modules/zypperpkg.py", line 414, in __call
    if self._check_result():
  File "/var/tmp/venv-salt-minion/lib/python3.10/site-packages/salt/modules/zypperpkg.py", line 331, in _check_result
    if self._is_zypper_lock() or self._is_rpm_lock():
  File "/var/tmp/venv-salt-minion/lib/python3.10/site-packages/salt/modules/zypperpkg.py", line 298, in _is_rpm_lock
    with salt.utils.files.fopen(self.RPM_LOCK, mode="w+") as rfh:
  File "/var/tmp/venv-salt-minion/lib64/python3.10/site-packages/salt/utils/files.py", line 393, in fopen
    f_handle = open(*args, **kwargs)  # pylint: disable=resource-leakage
OSError: [Errno 30] Read-only file system: '/var/lib/rpm/.rpm.lock'

     Started: 13:11:20.461061
    Duration: 6757.678
         SLS: packages.patchinstall
     Changed: {}
```

**Comment by juliogonzalez** [comment]
Maybe the problem with the key and the `pkg.installation` are different things.

If I try to add the Uyuni Leap 15 cient tools to an openSUSE MicroOS, I just saw this:

```
n241:~ # zypper ar https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master:/openSUSE_Leap_15-Uyuni-Client-Tools/openSUSE_Leap_15.0/systemsmanagement:Uyuni:Master:openSUSE_Leap_15-Uyuni-Client-Tools.repo
Repository 'systemsmanagement:Uyuni:Master:openSUSE_Leap_15-Uyuni-Client-Tools (openSUSE_Leap_15.0)' successfully added

URI         : https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master:/openSUSE_Leap_15-Uyuni-Client-Tools/openSUSE_Leap_15.0/
Enabled     : Yes
GPG Check   : Yes
Autorefresh : No
Priority    : 99 (default priority)

Repository priorities are without effect. All enabled repositories share the same priority.

n241:~ # zypper ref
Repository 'openSUSE-Tumbleweed-Non-Oss' is up to date.                                                                                                                                                                                     
Repository 'openSUSE-Tumbleweed-Oss' is up to date.                                                                                                                                                                                         
Repository 'openSUSE-Tumbleweed-Update' is up to date.                                                                                                                                                                                      

New repository or package signing key received:

  Repository:       systemsmanagement:Uyuni:Master:openSUSE_Leap_15-Uyuni-Client-Tools (openSUSE_Leap_15.0)
  Key Fingerprint:  62F0 28DE 22F8 BF49 B88B C9E5 972E 5D6C 0D20 833E
  Key Name:         systemsmanagement:Uyuni OBS Project <systemsmanagement:Uyuni@build.opensuse.org>
  Key Algorithm:    RSA 2048
  Key Created:      Fri Oct  7 14:00:36 2022
  Key Expires:      Sun Dec 15 14:00:36 2024
  Rpm Name:         gpg-pubkey-0d20833e-63403104



    Note: Signing data enables the recipient to verify that no modifications occurred after the data
    were signed. Accepting data with no, wrong or unknown signature can lead to a corrupted system
    and in extreme cases even to a system compromise.

    Note: A GPG pubkey is clearly identified by its fingerprint. Do not rely on the key's name. If
    you are not sure whether the presented key is authentic, ask the repository provider or check
    their web site. Many providers maintain a web page showing the fingerprints of the GPG keys they
    are using.

Do you want to reject the key, trust temporarily, or trust always? [r/t/a/?] (r): a
Subprocess failed. Error: Failed to import public key [972E5D6C0D20833E-63403104] [systemsmanagement:Uyuni OBS Project <systemsmanagement:Uyuni@build.opensuse.org>] [expires: 2024-12-15]
History:
 - Command exited with status 1.
 - error: /var/tmp/zypp.fgdOzJ/pubkey-972E5D6C0D20833E-v8To8R: key 1 import failed.
 - error: can't create transaction lock on /usr/lib/sysimage/rpm/.rpm.lock (Read-only file system)

Retrieving repository 'systemsmanagement:Uyuni:Master:openSUSE_Leap_15-Uyuni-Client-Tools (openSUSE_Leap_15.0)' metadata .............................................................................................................[done]
All repositories have been refreshed.
```
So in this case, and without involving salt, the repo gets installed, but the key does not.

I wonder how it is at a non-salt-ssh system didn't show this problem.

**Comment by nodeg** [comment]
I ran into the same issue when onboarding a SLE Micro 5.3 SSH minion and then e.g. trying to update packages:

```salt
----------
          ID: pkg_installed
    Function: pkg.installed
        Name: pkg_installed
      Result: false
     Comment: An exception occurred in this state: Traceback (most recent call last):
  File "/var/tmp/venv-salt-minion/lib64/python3.10/site-packages/salt/state.py", line 2214, in call
    ret = self.states[cdata["full"]](
  File "/var/tmp/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/var/tmp/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1203, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/var/tmp/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1218, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/var/tmp/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1251, in wrapper
    return f(*args, **kwargs)
  File "/var/tmp/venv-salt-minion/lib/python3.10/site-packages/salt/states/pkg.py", line 1893, in installed
    pkg_ret = __salt__["pkg.install"](
  File "/var/tmp/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/var/tmp/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1203, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/var/tmp/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1218, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/var/tmp/venv-salt-minion/lib/python3.10/site-packages/salt/modules/zypperpkg.py", line 1804, in install
    __zypper__(
  File "/var/tmp/venv-salt-minion/lib/python3.10/site-packages/salt/modules/zypperpkg.py", line 414, in __call
    if self._check_result():
  File "/var/tmp/venv-salt-minion/lib/python3.10/site-packages/salt/modules/zypperpkg.py", line 331, in _check_result
    if self._is_zypper_lock() or self._is_rpm_lock():
  File "/var/tmp/venv-salt-minion/lib/python3.10/site-packages/salt/modules/zypperpkg.py", line 298, in _is_rpm_lock
    with salt.utils.files.fopen(self.RPM_LOCK, mode="w+") as rfh:
  File "/var/tmp/venv-salt-minion/lib64/python3.10/site-packages/salt/utils/files.py", line 393, in fopen
    f_handle = open(*args, **kwargs)  # pylint: disable=resource-leakage
OSError: [Errno 30] Read-only file system: '/var/lib/rpm/.rpm.lock'

     Started: 08:52:06.480262
    Duration: 2201.828
         SLS: packages.pkginstall
     Changed: {}
```
