### ISSUE TITLE
spacewalk-repo-sync fails with "Invalid IPv6 URL"

### ISSUE THREAD

**Issue by sbluhm** [uyuni-project/uyuni#6564]
### Problem description

**NOTE: Issue occurs on Enterprise Linux 9 only (not Leap)**

spacewalk-repo-sync fails with `Invalid IPv6 URL` on sources containing  `:`

```
#  /usr/bin/spacewalk-repo-sync --channel almalinux9-uyuni-client-x86_64  --type yum --non-interactive
22:04:33 ======================================
22:04:33 | Channel: almalinux9-uyuni-client-x86_64
22:04:33 ======================================
22:04:33 Sync of channel started.
22:04:35 Unhandled error occurred: Invalid IPv6 URL
22:04:35 Unexpected error: <class 'ValueError'>
22:04:35 Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/spacewalk/satellite_tools/reposync.py", line 603, in sync
    plugin = self.repo_plugin(url, repo_name, insecure, self.interactive,
  File "/usr/lib/python3.9/site-packages/spacewalk/satellite_tools/repo_plugins/yum_dnf_src.py", line 148, in __init__
    self.setup_repo(repo, no_mirrors, ca_cert_file, client_cert_file, client_key_file)
  File "/usr/lib/python3.9/site-packages/spacewalk/satellite_tools/repo_plugins/yum_dnf_src.py", line 209, in setup_repo
    if not self.clean_urls(self.dnfbase.repos[self.repoid]._repo.getMirrors()):
  File "/usr/lib/python3.9/site-packages/spacewalk/satellite_tools/repo_plugins/yum_dnf_src.py", line 239, in clean_urls
    s = dnf.pycomp.urlparse.urlparse(url)[0]
  File "/usr/lib64/python3.9/urllib/parse.py", line 393, in urlparse
    splitresult = urlsplit(url, scheme, allow_fragments)
  File "/usr/lib64/python3.9/urllib/parse.py", line 484, in urlsplit
    raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL

22:04:37 Total time: 0:00:03
```

### Steps to reproduce

1. Add the channel: `/usr/bin/spacewalk-common-channels -u admin -p admin -k unlimited -a x86_64 'almalinux9-uyuni-client' `
2. Verify repo url to be `https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/EL9-Uyuni-Client-Tools/EL_9/`
3. Run a sync: `/usr/bin/spacewalk-repo-sync --channel almalinux9-uyuni-client-x86_64  --type yum --non-interactive`

### Uyuni version

```bash
# dnf info Uyuni-Server-Release
Last metadata expiration check: 0:39:32 ago on Wed 01 Feb 2023 09:27:40 PM CET.
Installed Packages
Name         : Uyuni-Server-release
Version      : 2022.03
Release      : 197.3.uyuni1
Architecture : x86_64
Size         : 1.4 k
Source       : Uyuni-Server-release-2022.03-197.3.uyuni1.src.rpm
Repository   : @System
From repo    : download.opensuse.org_repositories_home_sbluhm_branches_systemsmanagement_Uyuni_Master_AlmaLinux_9_
Summary      : Uyuni Server
License      : GPL-2.0-or-later
Description  : Uyuni lets you efficiently manage physical, virtual,
             : and cloud-based Linux systems. It provides automated and cost-effective
             : configuration and software management, asset management, and system
             : provisioning.
```

### Useful logs

```bash
#  /usr/bin/spacewalk-repo-sync --channel almalinux9-uyuni-client-x86_64  --type yum --non-interactive
22:04:33 ======================================
22:04:33 | Channel: almalinux9-uyuni-client-x86_64
22:04:33 ======================================
22:04:33 Sync of channel started.
22:04:35 Unhandled error occurred: Invalid IPv6 URL
22:04:35 Unexpected error: <class 'ValueError'>
22:04:35 Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/spacewalk/satellite_tools/reposync.py", line 603, in sync
    plugin = self.repo_plugin(url, repo_name, insecure, self.interactive,
  File "/usr/lib/python3.9/site-packages/spacewalk/satellite_tools/repo_plugins/yum_dnf_src.py", line 148, in __init__
    self.setup_repo(repo, no_mirrors, ca_cert_file, client_cert_file, client_key_file)
  File "/usr/lib/python3.9/site-packages/spacewalk/satellite_tools/repo_plugins/yum_dnf_src.py", line 209, in setup_repo
    if not self.clean_urls(self.dnfbase.repos[self.repoid]._repo.getMirrors()):
  File "/usr/lib/python3.9/site-packages/spacewalk/satellite_tools/repo_plugins/yum_dnf_src.py", line 239, in clean_urls
    s = dnf.pycomp.urlparse.urlparse(url)[0]
  File "/usr/lib64/python3.9/urllib/parse.py", line 393, in urlparse
    splitresult = urlsplit(url, scheme, allow_fragments)
  File "/usr/lib64/python3.9/urllib/parse.py", line 484, in urlsplit
    raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL

22:04:37 Total time: 0:00:03
```

### Additional information

Replacing all colons `:`  with `%3A` will not resolve the issue.

**Comment by sbluhm** [comment]
More infos from the log
This worked on my old Uyuni 2021.11 / EL8 until 2021-12-22 (confirmed), maybe even until 2022-01-31
Long time no sync...
I updated to 2022.05
Issue first noticed on the next sync (literally) on 2023-01-25.
I was able to alter the URL to `http://ftp.gwdg.de/pub/opensuse/repositories/systemsmanagement%3A/Uyuni%3A/Stable%3A/CentOS7-Uyuni-Client-Tools/CentOS_7/` and it worked successfully.

Just tried it back on Master. Replaced the URL from `https://download.opensuse.org/` to `http://ftp.gwdg.de/pub/opensuse/` and the sync successfully worked. So this could indicate a mirrorlist issue.

But then why do other mirrorlists work? For example `https://mirrors.almalinux.org`.

Ideas: download.opensuse.org can refer IPv6 mirror lists but my network is not set up for it.

**Comment by sbluhm** [comment]
It seems that my servers do have an IPv6 (self) assigned. But my network is not set up for it (no routers or internet set up).

**Comment by sbluhm** [comment]
Info from H. Hoffmann:

There is JavaScript code on that page:

```
</style>
      <script>//<![CDATA[
          $(function() {
            setupForAll();
                setupBrowseTable("/repositories/systemsmanagement:/Uyuni:/Stable:/EL8-Uyuni-Client-Tools/EL_8");
          } );
//]]></script>
      <link id="favicon-16" rel="icon" href="/asset/e207a92f20/logo-16.png" sizes="16x16" type="image/png">
      <link id="favicon-svg" rel="icon" href="/asset/f8027e92e2/logo.svg" sizes="any" type="image/svg+xml">
  </head>
  <body>

```
the line containing `//]]></script>` fails at `/usr/lib64/python3.9/urllib/parse.py` line 482 onwards due to `]]`


Seems the issue is related to Python 3.9.
