### ISSUE TITLE
Adding repo with spacewalk-common-channels fails with api error.

### ISSUE THREAD

**Issue by j-kihet** [uyuni-project/uyuni#6568]
### Problem description

Adding Oracle Linux 9 repos fails with api error.

### Steps to reproduce

spacewalk-common-channels -a  x86_64 oraclelinux9 oraclelinux9-addons oraclelinux9-appstream oraclelinux9-rdma oraclelinux9-uyuni-client

### Uyuni version

```bash
2022.11 to 2023.01
```

### Uyuni proxy version (if used)

```bash
None
```

### Useful logs

```bash
Traceback (most recent call last):
  File "/usr/bin/spacewalk-common-channels", line 278, in <module>
    client, key = connect(options.user, options.password, options.server)
  File "/usr/bin/spacewalk-common-channels", line 120, in connect
    key = xmlrpc_login(client, options.user, password)
  File "/usr/lib/python3.6/site-packages/uyuni/common/cli.py", line 74, in xmlrpc_login
    sessionkey = client.auth.login(username, password)
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1187, in single_request
    dict(resp.getheaders())
xmlrpc.client.ProtocolError: <ProtocolError for localhost/rpc/api: 404 Not Found>
```

### Additional information

Similar to:
https://github.com/uyuni-project/uyuni/issues/6041

**Comment by juliogonzalez** [comment]
Last time, this was caused by problems on the cobbler migrations, IIRC.

If that's the case, you should see something on the logs when you updates from any version to 2022.10, or later if you skipped 2022.10

However, I can't recall what log should show the problems. Meaybe @meaksh remembers about it.

**Comment by j-kihet** [comment]
Still getting this error on Uyuni 2023.03

**Comment by mcalmer** [comment]
@j-kihet any log messages from the server side? Please check /var/log/rhn/rhn_web_ui.log .
And check if tomcat service is running.

**Comment by j-kihet** [comment]
Tomcat is running , nothing showed up to webui log.

**Comment by cbbayburt** [comment]
I can't reproduce it either. Maybe tomcat/apache logs tell more. Please check if there's any unusual entry for `rhn/rpc/api` URI

Also, a full restart by running `spacewalk-service restart` might help.

**Comment by j-kihet** [comment]
Found nothing useful in rhn logs when trying to add the channels again.
Apache only shows 404 in logs.
Restarting does nothing , this is a persistent issue even when upgrading to newer versions.

**Comment by j-kihet** [comment]
This is still an issue on 2032.09. Found some info that might help. 
When running salt-api from the commands line it outputs an error.
```
# salt-api
[ERROR   ] [02/Oct/2023:13:30:19] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x7fb802c6fcf8>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/portend.py", line 115, in free
    Checker(timeout=0.1).assert_free(host, port)
  File "/usr/lib/python3.6/site-packages/portend.py", line 69, in assert_free
    list(itertools.starmap(self._connect, info))
  File "/usr/lib/python3.6/site-packages/portend.py", line 85, in _connect
    raise PortNotFree(tmpl.format(**locals()))
portend.PortNotFree: Port 127.0.0.1 is in use on 9080.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cherrypy/process/wspbus.py", line 230, in publish
    output.append(listener(*args, **kwargs))
  File "/usr/lib/python3.6/site-packages/cherrypy/_cpserver.py", line 180, in start
    super(Server, self).start()
  File "/usr/lib/python3.6/site-packages/cherrypy/process/servers.py", line 177, in start
    portend.free(*self.bind_addr, timeout=Timeouts.free)
  File "/usr/lib/python3.6/site-packages/portend.py", line 119, in free
    raise Timeout("Port {port} not free on {host}.".format(**locals()))
portend.Timeout: Port 9080 not free on 127.0.0.1.

[ERROR   ] [02/Oct/2023:13:30:19] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cherrypy/process/wspbus.py", line 268, in start
    self.publish('start')
  File "/usr/lib/python3.6/site-packages/cherrypy/process/wspbus.py", line 248, in publish
    raise exc
cherrypy.process.wspbus.ChannelFailures: Timeout('Port 9080 not free on 127.0.0.1.',)

^C[WARNING ] SaltAPI received a SIGINT. Exiting.
The salt-api is shutdown. SaltAPI received a SIGINT. Exited.`
```
`service salt-api  status` shows that the service is running. The only thing using port 9080 is salt-api.

**Comment by j-kihet** [comment]
Spacecmd api command still seem to work.

**Comment by vzhestkov** [comment]
@j-kihet seems like the issue has no updates for a long time. Do you still have this issue? I didn't get the idea of the actions with `salt-api` as it has nothing to do with XML-RPC API of Uyuni. Is it ok to close the issue now?

**Comment by vzhestkov** [comment]
Closing this issue as it's old and I don't think it's still reproducible, if it's wrong, feel free to reopen it. Most probably the issue was caused by some issues with this particular deployment.
