### ISSUE TITLE
Missing dependency for python3-simplejson

### ISSUE THREAD

**Issue by stdevel** [uyuni-project/uyuni#6608]
### Problem description

When running the `spacewalk-repo-sync` command, the following error message is shown:

```command
# spacewalk-repo-sync -l
Traceback (most recent call last):
  File "/usr/bin/spacewalk-repo-sync", line 25, in <module>
    import simplejson as json
ModuleNotFoundError: No module named 'simplejson'
```

Also, automatic synchronization isn't working. Manually installing the package, fixes the issue.

### Steps to reproduce

1. Run the `spacewalk-repo-sync` command or click the **Sync** button in the Web UI

### Uyuni version

```bash
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2023.01-220400.196.2.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2023.01-220400.196.2.uyuni2.src
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

### Useful logs

```bash
rhn_taskomatic_daemon.log also shows the following error:


2023-02-13 18:31:28,473 [DefaultQuartzScheduler_Worker-3] ERROR com.redhat.rhn.taskomatic.task.RepoSyncTask - Command '[/usr/bin/spacewalk-repo-sync, --channel, opensuse_leap15_4-uyuni-client-x86_64, --type, yum, --non-interactive]' exited with error code 1: Traceback (most recent call last):
  File "/usr/bin/spacewalk-repo-sync", line 25, in <module>
    import simplejson as json
ModuleNotFoundError: No module named 'simplejson'
```
```


### Additional information

Error message as seen in the Web UI:

```
Command '[/usr/bin/spacewalk-repo-sync, --channel, opensuse_leap15_4-uyuni-client-x86_64, --type, yum, --non-interactive]' exited with error code 1: Traceback (most recent call last):
  File "/usr/bin/spacewalk-repo-sync", line 25, in 
    import simplejson as json
ModuleNotFoundError: No module named 'simplejson'
```

**Comment by sbluhm** [comment]
This seems to be the fix for the issue: https://github.com/uyuni-project/uyuni/pull/6661
