### ISSUE TITLE
Spacecmd failures with API 

### ISSUE THREAD

**Issue by fullerje** [uyuni-project/uyuni#6610]
### Problem description

I have noticed a peculiar thing about the spacecmd CLI. I'm unable to run "softwarechannel_*" action tasks without a 500 error on the RPC API call, regardless of amount.
I've run spacecmd command "clear_caches" per documentation to no avail as well.
SPW_SERVER == FQDN
"# spacecmd"
Welcome to spacecmd, a command-line interface to Spacewalk.

"## INFO: Connected to https://$SPW_SERVER/rpc/api as "admin_user"
spacecmd {SSM:0}> softwarechannel_removepackages centos7-dell-independent TAPE_FR*
Packages

TAPE_FRMW_LX_R294530-93GP-23.01.13.noarch
TAPE_FRMW_LX_R294530-93GP-23.01.27.noarch

Remove these packages [y/N\]: y
ERROR: <ProtocolError for $SPW_SERVER/rpc/api: 500 500>

### Steps to reproduce

1.   Execute spacecmd from command line and successfully connect to API with appropriate credentals
2.   Run any management command:  softwarechannel_removepackages centos7-dell-independent TAPE_FR*
3.   Successfully finds details of the management command and asked for execution. 
4.   Receive ERROR: ProtocolError for $SPW_SERVER/rpc/api: 500> and exits
5.   Can backtrack error in tomcast logs (provided)
...

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2023.01-220400.196.2.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2023.01-220400.196.2.uyuni2.src
Summary        : Uyuni Server
```

### Useful logs

```bash
This error appears in tomcat logs after execution of command. 

/var/log/tomcat/localhost.log

13-Feb-2023 23:11:57.300 SEVERE [ajp-nio-127.0.0.1-8009-exec-9] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [XMLRPC] in context with path [/rhn] threw exception
        javax.persistence.PersistenceException: org.hibernate.HibernateException: identifier of an instance of com.redhat.rhn.domain.task.Task was altered from com.redhat.rhn.domain.task.Task$TaskId@cc8c8929 to com.redhat.rhn.domain.task.Task$TaskId@cc8c6982
                at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
                at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
                at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:188)
                at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1478)
                at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:512)
                at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3310)
                at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2506)
                at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:447)
                at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:178)
                at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$300(JdbcResourceLocalTransactionCoordinatorImpl.java:39)
                at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:271)
                at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:104)
                at com.redhat.rhn.common.hibernate.AbstractConnectionManager.commitTransaction(AbstractConnectionManager.java:234)
                at com.redhat.rhn.common.hibernate.HibernateFactory.commitTransaction(HibernateFactory.java:366)
                at com.redhat.rhn.frontend.servlets.SessionFilter.doFilter(SessionFilter.java:62)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at com.redhat.rhn.frontend.servlets.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:98)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
                at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
                at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:432)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1591)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.base/java.lang.Thread.run(Thread.java:829)
        Caused by: org.hibernate.HibernateException: identifier of an instance of com.redhat.rhn.domain.task.Task was altered from com.redhat.rhn.domain.task.Task$TaskId@cc8c8929 to com.redhat.rhn.domain.task.Task$TaskId@cc8c6982
                at org.hibernate.event.internal.DefaultFlushEntityEventListener.checkId(DefaultFlushEntityEventListener.java:78)
                at org.hibernate.event.internal.DefaultFlushEntityEventListener.getValues(DefaultFlushEntityEventListener.java:199)
                at org.hibernate.event.internal.DefaultFlushEntityEventListener.onFlushEntity(DefaultFlushEntityEventListener.java:159)
                at org.hibernate.event.internal.AbstractFlushingEventListener.flushEntities(AbstractFlushingEventListener.java:235)
                at org.hibernate.event.internal.AbstractFlushingEventListener.flushEverythingToExecutions(AbstractFlushingEventListener.java:94)
                at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:38)
                at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1472)
                ... 33 more
```

**Comment by mcalmer** [comment]
I think this will be fixed with the next Uyuni release.
https://github.com/uyuni-project/uyuni/pull/6542 was just merged and fix the same exception.
