### ISSUE TITLE
CSV extracts for system list in System Group and SSM views result in an error

### ISSUE THREAD

**Issue by ppanon2022** [uyuni-project/uyuni#6631]
### Problem description

Trying to run a CSV export when viewing systems in a System Group or in the SSM return

CSV Export Failed
The CSV file you requested could not be exported, likely due to one of the following reasons:

Your login session to the Uyuni expired. Uyuni sessions time out when your browser is left unattended for an extended period of time for security.
You may have followed an incorrect or out-of-date link. Double-check the link you followed - did you type or copy it correctly? If so, you may wish to contact the person who provided you with this link to let them know that it should be updated.
You may have used an out-of-date bookmark to get to this page. You may wish to delete or correct the bookmark you used.
To access the CSV you requested, please re-visit the page you wanted to export data from, and click the 'Export CSV' link again.

However it works on the global System List. Maybe changes to make it work for the cached/denormalized data on the System List broke the CSV export on the other non-cached views?

### Steps to reproduce

1. Open a System Group or the SSM
2. Switch to the Systems tab
3. Click on the Download CSV link/icon

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2023.01-220400.196.2.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2023.01-220400.196.2.uyuni2.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

### Useful logs

```bash
From rhn_web_ui.log

2023-02-17 16:01:36,433 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-5] ERROR com.redhat.rhn.frontend.action.CSVDownloadAction - Failed to generate CSV
java.lang.ClassCastException: class com.redhat.rhn.frontend.dto.SystemOverview cannot be cast to class com.redhat.rhn.frontend.dto.SystemSearchResult (com.redhat.rhn.frontend.dto.SystemOverview and com.redhat.rhn.frontend.dto.SystemSearchResult are in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @6941827a)
        at com.redhat.rhn.frontend.action.CSVDownloadAction.mergeWithPartialResult(CSVDownloadAction.java:219) ~[rhn.jar:?]
        at com.redhat.rhn.frontend.action.CSVDownloadAction.getStreamInfo(CSVDownloadAction.java:202) ~[rhn.jar:?]
        at org.apache.struts.actions.DownloadAction.execute(DownloadAction.java:106) ~[struts.jar:1.2.9]
        at com.redhat.rhn.frontend.action.CSVDownloadAction.execute(CSVDownloadAction.java:73) [rhn.jar:?]
        at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:431) [struts.jar:1.2.9]
        at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:237) [struts.jar:1.2.9]
        at com.redhat.rhn.frontend.struts.RhnRequestProcessor.process(RhnRequestProcessor.java:104) [rhn.jar:?]
        at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1196) [struts.jar:1.2.9]
        at org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:414) [struts.jar:1.2.9]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) [tomcat-servlet-4.0-api.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-servlet-4.0-api.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.36]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-websocket.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.36]
        at com.redhat.rhn.frontend.servlets.AuthFilter.doFilter(AuthFilter.java:99) [rhn.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.36]
        at com.opensymphony.module.sitemesh.filter.PageFilter.parsePage(PageFilter.java:142) [sitemesh.jar:?]
        at com.opensymphony.module.sitemesh.filter.PageFilter.doFilter(PageFilter.java:58) [sitemesh.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.36]
        at com.redhat.rhn.frontend.servlets.LocalizedEnvironmentFilter.doFilter(LocalizedEnvironmentFilter.java:71) [rhn.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.36]
        at com.redhat.rhn.frontend.servlets.EnvironmentFilter.doFilter(EnvironmentFilter.java:102) [rhn.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.36]
        at com.redhat.rhn.frontend.servlets.SessionFilter.doFilter(SessionFilter.java:59) [rhn.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.36]
        at com.redhat.rhn.frontend.servlets.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:98) [rhn.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.36]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [catalina.jar:9.0.36]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.36]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [catalina.jar:9.0.36]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.36]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.36]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690) [catalina.jar:9.0.36]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.36]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.36]
        at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:432) [tomcat-coyote.jar:9.0.36]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.36]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-coyote.jar:9.0.36]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1591) [tomcat-coyote.jar:9.0.36]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.36]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.36]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by digdilem-work** [comment]
I encountered this same issue today. 

I selected a number of machines from a scheduled report run yesterday and added it to SSM. 

I then viewed the machines in the SSM, scrolled to the bottom and hit "export CSV"  (From url: /rhn/systems/ssm/ListSystems.do )

A few seconds later, Uyuni responded with the error:

(At url: `/rhn/CSVDownloadAction.do?__CSV__exportColumnsParam=exportColumns_1680466951&__CSV_queryMode=query_1680466951&__CSV_uniqueName=1680466951` )

![image](https://github.com/uyuni-project/uyuni/assets/130057973/b43c7af0-224e-4b68-bd70-6682cb98e7e8)


/var/log/tomcat has this for localhost:

```
172.21.205.12 - - [01/Jun/2023:07:55:25 +0100] "POST /rhn/manager/frontend-log HTTP/1.1" 200 16
172.21.205.12 - - [01/Jun/2023:07:55:30 +0100] "GET /rhn/CSVDownloadAction.do?__CSV__exportColumnsParam=exportColumns_1680466951&__CSV_queryMode=query_1680466951&__CSV_uniqueName=1680466951 HTTP/1.1" 200 35517
172.21.205.12 - - [01/Jun/2023:07:55:30 +0100] "POST /rhn/manager/frontend-log HTTP/1.1" 200 16
172.21.205.12 - - [01/Jun/2023:07:55:30 +0100] "GET /rhn/errors/404.jsp HTTP/1.1" 404 4666
127.0.0.1 - - [01/Jun/2023:07:55:31 +0100] "GET /rhn/websocket/notifications HTTP/1.1" 101 -
```

/var/log/rhn/rhn_web_ui.log has:

```
2023-06-01 08:02:56,752 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-200] ERROR com.redhat.rhn.frontend.action.CSVDownloadAction - Failed to generate CSV
java.lang.ClassCastException: class com.redhat.rhn.frontend.dto.SystemOverview cannot be cast to class com.redhat.rhn.frontend.dto.SystemSearchResult (com.redhat.rhn.frontend.dto.SystemOverview and com.redhat.rhn.frontend.dto.SystemSearchResult are in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @7e928e2f)
        at com.redhat.rhn.frontend.action.CSVDownloadAction.mergeWithPartialResult(CSVDownloadAction.java:219) ~[rhn.jar:?]
```

I don't often use this feature and cannot say when it stopped working, but when I do it's quite a time saver so it would be very good to solve it. 


This error is 100% reproducable even when there is only one machine listed in the SSM.
