### ISSUE TITLE
Uyuni TASKOMATIC NOTIFICATION from uyuni

### ISSUE THREAD

**Issue by greinick** [uyuni-project/uyuni#6666]
Since the recent update to 2023.01 from 2022.12 I get  some notifications which I can't contextualise.

It might be related to a bug I read about, but can't remember the ID or the source, so may be someone has a hint.

The notification messages are different:

```
Taskomatic bunch repo-sync-bunch was scheduled to run within the repo-sync-1-143 schedule.
Subtask repo-sync failed.
For more information check null.
```

and 

```
Taskomatic bunch repo-sync-bunch was scheduled to run within the repo-sync-1-111 schedule.
Subtask repo-sync finished successfully and is back to normal.
```
In the logfile _rhn_taskomatic_daemon.log_ I see:

```
2023-02-28 05:16:00,107 [DefaultQuartzScheduler_Worker-8] INFO  com.redhat.rhn.taskomatic.task.SystemOverviewUpdateQueue - In the queue: 18
2023-02-28 05:17:00,024 [DefaultQuartzScheduler_Worker-16] WARN  com.redhat.rhn.taskomatic.task.ChannelRepodata - Maximum number of workers already put ... skipping.
2023-02-28 05:17:00,053 [DefaultQuartzScheduler_Worker-14] INFO  com.redhat.rhn.taskomatic.task.ErrataCacheTask - In the queue: 18
2023-02-28 05:17:39,884 [DefaultQuartzScheduler_Worker-1] ERROR com.redhat.rhn.taskomatic.task.RepoSyncTask - Executing a task threw an exception: java.lang.NumberFormatException
2023-02-28 05:17:39,884 [DefaultQuartzScheduler_Worker-1] ERROR com.redhat.rhn.taskomatic.task.RepoSyncTask - Message: For input string: "5054-2"
2023-02-28 05:17:39,884 [DefaultQuartzScheduler_Worker-1] ERROR com.redhat.rhn.taskomatic.task.RepoSyncTask - Cause:
2023-02-28 05:17:39,885 [DefaultQuartzScheduler_Worker-1] ERROR com.redhat.rhn.taskomatic.task.RepoSyncTask - Stack trace:java.lang.NumberFormatException: For input string: "5054-2"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Long.parseLong(Long.java:692)
        at java.base/java.lang.Long.parseLong(Long.java:817)
        at com.redhat.rhn.manager.content.ubuntu.UbuntuErrataManager.lambda$processUbuntuErrata$24(UbuntuErrataManager.java:280)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1764)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at com.redhat.rhn.manager.content.ubuntu.UbuntuErrataManager.lambda$processUbuntuErrata$26(UbuntuErrataManager.java:316)
        at com.redhat.rhn.common.util.TimeUtils.logTime(TimeUtils.java:48)
        at com.redhat.rhn.manager.content.ubuntu.UbuntuErrataManager.processUbuntuErrata(UbuntuErrataManager.java:233)
        at com.redhat.rhn.manager.content.ubuntu.UbuntuErrataManager.processUbuntuErrataByIds(UbuntuErrataManager.java:206)
        at com.redhat.rhn.manager.content.ubuntu.UbuntuErrataManager.sync(UbuntuErrataManager.java:197)
        at com.redhat.rhn.taskomatic.task.RepoSyncTask.execute(RepoSyncTask.java:118)
        at com.redhat.rhn.taskomatic.task.RhnJavaJob.execute(RhnJavaJob.java:105)
        at com.redhat.rhn.taskomatic.TaskoJob.doExecute(TaskoJob.java:214)
        at com.redhat.rhn.taskomatic.TaskoJob.runTask(TaskoJob.java:180)
        at com.redhat.rhn.taskomatic.TaskoJob.execute(TaskoJob.java:133)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
```

Within the Uyuni web interface all looks good to me, updated packages are synced for the different repos and can be installed on systems etc.

Thanks for feedback. /G

**Comment by greinick** [comment]
Thanks, that was the Bug / problem I.

I'll wait for the update.
