### ISSUE TITLE
 mgr-inter-sync fails with  Error message: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by chaitanyaveerla** [uyuni-project/uyuni#6938]
### Problem description

After upgrading to Uyuni version 2023.04 the mgr-inter-sync is failing 

08:48:13 --- Warning: SSL connection made but no CA certificate used
08:48:13
08:48:13
ERROR: there was a problem synchronizing the information.
       Error message: [Errno -2] Name or service not known

08:48:13 *** TRACEBACK:
08:48:13 Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/satsync.py", line 215, in main
    self.syncer.initialize()
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/satsync.py", line 557, in initialize
    auth.checkAuth()
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/xmlWireSource.py", line 378, in checkAuth
    authYN = self._xmlrpc('authentication.check', (self.systemid,))
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/xmlWireSource.py", line 357, in _xmlrpc
    retval = getattr(BaseWireSource.serverObj, function)(*params)
  File "/usr/lib/python3.6/site-packages/rhn/rpclib.py", line 659, in __call__
    return self._send(self._name, args)
  File "/usr/lib/python3.6/site-packages/rhn/rpclib.py", line 391, in _request
    self._handler, request, verbose=self._verbose)
  File "/usr/lib/python3.6/site-packages/rhn/transports.py", line 177, in request
    headers, fd = req.send_http(host, handler)
  File "/usr/lib/python3.6/site-packages/rhn/transports.py", line 728, in send_http
    self._connection.connect()
  File "/usr/lib/python3.6/site-packages/rhn/connections.py", line 187, in connect
    socket.AF_UNSPEC, socket.SOCK_STREAM)
  File "/usr/lib64/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

08:48:13 *** BASIC INFO:
 (<class 'socket.gaierror'>, gaierror(-2, 'Name or service not known'))

### Steps to reproduce

1.upgrade Uyuni-Server-release
2.mgr-inter-sync --list-channels

### Uyuni version

```bash
Loading repository data...
Reading installed packages...


Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2023.04-220400.204.2.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2023.04-220400.204.2.uyuni2.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

**Comment by mcalmer** [comment]
Sounds like network problems. Is DNS working?

**Comment by chaitanyaveerla** [comment]
Thaks mcalmer. I found reverse lookup is not working. after fixing the reverse lookup the issue got fixed.
