### ISSUE TITLE
'Unsupported product profile update called' while registering

### ISSUE THREAD

**Issue by a30000931** [uyuni-project/uyuni#7066]
### Problem description

Centos 7.9 Guest fails to register to SUMA 4.2.12 ( also observed on 4.1.15 )

```
/usr/sbin/rhnreg_ks --force --activationkey 1-centos7_2023-04-17.key

[Wed May 24 16:57:18 2023] up2date Unsupported product profile update called
[Wed May 24 16:57:18 2023] up2date
Traceback (most recent call last):
  File "/usr/sbin/rhnreg_ks", line 223, in <module>
    cli.run()
  File "/usr/lib/python2.7/site-packages/up2date_client/rhncli.py", line 91, in run
    sys.exit(self.main() or 0)
  File "/usr/sbin/rhnreg_ks", line 137, in main
    self.options.password, profilename, self.options.activationkey, other)
  File "/usr/lib/python2.7/site-packages/up2date_client/rhnreg.py", line 369, in registerSystem
    registerSystemAddProductProfile( s, auth_dict )
  File "/usr/lib/python2.7/site-packages/up2date_client/rhnreg.py", line 337, in registerSystemAddProductProfile
    raise NotImplementedError
<type 'exceptions.NotImplementedError'>:
```

### Steps to reproduce

1. Create Centos guest - I used 'CentOS Linux release 7.9.2009 (Core)'
2. attempt to register with SUMA using bootstrap
...

### Uyuni version

```bash
yum info python2-spacewalk-client-tools-4.4.5-2.1.uyuni.noarch
Loaded plugins: langpacks, susemanagerplugin, yumnotify
Installed Packages
Name        : python2-spacewalk-client-tools
Arch        : noarch
Version     : 4.4.5
Release     : 2.1.uyuni
Size        : 167 k
Repo        : installed
From repo   : susemanager:bootstrap
Summary     : Support programs and libraries for Spacewalk
URL         : https://github.com/uyuni-project/uyuni
License     : GPL-2.0-only
Description : Python 2 specific files of spacewalk-client-tools.
```

**Comment by avshiliaev** [comment]
You need a compatible version of the `python2-spacewalk-client-tools`. In your case it's `4.4.5-2.1`. Also note the SUMA 4.1 is EOL and the 4.2 is due on 31 Oct 2023.

**Comment by a30000931** [comment]
thanks for quick response @avshiliaev 

The SUMA bootstrap repo delivers that exact version:
```
 yum info python2-spacewalk-client-tools
Loaded plugins: langpacks, susemanagerplugin, yumnotify
Installed Packages
Name        : python2-spacewalk-client-tools
Arch        : noarch
Version     : 4.4.5
Release     : 2.1.uyuni
```

and yes i'm using SUMA 4.2.12

**Comment by a30000931** [comment]
in case anyone else gets stuck here
Suse engineering advised that SUMA 4.2 is only compatible with the 4.3 uyuni packages  - not 4.4 - which is what i had in my auto-generated bootstrap repo

as a test i created a traditional client compatible bootstrap repo by cloning and removing all 4.4 packages and can once again configure traditional clients

is there a way in mgr_bootstrap_data.py to specify a 'maximum' version for the installed packages?

**Comment by mbussolotto** [comment]
> is there a way in mgr_bootstrap_data.py to specify a 'maximum' version for the installed packages?

unfortunately it's not possible, you can just use these two formats:
```
| alternative. Example: "a|b" when package "a" cannot be found try "b". First match wins.
                One must be available.
 * optional. Example: "a*" if "a" is available add it, otherwise ignore it
```

**Comment by agraul** [comment]
Please open a support case in SUSE Customer Center for problems with SUSE Manager, this issue tracker is only for issues with Uyuni.
