### ISSUE TITLE
 Uyuni 2023.03: More than one row with the given identifier was found: XX, for class: com.redhat.rhn.domain.channel.Comps

### ISSUE THREAD

**Issue by phibid** [uyuni-project/uyuni#7095]
### Problem description

Not sure from when exactly it started to occur, but we are not able to manage our Channels anymore from the Web GUI nor spacewalk CLI on both our production and pre-production environments. AFAIK, no modifications were recently done on both systems.

Trying to access to https://uyuni/rhn/software/channels/All.do immediately trigger an 'Internal Server Error' with following stack trace in tomcat logs:

```
05-Jun-2023 08:57:26.727 SEVERE [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-4] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [action] in context with path [/rhn] threw exception [org.hibernate.HibernateException: More 
than one row with the given identifier was found: 169, for class: com.redhat.rhn.domain.channel.Channel] with root cause
        org.hibernate.HibernateException: More than one row with the given identifier was found: 169, for class: com.redhat.rhn.domain.channel.Channel
                at org.hibernate.loader.entity.plan.AbstractLoadPlanBasedEntityLoader.extractEntityResult(AbstractLoadPlanBasedEntityLoader.java:254)
                at org.hibernate.loader.entity.plan.AbstractLoadPlanBasedEntityLoader.load(AbstractLoadPlanBasedEntityLoader.java:198)
                at org.hibernate.persister.entity.AbstractEntityPersister.load(AbstractEntityPersister.java:4290)
                at org.hibernate.event.internal.DefaultLoadEventListener.loadFromDatasource(DefaultLoadEventListener.java:604)
                at org.hibernate.event.internal.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:572)
                at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:226)
                at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:350)
                at org.hibernate.event.internal.DefaultLoadEventListener.doOnLoad(DefaultLoadEventListener.java:127)
                at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:93)
                at org.hibernate.internal.SessionImpl.fireLoadNoChecks(SessionImpl.java:1277)
                at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1265)
                at org.hibernate.internal.SessionImpl.access$2000(SessionImpl.java:208)
                at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.doLoad(SessionImpl.java:2901)
                at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.load(SessionImpl.java:2875)
                at org.hibernate.internal.SessionImpl.get(SessionImpl.java:1097)
                at com.redhat.rhn.domain.channel.ChannelFactory.lookupById(ChannelFactory.java:85)
                at com.redhat.rhn.frontend.dto.ChannelTreeNode.compareTo(ChannelTreeNode.java:395)
                at com.redhat.rhn.frontend.dto.ChannelTreeNode.compareTo(ChannelTreeNode.java:33)
                at java.base/java.util.ComparableTimSort.binarySort(ComparableTimSort.java:262)
                at java.base/java.util.ComparableTimSort.sort(ComparableTimSort.java:207)
                at java.base/java.util.Arrays.sort(Arrays.java:1315)
                at java.base/java.util.Arrays.sort(Arrays.java:1509)
                at java.base/java.util.ArrayList.sort(ArrayList.java:1750)
                at java.base/java.util.Collections.sort(Collections.java:145)
                at com.redhat.rhn.frontend.filter.TreeFilter.handleOrphans(TreeFilter.java:197)
                at com.redhat.rhn.frontend.filter.TreeFilter.filterData(TreeFilter.java:93)
                at com.redhat.rhn.frontend.listview.ListControl.filterData(ListControl.java:167)
                at com.redhat.rhn.manager.BaseManager.processListControl(BaseManager.java:184)
                at com.redhat.rhn.manager.BaseManager.makeDataResult(BaseManager.java:94)
                at com.redhat.rhn.manager.channel.ChannelManager.allChannelTree(ChannelManager.java:308)
                at com.redhat.rhn.frontend.action.channel.AllChannelTreeAction.getDataResult(AllChannelTreeAction.java:36)
                at com.redhat.rhn.frontend.action.channel.BaseChannelTreeAction.execute(BaseChannelTreeAction.java:55)
                at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:431)
                at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:237)
                at com.redhat.rhn.frontend.struts.RhnRequestProcessor.process(RhnRequestProcessor.java:104)
                at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1196)
                at org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:414)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
                at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
                at com.redhat.rhn.frontend.servlets.AuthFilter.doFilter(AuthFilter.java:99)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
                at com.opensymphony.module.sitemesh.filter.PageFilter.parsePage(PageFilter.java:142)
                at com.opensymphony.module.sitemesh.filter.PageFilter.doFilter(PageFilter.java:58)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
                at com.redhat.rhn.frontend.servlets.LocalizedEnvironmentFilter.doFilter(LocalizedEnvironmentFilter.java:71)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
                at com.redhat.rhn.frontend.servlets.EnvironmentFilter.doFilter(EnvironmentFilter.java:102)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
                at com.redhat.rhn.frontend.servlets.SessionFilter.doFilter(SessionFilter.java:59)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
                at com.redhat.rhn.frontend.servlets.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:98)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
                at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
                at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:433)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1684)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.base/java.lang.Thread.run(Thread.java:829)
```

Knowing that the channel identifier 169 corresponds to AlmaLinux 8 channels, I have tried to remove them by hand, but no way neither, and we can notice that the problematic identifier varies in the output:

```
uyuni:/ # spacecmd -- softwarechannel_delete almalinux8-x86_64-appstream
INFO: Connected to https://uyuni/rpc/api as admin
Channels
--------
almalinux8-x86_64-appstream

Delete these channels [y/N]: y
ERROR: redstone.xmlrpc.XmlRpcFault: unhandled internal exception: org.hibernate.HibernateException: More than one row with the given identifier was found: 170, for class: com.redhat.rhn.domain.channel.Comps

```
```
uyuni:/ # spacecmd -- softwarechannel_delete almalinux8-x86_64-appstream
INFO: Connected to https://uyuni/rpc/api as admin
Channels
--------
almalinux8-x86_64-appstream

Delete these channels [y/N]: y
ERROR: redstone.xmlrpc.XmlRpcFault: unhandled internal exception: org.hibernate.HibernateException: More than one row with the given identifier was found: 170, for class: com.redhat.rhn.domain.channel.Comps
```

### Steps to reproduce

In the Web GUI, navigate in /rhn/software/channels/All.do which will trigger an 'Internal Server Error'.

### Uyuni version

```bash
uyuni:/# zypper info Uyuni-server-release
Loading repository data...
Reading installed packages...


Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2023.04-220400.204.2.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : out-of-date (version 2023.03-220400.199.1.uyuni2 installed)
Source package : Uyuni-Server-release-2023.04-220400.204.2.uyuni2.src
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

**Comment by slsnow** [comment]
It seems the devs already know about this, and it is being addressed (see [PR-6505](https://github.com/uyuni-project/uyuni/pull/6505)).

---

If you run `echo "select * from rhnchannelcomps where channel_id='169'" | spacewalk-sql --select-mode -`, you'll probably see duplicate entries.

That PR should prevent this from happening in the future, but if it's already happened, you may want to do the following:

## 1. Make a backup of the database, or at least dump the rhnchannelcomps table:
```
pg_dump -U <DB_USER> -t rhnchannelcomps -f rhnchannelcomps-dump.sql <DB_NAME>
```
## 2. Run the bellow script to clean up the duplicate entries:

```
spacewalk-sql --select-mode /path/to/delete-duplicates.sql
```

delete-duplicates.sql
```
DELETE FROM rhnchannelcomps c
WHERE comps_type_id = 1
AND EXISTS (
    SELECT last_modified
    FROM rhnchannelcomps
    WHERE id != c.id
    AND channel_id = c.channel_id
    AND last_modified >= c.last_modified
    AND comps_type_id = 1);
```

Perhaps there will some part of the scheme upgrade scripts to do this cleanup for you, but let me know how that goes for you.

---

## Restore

If there were any issues for some reason, you can restore that table, like this:
```
pg_restore -U <DB_USER> -d <DB_NAME> rhnchannelcomps-dump.sql
```

**Comment by phibid** [comment]
All solved ! Thanks for the solution provided.

```
uyuni:~ # echo "select * from rhnchannelcomps where channel_id='169'" | spacewalk-sql --select-mode -
 id  | channel_id |              relative_filename               |         last_modified         |            created            |           modified            | comps_type_id
-----+------------+----------------------------------------------+-------------------------------+-------------------------------+-------------------------------+---------------
 129 |        169 | rhn/comps/almalinux8-x86_64/comps.xml        | 2023-05-18 02:43:29.979614+00 | 2021-07-21 04:21:01.349158+00 | 2023-05-18 02:43:28.499635+00 |             1
 196 |        169 | rhn/comps/almalinux8-x86_64/comps.x86_64.xml | 2023-05-18 18:00:48.570534+00 | 2023-05-18 18:00:46.852525+00 | 2023-05-18 18:00:46.852525+00 |             1
(2 rows)
uyuni:~ #
uyuni:~ # spacewalk-sql --select-mode /var/lib/pgsql/delete-duplicate.sql
DELETE 5
uyuni:~ #
uyuni:~ #
uyuni:~ # echo "select * from rhnchannelcomps where channel_id='169'" | spacewalk-sql --select-mode -
 id  | channel_id |              relative_filename               |         last_modified         |            created            |           modified            | comps_type_id
-----+------------+----------------------------------------------+-------------------------------+-------------------------------+-------------------------------+---------------
 196 |        169 | rhn/comps/almalinux8-x86_64/comps.x86_64.xml | 2023-05-18 18:00:48.570534+00 | 2023-05-18 18:00:46.852525+00 | 2023-05-18 18:00:46.852525+00 |             1
(1 row)   
```

Closing :-)
