### ISSUE TITLE
SSM error when scheduling highstate with a maintenance window and timezone different to UTC

### ISSUE THREAD

**Issue by tbryant-ib** [uyuni-project/uyuni#7211]
### Problem description

When one or more systems with a maintenance schedule are added to the System Set Manager in Uyuni 2023.04 you are unable to schedule are high state using the selected maintenance window and receive the error "Server error, please check log files."

In my test I selected a maintenance window 6/29/23 3:00:00 AM NZST - 6/29/23 6:00:00 AM NZST.

**The request payload sent by the browser is incorrect**, it is specifying the **timezone as Z (UTC)** but using the **current NZST time converted to UTC** rather than a selecting a time within the maintenance window.
In this case I clicked Apply Highstate at 2023-06-28 15:37 NZST
`POST /rhn/manager/api/states/applyall`
`{"ids":[1000010167,1000010149],"earliest":"2023-06-28T03:37:33.756**Z**","actionChain":null,"test":false}`

The attached error log from `/var/log/rhn/rhn_web_ui.log` shows the requested API time converted from UTC back to NZST

## Workaround
As you are unable to schedule the highstate via SSM to run during the maintenance window, instead select Add to New Action Chain, go to the action chain, select the maintenance window and click Save and Schedule

### Steps to reproduce

1. Ensure your server and local timezone is different to UTC
2. Create a Maintenance Window, your current time must not be within the maintenance window, and the current UTC time must also not be within the maintenance window
3. Edit the properties of a system and set it to the maintenance window
4. Add the System to SSM
5. Go to SSM > States > Select the desired Maintenance Window > Click Apply Highstate

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2023.04-220400.204.2.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2023.04-220400.204.2.uyuni2.src
Summary        : Uyuni Server
```

### Useful logs

```bash
/var/log/rhn/rhn_web_ui.log
2023-06-28 15:37:33,867 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-4] ERROR com.suse.manager.webui.controllers.StatesAPI - Could not apply highstate
com.suse.manager.maintenance.NotInMaintenanceModeException: Systems assigned to these schedules (Mon-Thu 3am-6am) do not have a maintenance window at Wed Jun 28 15:37:32 NZST 2023
        at com.suse.manager.maintenance.MaintenanceManager.canActionBeScheduled(MaintenanceManager.java:666) ~[rhn.jar:?]
        at com.redhat.rhn.manager.action.ActionManager.scheduleForExecution(ActionManager.java:1549) ~[rhn.jar:?]
        at com.redhat.rhn.manager.action.ActionChainManager.createActions(ActionChainManager.java:622) ~[rhn.jar:?]
        at com.redhat.rhn.manager.action.ActionChainManager.scheduleApplyStates(ActionChainManager.java:338) ~[rhn.jar:?]
        at com.suse.manager.webui.controllers.StatesAPI.applyHighstate(StatesAPI.java:439) ~[rhn.jar:?]
        at com.suse.manager.webui.utils.SparkApplicationHelper.lambda$withUser$1(SparkApplicationHelper.java:98) ~[rhn.jar:?]
        at com.suse.manager.webui.utils.SparkApplicationHelper.lambda$asJson$10(SparkApplicationHelper.java:404) ~[rhn.jar:?]
```

### Additional information

As my test was conducted at 3PM which is 3AM UTC, depending on the logic and when times are converted and then checked it may be thinking the state is safe to apply immediately as 3AM UTC is within the maintenance window when ignoring time zones.

**Comment by mbussolotto** [comment]
I think this one is fixed, please re-open it if not, thanks!
