### ISSUE TITLE
Error syncing the channel - python 3.6

### ISSUE THREAD

**Issue by Ripper66Six** [uyuni-project/uyuni#7213]
### Problem description

Hello,

currently we get errors on channel sync on Ubuntu 20.04 repositories in python 3.6
We have tried to resolve this byself, but we cannot find solution.

Examples:

On mongodb6 repo:

Command '[/usr/bin/spacewalk-repo-sync, --channel, mongodb6-ubuntu-20.04-x86_64, --type, deb, --non-interactive]' exited with error code 1: 02:48:16 ======================================
02:48:16 | Channel: mongodb6-ubuntu-20.04-x86_64
02:48:16 ======================================
02:48:16 Sync of channel started.
02:48:17 Unhandled error occurred: 'Packages'
02:48:17 Unexpected error:
02:48:17 Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 610, in sync
http_headers=source_url["http_headers"])
File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/deb_src.py", line 339, in __init__
self.repo.verify()
File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/deb_src.py", line 183, in verify
if not repo.DpkgRepo(self.url, self._get_proxies(), self.gpg_verify).verify_packages_index():
File "/usr/lib/python3.6/site-packages/spacewalk/common/repo.py", line 435, in verify_packages_index
entry = self.get_release_index().get(name)
File "/usr/lib/python3.6/site-packages/spacewalk/common/repo.py", line 77, in get
return self[key]
KeyError: 'Packages'

02:48:17 Updating overview of 1 systems
02:48:17 Total time: 0:00:01

On Graylog repo:
Command '[/usr/bin/spacewalk-repo-sync, --channel, graylog-stable-5.0-x86_64, --type, deb, --non-interactive]' exited with error code 1: 02:45:09 ======================================
02:45:09 | Channel: graylog-stable-5.0-x86_64
02:45:09 ======================================
02:45:09 Sync of channel started.
02:45:10 Unhandled error occurred: '5.0/binary-amd64/Packages.gz'
02:45:10 Unexpected error:
02:45:10 Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 610, in sync
http_headers=source_url["http_headers"])
File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/deb_src.py", line 339, in __init__
self.repo.verify()
File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/deb_src.py", line 183, in verify
if not repo.DpkgRepo(self.url, self._get_proxies(), self.gpg_verify).verify_packages_index():
File "/usr/lib/python3.6/site-packages/spacewalk/common/repo.py", line 435, in verify_packages_index
entry = self.get_release_index().get(name)
File "/usr/lib/python3.6/site-packages/spacewalk/common/repo.py", line 77, in get
return self[key]
KeyError: '5.0/binary-amd64/Packages.gz'

02:45:10 Total time: 0:00:00

### Steps to reproduce

Not able to reproduce in other channels

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2023.04-220400.204.2.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2023.04-220400.204.2.uyuni2.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

### Uyuni proxy version (if used)

```bash
Information for package Uyuni-Proxy-release:
--------------------------------------------
Repository     : Uyuni Proxy Stable for openSUSE Leap 15.4 (x86_64)
Name           : Uyuni-Proxy-release
Version        : 2023.04-220400.204.2.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Proxy-release-2023.04-220400.204.2.uyuni2.src
Summary        : Uyuni Proxy
Description    :
    Uyuni Proxies extend large and/or geographically
    dispersed Uyuni environments to reduce load on the Uyuni
    Server, lower bandwidth needs, and provide faster local
    updates.
```

### Additional information

On checking the file reposync.py we are also not able to find any hint

**Comment by Ripper66Six** [comment]
Hello @agraul,

we have talked about this issue and it looks like the provider has implemented a failure in the last package.
We can close the issue
