### ISSUE TITLE
Duplicate system-uuids

### ISSUE THREAD

**Issue by st-man** [uyuni-project/uyuni#7217]
### Problem description

We are deploying latest stable Uyuni on a test env (server + two proxies) to choose a solution and make a decision. Environmen consists of 1000 opensuse154 VM systems, 1000 rhel7 and 1000 rhel8 VM's are used also. The virtualization team deployed the cloned machines (machine_id changed to unique value) so that all opensuse systems have the same uuid. Also, all 2000 rhel systems have another same uuid. (uuid which is returned with dmidecode: dmidecode -s system-uuid or salt [minion] smbios.get system-uuid, vmware name: uuid.bios https://kb.vmware.com/s/article/1541)
While bootstrapping the systems in bulk (by curl -Sks... and then accept all salt keys), uyuni cannot update it hardware profile correctly, since the systems have the same uuid. The rhnvirtualinstance has two unique records one with UUID form opensus and one from rhelx, but changing the virtual_system_id only. The hardwre profile refresh state return the error: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1
We're solved the issue by manually set the static UUID for each minion after bootstrapping (salt [minion] grains.set uuid "$(uuidgen)"), but the documentation doesn't specify the requirement to have a unique UUID for managed systems. 
Is it possible to somehow monitor that events and report the minion's system-uuid is not unique, but to complete the hardware profile update state without errors?

### Steps to reproduce

1. Make 1000 VM's with same system-uuid (uuid.bios)
2. Bootstrapping by curl -Sks https://server_hostname/pub/bootstrap/bootstrap-script.sh | /bin/bash
3. Accept the salt-keys (salt-key -A)
4. Look the WebUI Hardware profile updates log on the minions
5. Check the rhnvirtualinstance table (select * from rhnvirtualinstance;)

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni_server
Name           : Uyuni-Server-release
Version        : 2023.04-220400.204.2.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2023.04-220400.204.2.uyuni2.src
Summary        : Uyuni Server
```

### Uyuni proxy version (if used)

```bash
Information for package Uyuni-Proxy-release:
--------------------------------------------
Repository     : uyuni_proxy
Name           : Uyuni-Proxy-release
Version        : 2023.04-220400.204.2.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Proxy-release-2023.04-220400.204.2.uyuni2.src
Summary        : Uyuni Proxy
```

### Useful logs

```bash
rhn_web_ui.log:
2023-06-26 15:34:43,513 [salt-event-thread-40] ERROR com.redhat.rhn.frontend.events.TransactionHelper - com.suse.manager.reactor.PGEventListenerException
2023-06-26 15:34:43,513 [salt-event-thread-20] ERROR com.suse.manager.reactor.PGEventListener - Unexpected exception while executing a MessageAction
javax.persistence.OptimisticLockException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1
	at org.hibernate.internal.ExceptionConverterImpl.wrapStaleStateException(ExceptionConverterImpl.java:238) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:93) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1575) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
	at com.redhat.rhn.domain.server.VirtualInstanceFactory.lookupVirtualInstanceByUuid(VirtualInstanceFactory.java:357) ~[rhn.jar:?]
	at com.redhat.rhn.manager.system.VirtualInstanceManager.addGuestVirtualInstance(VirtualInstanceManager.java:235) ~[rhn.jar:?]
	at com.redhat.rhn.manager.system.VirtualInstanceManager.updateGuestVirtualInstance(VirtualInstanceManager.java:327) ~[rhn.jar:?]
	at com.suse.manager.reactor.hardware.HardwareMapper.updateVirtualInstance(HardwareMapper.java:733) ~[rhn.jar:?]
	at com.suse.manager.reactor.hardware.HardwareMapper.lambda$mapVirtualizationInfo$5(HardwareMapper.java:704) ~[rhn.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?]
	at com.suse.manager.reactor.hardware.HardwareMapper.mapVirtualizationInfo(HardwareMapper.java:703) ~[rhn.jar:?]
	at com.suse.manager.utils.SaltUtils.handleHardwareProfileUpdate(SaltUtils.java:1692) ~[rhn.jar:?]
	at com.suse.manager.utils.SaltUtils.lambda$updateServerAction$26(SaltUtils.java:595) ~[rhn.jar:?]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at com.suse.manager.utils.SaltUtils.updateServerAction(SaltUtils.java:595) ~[rhn.jar:?]
	at com.suse.manager.webui.services.SaltServerActionService.lambda$handleAction$147(SaltServerActionService.java:2670) ~[rhn.jar:?]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at com.suse.manager.webui.services.SaltServerActionService.lambda$handleAction$148(SaltServerActionService.java:2648) ~[rhn.jar:?]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at com.suse.manager.webui.services.SaltServerActionService.handleAction(SaltServerActionService.java:2641) ~[rhn.jar:?]
	at com.suse.manager.reactor.messaging.JobReturnEventMessageAction.lambda$execute$4(JobReturnEventMessageAction.java:134) ~[rhn.jar:?]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at com.suse.manager.reactor.messaging.JobReturnEventMessageAction.lambda$execute$5(JobReturnEventMessageAction.java:133) ~[rhn.jar:?]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at com.suse.manager.reactor.messaging.JobReturnEventMessageAction.execute(JobReturnEventMessageAction.java:133) ~[rhn.jar:?]
	at com.suse.manager.reactor.PGEventListener.lambda$notify$1(PGEventListener.java:76) ~[rhn.jar:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?]
	at com.suse.manager.reactor.PGEventListener.lambda$notify$2(PGEventListener.java:74) ~[rhn.jar:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?]
	at com.suse.manager.reactor.PGEventListener.notify(PGEventListener.java:71) ~[rhn.jar:?]
	at com.suse.salt.netapi.event.AbstractEventStream.notifyListeners(AbstractEventStream.java:64) ~[salt-netapi-clientsalt-netapi-client.jar:?]
	at com.suse.manager.reactor.PGEventStream.lambda$processEvents$6(PGEventStream.java:214) ~[rhn.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357) ~[?:?]
	at java.util.stream.Sink$ChainedReference.end(Sink.java:258) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
	at com.suse.manager.reactor.PGEventStream.processEvents(PGEventStream.java:208) ~[rhn.jar:?]
	at com.suse.manager.reactor.PGEventStream.lambda$notification$1(PGEventStream.java:192) ~[rhn.jar:?]
	at com.redhat.rhn.frontend.events.TransactionHelper.run(TransactionHelper.java:63) ~[rhn.jar:?]
	at com.redhat.rhn.frontend.events.TransactionHelper.handlingTransaction(TransactionHelper.java:48) ~[rhn.jar:?]
	at com.suse.manager.reactor.PGEventStream.lambda$notification$3(PGEventStream.java:191) ~[rhn.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1
	at org.hibernate.jdbc.Expectations$BasicExpectation.checkBatched(Expectations.java:67) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
	at org.hibernate.jdbc.Expectations$BasicExpectation.verifyOutcome(Expectations.java:54) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:46) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
	at org.hibernate.persister.entity.AbstractEntityPersister.delete(AbstractEntityPersister.java:3499) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
	at org.hibernate.persister.entity.AbstractEntityPersister.delete(AbstractEntityPersister.java:3756) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
	at org.hibernate.action.internal.EntityDeleteAction.execute(EntityDeleteAction.java:99) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:604) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:478) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:356) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
	at org.hibernate.event.internal.DefaultAutoFlushEventListener.onAutoFlush(DefaultAutoFlushEventListener.java:53) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
	at org.hibernate.internal.SessionImpl.autoFlushIfRequired(SessionImpl.java:1433) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1519) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
	at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1598) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1566) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
	... 47 more
```

**Comment by avshiliaev** [comment]
Hey @st-man 
Thanks for your report. Would [this part of the documentation](https://www.uyuni-project.org/uyuni-docs/en/uyuni/administration/troubleshooting/tshoot-registerclones.html) be relevant for your case?

**Comment by mikeletux** [comment]
@st-man any updates on this ticket or can we close it?

**Comment by avshiliaev** [comment]
Is this issue related?

https://github.com/uyuni-project/uyuni/issues/7568

**Comment by cbosdo** [comment]
No update for a very long time, closing
