### ISSUE TITLE
Schedule Pending Action don't end

### ISSUE THREAD

**Issue by st-man** [uyuni-project/uyuni#7226]
### Problem description

Some Schedule Pending Action events don't end. See /var/log/rhn/rhn_web_ui.log exceptions.
The column "statustype" is real absent it the "suseSystemOverview" table, but "status_type" is exist.

### Steps to reproduce

1. Schedule the action
2. Wait for end
3. Wait for end
4. Still waiting
5. Look at the /var/log/rhn/rhn_web_ui.log
6. Cancel action manually

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni_server
Name           : Uyuni-Server-release
Version        : 2023.04-220400.204.2.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2023.04-220400.204.2.uyuni2.src
Summary        : Uyuni Server
```

### Useful logs

```bash
2023-06-30 11:33:55,093 [ajp-nio-127.0.0.1-8009-exec-7] WARN  org.hibernate.engine.jdbc.spi.SqlExceptionHelper - SQL Error: 0, SQLState: 42703
2023-06-30 11:33:55,093 [ajp-nio-127.0.0.1-8009-exec-7] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - ERROR: column "statustype" does not exist
  Hint: Perhaps you meant to reference the column "o.status_type".
  Position: 119
2023-06-30 11:33:55,093 [ajp-nio-127.0.0.1-8009-exec-7] ERROR com.suse.manager.utils.PagedSqlQueryBuilder - Failed to process paged SQL query: SELECT O.* FROM suseSystemOverview O, rhnUserServerPerms USP WHERE O.id = USP.
server_id AND USP.user_id = :user_id ORDER BY statusType DESC
javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
        at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1575) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
        at com.suse.manager.utils.PagedSqlQueryBuilder.runQuery(PagedSqlQueryBuilder.java:355) ~[rhn.jar:?]
        at com.suse.manager.utils.PagedSqlQueryBuilder.run(PagedSqlQueryBuilder.java:338) ~[rhn.jar:?]
        at com.suse.manager.utils.PagedSqlQueryBuilder.run(PagedSqlQueryBuilder.java:277) ~[rhn.jar:?]
        at com.redhat.rhn.manager.system.SystemManager.systemListNew(SystemManager.java:914) ~[rhn.jar:?]
        at com.suse.manager.webui.controllers.SystemsController.allSystems(SystemsController.java:271) ~[rhn.jar:?]
        at com.suse.manager.webui.utils.SparkApplicationHelper.lambda$withUser$1(SparkApplicationHelper.java:98) ~[rhn.jar:?]
        at com.suse.manager.webui.utils.SparkApplicationHelper.lambda$asJson$10(SparkApplicationHelper.java:404) ~[rhn.jar:?]
        at spark.RouteImpl$1.handle(RouteImpl.java:72) ~[spark-corespark-core.jar:?]
        at spark.http.matching.Routes.execute(Routes.java:61) ~[spark-corespark-core.jar:?]
        at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:134) ~[spark-corespark-core.jar:?]
        at spark.servlet.SparkFilter.doFilter(SparkFilter.java:174) ~[spark-corespark-core.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[catalina.jar:9.0.75]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[catalina.jar:9.0.75]
        at com.redhat.rhn.frontend.servlets.AuthFilter.doFilter(AuthFilter.java:99) ~[rhn.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[catalina.jar:9.0.75]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[catalina.jar:9.0.75]
        at com.opensymphony.module.sitemesh.filter.PageFilter.parsePage(PageFilter.java:142) ~[sitemesh.jar:?]
        at com.opensymphony.module.sitemesh.filter.PageFilter.doFilter(PageFilter.java:58) ~[sitemesh.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[catalina.jar:9.0.75]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[catalina.jar:9.0.75]
        at com.redhat.rhn.frontend.servlets.LocalizedEnvironmentFilter.doFilter(LocalizedEnvironmentFilter.java:71) ~[rhn.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[catalina.jar:9.0.75]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[catalina.jar:9.0.75]
        at com.redhat.rhn.frontend.servlets.EnvironmentFilter.doFilter(EnvironmentFilter.java:102) ~[rhn.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[catalina.jar:9.0.75]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[catalina.jar:9.0.75]
        at com.redhat.rhn.frontend.servlets.SessionFilter.doFilter(SessionFilter.java:59) ~[rhn.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[catalina.jar:9.0.75]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[catalina.jar:9.0.75]
        at com.redhat.rhn.frontend.servlets.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:98) ~[rhn.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[catalina.jar:9.0.75]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[catalina.jar:9.0.75]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) ~[catalina.jar:9.0.75]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[catalina.jar:9.0.75]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481) ~[catalina.jar:9.0.75]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130) ~[catalina.jar:9.0.75]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[catalina.jar:9.0.75]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:673) ~[catalina.jar:9.0.75]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[catalina.jar:9.0.75]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[catalina.jar:9.0.75]
at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:422) ~[tomcat-coyote.jar:9.0.75]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-coyote.jar:9.0.75]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926) ~[tomcat-coyote.jar:9.0.75]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791) ~[tomcat-coyote.jar:9.0.75]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-coyote.jar:9.0.75]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-util.jar:9.0.75]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-util.jar:9.0.75]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-util.jar:9.0.75]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
        at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:106) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:69) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
        at org.hibernate.loader.Loader.getResultSet(Loader.java:2265) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2028) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1990) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
        at org.hibernate.loader.Loader.doQuery(Loader.java:949) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
        at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:351) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
        at org.hibernate.loader.Loader.doList(Loader.java:2787) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
        at org.hibernate.loader.Loader.doList(Loader.java:2770) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
        at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2604) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
        at org.hibernate.loader.Loader.list(Loader.java:2599) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
        at org.hibernate.loader.custom.CustomLoader.list(CustomLoader.java:338) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
        at org.hibernate.internal.SessionImpl.listCustomQuery(SessionImpl.java:2243) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
        at org.hibernate.internal.AbstractSharedSessionContract.list(AbstractSharedSessionContract.java:1069) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
        at org.hibernate.query.internal.NativeQueryImpl.doList(NativeQueryImpl.java:173) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
        at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1566) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
        ... 49 more
Caused by: org.postgresql.util.PSQLException: ERROR: column "statustype" does not exist
  Hint: Perhaps you meant to reference the column "o.status_type".
```

**Comment by mcalmer** [comment]
Is this known @cbosdo ?

**Comment by cbosdo** [comment]
No, I wasn't aware of it

**Comment by cbosdo** [comment]
The stack trace has no relation with the title of the issue: this is a failure when showing the systems list and ordering by status type, and even that I fail to understand how that can happen given the name in the UI passed to the query is `status_type`

**Comment by cbosdo** [comment]
This backtrace is fixed with https://github.com/uyuni-project/uyuni/commit/e58aa95
