### ISSUE TITLE
Error when salt minion gets deleted

### ISSUE THREAD

**Issue by sbluhm** [uyuni-project/uyuni#7234]
### Problem description

Deleting Salt minions results in an error in `/var/log/salt/api` (see below).

Root cause:
`https://github.com/uyuni-project/uyuni/blob/master/python/uyuni/common/fileutils.py` (https://github.com/uyuni-project/uyuni/pull/7070) has been adapted to use the context manager which tries to access `/etc/rhn/rhn.conf`.

When removing a client, Salt calls `fileutils.py` but does not have permission to `rhn.conf` (only user `root` and group `www`).

#### Potential fix suggestions:
- fix in `spacewalk-setup` to add user `salt` to group `www`. (in `uyuni/blob/master/spacewalk/setup/lib/Spacewalk/Setup.pm` and as `%post` in `uyuni/blob/master/spacewalk/setup/spacewalk-setup.spec`
- change the group ownership from `www` to susemanager for `/etc/rhn` and `/etc/rhn/rhn.conf`

### Steps to reproduce

1. unknown/delete client

### Uyuni version

```bash
Uyuni Master 2023-07-04
```

### Useful logs

```bash
`/var/log/salt/api`:


2023-07-03 11:59:45,543 [salt.loader.lazy :793 ][ERROR   ][13354] Failed to import runners mgrutil, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/spacewalk/common/rhnConfig.py", line 104, in modifiedYN
    si = os.stat(self.filename)
PermissionError: [Errno 13] Permission denied: '/etc/rhn/rhn.conf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/salt/loader/lazy.py", line 772, in _load_module
    mod = self.run(spec.loader.load_module)
  File "/usr/lib/python3.9/site-packages/salt/loader/lazy.py", line 1234, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/salt/loader/lazy.py", line 1249, in _run_as
    return _func_or_method(*args, **kwargs)
  File "<frozen importlib._bootstrap_external>", line 529, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1029, in load_module
  File "<frozen importlib._bootstrap_external>", line 854, in load_module
  File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/share/susemanager/modules/runners/mgrutil.py", line 11, in <module>
    import certs.mgr_ssl_cert_setup
  File "/usr/lib/python3.9/site-packages/certs/mgr_ssl_cert_setup.py", line 26, in <module>
    from spacewalk.common.rhnLog import initLOG, log_time, log_clean
  File "/usr/lib/python3.9/site-packages/spacewalk/common/__init__.py", line 21, in <module>
    from spacewalk.common.rhnApache import rhnApache
  File "/usr/lib/python3.9/site-packages/spacewalk/common/rhnApache.py", line 30, in <module>
    from spacewalk.common.rhnLog import log_debug, log_error, log_setreq
  File "/usr/lib/python3.9/site-packages/spacewalk/common/rhnLog.py", line 39, in <module>
    from uyuni.common.fileutils import getUidGid
  File "/usr/lib/python3.9/site-packages/uyuni/common/fileutils.py", line 30, in <module>
    from uyuni.common.context_managers import cfg_component
  File "/usr/lib/python3.9/site-packages/uyuni/common/context_managers.py", line 3, in <module>
    from spacewalk.common.rhnConfig import CFG, initCFG
  File "/usr/lib/python3.9/site-packages/spacewalk/common/rhnConfig.py", line 539, in <module>
    ALL_CFG.parse()
  File "/usr/lib/python3.9/site-packages/spacewalk/common/rhnConfig.py", line 129, in parse
    timeDiff = self.modifiedYN()
  File "/usr/lib/python3.9/site-packages/spacewalk/common/rhnConfig.py", line 107, in modifiedYN
    if e[0] == 13: #Error code 13 - Permission denied
TypeError: 'PermissionError' object is not subscriptable
```
```


### Additional information

Temporary workaround: Add user `salt` to group `www`

**Comment by mcalmer** [comment]
@agraul I think you are already working on it, right?

**Comment by agraul** [comment]
I looked at this problem yesterday with @cbosdo and we tracked the problem down to rhnConfig reading config files just to set a `PRODUCT_VERSION` constant. We prepared a patch (https://github.com/uyuni-project/uyuni/pull/7237) that stops reading the config files to set `PRODUCT_VERSION` and just hard codes it to "Uyuni" (with an override for "SUSE Manager" at RPM build time).

Now that the PR is merged, this should already be fixed. Can you try again @sbluhm ?

**Comment by cbosdo** [comment]
Fix merged in master now

**Comment by sbluhm** [comment]
Thank you @agraul . Will get this checked!

**Comment by sbluhm** [comment]
Confirmed working. Thanks a lot for this work.
