### ISSUE TITLE
Refreshing Debian packages throws an exception

### ISSUE THREAD

**Issue by HoussemNasri** [uyuni-project/uyuni#7441]
### Problem description

According to this [comment](https://github.com/saltstack/salt/issues/50550#issuecomment-439575884) the "keyword arguments are not valid" error is triggered when passing string arguments that contain an equal '=' character to a python module. 

```json
   "mgrcompat_|-packages_|-pkg.info_installed_|-module_run": {
      "name": "pkg.info_installed",
      "changes": {},
      "comment": "Module function pkg.info_installed threw an exception. Exception: The following keyword arguments are not valid: attr=status,arch,epoch,version,release,install_date_time_t, errors=report",
      "result": false,
      "__sls__": "packages.profileupdate",
      "__run_num__": 3,
      "start_time": "01:49:51.182069",
      "duration": 34.251,
      "__id__": "packages"
   }
```

Refs https://github.com/uyuni-project/uyuni/issues/1285
Refs https://github.com/saltstack/salt/issues/50550

### Steps to reproduce

1. From Uyuni UI, go to a Debian system
2. Select software and "update packages list"
3. Operation fails and a null pointer exception thrown in logs

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : server_pool_repo
Name           : Uyuni-Server-release
Version        : 2023.04-220400.204.2.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2023.04-220400.204.2.uyuni2.src
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

### Useful logs

```bash
java.lang.NullPointerException: null
	at com.suse.manager.utils.SaltUtils.updatePackages(SaltUtils.java:1535) ~[rhn.jar:?]
	at com.suse.manager.utils.SaltUtils.lambda$handlePackageProfileUpdate$81(SaltUtils.java:1386) ~[rhn.jar:?]
	at com.redhat.rhn.common.hibernate.HibernateFactory.lambda$doWithoutAutoFlushing$0(HibernateFactory.java:719) ~[rhn.jar:?]
	at com.redhat.rhn.common.hibernate.HibernateFactory.doWithoutAutoFlushing(HibernateFactory.java:663) ~[rhn.jar:?]
	at com.redhat.rhn.common.hibernate.HibernateFactory.doWithoutAutoFlushing(HibernateFactory.java:718) ~[rhn.jar:?]
	at com.redhat.rhn.common.hibernate.HibernateFactory.doWithoutAutoFlushing(HibernateFactory.java:691) ~[rhn.jar:?]
	at com.suse.manager.utils.SaltUtils.handlePackageProfileUpdate(SaltUtils.java:1355) ~[rhn.jar:?]
	at com.suse.manager.utils.SaltUtils.lambda$updateServerAction$25(SaltUtils.java:587) ~[rhn.jar:?]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at com.suse.manager.utils.SaltUtils.updateServerAction(SaltUtils.java:584) ~[rhn.jar:?]
	at com.suse.manager.webui.services.SaltServerActionService.lambda$handleAction$147(SaltServerActionService.java:2667) ~[rhn.jar:?]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at com.suse.manager.webui.services.SaltServerActionService.lambda$handleAction$148(SaltServerActionService.java:2645) ~[rhn.jar:?]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at com.suse.manager.webui.services.SaltServerActionService.handleAction(SaltServerActionService.java:2638) ~[rhn.jar:?]
	at com.suse.manager.reactor.messaging.JobReturnEventMessageAction.lambda$execute$4(JobReturnEventMessageAction.java:135) ~[rhn.jar:?]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at com.suse.manager.reactor.messaging.JobReturnEventMessageAction.lambda$execute$5(JobReturnEventMessageAction.java:134) ~[rhn.jar:?]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at com.suse.manager.reactor.messaging.JobReturnEventMessageAction.execute(JobReturnEventMessageAction.java:134) ~[rhn.jar:?]
	at com.suse.manager.reactor.PGEventListener.lambda$notify$1(PGEventListener.java:76) ~[rhn.jar:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?]
	at com.suse.manager.reactor.PGEventListener.lambda$notify$2(PGEventListener.java:74) ~[rhn.jar:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?]
	at com.suse.manager.reactor.PGEventListener.notify(PGEventListener.java:71) ~[rhn.jar:?]
	at com.suse.salt.netapi.event.AbstractEventStream.notifyListeners(AbstractEventStream.java:64) ~[salt-netapi-client-0.21.0.jar:?]
	at com.suse.manager.reactor.PGEventStream.lambda$processEvents$6(PGEventStream.java:214) ~[rhn.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357) ~[?:?]
	at java.util.stream.Sink$ChainedReference.end(Sink.java:258) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
	at com.suse.manager.reactor.PGEventStream.processEvents(PGEventStream.java:208) ~[rhn.jar:?]
	at com.suse.manager.reactor.PGEventStream.lambda$notification$1(PGEventStream.java:192) ~[rhn.jar:?]
	at com.redhat.rhn.frontend.events.TransactionHelper.run(TransactionHelper.java:63) ~[rhn.jar:?]
	at com.redhat.rhn.frontend.events.TransactionHelper.handlingTransaction(TransactionHelper.java:48) ~[rhn.jar:?]
	at com.suse.manager.reactor.PGEventStream.lambda$notification$3(PGEventStream.java:191) ~[rhn.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

**Comment by HoussemNasri** [comment]
It is reproducible when using `saltstack/salt`, nothing happens when using `openSUSE/salt`. Since it is expected for client systems to use the openSUSE fork of salt then this issue is invalid. There could, however, be an issue with https://github.com/uyuni-project/sumaform because that is what I used to provision a Debian client and it had the saltstack version of salt installed. 

Overall, I suggest closing this one and I'll try to investigate more about the problem and open an issue in https://github.com/uyuni-project/sumaform instead. 

Here is a gitter thread for more context: https://matrix.to/#/!hmhBzMsPSlnAgDeTDS:gitter.im/$lzu3TJeiQvkQqhhfmqIJ8aiZTt3O5bzAERWOkZ4MzbM?via=gitter.im&via=matrix.org&via=opensuse.org
