### ISSUE TITLE
mgr-inter-sync --list-channels problem sync with slave

### ISSUE THREAD

**Issue by santix1989** [uyuni-project/uyuni#7565]
### Problem description

Hi,
I have configured 2 nodes, one master and one slave, with this step : 

https://www.uyuni-project.org/uyuni-docs/en/uyuni/administration/iss.html

when started the sync, have this issue : 

```
mgr-inter-sync --list-channels
15:58:41 Uyuni - live synchronization
15:58:41    url: https://XXXXXXX
15:58:41    debug/output level: 1
15:58:41 --- Warning: SSL connection made but no CA certificate used
HOST:  443
15:58:41 
15:58:41 
ERROR: there was a problem synchronizing the information.
       Error message: [Errno -2] Name or service not known

15:58:41 *** TRACEBACK: 
15:58:41 Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/satsync.py", line 215, in main
    self.syncer.initialize()
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/satsync.py", line 558, in initialize
    auth.checkAuth()
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/xmlWireSource.py", line 378, in checkAuth
    authYN = self._xmlrpc('authentication.check', (self.systemid,))
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/xmlWireSource.py", line 357, in _xmlrpc
    retval = getattr(BaseWireSource.serverObj, function)(*params)
  File "/usr/lib/python3.6/site-packages/rhn/rpclib.py", line 659, in __call__
    return self._send(self._name, args)
  File "/usr/lib/python3.6/site-packages/rhn/rpclib.py", line 391, in _request
    self._handler, request, verbose=self._verbose)
  File "/usr/lib/python3.6/site-packages/rhn/transports.py", line 177, in request
    headers, fd = req.send_http(host, handler)
  File "/usr/lib/python3.6/site-packages/rhn/transports.py", line 728, in send_http
    self._connection.connect()
  File "/usr/lib/python3.6/site-packages/rhn/connections.py", line 191, in connect
    socket.AF_UNSPEC, socket.SOCK_STREAM)
  File "/usr/lib64/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

15:58:41 *** BASIC INFO:
 (<class 'socket.gaierror'>, gaierror(-2, 'Name or service not known'))

```
I have print the variables with :

`print("HOST:",self.host,self.port)
`
output is:
HOST:  443 

host is null, on: 
       ```
 results = socket.getaddrinfo(self.host, self.port,
            socket.AF_UNSPEC, socket.SOCK_STREAM)
```
if try to set the host with:

`self.host="XXXXXXXXXXX"`

the command work.

Could you help me please ?

### Steps to reproduce

1.
2.
3.
...

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2023.04-220400.204.2.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2023.04-220400.204.2.uyuni2.src
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

**Comment by mikeletux** [comment]
Hello there @santix1989 

Were you able to test code in PR https://github.com/uyuni-project/uyuni/pull/7588 ?
Looks like the change proposed there would solve the issue.

Please let me know.
Best regards!

**Comment by santix1989** [comment]
Hi,
@mikeletux this PR fix the issue.

Thanks
Best regards

**Comment by mikeletux** [comment]
I'll close this issue. Please keep an eye on the PR :smile:
