### ISSUE TITLE
Channel subscription fails on enabled COPR repository

### ISSUE THREAD

**Issue by sbluhm** [uyuni-project/uyuni#7631]
### Problem description

On an Enterprise Linux system, channel subscription fails when a copr repo has been previously enabled.
Error message: in /var/log/venv-salt-minion:

`Module function pkg.mod_repo threw an exception. Exception: list index out of range`

Section from the Uyuni event:
```
mgrcompat_|-disable_repo_copr:copr.fedorainfracloud.org:sbluhm:os-tools_|-pkg.mod_repo_|-module_run:
    name: pkg.mod_repo
    changes: {
        }
    comment: 'Module function pkg.mod_repo threw an exception. Exception: list index out of range'
    result: false
    __sls__: channels
    __run_num__: 13.0
    start_time: '10:47:22.571407'
    duration: 2.574
    __id__: disable_repo_copr:copr.fedorainfracloud.org:sbluhm:os-tools

```

### Steps to reproduce

1. Install a clean Enterprise Linux 9 System
2. `dnf copr enable sbluhm/os-tools`
3. enroll the system in Uyuni
4. Subscribe to channels

### Uyuni version

```bash
# dnf info Uyuni-Server-release
Last metadata expiration check: 1:02:01 ago on Tue 03 Oct 2023 09:10:38 PM CEST.
Installed Packages
Name         : Uyuni-Server-release
Version      : 2023.09
Release      : 230900.207.3.uyuni3
Architecture : x86_64
Size         : 1.4 k
Source       : Uyuni-Server-release-2023.09-230900.207.3.uyuni3.src.rpm
Repository   : @System
From repo    : copr:copr.fedorainfracloud.org:sbluhm:uyuni-release
Summary      : Uyuni Server
License      : GPL-2.0-or-later
Description  : Uyuni lets you efficiently manage physical, virtual,
             : and cloud-based Linux systems. It provides automated and cost-effective
             : configuration and software management, asset management, and system
             : provisioning.
```

### Useful logs

```bash
mgrcompat_|-disable_repo_copr:copr.fedorainfracloud.org:sbluhm:os-tools_|-pkg.mod_repo_|-module_run:
    name: pkg.mod_repo
    changes: {
        }
    comment: 'Module function pkg.mod_repo threw an exception. Exception: list index out of range'
    result: false
    __sls__: channels
    __run_num__: 13.0
    start_time: '10:47:22.571407'
    duration: 2.574
    __id__: disable_repo_copr:copr.fedorainfracloud.org:sbluhm:os-tools
```
```


### Additional information

Workaround:
Disable the copr repo: `dnf copr disable sbluhm/os-tools`

**Comment by bigmike-19** [comment]
I have a similar issue with Ubuntu 22.04, running on 2023.09
I had to remove an existing repo from /etc/apt/source.list and apply the channels again.

% if (repos_disabled.match_str in entry['file'])|string == repos_disabled.matching|string and entry.get('enabled', True) %}
disable_repo_{{ repos_disabled.count }}:
[...]
---
Traceback (most recent call last):
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/utils/templates.py", line 476, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 10, in top-level template code
  File "/var/cache/venv-salt-minion/files/base/channels/disablelocalrepos.sls", line 8, in top-level template code
    {% set repos = salt['pkg.list_repos']() %}
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/loader/lazy.py", line 1234, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/loader/lazy.py", line 1249, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/modules/aptpkg.py", line 1917, in list_repos
    signedby = _get_opts(line=source.line)["signedby"].get("value", "")
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/modules/aptpkg.py", line 1743, in _get_opts
    ret[other_opt]["value"] = opt.split("=", 1)[1]

FYI.

**Comment by sbluhm** [comment]
Interesting that you got a stack trace. Out of curiosity, did you increase the default log levels? I only got that one line.

**Comment by bigmike-19** [comment]
> @bigmike-19 , interesting that you got a stack trace. Out of curiosity, did you increase the default log levels? I only got that one line.

I looked at the web log /var/log/rhn/rhn_web_ui.log on the server and the client log /var/log/venv-salt-minion.log. I didn't increase the debug levels. I have only built Ubuntu systems since the upgrade to 2023.9. Though, it seems if I have other repos in the source.list file, the channel apply fails.

**Comment by sbluhm** [comment]
Thank you. Then I am not 100% sure if it is related. You get a Python stack trace, I don't. So my error might be in a different place in the code.

**Comment by avshiliaev** [comment]
Hey everyone, thanks for the report. 
It looks like a real bug on the salt side. Need to investigate a bit more.
