### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'append' on Uyuni client

### ISSUE THREAD

**Issue by hsh-it** [uyuni-project/uyuni#7867]
### Problem description

I installed salt-minion on an Ubuntu server 22.04 and started it. After that I could see the system in Uyuni and accept the key. That was yesterday. Today I get an error message on the system.

Furthermore, Uyuni does not recognize that the system has updates although the repository has been entered and updated today.

I was able to find something similar here:
https://github.com/saltstack/salt/issues/61135
https://github.com/uyuni-project/uyuni/issues/6330

### Steps to reproduce

1. Install Ubuntu 22.04
2. Install salt Minion
3. configure /etc/salt/minion.d/uyuni.conf
4. start service
5. wait a day
6. restart service
```
master: uyuni.domain.com
 
grains:
  susemanager:
    activation_key: "1-Fingerprint"
 
server_id_use_crc: adler32
enable_legacy_startup_events: False
enable_fqdns_grains: False
```

Restart Service:
`sudo systemctl restart salt-minion`

### Uyuni version

```bash
Retrieving repository 'Update repository of openSUSE Backports' metadata ................................................................................................[done]
Building repository 'Update repository of openSUSE Backports' cache .....................................................................................................[done]
Retrieving repository 'Update repository with updates from SUSE Linux Enterprise 15' metadata ...........................................................................[done]
Building repository 'Update repository with updates from SUSE Linux Enterprise 15' cache ................................................................................[done]
Retrieving repository 'Hauptaktualisierungs-Repository' metadata ........................................................................................................[done]
Building repository 'Hauptaktualisierungs-Repository' cache .............................................................................................................[done]
Retrieving repository 'Aktualisierungs-Repository (Nicht-Open-Source-Software)' metadata ................................................................................[done]
Building repository 'Aktualisierungs-Repository (Nicht-Open-Source-Software)' cache .....................................................................................[done]
Loading repository data...
Reading installed packages...


Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2023.04-220400.204.2.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2023.04-220400.204.2.uyuni2.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

### Useful logs

```bash
Logs from Client:
$ tail -n 100 /var/log/salt/minion

AttributeError: 'dict' object has no attribute 'append'
2023-11-14 14:31:37,429 [salt.minion      :2956][CRITICAL][1564] The beacon errored:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 2954, in handle_beacons
    beacons = self.process_beacons(self.functions)
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 516, in process_beacons
    return self.beacons.process(
  File "/usr/lib/python3/dist-packages/salt/beacons/__init__.py", line 74, in process
    b_config[mod].append({"_beacon_name": mod})
AttributeError: 'dict' object has no attribute 'append'
2023-11-14 14:31:38,429 [salt.minion      :2956][CRITICAL][1564] The beacon errored:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 2954, in handle_beacons
    beacons = self.process_beacons(self.functions)
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 516, in process_beacons
    return self.beacons.process(
  File "/usr/lib/python3/dist-packages/salt/beacons/__init__.py", line 74, in process
    b_config[mod].append({"_beacon_name": mod})
AttributeError: 'dict' object has no attribute 'append'
2023-11-14 14:31:39,429 [salt.minion      :2956][CRITICAL][1564] The beacon errored:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 2954, in handle_beacons
    beacons = self.process_beacons(self.functions)
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 516, in process_beacons
    return self.beacons.process(
  File "/usr/lib/python3/dist-packages/salt/beacons/__init__.py", line 74, in process
    b_config[mod].append({"_beacon_name": mod})
AttributeError: 'dict' object has no attribute 'append'
2023-11-14 14:31:40,428 [salt.minion      :2956][CRITICAL][1564] The beacon errored:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 2954, in handle_beacons
    beacons = self.process_beacons(self.functions)
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 516, in process_beacons
    return self.beacons.process(
  File "/usr/lib/python3/dist-packages/salt/beacons/__init__.py", line 74, in process
    b_config[mod].append({"_beacon_name": mod})
AttributeError: 'dict' object has no attribute 'append'
2023-11-14 14:31:41,429 [salt.minion      :2956][CRITICAL][1564] The beacon errored:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 2954, in handle_beacons
    beacons = self.process_beacons(self.functions)
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 516, in process_beacons
    return self.beacons.process(
  File "/usr/lib/python3/dist-packages/salt/beacons/__init__.py", line 74, in process
    b_config[mod].append({"_beacon_name": mod})
AttributeError: 'dict' object has no attribute 'append'
2023-11-14 14:31:42,428 [salt.minion      :2956][CRITICAL][1564] The beacon errored:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 2954, in handle_beacons
    beacons = self.process_beacons(self.functions)
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 516, in process_beacons
    return self.beacons.process(
  File "/usr/lib/python3/dist-packages/salt/beacons/__init__.py", line 74, in process
    b_config[mod].append({"_beacon_name": mod})
AttributeError: 'dict' object has no attribute 'append'
2023-11-14 14:31:43,429 [salt.minion      :2956][CRITICAL][1564] The beacon errored:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 2954, in handle_beacons
    beacons = self.process_beacons(self.functions)
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 516, in process_beacons
    return self.beacons.process(
  File "/usr/lib/python3/dist-packages/salt/beacons/__init__.py", line 74, in process
    b_config[mod].append({"_beacon_name": mod})
AttributeError: 'dict' object has no attribute 'append'
2023-11-14 14:31:44,428 [salt.minion      :2956][CRITICAL][1564] The beacon errored:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 2954, in handle_beacons
    beacons = self.process_beacons(self.functions)
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 516, in process_beacons
    return self.beacons.process(
  File "/usr/lib/python3/dist-packages/salt/beacons/__init__.py", line 74, in process
    b_config[mod].append({"_beacon_name": mod})
AttributeError: 'dict' object has no attribute 'append'
2023-11-14 14:31:45,429 [salt.minion      :2956][CRITICAL][1564] The beacon errored:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 2954, in handle_beacons
    beacons = self.process_beacons(self.functions)
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 516, in process_beacons
    return self.beacons.process(
  File "/usr/lib/python3/dist-packages/salt/beacons/__init__.py", line 74, in process
    b_config[mod].append({"_beacon_name": mod})
AttributeError: 'dict' object has no attribute 'append'
2023-11-14 14:31:46,429 [salt.minion      :2956][CRITICAL][1564] The beacon errored:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 2954, in handle_beacons
    beacons = self.process_beacons(self.functions)
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 516, in process_beacons
    return self.beacons.process(
  File "/usr/lib/python3/dist-packages/salt/beacons/__init__.py", line 74, in process
    b_config[mod].append({"_beacon_name": mod})
AttributeError: 'dict' object has no attribute 'append'
2023-11-14 14:31:47,428 [salt.minion      :2956][CRITICAL][1564] The beacon errored:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 2954, in handle_beacons
    beacons = self.process_beacons(self.functions)
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 516, in process_beacons
    return self.beacons.process(
  File "/usr/lib/python3/dist-packages/salt/beacons/__init__.py", line 74, in process
    b_config[mod].append({"_beacon_name": mod})
AttributeError: 'dict' object has no attribute 'append'
```
$ dpkg -l|grep salt
```
ii  salt-common                           3004.1+dfsg-2                           all          shared libraries that salt requires for all packages
ii  salt-minion                           3004.1+dfsg-2                           all          client package for salt, the distributed remote execution system
```

$ apt-cache show salt-minion
```
Package: salt-minion
Status: install ok installed
Priority: optional
Section: admin
Installed-Size: 118
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: all
Source: salt
Version: 3004.1+dfsg-2
Depends: dctrl-tools, lsb-base (>= 3.0-6), python3-m2crypto | python3-pycryptodome | python3-crypto (>= 2.6), python3-systemd | sysvinit-core, python3-zmq (>= 13.1.0), salt-common (= 3004.1+dfsg-2), python3:any
Pre-Depends: init-system-helpers (>= 1.54~)
Recommends: debconf-utils, dmidecode, e2fsprogs, fdisk
Suggests: python3-augeas
Conffiles:
 /etc/init.d/salt-minion e9f07842654aa259520859354cdd77ec
 /etc/salt/minion 0daf504dab3678034760c32db803347b
Description: client package for salt, the distributed remote execution system
 salt is a powerful remote execution manager that can be used to
 administer servers in a fast and efficient way.
 .
 It allows commands to be executed across large groups of
 servers. This means systems can be easily managed, but data can
 also be easily gathered.  Quick introspection into running
 systems becomes a reality.
 .
 Remote execution is usually used to set up a certain state on a
 remote system. Salt addresses this problem as well, the salt
 state system uses salt state files to define the state a server
 needs to be in.
 .
 Between the remote execution system, and state management Salt
 addresses the backbone of cloud and data center management.
 .
 This particular package provides the worker / agent for salt.
Description-md5: 68cd9e3bef3cabf85260509cdfa84a15
Original-Maintainer: Debian Salt Team <pkg-salt-team@alioth-lists.debian.net>
Homepage: https://saltproject.io/
```
```


### Additional information

_No response_

**Comment by hsh-it** [comment]
I get the same error when installing via the manufacturer:
https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/ubuntu.html

```
$ dpkg -l|grep salt
ii  salt-common                           3006.4                                  amd64        shared libraries that salt requires for all packages
ii  salt-minion                           3006.4                                  amd64        client package for salt, the distributed remote execution system
```

```
$ sudo tail -n 100 /var/log/salt/minion
AttributeError: 'dict' object has no attribute 'append'
2023-11-16 08:23:53,734 [salt.minion      :3029][CRITICAL][18035] The beacon errored:
Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 3027, in handle_beacons
    beacons = self.process_beacons(self.functions)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 510, in process_beacons
    return self.beacons.process(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/beacons/__init__.py", line 97, in process
    b_config[mod].append({"_beacon_name": mod})
AttributeError: 'dict' object has no attribute 'append'
2023-11-16 08:23:54,735 [salt.minion      :3029][CRITICAL][18035] The beacon errored:
Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 3027, in handle_beacons
    beacons = self.process_beacons(self.functions)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 510, in process_beacons
    return self.beacons.process(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/beacons/__init__.py", line 97, in process
    b_config[mod].append({"_beacon_name": mod})
AttributeError: 'dict' object has no attribute 'append'
2023-11-16 08:23:55,734 [salt.minion      :3029][CRITICAL][18035] The beacon errored:
Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 3027, in handle_beacons
    beacons = self.process_beacons(self.functions)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 510, in process_beacons
    return self.beacons.process(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/beacons/__init__.py", line 97, in process
    b_config[mod].append({"_beacon_name": mod})
AttributeError: 'dict' object has no attribute 'append'
2023-11-16 08:23:56,734 [salt.minion      :3029][CRITICAL][18035] The beacon errored:
Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 3027, in handle_beacons
    beacons = self.process_beacons(self.functions)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 510, in process_beacons
    return self.beacons.process(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/beacons/__init__.py", line 97, in process
    b_config[mod].append({"_beacon_name": mod})
AttributeError: 'dict' object has no attribute 'append'
2023-11-16 08:23:57,732 [salt.minion      :3029][CRITICAL][18035] The beacon errored:
Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 3027, in handle_beacons
    beacons = self.process_beacons(self.functions)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 510, in process_beacons
    return self.beacons.process(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/beacons/__init__.py", line 97, in process
    b_config[mod].append({"_beacon_name": mod})
AttributeError: 'dict' object has no attribute 'append'
2023-11-16 08:23:58,734 [salt.minion      :3029][CRITICAL][18035] The beacon errored:
Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 3027, in handle_beacons
    beacons = self.process_beacons(self.functions)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 510, in process_beacons
    return self.beacons.process(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/beacons/__init__.py", line 97, in process
    b_config[mod].append({"_beacon_name": mod})
AttributeError: 'dict' object has no attribute 'append'
2023-11-16 08:23:59,732 [salt.minion      :3029][CRITICAL][18035] The beacon errored:
Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 3027, in handle_beacons
    beacons = self.process_beacons(self.functions)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 510, in process_beacons
    return self.beacons.process(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/beacons/__init__.py", line 97, in process
    b_config[mod].append({"_beacon_name": mod})
AttributeError: 'dict' object has no attribute 'append'
2023-11-16 08:24:00,734 [salt.minion      :3029][CRITICAL][18035] The beacon errored:
Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 3027, in handle_beacons
    beacons = self.process_beacons(self.functions)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 510, in process_beacons
    return self.beacons.process(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/beacons/__init__.py", line 97, in process
    b_config[mod].append({"_beacon_name": mod})
AttributeError: 'dict' object has no attribute 'append'
2023-11-16 08:24:01,733 [salt.minion      :3029][CRITICAL][18035] The beacon errored:
Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 3027, in handle_beacons
    beacons = self.process_beacons(self.functions)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 510, in process_beacons
    return self.beacons.process(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/beacons/__init__.py", line 97, in process
    b_config[mod].append({"_beacon_name": mod})
AttributeError: 'dict' object has no attribute 'append'
2023-11-16 08:24:02,734 [salt.minion      :3029][CRITICAL][18035] The beacon errored:
Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 3027, in handle_beacons
    beacons = self.process_beacons(self.functions)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 510, in process_beacons
    return self.beacons.process(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/beacons/__init__.py", line 97, in process
    b_config[mod].append({"_beacon_name": mod})
AttributeError: 'dict' object has no attribute 'append'
2023-11-16 08:24:03,734 [salt.minion      :3029][CRITICAL][18035] The beacon errored:
Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 3027, in handle_beacons
    beacons = self.process_beacons(self.functions)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 510, in process_beacons
    return self.beacons.process(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/beacons/__init__.py", line 97, in process
    b_config[mod].append({"_beacon_name": mod})
AttributeError: 'dict' object has no attribute 'append'
```

```
$ sudo systemctl status salt-minion
● salt-minion.service - The Salt Minion
     Loaded: loaded (/lib/systemd/system/salt-minion.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2023-11-16 08:26:52 CET; 20s ago
       Docs: man:salt-minion(1)
             file:///usr/share/doc/salt/html/contents.html
             https://docs.saltproject.io/en/latest/contents.html
   Main PID: 19244 (python3.10)
      Tasks: 7 (limit: 19052)
     Memory: 63.2M
        CPU: 3.501s
     CGroup: /system.slice/salt-minion.service
             ├─19244 /opt/saltstack/salt/bin/python3.10 /usr/bin/salt-minion
             └─19253 "/opt/saltstack/salt/bin/python3.10 /usr/bin/salt-minion MultiMinionProcessManager MinionProcessManager"

Nov 16 08:27:11 v0028 salt-minion[19253]: AttributeError: 'dict' object has no attribute 'append'
Nov 16 08:27:12 v0028 salt-minion[19253]: [CRITICAL] The beacon errored:
Nov 16 08:27:12 v0028 salt-minion[19253]: Traceback (most recent call last):
Nov 16 08:27:12 v0028 salt-minion[19253]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 3027, in handle_beacons
Nov 16 08:27:12 v0028 salt-minion[19253]:     beacons = self.process_beacons(self.functions)
Nov 16 08:27:12 v0028 salt-minion[19253]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 510, in process_beacons
Nov 16 08:27:12 v0028 salt-minion[19253]:     return self.beacons.process(
Nov 16 08:27:12 v0028 salt-minion[19253]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/beacons/__init__.py", line 97, in process
Nov 16 08:27:12 v0028 salt-minion[19253]:     b_config[mod].append({"_beacon_name": mod})
Nov 16 08:27:12 v0028 salt-minion[19253]: AttributeError: 'dict' object has no attribute 'append'
```

System:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

$ uname -r
5.15.0-88-generic
```

**Comment by meaksh** [comment]
Hi @hsh-it , thanks for your report!

The problem here is that you are installing Salt package from the Ubuntu channels and NOT from the Uyuni Client Tools Channels for Ubuntu 22.04.

It is mandatory that the Salt package you use is coming from the Uyuni repositories. In case of Ubuntu 22.04, only Salt Bundle (venv-salt-minion) is supported.

Please, have a look to the "Registering Ubuntu 20.04 and 22.04 Clients" page in the Uyuni documentation: https://www.uyuni-project.org/uyuni-docs/en/uyuni/client-configuration/clients-ubuntu.html

Then you can follow the "Client Registration" guide: https://www.uyuni-project.org/uyuni-docs/en/uyuni/client-configuration/registration-methods.html

I'm closing this issue now. Feel free to reopen if that is necessary. Thanks!
