### ISSUE TITLE
Content Lifecycle Project shows 500 Internal Server Error

### ISSUE THREAD

**Issue by j-kihet** [uyuni-project/uyuni#7994]
### Problem description

When selecting a Content Lifecycle Project, WebUI shows 500 Internal Server Error.
Oracle linux 8 and 9.
### Steps to reproduce

1. Open a Content Lifecycle Project from WebUI

### Uyuni version

```bash
2023.09 this also happens in 2023.10
```

### Uyuni proxy version (if used)

```bash
not used
```

### Useful logs

```bash
rhn_web_ui.log
2023-11-29 12:28:05,597 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-1] ERROR spark.http.matching.GeneralError -
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 2 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226) ~[google-gson_google-gsongson.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:954) ~[google-gson_google-gsongson.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:919) ~[google-gson_google-gsongson.jar:?]
	at com.redhat.rhn.domain.contentmgmt.modulemd.ModulemdApi.callSync(ModulemdApi.java:140) ~[rhn.jar:?]
	at com.redhat.rhn.domain.contentmgmt.modulemd.ModulemdApi.getPackagesForModules(ModulemdApi.java:91) ~[rhn.jar:?]
	at com.redhat.rhn.manager.contentmgmt.DependencyResolver.resolveModularDependencies(DependencyResolver.java:142) ~[rhn.jar:?]
	at com.redhat.rhn.manager.contentmgmt.DependencyResolver.resolveFilters(DependencyResolver.java:119) ~[rhn.jar:?]
	at com.redhat.rhn.domain.contentmgmt.validation.ModularDependencyValidator.validate(ModularDependencyValidator.java:81) ~[rhn.jar:?]
	at com.redhat.rhn.domain.contentmgmt.validation.ContentProjectValidator.lambda$validate$0(ContentProjectValidator.java:63) ~[rhn.jar:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at com.redhat.rhn.domain.contentmgmt.validation.ContentProjectValidator.validate(ContentProjectValidator.java:64) ~[rhn.jar:?]
	at com.suse.manager.webui.controllers.contentmanagement.mappers.ResponseMappers.mapProjectFromDB(ResponseMappers.java:188) ~[rhn.jar:?]
	at com.suse.manager.webui.controllers.contentmanagement.ContentManagementViewsController.lambda$editProjectView$2(ContentManagementViewsController.java:125) ~[rhn.jar:?]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at com.suse.manager.webui.controllers.contentmanagement.ContentManagementViewsController.editProjectView(ContentManagementViewsController.java:107) ~[rhn.jar:?]
	at com.suse.manager.webui.utils.SparkApplicationHelper.lambda$withRolesTemplate$5(SparkApplicationHelper.java:228) ~[rhn.jar:?]
	at com.suse.manager.webui.utils.SparkApplicationHelper.lambda$withCsrfToken$6(SparkApplicationHelper.java:322) ~[rhn.jar:?]
	at spark.TemplateViewRouteImpl$1.handle(TemplateViewRouteImpl.java:66) ~[spark-corespark-core.jar:?]
	at spark.http.matching.Routes.execute(Routes.java:61) ~[spark-corespark-core.jar:?]
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:134) ~[spark-corespark-core.jar:?]
	at spark.servlet.SparkFilter.doFilter(SparkFilter.java:174) ~[spark-corespark-core.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[catalina.jar:9.0.75]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[catalina.jar:9.0.75]
	at com.redhat.rhn.frontend.servlets.AuthFilter.doFilter(AuthFilter.java:99) ~[rhn.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[catalina.jar:9.0.75]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[catalina.jar:9.0.75]
	at com.opensymphony.module.sitemesh.filter.PageFilter.parsePage(PageFilter.java:142) ~[sitemesh.jar:?]
	at com.opensymphony.module.sitemesh.filter.PageFilter.doFilter(PageFilter.java:58) ~[sitemesh.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[catalina.jar:9.0.75]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[catalina.jar:9.0.75]
	at com.redhat.rhn.frontend.servlets.LocalizedEnvironmentFilter.doFilter(LocalizedEnvironmentFilter.java:71) ~[rhn.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[catalina.jar:9.0.75]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[catalina.jar:9.0.75]
	at com.redhat.rhn.frontend.servlets.EnvironmentFilter.doFilter(EnvironmentFilter.java:99) ~[rhn.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[catalina.jar:9.0.75]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[catalina.jar:9.0.75]
	at com.redhat.rhn.frontend.servlets.SessionFilter.doFilter(SessionFilter.java:59) ~[rhn.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[catalina.jar:9.0.75]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[catalina.jar:9.0.75]
	at com.redhat.rhn.frontend.servlets.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:98) ~[rhn.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[catalina.jar:9.0.75]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[catalina.jar:9.0.75]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) ~[catalina.jar:9.0.75]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[catalina.jar:9.0.75]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481) ~[catalina.jar:9.0.75]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130) ~[catalina.jar:9.0.75]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[catalina.jar:9.0.75]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:673) ~[catalina.jar:9.0.75]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[catalina.jar:9.0.75]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[catalina.jar:9.0.75]
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:422) ~[tomcat-coyote.jar:9.0.75]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-coyote.jar:9.0.75]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926) ~[tomcat-coyote.jar:9.0.75]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791) ~[tomcat-coyote.jar:9.0.75]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-coyote.jar:9.0.75]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-util.jar:9.0.75]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-util.jar:9.0.75]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-util.jar:9.0.75]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 2 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384) ~[google-gson_google-gsongson.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215) ~[google-gson_google-gsongson.jar:?]
	... 64 more
2023-11-29 12:28:06,642 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-3] ERROR spark.http.matching.GeneralError -
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 2 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226) ~[google-gson_google-gsongson.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:954) ~[google-gson_google-gsongson.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:919) ~[google-gson_google-gsongson.jar:?]
	at com.redhat.rhn.domain.contentmgmt.modulemd.ModulemdApi.callSync(ModulemdApi.java:140) ~[rhn.jar:?]
	at com.redhat.rhn.domain.contentmgmt.modulemd.ModulemdApi.getPackagesForModules(ModulemdApi.java:91) ~[rhn.jar:?]
	at com.redhat.rhn.manager.contentmgmt.DependencyResolver.resolveModularDependencies(DependencyResolver.java:142) ~[rhn.jar:?]
	at com.redhat.rhn.manager.contentmgmt.DependencyResolver.resolveFilters(DependencyResolver.java:119) ~[rhn.jar:?]
	at com.redhat.rhn.domain.contentmgmt.validation.ModularDependencyValidator.validate(ModularDependencyValidator.java:81) ~[rhn.jar:?]
	at com.redhat.rhn.domain.contentmgmt.validation.ContentProjectValidator.lambda$validate$0(ContentProjectValidator.java:63) ~[rhn.jar:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at com.redhat.rhn.domain.contentmgmt.validation.ContentProjectValidator.validate(ContentProjectValidator.java:64) ~[rhn.jar:?]
	at com.suse.manager.webui.controllers.contentmanagement.mappers.ResponseMappers.mapProjectFromDB(ResponseMappers.java:188) ~[rhn.jar:?]
	at com.suse.manager.webui.controllers.contentmanagement.ContentManagementViewsController.lambda$editProjectView$2(ContentManagementViewsController.java:125) ~[rhn.jar:?]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at com.suse.manager.webui.controllers.contentmanagement.ContentManagementViewsController.editProjectView(ContentManagementViewsController.java:107) ~[rhn.jar:?]
	at com.suse.manager.webui.utils.SparkApplicationHelper.lambda$withRolesTemplate$5(SparkApplicationHelper.java:228) ~[rhn.jar:?]
	at com.suse.manager.webui.utils.SparkApplicationHelper.lambda$withCsrfToken$6(SparkApplicationHelper.java:322) ~[rhn.jar:?]
	at spark.TemplateViewRouteImpl$1.handle(TemplateViewRouteImpl.java:66) ~[spark-corespark-core.jar:?]
	at spark.http.matching.Routes.execute(Routes.java:61) ~[spark-corespark-core.jar:?]
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:134) ~[spark-corespark-core.jar:?]
	at spark.servlet.SparkFilter.doFilter(SparkFilter.java:174) ~[spark-corespark-core.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[catalina.jar:9.0.75]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[catalina.jar:9.0.75]
	at com.redhat.rhn.frontend.servlets.AuthFilter.doFilter(AuthFilter.java:99) ~[rhn.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[catalina.jar:9.0.75]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[catalina.jar:9.0.75]
	at com.opensymphony.module.sitemesh.filter.PageFilter.parsePage(PageFilter.java:142) ~[sitemesh.jar:?]
	at com.opensymphony.module.sitemesh.filter.PageFilter.doFilter(PageFilter.java:58) ~[sitemesh.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[catalina.jar:9.0.75]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[catalina.jar:9.0.75]
	at com.redhat.rhn.frontend.servlets.LocalizedEnvironmentFilter.doFilter(LocalizedEnvironmentFilter.java:71) ~[rhn.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[catalina.jar:9.0.75]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[catalina.jar:9.0.75]
	at com.redhat.rhn.frontend.servlets.EnvironmentFilter.doFilter(EnvironmentFilter.java:99) ~[rhn.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[catalina.jar:9.0.75]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[catalina.jar:9.0.75]
	at com.redhat.rhn.frontend.servlets.SessionFilter.doFilter(SessionFilter.java:59) ~[rhn.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[catalina.jar:9.0.75]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[catalina.jar:9.0.75]
	at com.redhat.rhn.frontend.servlets.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:98) ~[rhn.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[catalina.jar:9.0.75]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[catalina.jar:9.0.75]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) ~[catalina.jar:9.0.75]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[catalina.jar:9.0.75]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481) ~[catalina.jar:9.0.75]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130) ~[catalina.jar:9.0.75]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[catalina.jar:9.0.75]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:673) ~[catalina.jar:9.0.75]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[catalina.jar:9.0.75]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[catalina.jar:9.0.75]
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:422) ~[tomcat-coyote.jar:9.0.75]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-coyote.jar:9.0.75]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926) ~[tomcat-coyote.jar:9.0.75]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791) ~[tomcat-coyote.jar:9.0.75]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-coyote.jar:9.0.75]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-util.jar:9.0.75]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-util.jar:9.0.75]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-util.jar:9.0.75]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 2 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384) ~[google-gson_google-gsongson.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215) ~[google-gson_google-gsongson.jar:?]
	... 64 more
```

spacecmd error
```
ERROR: <Fault -1: 'redstone.xmlrpc.XmlRpcFault: unhandled internal exception: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 2 column 1 path $'>
```

### Additional information

Trying to build the project also results in an error using spacecmd.
This is not for every lifecycle project but most in my case.
I can create new projects and build them from the same source.
It broke out of nowhere. The last build of the project was weeks ago.

**Comment by tuudik** [comment]
+1 having exactly the same issue for last two days

**Comment by jkarjanl** [comment]
One more detail: We have only Rocky Linux 8 channels and Content Lifecycle projects in our Uyuni server. They released RockyLinux 8.9 at 22th November, perhaps some rpm package is corrupted of somewhat different and Uyuni can't process it properly? When the problem occurs there are every time Content Lifecycle filters involved.

**Comment by cbbayburt** [comment]
Hi @j-kihet, I tried to reproduce the issue with some freshly synced repositories (OL9, Rocky 8.9) but couldn't reproduce the issue on 2023.10.

However, looking at the exception message, it seems that a recent update of the AppStream repository included some change in the module metadata structure that breaks the CLM.

Could you please create a tarball of the modules directory of whatever AppStream repo you are using as a source in your CLM project in your Uyuni server and upload it so I can examine:

`/var/spacewalk/rhn/modules/<appstream_repo_label>`

**Comment by tuudik** [comment]
@jkarjanl Can you post also your module directory tarball? Or did you manage to find a workaround?

**Comment by cbbayburt** [comment]
Interesting.. I tried the data from both uploads but both seem to work fine. What exact versions are installed for `spacewalk-java` and `mgr-libmod` packages on your system?

**Comment by j-kihet** [comment]
@cbbayburt 
```
Information for package spacewalk-java:
---------------------------------------
Repository     : Uyuni Server Stable
Name           : spacewalk-java
Version        : 4.4.20-230900.1.3.uyuni3
```
```
Repository     : Uyuni Server Stable
Name           : mgr-libmod
Version        : 4.4.2-230900.1.2.uyuni3
```

**Comment by jkarjanl** [comment]
spacewalk-java-4.4.14-220400.1.2.uyuni2.noarch
mgr-libmod-4.4.1-220400.1.1.uyuni2.noarch

**Comment by jkarjanl** [comment]
I didn't change the file, but I manually renamed all *.bz2 -files in /var/spacewalk/rhn/modules/remi-8-modular/ directory and then updated database accordingly:

`select * from rhnchannelcomps WHERE relative_filename LIKE '%bz2';`

`UPDATE rhnchannelcomps
SET relative_filename = substring(relative_filename FROM 1 FOR length(relative_filename) - 4)
WHERE relative_filename LIKE '%.bz2';`

After that everything worked. Of course I must repeat the process after every repo sync.
