### ISSUE TITLE
How to give answers to download questions

### ISSUE THREAD

**Issue by 4Ara** [uyuni-project/uyuni#8198]
# Question

When downloading power tools to support Sles on IBM Power (sles versions 12.5, 15.3, 15.4 , 15.5)

    IBM POWER Tools for SLE 15 ppc64le 
    IBM POWER Advance Toolchain for SLE 15 ppc64le 

![image](https://github.com/uyuni-project/uyuni/assets/25799051/56b246c5-f041-44eb-8bd8-9017eab938c6)

The question seems to be where to accept the key or how to answer the download question "Do you want to reject the key, trust temporarily, or trust always? [r/t/a/?] (r): r"

Actually i get the following error found in /var/log/rhn/rhn_taskomatic_daemon.log.

thanks in advance

2024-01-23 14:13:58,157 [DefaultQuartzScheduler_Worker-7] INFO  com.redhat.rhn.taskomatic.task.RepoSyncTask - Syncing repos for channel: IBM-POWER-Tools for ppc64le SAP SP4
2024-01-23 14:14:01,018 [Thread-557529] INFO  com.redhat.rhn.taskomatic.task.RepoSyncTask - 14:13:58 ======================================
14:13:58 | Channel: ibm-power-tools-ppc64le-sap-sp4
14:13:58 ======================================
14:13:58 Sync of channel started.
**_Retrieving repository 'ibm-power-tools-ppc64le-sap-sp4' metadata [....._**

New repository or package signing key received:

  Repository:       ibm-power-tools-ppc64le-sap-sp4
  Key Fingerprint:  0185 5EF7 3368 3A52 FFED 96B1 0A28 58B0 3E6E 42BE
  Key Name:         Linux on POWER (IBM Linux Technology Center) <poweryum@linux.vnet.ibm.com>
  Key Algorithm:    DSA 1024
  Key Created:      Thu 19 May 2011 11:55:24 PM CEST
  Key Expires:      (does not expire)
  Subkey:           37275A560BEE1DDD 2011-05-19 [does not expire]
  Rpm Name:         gpg-pubkey-3e6e42be-4dd591cc

    **_Note: Signing data enables the recipient to verify that no modifications occurred after the data
    were signed. Accepting data with no, wrong or unknown signature can lead to a corrupted system
    and in extreme cases even to a system compromise.

    Note: A GPG pubkey is clearly identified by its fingerprint. Do not rely on the key's name. If
    you are not sure whether the presented key is authentic, ask the repository provider or check
    their web site. Many providers maintain a web page showing the fingerprints of the GPG keys they
    are using._**

**_Do you want to reject the key, trust temporarily, or trust always? [r/t/a/?] (r): r_**
error]
14:14:00 RepoMDError: Cannot access repository.
Repository 'ibm-power-tools-ppc64le-sap-sp4' is invalid.
[ibm-power-tools-ppc64le-sap-sp4|https://public.dhe.ibm.com/software/server/POWER/Linux/yum/OSS/SLES/15/ppc64le/] Valid metadata not found at specified URL
History:
 - Signature verification failed for repomd.xml
 - Can't provide /repodata/repomd.xml

Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'ibm-power-tools-ppc64le-sap-sp4' because of the above error.
Could not refresh the repositories because of errors.

14:14:00 Total time: 0:00:02

2024-01-23 14:14:01,018 [DefaultQuartzScheduler_Worker-7] ERROR com.redhat.rhn.taskomatic.task.RepoSyncTask - Unable to sync channel 661
org.quartz.JobExecutionException: Command '[/usr/bin/spacewalk-repo-sync, --channel, ibm-power-tools-ppc64le-sap-sp4, --type, yum, --non-interactive]' exited with error code 1: 14:13:58 ======================================
14:13:58 | Channel: ibm-power-tools-ppc64le-sap-sp4
14:13:58 ======================================
14:13:58 Sync of channel started.
Retrieving repository 'ibm-power-tools-ppc64le-sap-sp4' metadata [.....

New repository or package signing key received:

  Repository:       ibm-power-tools-ppc64le-sap-sp4
  Key Fingerprint:  0185 5EF7 3368 3A52 FFED 96B1 0A28 58B0 3E6E 42BE
  Key Name:         Linux on POWER (IBM Linux Technology Center) <poweryum@linux.vnet.ibm.com>
  Key Algorithm:    DSA 1024
  Key Created:      Thu 19 May 2011 11:55:24 PM CEST
  Key Expires:      (does not expire)
  Subkey:           37275A560BEE1DDD 2011-05-19 [does not expire]
  Rpm Name:         gpg-pubkey-3e6e42be-4dd591cc

    Note: Signing data enables the recipient to verify that no modifications occurred after the data
    were signed. Accepting data with no, wrong or unknown signature can lead to a corrupted system
    and in extreme cases even to a system compromise.

    Note: A GPG pubkey is clearly identified by its fingerprint. Do not rely on the key's name. If
    you are not sure whether the presented key is authentic, ask the repository provider or check
    their web site. Many providers maintain a web page showing the fingerprints of the GPG keys they
    are using.

Do you want to reject the key, trust temporarily, or trust always? [r/t/a/?] (r): r
error]
14:14:00 RepoMDError: Cannot access repository.
Repository 'ibm-power-tools-ppc64le-sap-sp4' is invalid.
[ibm-power-tools-ppc64le-sap-sp4|https://public.dhe.ibm.com/software/server/POWER/Linux/yum/OSS/SLES/15/ppc64le/] Valid metadata not found at specified URL
History:
 - Signature verification failed for repomd.xml
 - Can't provide /repodata/repomd.xml

Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'ibm-power-tools-ppc64le-sap-sp4' because of the above error.
Could not refresh the repositories because of errors.

14:14:00 Total time: 0:00:02

    at com.redhat.rhn.taskomatic.task.RhnJavaJob.executeExtCmd(RhnJavaJob.java:88) ~[rhn.jar:?]
    at com.redhat.rhn.taskomatic.task.RepoSyncTask.execute(RepoSyncTask.java:97) ~[rhn.jar:?]
    at com.redhat.rhn.taskomatic.task.RhnJavaJob.execute(RhnJavaJob.java:56) ~[rhn.jar:?]
    at com.redhat.rhn.taskomatic.TaskoJob.doExecute(TaskoJob.java:240) ~[rhn.jar:?]
    at com.redhat.rhn.taskomatic.TaskoJob.runTemplate(TaskoJob.java:193) ~[rhn.jar:?]
    at com.redhat.rhn.taskomatic.TaskoJob.execute(TaskoJob.java:145) ~[rhn.jar:?]
    at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.3.0.jar:?]
    at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) ~[quartz-2.3.0.jar:?]
                                                                                                                  

## Version of Uyuni Server and Proxy (if used)
`zypper info Uyuni-Server-release` 
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2023.10-230900.209.1.uyuni3
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2023.10-230900.209.1.uyuni3.src
Summary        : Uyuni Server

_and_ `zypper info Uyuni-Proxy-release` _(if used)_
package 'Uyuni-Proxy-release' not found

**Comment by whasleycardoso** [comment]
Does anyone have any information about this?

It would be interesting if there was a parameter for spacewalk-repo-sync that automatically accepts the certificate. --non-interactive applies the default, but the default is to reject.
