### ISSUE TITLE
"split DNS" and containerized Proxy can cause trouble

### ISSUE THREAD

**Issue by jmozd** [uyuni-project/uyuni#8356]
### Problem description

We needed to set up a test bed Uyuni proxy, where the container and base machine have no access to the DNS resolution the clients use - the used proxy FQDN is not resolvable via DNS for the proxy host + container.

To get by the startup check done by the httpd container, we created an /etc/hosts entry for the proxy FQDN in addition to the base machine's FQDN.

After the next hardware scan of the base machine, clients can no longer register via that proxy.

Background analysis:

- whenever Uyuni Server runs a "hardware refresh" for a system, multiple /etc/hosts entries pointing to the system's IP result in multiple FQDN entries stored in the Uyuni database (table "rhnserverfqdn"). One of these entries can be selected as "primary FQDN" in Uyuni Server webUI, this does not change the behavior described in this ticket.
- in case of "split DNS", IOW when the clients use a different DNS (to resolve the "proxy FQDN") than the (containerized) Uyuni Proxy and the Proxy cannot resolve the intended Proxy FQDN, then a typical approach is to add the Proxy FQDN to /etc/hosts of the Proxy machine. This will allow the startup checks to resolve the Proxy FQDN.
- Creating the containerized Proxy adds an "external" system to the Uyuni Server database, also using the Proxy FQDN
- During onboarding a new client, Uyuni Server queries the database for the name of the used Proxy and receives conflicting system IDs for that FQDN (the ID of the base machine and the ID of the "external" system), leading to an error during onboarding
```
(Server.findByFqdn with params {name=proxy.customer.com} failed
    at com.redhat.rhn.common.hibernate.HibernateFactory.lookupObjectByNamedQuery(HibernateFactory.java:212)
```

### Steps to reproduce

1. set up a containerized Uyuni Proxy, where the machine has a different system name than the Proxy FQDN, and add both the system FQDN and the Proxy FQDN to /etc/hosts. For full effect, the Proxy FQDN should not e resolvable via DNS.
2. Run an Uyuni Server "hardware refresh" on the proxy machine, then check that both FQDNs from /etc/hosts are available on the Uyuni Server system's "Details" / "Wardware" page ("primary FQDN" drop-down)
3. Check the existence of the Proxy "system" in Uyuni Server's webUI, with the same FQDN as one of the proxy machine FQDNs
4. Try to register a new minion using that Uyuni proxy (will fail) or try to set the Proxy in a system's "Details" / "Connection" page (will reconfigure the minion, but show no new Proxy connection in the webUI)
5. Check /var/log/rhn/rhn_web_ui.log for the mentioned error message.

### Uyuni version

```bash
SUMA 4.3.10
```

### Uyuni proxy version (if used)

```bash
Repository         : lp1ap-15.4-prod-uyuni-leap_15.4
Name               : Uyuni-Proxy-release
Version            : 2023.09-230900.207.2.uyuni3
Arch               : x86_64
Anbieter           : obs://build.opensuse.org/systemsmanagement:Uyuni
Installierte Größe : 1,4 KiB
Installiert        : Ja
Status             : veraltet (Version 2023.08-220400.205.6.uyuni2 installiert)
Quellpaket         : Uyuni-Proxy-release-2023.09-230900.207.2.uyuni3.src

yes, we know this is old - the effect is not related to the Proxy version, though.
```

### Useful logs

```bash
/var/log/rhn/rhn_web_ui.log:

2024-02-20 13:59:08,106 [salt-event-thread-1] ERROR com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction - Error registering minion id: newminion
com.redhat.rhn.common.hibernate.HibernateRuntimeException: Executing query Server.findByFqdn with params {name=proxy.customer.com} failed
    at com.redhat.rhn.common.hibernate.HibernateFactory.lookupObjectByNamedQuery(HibernateFactory.java:212) ~[rhn.jar:?]
    at com.redhat.rhn.common.hibernate.HibernateFactory.lookupObjectByNamedQuery(HibernateFactory.java:182) ~[rhn.jar:?]
    at com.redhat.rhn.domain.server.ServerFactory.findByFqdn(ServerFactory.java:1081) ~[rhn.jar:?]
    at com.redhat.rhn.domain.server.ServerFactory.lookupProxyServer(ServerFactory.java:218) ~[rhn.jar:?]
```

### Additional information

I do not see an easy way to resolve this: When running a classic (non-containerized) Proxy under similar circumstances, being able to find it by its second FQDN entry is very helpful (there's no need to have that machine run under the proxy FQDN although the environment does expect some different machine name, and you can even have multiple proxy FQDNs this way). Maybe a second query run, considering only "primary FQDNs" (see "rhnserverfqdn" for details), might be an option.

OTOH, maybe adding some hint on this limitation of the containerized Proxy might be a good start.

**Comment by mbussolotto** [comment]
@cbosdo , @rjmateus I know for containerized server the container and host machine should have the same FQDN, I think this constrain is valid also for proxy httpd container and host machine, right? In this case I think this is a known limitation and right it clear in documentation

**Comment by jmozd** [comment]
@mbussolotto I believe this would cause the same type of problem (been there in the beginning of our "containerized proxy" journey, IIRC): You'd have two FQDN entries, as there's the "container" system in the database (type "external", created when setting up the container config) and the "host machine" as well (created when onboarding the host machine).

**Comment by rjmateus** [comment]
We can use just one FQDN for the containerized proxy also, and avoid the need to have 2 system entries on SUSE Manager server.
However, the primary FQDN should be used to generate the containerized proxy configuration files (that FQDN is used as the minion ID on suse Manager server).

Can you try registering the minion where you want to deploy the containerized proxy, and have as primary FQDN the one you want to use for the containerized proxy. After that generate a new proxy configuration using the primary FQDN. It should NOT add a new external system entry but set the pre-existing system as a proxy.

After this use the configuration data to deploy the containerized proxy.
