### ISSUE TITLE
recurring-action-executor reporting failures when recurring actions execute at the same time

### ISSUE THREAD

**Issue by gabjef** [uyuni-project/uyuni#8400]
### Problem description

recurring-action-executor reporting failures when recurring actions execute at the same time.

From status emails:

> Taskomatic bunch recurring-action-executor-bunch was scheduled to run within the recurring-action-22 schedule.
> Subtask recurring-action-executor failed.
> For more information check taskomatic daemon logs.

> Taskomatic bunch recurring-action-executor-bunch was scheduled to run within the recurring-action-22 schedule.
> Subtask recurring-action-executor finished successfully and is back to normal.

### Steps to reproduce

1. Set up two recurring schedules that will never run on the same minute of the hour (both custom states in our case):
Sched1 - Run every 13 minutes: 0 0/13 * ? * *
Sched2 - Run at 20 minutes on the hour: 0 20 * ? * *

All works fine.

2. Adjust execution time so they will "collide" at 20 minutes after the hour:
Change Sched1 to run every 10 minutes: 0 0/10 * ? * *
Leave Sched2 to run at 20 minutes on the hour: 0 20 * ? * *

When when actions collide timewise, com.redhat.rhn.taskomatic.task.RecurringActionJob throws an exception  in the taskomatic log 

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2024.02-230900.213.1.uyuni3
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2024.02-230900.213.1.uyuni3.src
Summary        : Uyuni Server
```

### Uyuni proxy version (if used)

```bash
N/A
```

### Useful logs

```bash
2024-03-05 18:20:00,064 [DefaultQuartzScheduler_Worker-1] WARN  com.suse.manager.maintenance.MaintenanceManager - Skipping action for 0 minions.
2024-03-05 18:20:00,286 [DefaultQuartzScheduler_Worker-4] INFO  com.redhat.rhn.taskomatic.task.MinionActionExecutor - Executing action: 13715
2024-03-05 18:20:10,065 [DefaultQuartzScheduler_Worker-6] ERROR com.redhat.rhn.taskomatic.task.RecurringActionJob - Executing a task threw an exception: java.lang.NumberFormatException
java.lang.NumberFormatException: For input string: "22-retry20240305182010"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:?]
        at java.lang.Long.parseLong(Long.java:692) ~[?:?]
        at java.lang.Long.parseLong(Long.java:817) ~[?:?]
        at com.redhat.rhn.domain.recurringactions.RecurringActionFactory.lookupByJobName(RecurringActionFactory.java:276) ~[rhn.jar:?]
        at com.redhat.rhn.taskomatic.task.RecurringActionJob.execute(RecurringActionJob.java:64) ~[rhn.jar:?]
        at com.redhat.rhn.taskomatic.task.RhnJavaJob.execute(RhnJavaJob.java:56) ~[rhn.jar:?]
        at com.redhat.rhn.taskomatic.TaskoJob.doExecute(TaskoJob.java:240) ~[rhn.jar:?]
        at com.redhat.rhn.taskomatic.TaskoJob.runTemplate(TaskoJob.java:193) ~[rhn.jar:?]
        at com.redhat.rhn.taskomatic.TaskoJob.execute(TaskoJob.java:145) ~[rhn.jar:?]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.3.0.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) ~[quartz-2.3.0.jar:?]
2024-03-05 18:21:00,056 [DefaultQuartzScheduler_Worker-13] INFO  com.redhat.rhn.taskomatic.task.ErrataCacheTask - In the queue: 7
2024-03-05 18:21:00,212 [DefaultQuartzScheduler_Worker-1] INFO  com.redhat.rhn.taskomatic.task.SystemOverviewUpdateQueue - In the queue: 7
2024-03-05 18:22:00,125 [DefaultQuartzScheduler_Worker-18] INFO  com.redhat.rhn.taskomatic.task.SystemOverviewUpdateQueue - In the queue: 4
2024-03-05 18:30:00,069 [DefaultQuartzScheduler_Worker-12] WARN  com.suse.manager.maintenance.MaintenanceManager - Skipping action for 0 minions.
2024-03-05 18:30:00,234 [DefaultQuartzScheduler_Worker-7] INFO  com.redhat.rhn.taskomatic.task.MinionActionExecutor - Executing action: 13716
2024-03-05 18:31:00,052 [DefaultQuartzScheduler_Worker-17] INFO  com.redhat.rhn.taskomatic.task.ErrataCacheTask - In the queue: 1
2024-03-05 18:31:00,108 [DefaultQuartzScheduler_Worker-1] INFO  com.redhat.rhn.taskomatic.task.SystemOverviewUpdateQueue - In the queue: 1
2024-03-05 18:32:00,131 [DefaultQuartzScheduler_Worker-18] INFO  com.redhat.rhn.taskomatic.task.SystemOverviewUpdateQueue - In the queue: 1
2024-03-05 18:40:00,071 [DefaultQuartzScheduler_Worker-13] WARN  com.suse.manager.maintenance.MaintenanceManager - Skipping action for 0 minions.
2024-03-05 18:40:00,218 [DefaultQuartzScheduler_Worker-2] INFO  com.redhat.rhn.taskomatic.task.MinionActionExecutor - Executing action: 13717
2024-03-05 18:41:00,049 [DefaultQuartzScheduler_Worker-7] INFO  com.redhat.rhn.taskomatic.task.ErrataCacheTask - In the queue: 1
2024-03-05 18:41:00,109 [DefaultQuartzScheduler_Worker-9] INFO  com.redhat.rhn.taskomatic.task.SystemOverviewUpdateQueue - In the queue: 1
2024-03-05 18:42:00,120 [DefaultQuartzScheduler_Worker-5] INFO  com.redhat.rhn.taskomatic.task.SystemOverviewUpdateQueue - In the queue: 1
2024-03-05 18:50:00,053 [DefaultQuartzScheduler_Worker-1] WARN  com.suse.manager.maintenance.MaintenanceManager - Skipping action for 0 minions.
2024-03-05 18:50:00,219 [DefaultQuartzScheduler_Worker-2] INFO  com.redhat.rhn.taskomatic.task.MinionActionExecutor - Executing action: 13718
2024-03-05 18:51:00,050 [DefaultQuartzScheduler_Worker-4] INFO  com.redhat.rhn.taskomatic.task.ErrataCacheTask - In the queue: 1
2024-03-05 18:51:00,091 [DefaultQuartzScheduler_Worker-17] INFO  com.redhat.rhn.taskomatic.task.SystemOverviewUpdateQueue - In the queue: 1
2024-03-05 18:52:00,090 [DefaultQuartzScheduler_Worker-8] INFO  com.redhat.rhn.taskomatic.task.SystemOverviewUpdateQueue - In the queue: 1
2024-03-05 19:00:00,083 [DefaultQuartzScheduler_Worker-14] INFO  com.redhat.rhn.taskomatic.task.SessionCleanup - 6 stale session(s) deleted
2024-03-05 19:00:00,146 [DefaultQuartzScheduler_Worker-8] WARN  com.suse.manager.maintenance.MaintenanceManager - Skipping action for 0 minions.
2024-03-05 19:00:00,226 [DefaultQuartzScheduler_Worker-2] INFO  com.redhat.rhn.taskomatic.task.SystemOverviewUpdateQueue - In the queue: 9
2024-03-05 19:00:00,375 [DefaultQuartzScheduler_Worker-17] INFO  com.redhat.rhn.taskomatic.task.MinionActionExecutor - Executing action: 13719
2024-03-05 19:01:00,049 [DefaultQuartzScheduler_Worker-20] INFO  com.redhat.rhn.taskomatic.task.ErrataCacheTask - In the queue: 1
2024-03-05 19:01:00,086 [DefaultQuartzScheduler_Worker-11] INFO  com.redhat.rhn.taskomatic.task.SystemOverviewUpdateQueue - In the queue: 1
2024-03-05 19:02:00,085 [DefaultQuartzScheduler_Worker-8] INFO  com.redhat.rhn.taskomatic.task.SystemOverviewUpdateQueue - In the queue: 1
2024-03-05 19:10:00,070 [DefaultQuartzScheduler_Worker-11] WARN  com.suse.manager.maintenance.MaintenanceManager - Skipping action for 0 minions.
2024-03-05 19:10:00,445 [DefaultQuartzScheduler_Worker-3] INFO  com.redhat.rhn.taskomatic.task.MinionActionExecutor - Executing action: 13720
2024-03-05 19:11:00,082 [DefaultQuartzScheduler_Worker-17] INFO  com.redhat.rhn.taskomatic.task.ErrataCacheTask - In the queue: 1
2024-03-05 19:11:00,114 [DefaultQuartzScheduler_Worker-12] INFO  com.redhat.rhn.taskomatic.task.SystemOverviewUpdateQueue - In the queue: 1
2024-03-05 19:12:00,116 [DefaultQuartzScheduler_Worker-11] INFO  com.redhat.rhn.taskomatic.task.SystemOverviewUpdateQueue - In the queue: 1
2024-03-05 19:20:00,090 [DefaultQuartzScheduler_Worker-14] WARN  com.suse.manager.maintenance.MaintenanceManager - Skipping action for 0 minions.
2024-03-05 19:20:00,247 [DefaultQuartzScheduler_Worker-3] INFO  com.redhat.rhn.taskomatic.task.MinionActionExecutor - Executing action: 13721
2024-03-05 19:20:10,060 [DefaultQuartzScheduler_Worker-7] ERROR com.redhat.rhn.taskomatic.task.RecurringActionJob - Executing a task threw an exception: java.lang.NumberFormatException
java.lang.NumberFormatException: For input string: "22-retry20240305192010"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:?]
        at java.lang.Long.parseLong(Long.java:692) ~[?:?]
        at java.lang.Long.parseLong(Long.java:817) ~[?:?]
        at com.redhat.rhn.domain.recurringactions.RecurringActionFactory.lookupByJobName(RecurringActionFactory.java:276) ~[rhn.jar:?]
        at com.redhat.rhn.taskomatic.task.RecurringActionJob.execute(RecurringActionJob.java:64) ~[rhn.jar:?]
        at com.redhat.rhn.taskomatic.task.RhnJavaJob.execute(RhnJavaJob.java:56) ~[rhn.jar:?]
        at com.redhat.rhn.taskomatic.TaskoJob.doExecute(TaskoJob.java:240) ~[rhn.jar:?]
        at com.redhat.rhn.taskomatic.TaskoJob.runTemplate(TaskoJob.java:193) ~[rhn.jar:?]
        at com.redhat.rhn.taskomatic.TaskoJob.execute(TaskoJob.java:145) ~[rhn.jar:?]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.3.0.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) ~[quartz-2.3.0.jar:?]
2024-03-05 19:21:00,064 [DefaultQuartzScheduler_Worker-12] INFO  com.redhat.rhn.taskomatic.task.ErrataCacheTask - In the queue: 7
2024-03-05 19:21:00,111 [DefaultQuartzScheduler_Worker-13] INFO  com.redhat.rhn.taskomatic.task.SystemOverviewUpdateQueue - In the queue: 7
2024-03-05 19:22:00,114 [DefaultQuartzScheduler_Worker-8] INFO  com.redhat.rhn.taskomatic.task.SystemOverviewUpdateQueue - In the queue: 5
2024-03-05 19:30:00,026 [DefaultQuartzScheduler_Worker-9] INFO  com.redhat.rhn.taskomatic.task.SessionCleanup - 6 stale session(s) deleted
2024-03-05 19:30:00,065 [DefaultQuartzScheduler_Worker-13] WARN  com.suse.manager.maintenance.MaintenanceManager - Skipping action for 0 minions.
2024-03-05 19:30:00,248 [DefaultQuartzScheduler_Worker-3] INFO  com.redhat.rhn.taskomatic.task.MinionActionExecutor - Executing action: 13722
2024-03-05 19:31:00,048 [DefaultQuartzScheduler_Worker-6] INFO  com.redhat.rhn.taskomatic.task.ErrataCacheTask - In the queue: 1
2024-03-05 19:31:00,073 [DefaultQuartzScheduler_Worker-20] INFO  com.redhat.rhn.taskomatic.task.SystemOverviewUpdateQueue - In the queue: 1
2024-03-05 19:32:00,080 [DefaultQuartzScheduler_Worker-10] INFO  com.redhat.rhn.taskomatic.task.SystemOverviewUpdateQueue - In the queue: 1
```

**Comment by mcalmer** [comment]
Looks like https://github.com/uyuni-project/uyuni/pull/8237 could fix it

**Comment by mcalmer** [comment]
should be fixed with the next uyuni release
