### ISSUE TITLE
proxy container: error on sending mails

### ISSUE THREAD

**Issue by mbussolotto** [uyuni-project/uyuni#8489]
### Problem description

SMTP is hardcoded to localhost

### Steps to reproduce

```
[proxy-broker] [Wed Mar 20 16:43:59 2024] [error] [pid 46] src/server/wsgi_logger.c(147): [client 192.168.100.1:60170] Traceback (most recent call last):
[proxy-broker] [Wed Mar 20 16:43:59 2024] [error] [pid 46] src/server/wsgi_logger.c(147): [client 192.168.100.1:60170]   File "/usr/share/rhn/wsgi/xmlrpc.py", line 23, in application
[proxy-broker] [Wed Mar 20 16:43:59 2024] [error] [pid 46] src/server/wsgi_logger.c(147): [client 192.168.100.1:60170]     "proxy.apacheServer")
[proxy-broker] [Wed Mar 20 16:43:59 2024] [error] [pid 46] src/server/wsgi_logger.c(147): [client 192.168.100.1:60170]   File "/usr/share/rhn/wsgi/wsgiHandler.py", line 57, in handle
[proxy-broker] [Wed Mar 20 16:43:59 2024] [error] [pid 46] src/server/wsgi_logger.c(147): [client 192.168.100.1:60170]     ret = appServ(req)
[proxy-broker] [Wed Mar 20 16:43:59 2024] [error] [pid 46] src/server/wsgi_logger.c(147): [client 192.168.100.1:60170]   File "/usr/share/rhn/proxy/apacheServer.py", line 68, in __call__
[proxy-broker] [Wed Mar 20 16:43:59 2024] [error] [pid 46] src/server/wsgi_logger.c(147): [client 192.168.100.1:60170]     severity="unhandled")
[proxy-broker] [Wed Mar 20 16:43:59 2024] [error] [pid 46] src/server/wsgi_logger.c(147): [client 192.168.100.1:60170]   File "/usr/lib/python3.6/site-packages/spacewalk/common/rhnTB.py", line 196, in Traceback
[proxy-broker] [Wed Mar 20 16:43:59 2024] [error] [pid 46] src/server/wsgi_logger.c(147): [client 192.168.100.1:60170]     rhnMail.send(headers, outstring)
[proxy-broker] [Wed Mar 20 16:43:59 2024] [error] [pid 46] src/server/wsgi_logger.c(147): [client 192.168.100.1:60170]   File "/usr/lib/python3.6/site-packages/spacewalk/common/rhnMail.py", line 81, in send
[proxy-broker] [Wed Mar 20 16:43:59 2024] [error] [pid 46] src/server/wsgi_logger.c(147): [client 192.168.100.1:60170]     with smtplib.SMTP("localhost") as smtp:
[proxy-broker] [Wed Mar 20 16:43:59 2024] [error] [pid 46] src/server/wsgi_logger.c(147): [client 192.168.100.1:60170]   File "/usr/lib64/python3.6/smtplib.py", line 251, in __init__
[proxy-broker] [Wed Mar 20 16:43:59 2024] [error] [pid 46] src/server/wsgi_logger.c(147): [client 192.168.100.1:60170]     (code, msg) = self.connect(host, port)
[proxy-broker] [Wed Mar 20 16:43:59 2024] [error] [pid 46] src/server/wsgi_logger.c(147): [client 192.168.100.1:60170]   File "/usr/lib64/python3.6/smtplib.py", line 336, in connect
[proxy-broker] [Wed Mar 20 16:43:59 2024] [error] [pid 46] src/server/wsgi_logger.c(147): [client 192.168.100.1:60170]     self.sock = self._get_socket(host, port, self.timeout)
[proxy-broker] [Wed Mar 20 16:43:59 2024] [error] [pid 46] src/server/wsgi_logger.c(147): [client 192.168.100.1:60170]   File "/usr/lib64/python3.6/smtplib.py", line 307, in _get_socket
[proxy-broker] [Wed Mar 20 16:43:59 2024] [error] [pid 46] src/server/wsgi_logger.c(147): [client 192.168.100.1:60170]     self.source_address)
[proxy-broker] [Wed Mar 20 16:43:59 2024] [error] [pid 46] src/server/wsgi_logger.c(147): [client 192.168.100.1:60170]   File "/usr/lib64/python3.6/socket.py", line 724, in create_connection
[proxy-broker] [Wed Mar 20 16:43:59 2024] [error] [pid 46] src/server/wsgi_logger.c(147): [client 192.168.100.1:60170]     raise err
[proxy-broker] [Wed Mar 20 16:43:59 2024] [error] [pid 46] src/server/wsgi_logger.c(147): [client 192.168.100.1:60170]   File "/usr/lib64/python3.6/socket.py", line 713, in create_connection
[proxy-broker] [Wed Mar 20 16:43:59 2024] [error] [pid 46] src/server/wsgi_logger.c(147): [client 192.168.100.1:60170]     sock.connect(sa)
```

### Uyuni version

```bash
2024.02
```

**Comment by nodeg** [comment]
Is this still the case @mbussolotto?
