### ISSUE TITLE
Executing command 'dnf' in directory '/root'

### ISSUE THREAD

**Issue by gabardyne** [uyuni-project/uyuni#8692]
# Question

I see this in the logs of my systemd venv-salt-minion service on rocky8 clients:

_Executing command 'dnf' in directory '/root'_

It repeats every ten seconds. Is it normal? Is it possible to make it repeats every 1 minute instead?

## Version of Uyuni Server and Proxy (if used)

Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2024.01-230900.212.1.uyuni3
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2024.01-230900.212.1.uyuni3.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.

**Comment by rjmateus** [comment]
Hey,
It's expected and needed for the reboot required feature. It will be changes to run every 2 minutes on rhel and it's clones.

**Comment by gabardyne** [comment]
Hello,
Thanks for the answer.
It will changes to run every 2 minutes on rhel in the next uyuni release?

I see this error in dnf log:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dnf/cli/main.py", line 67, in main
    return _main(base, args, cli_class, option_parser_class)
  File "/usr/lib/python3.6/site-packages/dnf/cli/main.py", line 106, in _main
    return cli_run(cli, base)
  File "/usr/lib/python3.6/site-packages/dnf/cli/main.py", line 122, in cli_run
    cli.run()
  File "/usr/lib/python3.6/site-packages/dnf/cli/cli.py", line 1055, in run
    return self.command.run()
  File "/usr/lib/python3.6/site-packages/dnf-plugins/needs_restarting.py", line 261, in run
    raise dnf.exceptions.Error()  # Sets exit code 1
dnf.exceptions.Error: None

Do I need to be worried about that?

**Comment by rjmateus** [comment]
about the error maybe @wweellddeerr may know more. 
The change in the frequency will happen in a future release, I'm not sure if the next one. But if not, would be 2 form now.

**Comment by cFabij** [comment]
@gabardyne
In the meantime, I can recommend implementing this custom configuration to lessen the log spam ; )
https://github.com/uyuni-project/uyuni/issues/8457#issuecomment-2009520171
