### ISSUE TITLE
Unable to install patterns-uyuni_server-2024.05-230900.1.1.uyuni3.x86_64

### ISSUE THREAD

**Issue by szymonsypula** [uyuni-project/uyuni#8859]
### Problem description

Installation process failed.

Command used: 
zypper -n update --auto-agree-with-licenses
'zypper' 'addrepo' '-G' 'https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable/images/repo/Uyuni-Server-POOL-x86_64-Media1/' 'uyuni-server-stable'
'zypper' '--gpg-auto-import-keys' 'refresh'
'zypper' '-n' 'install' '--auto-agree-with-licenses' 'patterns-uyuni_server'
'/usr/lib/susemanager/bin/mgr-setup' '-s'

× taskomatic.service - Taskomatic
     Loaded: loaded (/usr/lib/systemd/system/taskomatic.service; enabled; vendor preset: disabled)
    Drop-In: /usr/lib/systemd/system/taskomatic.service.d
             └─override.conf
     Active: failed (Result: exit-code) since Mon 2024-06-03 09:25:32 UTC; 16s ago
    Process: 26340 ExecStart=/usr/sbin/taskomatic (code=exited, status=255/EXCEPTION)
   Main PID: 26340 (code=exited, status=255/EXCEPTION)

### Steps to reproduce

1. Setup Uyuni server using cmd commands and answer file

### Uyuni version

```bash
patterns-uyuni_server-2024.05-230900.1.1.uyuni3.x86_64
```

### Useful logs

```bash
Installation output: 

CREATE ROLE
* Loading answer file: /root/spacewalk-answers.
** Database: Setting up database connection for PostgreSQL backend.
** Database: Populating database.
** Database: --clear-db option used.  Clearing database.
** Database: Shutting down spacewalk services that may be using DB.
** Database: Services stopped.  Clearing DB.
Running spacewalk-sql --select-mode-direct /usr/share/susemanager/db/postgres/deploy.sql
*** Progress: ###########################
* Performing initial configuration.
* Configuring apache SSL virtual host.
* Creating SSL certificates.
** SSL: Generating server certificate.
** Database: Setting up report database.
** Database: --clear-db option used.  Clearing report database.
Running /usr/bin/uyuni-setup-reportdb create --db reportdb --user pythia_susemanager --host localhost --address * --remote 0.0.0.0/0,::/0 --autogenpw
*** Progress: #
** Database: Installation complete.
* Report DB Configured.
* Update configuration in database.
* Setting up Cobbler..
* Deploying configuration files.
* Restarting services.
Tomcat failed to start properly or the installer ran out of tries.  Please check /var/log/tomcat/catalina.out or /var/log/tomcat/catalina.$(date +%Y-%m-%d).log for errors.
ERROR: spacewalk-setup failed

----

/var/log/tomcat/catalina.out

03-Jun-2024 09:15:03.509 WARNING [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [rhn] appears to have started a thread named [RHN Message Dispatcher] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@11.0.23/java.lang.Object.wait(Native Method)
 EDU.oswego.cs.dl.util.concurrent.LinkedQueue.poll(LinkedQueue.java:170)
 com.redhat.rhn.common.messaging.MessageQueue.popEventMessage(MessageQueue.java:146)
 com.redhat.rhn.common.messaging.MessageDispatcher.run(MessageDispatcher.java:84)
 java.base@11.0.23/java.lang.Thread.run(Thread.java:829)
03-Jun-2024 09:15:03.543 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/share/susemanager/www/tomcat/webapps/rhn] has finished in [16,648] ms
03-Jun-2024 09:15:03.566 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-127.0.0.1-8009"]
03-Jun-2024 09:15:03.732 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-0:0:0:0:0:0:0:1-8009"]
03-Jun-2024 09:15:03.843 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-127.0.0.1-8080"]
03-Jun-2024 09:15:03.962 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [17161] milliseconds
03-Jun-2024 09:15:32.666 INFO [pool-4-thread-1] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [java.util.function.Consumer]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
        java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [java.util.function.Consumer]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
                at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1349)
                at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1337)
                at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1174)
                at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1141)
                at com.suse.manager.webui.websocket.WebsocketHeartbeatService.clearStaleSessions(WebsocketHeartbeatService.java:84)
                at com.suse.manager.webui.websocket.WebsocketHeartbeatService.lambda$initScheduler$2(WebsocketHeartbeatService.java:123)
                at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
                at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
                at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at java.base/java.lang.Thread.run(Thread.java:829)
```

### Additional information

NAME="openSUSE Leap"
VERSION="15.5"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.5"
PRETTY_NAME="openSUSE Leap 15.5"

**Comment by szymonsypula** [comment]
Tomcat error logs:

SEVERE [main] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener ins
tance of class [com.redhat.rhn.webapp.RhnServletListener]
        java.lang.NoClassDefFoundError: net/bytebuddy/NamingStrategy$SuffixingRandom$BaseNameResolver


SEVERE [main] org.apache.catalina.core.StandardContext.listenerStop Exception sending context destroyed event to listener instan
ce of class [com.redhat.rhn.webapp.RhnServletListener]
        java.lang.NullPointerException

**Comment by mikekuzak** [comment]
Same issue +1

**Comment by werwaznadn** [comment]
Hi, 

same +1 
Bump.

**Comment by simonello** [comment]
same +1

**Comment by shivamsaraiya** [comment]
+1

**Comment by rjmateus** [comment]
do you have any error after: 
```
SEVERE [main] org.apache.catalina.core.StandardContext.listenerStop Exception sending context destroyed event to listener instan
ce of class [com.redhat.rhn.webapp.RhnServletListener]
java.lang.NullPointerException
```

**Comment by szymonsypula** [comment]
In /var/log/tomcat/localhost.log only this two exceptions. 

In /var/log/tomcat/catalina.out

SEVERE [main] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be fo
und in the appropriate container log file

SEVERE [main] org.apache.catalina.core.StandardContext.startInternal Context [/rhn] startup failed due to previous errors

WARNING [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [rhn] appears to have started a thread named [pool-2-thread-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@11.0.23/sun.nio.ch.EPoll.wait(Native Method)

INFO [pool-4-thread-1] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [java.util.function.Consumer]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
        java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [java.util.function.Consumer]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
                at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1349)

**Comment by kyriakosChr12** [comment]
same issue +1

**Comment by fperrin-fr** [comment]
same issue +1

**Comment by mcalmer** [comment]
Does
```
$> ls -la /usr/share/susemanager/www/tomcat/webapps/rhn/WEB-INF/lib/
```

show any broken symlinks?

**Comment by simonello** [comment]
> Does
> 
> ```
> $> ls -la /usr/share/susemanager/www/tomcat/webapps/rhn/WEB-INF/lib/
> ```
> 
> show any broken symlinks?

none in my installation.

**Comment by szymonsypula** [comment]
No broken symlinks. 
Below symlinks from mentioned directory: 

```
ls -la /usr/share/susemanager/www/tomcat/webapps/rhn/WEB-INF/lib/
total 12
drwxrwxr-x 2 tomcat tomcat 8192 Jun  3 11:09 .
drwxrwxr-x 8 tomcat tomcat  172 Jun  3 11:09 ..
lrwxrwxrwx 1 tomcat tomcat   35 May 14 12:34 antlr.jar -> ../../../../../../../java/antlr.jar
lrwxrwxrwx 1 tomcat tomcat   53 May 14 12:34 apache-commons-compress.jar -> ../../../../../../../java/apache-commons-compress.jar
lrwxrwxrwx 1 tomcat tomcat   62 May 14 12:34 apache-commons-jexl_commons-jexl.jar -> ../../../../../../../java/apache-commons-jexl/commons-jexl.jar
lrwxrwxrwx 1 tomcat tomcat   54 May 14 12:34 apache-commons-validator.jar -> ../../../../../../../java/apache-commons-validator.jar
lrwxrwxrwx 1 tomcat tomcat   34 May 14 12:34 bcel.jar -> ../../../../../../../java/bcel.jar
lrwxrwxrwx 1 tomcat tomcat   51 May 14 12:34 byte-buddy_byte-buddy.jar -> ../../../../../../../java/byte-buddy/byte-buddy.jar
lrwxrwxrwx 1 tomcat tomcat   34 May 14 12:34 c3p0.jar -> ../../../../../../../java/c3p0.jar
lrwxrwxrwx 1 tomcat tomcat   41 May 14 12:34 cglib_cglib.jar -> ../../../../../../../java/cglib/cglib.jar
lrwxrwxrwx 1 tomcat tomcat   49 May 14 12:34 classmate_classmate.jar -> ../../../../../../../java/classmate/classmate.jar
lrwxrwxrwx 1 tomcat tomcat   47 May 14 12:34 commons-beanutils.jar -> ../../../../../../../java/commons-beanutils.jar
lrwxrwxrwx 1 tomcat tomcat   41 May 14 12:34 commons-cli.jar -> ../../../../../../../java/commons-cli.jar
lrwxrwxrwx 1 tomcat tomcat   43 May 14 12:34 commons-codec.jar -> ../../../../../../../java/commons-codec.jar
lrwxrwxrwx 1 tomcat tomcat   49 May 14 12:34 commons-collections.jar -> ../../../../../../../java/commons-collections.jar
lrwxrwxrwx 1 tomcat tomcat   46 May 14 12:34 commons-digester.jar -> ../../../../../../../java/commons-digester.jar
lrwxrwxrwx 1 tomcat tomcat   47 May 14 12:34 commons-discovery.jar -> ../../../../../../../java/commons-discovery.jar
lrwxrwxrwx 1 tomcat tomcat   40 May 14 12:34 commons-el.jar -> ../../../../../../../java/commons-el.jar
lrwxrwxrwx 1 tomcat tomcat   48 May 14 12:34 commons-fileupload.jar -> ../../../../../../../java/commons-fileupload.jar
lrwxrwxrwx 1 tomcat tomcat   40 May 14 12:34 commons-io.jar -> ../../../../../../../java/commons-io.jar
lrwxrwxrwx 1 tomcat tomcat   43 May 14 12:34 commons-lang3.jar -> ../../../../../../../java/commons-lang3.jar
lrwxrwxrwx 1 tomcat tomcat   45 May 14 12:34 commons-logging.jar -> ../../../../../../../java/commons-logging.jar
lrwxrwxrwx 1 tomcat tomcat   40 May 14 12:34 concurrent.jar -> ../../../../../../../java/concurrent.jar
lrwxrwxrwx 1 tomcat tomcat   85 May 14 12:34 concurrentlinkedhashmap-lruconcurrentlinkedhashmap-lru.jar -> ../../../../../../../java/concurrentlinkedhashmap-lru/concurrentlinkedhashmap-lru.jar
lrwxrwxrwx 1 tomcat tomcat   35 May 14 12:34 dom4j.jar -> ../../../../../../../java/dom4j.jar
lrwxrwxrwx 1 tomcat tomcat   33 May 14 12:34 dwr.jar -> ../../../../../../../java/dwr.jar
lrwxrwxrwx 1 tomcat tomcat   42 May 14 12:34 ehcache-core.jar -> ../../../../../../../java/ehcache-core.jar
lrwxrwxrwx 1 tomcat tomcat   50 May 14 12:34 geronimo-jta-1.1-api.jar -> ../../../../../../../java/geronimo-jta-1.1-api.jar
lrwxrwxrwx 1 tomcat tomcat   50 May 14 12:34 glassfish-activation.jar -> ../../../../../../../java/glassfish-activation.jar
lrwxrwxrwx 1 tomcat tomcat   48 May 14 12:34 glassfish-jaxb-api.jar -> ../../../../../../../java/glassfish-jaxb-api.jar
lrwxrwxrwx 1 tomcat tomcat   54 May 14 12:34 glassfish-jaxb_jaxb-impl.jar -> ../../../../../../../java/glassfish-jaxb/jaxb-impl.jar
lrwxrwxrwx 1 tomcat tomcat   57 May 14 12:34 glassfish-jaxb_jaxb-runtime.jar -> ../../../../../../../java/glassfish-jaxb/jaxb-runtime.jar
lrwxrwxrwx 1 tomcat tomcat   49 May 14 12:34 glassfish-jaxb_txw2.jar -> ../../../../../../../java/glassfish-jaxb/txw2.jar
lrwxrwxrwx 1 tomcat tomcat   53 May 14 12:34 google-gson_google-gsongson-extras.jar -> ../../../../../../../java/google-gson/gson-extras.jar
lrwxrwxrwx 1 tomcat tomcat   46 May 14 12:34 google-gson_google-gsongson.jar -> ../../../../../../../java/google-gson/gson.jar
lrwxrwxrwx 1 tomcat tomcat   89 May 14 12:34 hibernate-commons-annotations_hibernate-commons-annotations.jar -> ../../../../../../../java/hibernate-commons-annotations/hibernate-commons-annotations.jar
lrwxrwxrwx 1 tomcat tomcat   64 May 14 12:34 hibernate-types_hibernate-types-52.jar -> ../../../../../../../java/hibernate-types/hibernate-types-52.jar
lrwxrwxrwx 1 tomcat tomcat   55 May 14 12:34 hibernate5_hibernate-c3p0.jar -> ../../../../../../../java/hibernate5/hibernate-c3p0.jar
lrwxrwxrwx 1 tomcat tomcat   55 May 14 12:34 hibernate5_hibernate-core.jar -> ../../../../../../../java/hibernate5/hibernate-core.jar
lrwxrwxrwx 1 tomcat tomcat   58 May 14 12:34 hibernate5_hibernate-ehcache.jar -> ../../../../../../../java/hibernate5/hibernate-ehcache.jar
lrwxrwxrwx 1 tomcat tomcat   45 May 14 12:34 httpasyncclient.jar -> ../../../../../../../java/httpasyncclient.jar
lrwxrwxrwx 1 tomcat tomcat   55 May 14 12:34 httpcomponents_httpclient.jar -> ../../../../../../../java/httpcomponents/httpclient.jar
lrwxrwxrwx 1 tomcat tomcat   57 May 14 12:34 httpcomponents_httpcore-nio.jar -> ../../../../../../../java/httpcomponents/httpcore-nio.jar
lrwxrwxrwx 1 tomcat tomcat   53 May 14 12:34 httpcomponents_httpcore.jar -> ../../../../../../../java/httpcomponents/httpcore.jar
lrwxrwxrwx 1 tomcat tomcat   36 May 14 12:34 ical4j.jar -> ../../../../../../../java/ical4j.jar
lrwxrwxrwx 1 tomcat tomcat   52 May 14 12:34 istack-commons-runtime.jar -> ../../../../../../../java/istack-commons-runtime.jar
lrwxrwxrwx 1 tomcat tomcat   49 May 14 12:34 jackson-annotations.jar -> ../../../../../../../java/jackson-annotations.jar
lrwxrwxrwx 1 tomcat tomcat   42 May 14 12:34 jackson-core.jar -> ../../../../../../../java/jackson-core.jar
lrwxrwxrwx 1 tomcat tomcat   46 May 14 12:34 jackson-databind.jar -> ../../../../../../../java/jackson-databind.jar
lrwxrwxrwx 1 tomcat tomcat   43 May 14 12:34 jade4jjade4j.jar -> ../../../../../../../java/jade4j/jade4j.jar
lrwxrwxrwx 1 root   root     46 May  6 08:01 java-branding.jar -> ../../../../../../../rhn/lib/java-branding.jar
lrwxrwxrwx 1 tomcat tomcat   44 May 14 12:34 java-saml-core.jar -> ../../../../../../../java/java-saml-core.jar
lrwxrwxrwx 1 tomcat tomcat   39 May 14 12:34 java-saml.jar -> ../../../../../../../java/java-saml.jar
lrwxrwxrwx 1 tomcat tomcat   39 May 14 12:34 javassist.jar -> ../../../../../../../java/javassist.jar
lrwxrwxrwx 1 tomcat tomcat   40 May 14 12:34 javax.mail.jar -> ../../../../../../../java/javax.mail.jar
lrwxrwxrwx 1 tomcat tomcat   57 May 14 12:34 jboss-logging.jar -> ../../../../../../../java/jboss-logging/jboss-logging.jar
lrwxrwxrwx 1 tomcat tomcat   50 May 14 12:34 jctools_jctools-core.jar -> ../../../../../../../java/jctools/jctools-core.jar
lrwxrwxrwx 1 tomcat tomcat   34 May 14 12:34 jdom.jar -> ../../../../../../../java/jdom.jar
lrwxrwxrwx 1 tomcat tomcat   39 May 14 12:34 joda-time.jar -> ../../../../../../../java/joda-time.jar
lrwxrwxrwx 1 tomcat tomcat   36 May 14 12:34 jose4j.jar -> ../../../../../../../java/jose4j.jar
lrwxrwxrwx 1 tomcat tomcat   61 May 14 12:34 jpa-api_jakarta.persistence-api.jar -> ../../../../../../../java/jpa-api/jakarta.persistence-api.jar
lrwxrwxrwx 1 tomcat tomcat   45 May 14 12:34 log4j_log4j-api.jar -> ../../../../../../../java/log4j/log4j-api.jar
lrwxrwxrwx 1 tomcat tomcat   46 May 14 12:34 log4j_log4j-core.jar -> ../../../../../../../java/log4j/log4j-core.jar
lrwxrwxrwx 1 tomcat tomcat   45 May 14 12:34 log4j_log4j-jcl.jar -> ../../../../../../../java/log4j/log4j-jcl.jar
lrwxrwxrwx 1 tomcat tomcat   52 May 14 12:34 log4j_log4j-slf4j-impl.jar -> ../../../../../../../java/log4j/log4j-slf4j-impl.jar
lrwxrwxrwx 1 tomcat tomcat   66 May 14 12:34 mchange-commons_mchange-commons-java.jar -> ../../../../../../../java/mchange-commons/mchange-commons-java.jar
lrwxrwxrwx 1 tomcat tomcat   48 May 14 12:34 netty_netty-buffer.jar -> ../../../../../../../java/netty/netty-buffer.jar
lrwxrwxrwx 1 tomcat tomcat   47 May 14 12:34 netty_netty-codec.jar -> ../../../../../../../java/netty/netty-codec.jar
lrwxrwxrwx 1 tomcat tomcat   48 May 14 12:34 netty_netty-common.jar -> ../../../../../../../java/netty/netty-common.jar
lrwxrwxrwx 1 tomcat tomcat   49 May 14 12:34 netty_netty-handler.jar -> ../../../../../../../java/netty/netty-handler.jar
lrwxrwxrwx 1 tomcat tomcat   50 May 14 12:34 netty_netty-resolver.jar -> ../../../../../../../java/netty/netty-resolver.jar
lrwxrwxrwx 1 tomcat tomcat   79 May 14 12:34 netty_netty-transport-native-unix-common.jar -> ../../../../../../../../lib64/java/netty/netty-transport-native-unix-common.jar
lrwxrwxrwx 1 tomcat tomcat   51 May 14 12:34 netty_netty-transport.jar -> ../../../../../../../java/netty/netty-transport.jar
lrwxrwxrwx 1 tomcat tomcat   47 May 14 12:34 objectweb-asm_asm.jar -> ../../../../../../../java/objectweb-asm/asm.jar
lrwxrwxrwx 1 tomcat tomcat   49 May 14 12:34 ongres-scram_client.jar -> ../../../../../../../java/ongres-scram/client.jar
lrwxrwxrwx 1 tomcat tomcat   49 May 14 12:34 ongres-scram_common.jar -> ../../../../../../../java/ongres-scram/common.jar
lrwxrwxrwx 1 tomcat tomcat   56 May 14 12:34 ongres-stringprep_saslprep.jar -> ../../../../../../../java/ongres-stringprep/saslprep.jar
lrwxrwxrwx 1 tomcat tomcat   58 May 14 12:34 ongres-stringprep_stringprep.jar -> ../../../../../../../java/ongres-stringprep/stringprep.jar
lrwxrwxrwx 1 tomcat tomcat   33 May 14 12:34 oro.jar -> ../../../../../../../java/oro.jar
lrwxrwxrwx 1 tomcat tomcat   49 May 14 12:34 pgjdbc-ng_pgjdbc-ng.jar -> ../../../../../../../java/pgjdbc-ng/pgjdbc-ng.jar
lrwxrwxrwx 1 tomcat tomcat   43 May 14 12:34 pgjdbc-ng_spy.jar -> ../../../../../../../java/pgjdbc-ng/spy.jar
lrwxrwxrwx 1 root   root     45 May 14 12:34 postgresql-jdbc.jar -> ../../../../../../../java/postgresql-jdbc.jar
lrwxrwxrwx 1 tomcat tomcat   36 May 14 12:34 quartz.jar -> ../../../../../../../java/quartz.jar
lrwxrwxrwx 1 tomcat tomcat   52 May 14 12:34 redstone-xmlrpc-client.jar -> ../../../../../../../java/redstone-xmlrpc-client.jar
lrwxrwxrwx 1 tomcat tomcat   45 May 14 12:34 redstone-xmlrpc.jar -> ../../../../../../../java/redstone-xmlrpc.jar
lrwxrwxrwx 1 tomcat tomcat   36 May 14 12:34 rhn.jar -> ../../../../../../../rhn/lib/rhn.jar
lrwxrwxrwx 1 tomcat tomcat   67 May 14 12:34 salt-netapi-clientsalt-netapi-client.jar -> ../../../../../../../java/salt-netapi-client/salt-netapi-client.jar
lrwxrwxrwx 1 tomcat tomcat   41 May 14 12:34 simple-core.jar -> ../../../../../../../java/simple-core.jar
lrwxrwxrwx 1 tomcat tomcat   40 May 14 12:34 simple-xml.jar -> ../../../../../../../java/simple-xml.jar
lrwxrwxrwx 1 tomcat tomcat   42 May 14 12:34 simpleclient.jar -> ../../../../../../../java/simpleclient.jar
lrwxrwxrwx 1 tomcat tomcat   49 May 14 12:34 simpleclient_common.jar -> ../../../../../../../java/simpleclient_common.jar
lrwxrwxrwx 1 tomcat tomcat   52 May 14 12:34 simpleclient_hibernate.jar -> ../../../../../../../java/simpleclient_hibernate.jar
lrwxrwxrwx 1 tomcat tomcat   53 May 14 12:34 simpleclient_httpserver.jar -> ../../../../../../../java/simpleclient_httpserver.jar
lrwxrwxrwx 1 tomcat tomcat   50 May 14 12:34 simpleclient_servlet.jar -> ../../../../../../../java/simpleclient_servlet.jar
lrwxrwxrwx 1 tomcat tomcat   38 May 14 12:34 sitemesh.jar -> ../../../../../../../java/sitemesh.jar
lrwxrwxrwx 1 tomcat tomcat   39 May 14 12:34 slf4j_api.jar -> ../../../../../../../java/slf4j/api.jar
lrwxrwxrwx 1 tomcat tomcat   39 May 14 12:34 snakeyaml.jar -> ../../../../../../../java/snakeyaml.jar
lrwxrwxrwx 1 tomcat tomcat   51 May 14 12:34 spark-corespark-core.jar -> ../../../../../../../java/spark-core/spark-core.jar
lrwxrwxrwx 1 tomcat tomcat   69 May 14 12:34 spark-template-jadespark-template-jade.jar -> ../../../../../../../java/spark-template-jade/spark-template-jade.jar
lrwxrwxrwx 1 tomcat tomcat   40 May 14 12:34 statistics.jar -> ../../../../../../../java/statistics.jar
lrwxrwxrwx 1 tomcat tomcat   38 May 14 12:34 stax-api.jar -> ../../../../../../../java/stax-api.jar
lrwxrwxrwx 1 tomcat tomcat   39 May 14 12:34 stax2-api.jar -> ../../../../../../../java/stax2-api.jar
lrwxrwxrwx 1 tomcat tomcat   45 May 14 12:34 stringtree-json.jar -> ../../../../../../../java/stringtree-json.jar
lrwxrwxrwx 1 tomcat tomcat   36 May 14 12:34 struts.jar -> ../../../../../../../java/struts.jar
lrwxrwxrwx 1 tomcat tomcat   51 May 14 12:34 taglibs-standard-impl.jar -> ../../../../../../../java/taglibs-standard-impl.jar
lrwxrwxrwx 1 tomcat tomcat   53 May 14 12:34 taglibs-standard-jstlel.jar -> ../../../../../../../java/taglibs-standard-jstlel.jar
lrwxrwxrwx 1 tomcat tomcat   51 May 14 12:34 taglibs-standard-spec.jar -> ../../../../../../../java/taglibs-standard-spec.jar
lrwxrwxrwx 1 tomcat tomcat   47 May 14 12:34 woodstox-core-asl.jar -> ../../../../../../../java/woodstox-core-asl.jar
lrwxrwxrwx 1 tomcat tomcat   49 May 14 12:34 xalan-j2-serializer.jar -> ../../../../../../../java/xalan-j2-serializer.jar
lrwxrwxrwx 1 tomcat tomcat   38 May 14 12:34 xalan-j2.jar -> ../../../../../../../java/xalan-j2.jar
lrwxrwxrwx 1 tomcat tomcat   39 May 14 12:34 xerces-j2.jar -> ../../../../../../../java/xerces-j2.jar
lrwxrwxrwx 1 tomcat tomcat   36 May 14 12:34 xmlsec.jar -> ../../../../../../../java/xmlsec.jar
```

**Comment by mbussolotto** [comment]
I was able to reproduce the problem.

>× taskomatic.service - Taskomatic
Loaded: loaded (/usr/lib/systemd/system/taskomatic.service; enabled; vendor preset: disabled)
Drop-In: /usr/lib/systemd/system/taskomatic.service.d
└─override.conf
Active: failed (Result: exit-code) since Mon 2024-06-03 09:25:32 UTC; 16s ago
Process: 26340 ExecStart=/usr/sbin/taskomatic (code=exited, status=255/EXCEPTION)
Main PID: 26340 (code=exited, status=255/EXCEPTION)

can you confirm you also have this error in `/var/log/rhn/rhn_taskomatic_daemon.log` ?
```
Caused by: java.lang.ClassNotFoundException: net.bytebuddy.NamingStrategy$SuffixingRandom$BaseNameResolver
```

**Comment by szymonsypula** [comment]
I can confirm I have error in ```/var/log/rhn/rhn_taskomatic_daemon.log```

```
2024-06-04 07:28:21,801 [Thread-41] FATAL com.redhat.rhn.taskomatic.core.TaskomaticDaemon - net/bytebuddy/NamingStrategy$SuffixingRandom$BaseNameResolver
2024-06-04 07:28:21,808 [Thread-41] FATAL com.redhat.rhn.taskomatic.core.TaskomaticDaemon - java.lang.NoClassDefFoundError: net/bytebuddy/NamingStrategy$SuffixingRandom$BaseNameResolver
        at org.hibernate.cfg.Environment.buildBytecodeProvider(Environment.java:357)
        at org.hibernate.cfg.Environment.buildBytecodeProvider(Environment.java:352)
        at org.hibernate.cfg.Environment.<clinit>(Environment.java:246)
        at org.hibernate.boot.registry.StandardServiceRegistryBuilder.<init>(StandardServiceRegistryBuilder.java:122)
        at org.hibernate.boot.registry.StandardServiceRegistryBuilder.<init>(StandardServiceRegistryBuilder.java:96)
        at org.hibernate.cfg.Configuration.reset(Configuration.java:158)
        at org.hibernate.cfg.Configuration.<init>(Configuration.java:124)
        at org.hibernate.cfg.Configuration.<init>(Configuration.java:118)
        at com.redhat.rhn.common.hibernate.AbstractConnectionManager.createSessionFactory(AbstractConnectionManager.java:182)
        at com.redhat.rhn.common.hibernate.AbstractConnectionManager.initialize(AbstractConnectionManager.java:166)
        at com.redhat.rhn.common.hibernate.HibernateFactory.createSessionFactory(HibernateFactory.java:119)
        at com.redhat.rhn.taskomatic.core.SchedulerKernel.startup(SchedulerKernel.java:131)
        at com.redhat.rhn.taskomatic.core.TaskomaticDaemon.lambda$onStartup$0(TaskomaticDaemon.java:154)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: net.bytebuddy.NamingStrategy$SuffixingRandom$BaseNameResolver
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
        ... 14 more
```

**Comment by mbussolotto** [comment]
looks similar to https://github.com/spring-projects/spring-boot/issues/24476. I don't see `bytebuddy` as a build dependencies so it might explain the issue. I'll try to add it and let you know

**Comment by mbussolotto** [comment]
so, looks like the `byte-buddy` version present in the system is `1.14.16`, while we're compiling with `1.11`. You can verify the `byte-buddy` version used in your system running:
```
rpm -qf /usr/share/java/byte-buddy/byte-buddy.jar
```
Upgrading the build dependencies look not enough: since `net.bytebuddy.NamingStrategy.SuffixingRandom` it's deprecated I need to add `-Dnet.bytebuddy.NamingStrategy.SuffixingRandom=NamingStrategy.Suffixing` to `/etc/tomcat/conf.d/tomcat_java_opts.conf` (but without recompiling using the correct version, this fix would not work). Let me have another test than I'll create the PR for it.

**Comment by szymonsypula** [comment]
Current instilled version of byte-buddy:
byte-buddy-1.14.16-150200.5.7.1.noarch

**Comment by MaxHerrmannSVA** [comment]
Same issue here with same byte-buddy version as @szymonsypula on a fresh installation

Downgrading the byte-buddy worked to get the system running:
`zypper install --oldpackage byte-buddy=1.11.12-1.35.uyuni3`

**Comment by mbussolotto** [comment]
thanks for your feedback @MaxHerrmannSVA ! I think this can be a good solution by now.

**Comment by szymonsypula** [comment]
Before Uyuni installation executed:

```zypper -n install --auto-agree-with-licenses --oldpackage 'byte-buddy < 1.12'```

Uyuni installation ```patterns-uyuni_server-2024.05-230900.1.1.uyuni3.x86_64``` was completed successfully. 

Shall we expect some permanent fix in current version or we stick with this workaround ?

**Comment by Bjarke42** [comment]
This also solved my problem running `mgr-setup`, with byte-buddy installed version 1.14.16-150200.5.7.1.
Downgraded to the version suggested by: `zypper search -s byte-buddy`

My error was similar, RhnServletListener would not start.
