### ISSUE TITLE
Problem importing modular packages from https://rpms.remirepo.net/

### ISSUE THREAD

**Issue by bamorrow** [uyuni-project/uyuni#8972]
### Problem description

I am getting failures in trying to import he modular repo's from https://rpms.remirepo.net/ for EL8 and EL9.
A sample message I get is:

 File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/appstreams.py", line 294, in _parse_rpm_name
    raise ValueError(f"The value {nevra} cannot be parsed as a NEVRA string.")
ValueError: The value php-pecl-gmagick-0:2.0.6~RC1-3.el9.remi.7.4.x86_64 cannot be parsed as a NEVRA string.

If I remove that file and test, it just happens the same on the rest of the files in the repo.

### Steps to reproduce

1.  add repo baseurl=http://rpms.remirepo.net/enterprise/8/modular/x86_86/
2. try and run a sync
3.
...

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2024.05-230900.217.1.uyuni3
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2024.05-230900.217.1.uyuni3.src
Summary        : Uyuni Server
```

### Uyuni proxy version (if used)

```bash
N/A
```

### Useful logs

```bash
2024/06/25 10:13:27 -05:00 Importing packages finished.
2024/06/25 10:13:27 -05:00 
2024/06/25 10:13:27 -05:00   Linking packages to the channel.
2024/06/25 10:13:30 -05:00     1000 packages linked
2024/06/25 10:13:32 -05:00     1463 packages linked
2024/06/25 10:13:32 -05:00   Importing module metadata:
2024/06/25 10:13:32 -05:00     Modules in repo: 3
2024/06/25 10:13:32 -05:00 2 new package(s) imported for module composer:1:20240614071236:00000000:x86_64.
2024/06/25 10:13:32 -05:00 2 new package(s) imported for module composer:2:20240614071236:00000000:x86_64.
2024/06/25 10:13:32 -05:00 Unexpected error: <class 'ValueError'>
2024/06/25 10:13:32 -05:00 Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 783, in sync
    modulemd_importer.import_module_metadata()
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/appstreams.py", line 125, in import_module_metadata
    nevra = self._parse_rpm_name(rpm)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/appstreams.py", line 294, in _parse_rpm_name
    raise ValueError(f"The value {nevra} cannot be parsed as a NEVRA string.")
ValueError: The value php-pecl-gmagick-0:2.0.5~RC1-4.el8.remi.7.2.x86_64 cannot be parsed as a NEVRA string.
```

**Comment by bamorrow** [comment]
thank you.  That change works great
