### ISSUE TITLE
You are passing a list of packages that contains duplicated packages names

### ISSUE THREAD

**Issue by jay2theb** [uyuni-project/uyuni#8998]
### Problem description

Unable to use the WebUI to patch or update ubuntu systems since 2024.05, updating the client manually via apt works without issue

### Steps to reproduce

1. Install or update to Uyuni release 2024.05 
2. Sync all Ubuntu 22.04 repo's
3. Register a Ubuntu 22.04 client, and use the WebUI to apply package updates

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2024.05-230900.217.1.uyuni3
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : out-of-date (version 2023.09-230900.207.8.uyuni3 installed)
Source package : Uyuni-Server-release-2024.05-230900.217.1.uyuni3.src
Summary        : Uyuni Server
```

### Useful logs

```bash
ID: install_gnupg_debian
    Function: pkg.installed
        Name: install_gnupg_debian
      Result: true
     Comment: All specified packages are already installed
     Started: 09:18:20.072058
    Duration: 4.371
         SLS: channels
     Changed: {}
----------
          ID: pkg_installed
    Function: pkg.installed
        Name: pkg_installed
      Result: false
     Comment: An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/state.py", line 2401, in call
    ret = self.states[cdata["full"]](
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/loader/lazy.py", line 1234, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/loader/lazy.py", line 1249, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/loader/lazy.py", line 1282, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/states/pkg.py", line 1703, in installed
    result = _find_install_targets(
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/states/pkg.py", line 584, in _find_install_targets
    desired = _repack_pkgs(pkgs, normalize=normalize)
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/modules/pkg_resource.py", line 38, in _repack_pkgs
    raise SaltInvocationError(
salt.exceptions.SaltInvocationError: You are passing a list of packages that contains duplicated packages names: [OrderedDict([('libgdk-pixbuf2.0-bin:amd64', '2.42.8+dfsg-1ubuntu0.3')]), OrderedDict([('libmutter-10-0:amd64', '42.9-0ubuntu8')]), OrderedDict([('libjavascriptcoregtk-4.0-18:amd64', '2.44.2-0ubuntu0.22.04.1')]), OrderedDict([('libsss-idmap0:amd64', '2.6.3-1ubuntu3.3')]), OrderedDict([('libgtk-4-1:amd64', '4.6.9+ds-0ubuntu0.22.04.2')]), OrderedDict([('libtss2-tcti-swtpm0:amd64', '3.2.0-1ubuntu1.1')]), OrderedDict([('netplan.io:amd64', '0.106.1-7ubuntu0.22.04.4')]), OrderedDict([('gstreamer1.0-alsa:amd64', '1.20.1-1ubuntu0.2')]), OrderedDict([('libglib2.0-bin:amd64', '2.72.4-0ubuntu2.3')]), OrderedDict([('libvte-2.91-common:amd64', '0.68.0-1ubuntu0.1')]), OrderedDict([('sssd-ad-common:amd64', '2.6.3-1ubuntu3.3')]), OrderedDict([('cups-daemon:amd64', '2.4.1op1-1ubuntu4.10')]), OrderedDict([('libgs9-common:all', '9.55.0~dfsg1-0ubuntu5.7')]), OrderedDict([('libnetplan0:amd64', '0.106.1-7ubuntu0.22.04.4')]), OrderedDict([('bluez-obexd:amd64', '5.64-0ubuntu1.3')]), OrderedDict([('cups-ipp-utils:amd64', '2.4.1op1-1ubuntu4.10')]), OrderedDict([('libglib2.0-data:all', '2.72.4-0ubuntu2.3')]), OrderedDict([('libpam-sss:amd64', '2.6.3-1ubuntu3.3')]), OrderedDict([('libgtk-3-bin:amd64', '3.24.33-1ubuntu2.1')]), OrderedDict([('gstreamer1.0-gl:amd64', '1.20.1-1ubuntu0.2')]), OrderedDict([('libgif7:amd64', '5.1.9-2ubuntu0.1')]), OrderedDict([('sssd-krb5-common:amd64', '2.6.3-1ubuntu3.3')]), OrderedDict([('libtss2-tcti-mssim0:amd64', '3.2.0-1ubuntu1.1')]), OrderedDict([('libnss-sss:amd64', '2.6.3-1ubuntu3.3')]), OrderedDict([('libgstreamer-gl1.0-0:amd64', '1.20.1-1ubuntu0.2')]), OrderedDict([('libglib2.0-0:amd64', '2.72.4-0ubuntu2.3')]), OrderedDict([('vim-common:all', '2:8.2.3995-1ubuntu2.17')]), OrderedDict([('sssd-ad:amd64', '2.6.3-1ubuntu3.3')]), OrderedDict([('linux-image-generic-hwe-22.04:amd64', '6.5.0.41.41~22.04.2')]), OrderedDict([('libtiff5:amd64', '4.3.0-6ubuntu0.9')]), OrderedDict([('poppler-utils:amd64', '22.02.0-2ubuntu0.4')]), OrderedDict([('xxd:amd64', '2:8.2.3995-1ubuntu2.17')]), OrderedDict([('gir1.2-gtk-4.0:amd64', '4.6.9+ds-0ubuntu0.22.04.2')]), OrderedDict([('bind9-dnsutils:amd64', '1:9.18.24-0ubuntu0.22.04.1')]), OrderedDict([('gnome-remote-desktop:amd64', '42.9-0ubuntu0.22.04.2')]), OrderedDict([('libgdk-pixbuf-2.0-0:amd64', '2.42.8+dfsg-1ubuntu0.3')]), OrderedDict([('libgjs0g:amd64', '1.72.4-0ubuntu0.22.04.3~really.is.1.72.2.0ubuntu2')]), OrderedDict([('sssd-ipa:amd64', '2.6.3-1ubuntu3.3')]), OrderedDict([('libbluetooth3:amd64', '5.64-0ubuntu1.3')]), OrderedDict([('ubuntu-advantage-tools:all', '32.3~22.04')]), OrderedDict([('venv-salt-minion:amd64', '3006.0-32.1.uyuni')]), OrderedDict([('gir1.2-vte-2.91:amd64', '0.68.0-1ubuntu0.1')]), OrderedDict([('intel-microcode:amd64', '3.20240514.0ubuntu0.22.04.1')]), OrderedDict([('gtk-update-icon-cache:amd64', '3.24.33-1ubuntu2.1')]), OrderedDict([('libfprint-2-tod1:amd64', '1:1.94.3+tod1-0ubuntu2~22.04.07')]), OrderedDict([('libarchive13:amd64', '3.6.0-1ubuntu1.1')]), OrderedDict([('locales:all', '2.35-0ubuntu3.8')]), OrderedDict([('linux-headers-generic-hwe-22.04:amd64', '6.5.0.41.41~22.04.2')]), OrderedDict([('libgs9:amd64', '9.55.0~dfsg1-0ubuntu5.7')]), OrderedDict([('bluez-cups:amd64', '5.64-0ubuntu1.3')]), OrderedDict([('gir1.2-mutter-10:amd64', '42.9-0ubuntu8')]), OrderedDict([('libipa-hbac0:amd64', '2.6.3-1ubuntu3.3')]), OrderedDict([('gnome-shell-common:all', '42.9-0ubuntu2.1')]), OrderedDict([('gdb:amd64', '12.1-0ubuntu1~22.04.2')]), OrderedDict([('linux-image-generic-hwe-20.04:amd64', '5.15.0.113.113')]), OrderedDict([('libsss-sudo:amd64', '2.6.3-1ubuntu3.3')]), OrderedDict([('vim-tiny:amd64', '2:8.2.3995-1ubuntu2.17')]), OrderedDict([('gir1.2-webkit2-4.0:amd64', '2.44.2-0ubuntu0.22.04.1')]), OrderedDict([('gir1.2-gtk-3.0:amd64', '3.24.33-1ubuntu2.1')]), OrderedDict([('libpoppler-cpp0v5:amd64', '22.02.0-2ubuntu0.4')]), OrderedDict([('bind9-host:amd64', '1:9.18.24-0ubuntu0.22.04.1')]), OrderedDict([('openjdk-11-jre-headless:amd64', '11.0.23+9-1ubuntu1~22.04.1')]), OrderedDict([('linux-headers-generic-hwe-20.04:amd64', '5.15.0.113.113')]), OrderedDict([('libc-bin:amd64', '2.35-0ubuntu3.8')]), OrderedDict([('gir1.2-gdkpixbuf-2.0:amd64', '2.42.8+dfsg-1ubuntu0.3')]), OrderedDict([('libcdio19:amd64', '2.1.0-3ubuntu0.2')]), OrderedDict([('gstreamer1.0-x:amd64', '1.20.1-1ubuntu0.2')]), OrderedDict([('cups-bsd:amd64', '2.4.1op1-1ubuntu4.10')]), OrderedDict([('libsss-certmap0:amd64', '2.6.3-1ubuntu3.3')]), OrderedDict([('gstreamer1.0-plugins-base:amd64', '1.20.1-1ubuntu0.2')]), OrderedDict([('sssd-common:amd64', '2.6.3-1ubuntu3.3')]), OrderedDict([('python3-sss:amd64', '2.6.3-1ubuntu3.3')]), OrderedDict([('wget:amd64', '1.21.2-2ubuntu1.1')]), OrderedDict([('libgtk-4-bin:amd64', '4.6.9+ds-0ubuntu0.22.04.2')]), OrderedDict([('vim-runtime:all', '2:8.2.3995-1ubuntu2.17')]), OrderedDict([('libpoppler118:amd64', '22.02.0-2ubuntu0.4')]), OrderedDict([('snapd:amd64', '2.63+22.04')]), OrderedDict([('libsss-nss-idmap0:amd64', '2.6.3-1ubuntu3.3')]), OrderedDict([('gir1.2-mutter-10:amd64', '42.9-0ubuntu7.1')]), OrderedDict([('cups-core-drivers:amd64', '2.4.1op1-1ubuntu4.10')]), OrderedDict([('sssd-krb5:amd64', '2.6.3-1ubuntu3.3')]), OrderedDict([('cups-common:all', '2.4.1op1-1ubuntu4.10')]), OrderedDict([('ubuntu-pro-client:amd64', '32.3~22.04')]), OrderedDict([('libndp0:amd64', '1.8-0ubuntu3.1')]), OrderedDict([('libgdk-pixbuf2.0-common:all', '2.42.8+dfsg-1ubuntu0.3')]), OrderedDict([('mutter-common:all', '42.9-0ubuntu8')]), OrderedDict([('sssd-proxy:amd64', '2.6.3-1ubuntu3.3')]), OrderedDict([('libespeak-ng1:amd64', '1.50+dfsg-10ubuntu0.1')]), OrderedDict([('libtss2-esys-3.0.2-0:amd64', '3.2.0-1ubuntu1.1')]), OrderedDict([('gjs:amd64', '1.72.4-0ubuntu0.22.04.3~really.is.1.72.2.0ubuntu2')]), OrderedDict([('libtss2-tcti-device0:amd64', '3.2.0-1ubuntu1.1')]), OrderedDict([('fonts-opensymbol:all', '4:102.12+LibO7.6.7-0ubuntu0.23.10.1~bpo22.04.1')]), OrderedDict([('libtss2-mu0:amd64', '3.2.0-1ubuntu1.1')]), OrderedDict([('mutter-common:all', '42.9-0ubuntu7.1')]), OrderedDict([('openjdk-11-jre:amd64', '11.0.23+9-1ubuntu1~22.04.1')]), OrderedDict([('libgtk-3-0:amd64', '3.24.33-1ubuntu2.1')]), OrderedDict([('python3-idna:all', '3.3-1ubuntu0.1')]), OrderedDict([('libfprint-2-2:amd64', '1:1.94.3+tod1-0ubuntu2~22.04.07')]), OrderedDict([('cups-ppdc:amd64', '2.4.1op1-1ubuntu4.10')]), OrderedDict([('libmutter-10-0:amd64', '42.9-0ubuntu7.1')]), OrderedDict([('gstreamer1.0-plugins-base-apps:amd64', '1.20.1-1ubuntu0.2')]), OrderedDict([('cups-client:amd64', '2.4.1op1-1ubuntu4.10')]), OrderedDict([('gir1.2-javascriptcoregtk-4.0:amd64', '2.44.2-0ubuntu0.22.04.1')]), OrderedDict([('libvte-2.91-0:amd64', '0.68.0-1ubuntu0.1')]), OrderedDict([('vim:amd64', '2:8.2.3995-1ubuntu2.17')]), OrderedDict([('libvpx7:amd64', '1.11.0-2ubuntu2.3')]), OrderedDict([('libgtk-4-common:all', '4.6.9+ds-0ubuntu0.22.04.2')]), OrderedDict([('mutter:amd64', '42.9-0ubuntu7.1')]), OrderedDict([('libcupsimage2:amd64', '2.4.1op1-1ubuntu4.10')]), OrderedDict([('cups:amd64', '2.4.1op1-1ubuntu4.10')]), OrderedDict([('libcups2:amd64', '2.4.1op1-1ubuntu4.10')]), OrderedDict([('bluez:amd64', '5.64-0ubuntu1.3')]), OrderedDict([('espeak-ng-data:amd64', '1.50+dfsg-10ubuntu0.1')]), OrderedDict([('gdbserver:amd64', '12.1-0ubuntu1~22.04.2')]), OrderedDict([('gnome-shell:amd64', '42.9-0ubuntu2.1')]), OrderedDict([('libgstreamer-plugins-base1.0-0:amd64', '1.20.1-1ubuntu0.2')]), OrderedDict([('libgtk-3-common:all', '3.24.33-1ubuntu2.1')]), OrderedDict([('libtss2-tcti-cmd0:amd64', '3.2.0-1ubuntu1.1')]), OrderedDict([('libwebkit2gtk-4.0-37:amd64', '2.44.2-0ubuntu0.22.04.1')]), OrderedDict([('ghostscript:amd64', '9.55.0~dfsg1-0ubuntu5.7')]), OrderedDict([('ubuntu-pro-client-l10n:amd64', '32.3~22.04')]), OrderedDict([('libssl3:amd64', '3.0.2-0ubuntu1.16')]), OrderedDict([('bind9-libs:amd64', '1:9.18.24-0ubuntu0.22.04.1')]), OrderedDict([('linux-firmware:all', '20220329.git681281e4-0ubuntu3.31')]), OrderedDict([('mutter:amd64', '42.9-0ubuntu8')]), OrderedDict([('libc6-dbg:amd64', '2.35-0ubuntu3.8')]), OrderedDict([('libtss2-sys1:amd64', '3.2.0-1ubuntu1.1')]), OrderedDict([('libpoppler-glib8:amd64', '22.02.0-2ubuntu0.4')]), OrderedDict([('sssd-ldap:amd64', '2.6.3-1ubuntu3.3')]), OrderedDict([('libc6:amd64', '2.35-0ubuntu3.8')]), OrderedDict([('cups-server-common:all', '2.4.1op1-1ubuntu4.10')]), OrderedDict([('ghostscript-x:amd64', '9.55.0~dfsg1-0ubuntu5.7')]), OrderedDict([('openssl:amd64', '3.0.2-0ubuntu1.16')]), OrderedDict([('sssd:amd64', '2.6.3-1ubuntu3.3')])]. This cannot be processed. In case you are targeting different versions of the same package, please target them individually

     Started: 09:18:20.077662
    Duration: 54.074
         SLS: packages.pkginstall
     Changed: {}
```

### Additional information

An early indication that this issue will occur is the available package counts are different in the WebUI host details view, when compared to the package details view, see the screenshots below: 

![image](https://github.com/uyuni-project/uyuni/assets/26289047/c5dcaf41-1b1f-4194-9c3b-fdb4c7d2ad4b)

Package detail view:

![image](https://github.com/uyuni-project/uyuni/assets/26289047/4fafc4df-43c7-4b36-8bc2-196820e94189)

**Comment by mcalmer** [comment]
A fix is on the way and the next Uyuni release should have it. PR is linked
