### ISSUE TITLE
Certificate renewal fails on podman container

### ISSUE THREAD

**Issue by sbluhm** [uyuni-project/uyuni#9045]
### Problem description

Renewing certificates (partially) according to the documentation:
https://www.uyuni-project.org/uyuni-docs/en/uyuni/administration/ssl-certs-selfsigned.html

fails with 
```
/usr/lib64/python3.6/getpass.py:91: GetPassWarning: Can not control echo on the terminal.
  passwd = fallback_getpass(prompt, stream)
Warning: Password input may be echoed.
CA password: 
ERROR: unhandled exception occurred:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/getpass.py", line 69, in unix_getpass
    old = termios.tcgetattr(fd)     # a copy to save
termios.error: (25, 'Inappropriate ioctl for device')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/rhn-ssl-tool", line 52, in <module>
    sys.exit(mod.main() or 0)
  File "/usr/lib/python3.6/site-packages/certs/rhn_ssl_tool.py", line 1725, in main
    ret = _main() or 0
  File "/usr/lib/python3.6/site-packages/certs/rhn_ssl_tool.py", line 1685, in _main
    genServer_dependencies(getCAPassword(options, confirmYN=0), DEFS)
  File "/usr/lib/python3.6/site-packages/certs/rhn_ssl_tool.py", line 332, in getCAPassword
    pw = getpass.getpass("CA password: ")
  File "/usr/lib64/python3.6/getpass.py", line 91, in unix_getpass
    passwd = fallback_getpass(prompt, stream)
  File "/usr/lib64/python3.6/getpass.py", line 126, in fallback_getpass
    return _raw_input(prompt, stream)
  File "/usr/lib64/python3.6/getpass.py", line 148, in _raw_input
    raise EOFError
EOFError
```

### Steps to reproduce

1. Log into the Uyuni Podman host
2. `mgrctl exec 'rhn-ssl-tool --gen-server --dir="/root/ssl-build" --set-country="US" \
--set-state="example" --set-city="Hambühren" --set-org="example" \
--set-org-unit="example" --set-email="test@example.com" \
--set-hostname="uyuni.example.com" --set-cname="example.com"'
`

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : @System
Name           : Uyuni-Server-release
Version        : 2024.05-230900.217.1.uyuni3
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2024.05-230900.217.1.uyuni3.src
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

### Additional information

Running on Enterprise Linux 9 podman container
Workaround:
`mgrctl exec 'rhn-ssl-tool --gen-server --dir="/root/ssl-build" --set-country="US" \
--set-state="example" --set-city="Hambühren" --set-org="example" \
--set-org-unit="example" --set-email="test@example.com" \
--set-hostname="uyuni.example.com" --set-cname="example.com" \
--password="PASSWORD" '
`

Root cause is the need to define the certificate password via command prompt:
`CA password: `

**Comment by cbosdo** [comment]
could you pass `-ti` to `mgrctl exec`? Without this there will be no terminal passed as input to `rhn-ssl-tool`

**Comment by cbosdo** [comment]
This is working for me:

```
mgrctl exec -ti -- rhn-ssl-tool --gen-server --dir="/root/ssl-build" --set-country="US"  --set-state="example" --set-city="Hambühren" --set-org="example"  --set-org-unit="example" --set-email="test@example.com"  --set-hostname="uyuni.example.com" --set-cname="example.com"
```

**Comment by cbosdo** [comment]
Doc PR submitted, not a product issue.
