### ISSUE TITLE
Exception on "Schedule Autoinstallation"

### ISSUE THREAD

**Issue by sbluhm** [uyuni-project/uyuni#9091]
### Problem description

When selecting "Schedule Autoinstallation and Finish" the internal server error page appears and I get a stacktrace e-mail.

### Steps to reproduce

1. Set up Autoinstallation
2. Install a server via autoinstallation and register it to Uyuni
3. Go to System List --> <server> --> Provisioning --> Autoinstallation --> Schedule --> <select a profile>
4. Press "Schedule Autoinstallation and Finish"

### Uyuni version

```bash
Container 2024-07
```

### Useful logs

```bash
The following exception occurred while executing this request:
POST /rhn/systems/details/kickstart/ScheduleWizard.do

Date:7/24/24 6:05:02 AM UTC
Headers:
  host: uyuni.example.com
  user-agent: Mozilla/5.0 (X11; Linux x86_64; rv:126.0) Gecko/20100101 Firefox/126.0
  accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
  accept-language: de,en-US;q=0.7,en;q=0.3
  accept-encoding: gzip, deflate, br, zstd
  content-type: application/x-www-form-urlencoded
  content-length: 903
  Origin: https://uyuni.example.com
  connection: keep-alive
  referer: https://uyuni.example.com/rhn/systems/details/kickstart/ScheduleWizard.do?sid=1000010010&
  cookie: JSESSIONID=F26E61936C58B301F92504AC886C5A63; pxt-session-cookie=18520xbe6f9f8b5ce3a3110e95efc18a206415884141ecb1eba240e6964b97d67aba59
  Upgrade-Insecure-Requests: 1
  Sec-Fetch-Dest: document
  Sec-Fetch-Mode: navigate
  Sec-Fetch-Site: same-origin
  Sec-Fetch-User: ?1
  Priority: u=1

Request:
Local Name = uyuni.example.com
Server Name = uyuni.example.com
Requested Session Id came from Cookie
Requested Session Valid = true
Session = org.apache.catalina.session.StandardSessionFacade@5a91aedb[session=StandardSession[F26E61936C58B301F92504AC886C5A63]]
Protocol = https
Request Locale = en_US
Request Character Encoding = UTF-8
Attribute Names = rhnActiveLang, org.apache.struts.action.MESSAGE, org.apache.struts.action.mapping.instance, org.apache.tomcat.util.net.secure_protocol_version, requestedUri, session, javax.servlet.request.key_size, org.apache.struts.action.MODULE, list_1154021400_radio, javax.servlet.request.cipher_suite, javax.servlet.request.ssl_session_id, __sitemesh__filterapplied, kickstartScheduleWizardForm, cobbler_id, javax.servlet.jsp.jstl.fmt.timeZone.request,

Form Variables:
  sid: 1000010010
  csrf_token: -3310035659697233697
  submitted: true
  list_1154021400_hidden: null
  list_1154021400_filtername:
  list_1154021400_oldfilterval:
  list_1154021400_filterby: Autoinstallation Profile
  list_1154021400_filterval:
  1154021400_PAGE_SIZE_LABEL: 25
  1154021400_PAGE_SIZE_LABEL_SELECTED: null
  list_1154021400_filterattr: label
  list_1154021400_radio: 343b3ab2848642e1921fb1442dff57a3
  list_1154021400_sortby:
  list_1154021400_sortdir:
  list_1154021400_parent_is_an_element: true
  targetProfileType:
  targetProfile:
  targetServerProfile:
  postKernelParamsType:
  postKernelParams:
  kernelParamsType:
  kernelParams:
  networkType:
  networkInterface: ens34
  bondType: none
  bondInterface:
  bondOptions:
  hiddenBondSlaveInterfaces:
  bondStatic:
  bondAddress:
  bondNetmask:
  bondGateway:
  wizardStep: third
  cobbler_id:
  destroyDisks: false
  date_day: 24
  date_month: 6
  date_year: 2024
  date_hour: 6
  date_minute: 4
  date_am_pm: 0
  scheduleAsap: false


User Information:
User admin (id 1, org_id 1)

Exception:
javax.servlet.ServletException: java.lang.reflect.InvocationTargetException
        at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:535)
        at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:433)
        at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:237)
        at com.redhat.rhn.frontend.struts.RhnRequestProcessor.process(RhnRequestProcessor.java:104)
        at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1196)
        at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:432)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:555)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:199)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
        at com.redhat.rhn.frontend.servlets.SystemDetailsMessageFilter.doFilter(SystemDetailsMessageFilter.java:57)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
        at com.redhat.rhn.frontend.servlets.AuthFilter.doFilter(AuthFilter.java:112)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
        at com.opensymphony.module.sitemesh.filter.PageFilter.parsePage(PageFilter.java:142)
        at com.opensymphony.module.sitemesh.filter.PageFilter.doFilter(PageFilter.java:58)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
        at com.redhat.rhn.frontend.servlets.LocalizedEnvironmentFilter.doFilter(LocalizedEnvironmentFilter.java:71)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
        at com.redhat.rhn.frontend.servlets.EnvironmentFilter.doFilter(EnvironmentFilter.java:99)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
        at com.redhat.rhn.frontend.servlets.SessionFilter.doFilter(SessionFilter.java:59)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
        at com.redhat.rhn.frontend.servlets.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:98)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
        at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:424)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:936)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.redhat.rhn.frontend.struts.wizard.WizardStep.invoke(WizardStep.java:115)
        at com.redhat.rhn.frontend.struts.wizard.RhnWizardAction.dispatch(RhnWizardAction.java:104)
        at com.redhat.rhn.frontend.struts.wizard.RhnWizardAction.execute(RhnWizardAction.java:90)
        at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:431)
        ... 50 more
Caused by: java.util.NoSuchElementException: No value present
        at java.base/java.util.Optional.get(Optional.java:143)
        at com.redhat.rhn.frontend.action.kickstart.ScheduleKickstartWizardAction.parseKernelOptions(ScheduleKickstartWizardAction.java:1040)
        at com.redhat.rhn.frontend.action.kickstart.ScheduleKickstartWizardAction.parseKernelOptions(ScheduleKickstartWizardAction.java:1005)
        at com.redhat.rhn.frontend.action.kickstart.ScheduleKickstartWizardAction.runThird(ScheduleKickstartWizardAction.java:690)
        ... 58 more
```

### Additional information

I have seen this issue yesterday when updating the path in the distribution configuration page. Today, I couldn't reproduce it so it might be sporadic. There might be a connection though.

When I find time later, I can look at what's going on.

**Comment by mbussolotto** [comment]
Thanks @sbluhm for reporting it. Did it happen again or do you have any other information? Otherwise it's difficult to understand what happened and maybe it might be closed (and reopen if it happens again with more information)

**Comment by sbluhm** [comment]
@mbussolotto let me update Uyuni and check it out this week and close if it doesn't show up again.

**Comment by sbluhm** [comment]
@mbussolotto yes, this is still reproducible on 2024.08.
Anything you need for the analysis? I am also happy to organise screen sharing, if it helps.

**Comment by mbussolotto** [comment]
https://github.com/uyuni-project/uyuni/blob/531385b09894eb5c3bfb0700341ecbb64ac80849/java/code/src/com/redhat/rhn/frontend/action/kickstart/ScheduleKickstartWizardAction.java#L1039-L1042

This is the part of the code that fails. 
@aaannz is it fine that kernel options is not present (I guess so since it's an optional, but the code doesn't have any kind of check) ? Can you please have a look ? Thanks :)

**Comment by aaannz** [comment]
It could be fine not having any kernel options. It depends on what initrd is used and in what scenario. So IMO this should accept missing/empty kOpts.

**Comment by mbussolotto** [comment]
Thanks @aaannz .
@sbluhm I don't think we need any other infomation, the problem looks clear. I'll keep you updated
