### ISSUE TITLE
Oracle Linux 8 epel repository sync fails with PREPENDED_DIR on 2024.05 and 2024.07

### ISSUE THREAD

**Issue by j-kihet** [uyuni-project/uyuni#9095]
### Problem description

When trying to sync Oracle linux 8 epel repository it fails with "PREPENDED_DIR" error message.
Tested on a brand new podman instance and a old legacy version.

### Steps to reproduce

1. add Oracle Linux 8 epel repository. https://yum.oracle.com/repo/OracleLinux/OL8/developer/EPEL/x86_64/ 
2. sync repository. 

### Uyuni version

```bash
2024.05 and 2024.07
```

### Uyuni proxy version (if used)

```bash
not used
```

### Useful logs

```bash
Reopo log: 2024.07
2024/07/24 02:59:58 -00:00     28871/28872 : zswap-cli-0.9.1-1.el8.x86_64.rpm
2024/07/24 03:00:00 -00:00     28872/28872 : zvbi-debugsource-0.2.35-9.el8.x86_64.rpm
2024/07/24 03:00:00 -00:00 Filtering packages that failed to download
2024/07/24 03:00:00 -00:00 Importing packages started.
2024/07/24 03:00:00 -00:00
2024/07/24 03:00:00 -00:00   Importing packages to DB:
2024/07/24 03:00:00 -00:00 PREPENDED_DIR
2024/07/24 03:00:00 -00:00 PREPENDED_DIR
2024/07/24 03:00:00 -00:00 PREPENDED_DIR
2024/07/24 03:00:00 -00:00 PREPENDED_DIR
2024/07/24 03:00:00 -00:00 PREPENDED_DIR
2024/07/24 03:00:00 -00:00 PREPENDED_DIR
2024/07/24 03:00:00 -00:00 PREPENDED_DIR
2024/07/24 03:00:00 -00:00 PREPENDED_DIR
2024/07/24 03:00:00 -00:00 PREPENDED_DIR
2024/07/24 03:00:00 -00:00 PREPENDED_DIR
2024/07/24 03:00:00 -00:00 PREPENDED_DIR
2024/07/24 03:00:00 -00:00 PREPENDED_DIR
2024/07/24 03:00:00 -00:00 PREPENDED_DIR
2024/07/24 03:00:00 -00:00 PREPENDED_DIR
2024/07/24 03:00:00 -00:00 PREPENDED_DIR
2024/07/24 03:00:00 -00:00 PREPENDED_DIR
2024/07/24 03:00:00 -00:00 PREPENDED_DIR
2024/07/24 03:00:00 -00:00 PREPENDED_DIR
2024/07/24 03:00:00 -00:00 PREPENDED_DIR
2024/07/24 03:00:00 -00:00 PREPENDED_DIR
2024/07/24 03:00:00 -00:00 PREPENDED_DIR
2024/07/24 03:00:00 -00:00 PREPENDED_DIR
2024/07/24 03:00:00 -00:00 PREPENDED_DIR
```
```
Reopo log: 2024.05
2024/07/22 19:38:27 -00:00   Package batch #1420 of 1439 completed...
2024/07/22 19:38:27 -00:00 PREPENDED_DIR
2024/07/22 19:38:27 -00:00 PREPENDED_DIR
2024/07/22 19:38:27 -00:00 PREPENDED_DIR
2024/07/22 19:38:27 -00:00 PREPENDED_DIR
2024/07/22 19:38:27 -00:00 PREPENDED_DIR
2024/07/22 19:38:27 -00:00 PREPENDED_DIR
2024/07/22 19:38:27 -00:00 PREPENDED_DIR
2024/07/22 19:38:27 -00:00 PREPENDED_DIR
2024/07/22 19:38:27 -00:00   Package batch #1421 of 1439 completed...
2024/07/22 19:38:27 -00:00 Importing packages finished.
2024/07/22 19:38:27 -00:00 
2024/07/22 19:38:27 -00:00   Linking packages to the channel.
2024/07/22 19:38:27 -00:00 Unexpected error: <class 'AttributeError'>
2024/07/22 19:38:27 -00:00 Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 777, in sync
    plugin, data["id"], url, is_non_local_repo
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 1554, in import_packages
    importer.run()
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/importLib.py", line 818, in run
    self.fix()
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/packageImport.py", line 101, in fix
    if not CFG.ENABLE_NVREA:
  File "/usr/lib/python3.6/site-packages/spacewalk/common/rhnConfig.py", line 254, in __getattr__
    raise AttributeError(key)
AttributeError: ENABLE_NVREA

2024/07/22 19:38:27 -00:00   Updating overview of 92 systems
```

### Additional information

2024.07 does not show the NVREA error , 2024.05 does

**Comment by avshiliaev** [comment]
Hey @j-kihet 
thanks for the report! It's a known problem and the fix should be out soon.

* https://github.com/uyuni-project/uyuni/pull/8916

**Comment by j-kihet** [comment]
@avshiliaev 
Would this issue also cause problems when Package Profiles are updated/refreshed?
