### ISSUE TITLE
Uyuni Grafana formula fails apply high state on Suse Leap 15.6

### ISSUE THREAD

**Issue by Autoflow** [uyuni-project/uyuni#9138]
### Problem description

Hello community,
following the official documentation I tried the following:
1) select the host I try to activate Grafana formula for (Systems -> bigbrother.xx.xx)
2) open formulas tab and activate "Monitoring -> Grafana" and edited the properties on new Grafana tab
3) saved the changes
4) opened the States tab and clicked "Apply Highstates"

After some seconds I get "1 system failed to complete this action", Failed to apply state(s): highstate, Code 1
---------
Error: Could not parse state file. Please check YAML syntax.
- |-
    Rendering SLS 'base:grafana' failed: Jinja variable 'supported' is undefined; line 15

    ---
    [...]
          test.fail_without_changes:
            - name: "OS not supported!"
      {%- endif %}
    {%- endif %}

    {%- if supported %}    <======================
    {%- if salt['pillar.get']('grafana:enabled', False) %}
    {%- if salt['pillar.get']('mgr_server_is_uyuni', True) %}
      {% set product_name = 'Uyuni' %}
    {%- else %}
      {% set product_name = 'SUSE Manager' %}
    [...]
    ---
    
    The host I try to install Grafana on is a fresh SuSE Leap 15.6.

### Steps to reproduce

1) select the host to activate Grafana formula for (Systems -> your host)
2) open formulas tab and activate "Monitoring -> Grafana" and edit the properties on new Grafana tab
3) saved the changes
4) open the States tab and clicked "Apply Highstates"

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : @System
Name           : Uyuni-Server-release
Version        : 2024.07-230900.219.1.uyuni3
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2024.07-230900.219.1.uyuni3.src
Upstream URL   : https://www.uyuni-project.org/
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

### Useful logs

```bash
Salt Minion log:

2024-08-05 13:34:07,711 [salt.utils.templates:295 ][ERROR   ][24336] Rendering exception occurred
Traceback (most recent call last):
  File "/usr/lib/venv-salt-minion/lib64/python3.11/site-packages/salt/utils/templates.py", line 477, in render_jinja_tmpl
    output = template.render(**decoded_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/venv-salt-minion/lib64/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/venv-salt-minion/lib64/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 15, in top-level template code
jinja2.exceptions.UndefinedError: 'supported' is undefined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/venv-salt-minion/lib64/python3.11/site-packages/salt/utils/templates.py", line 219, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/venv-salt-minion/lib64/python3.11/site-packages/salt/utils/templates.py", line 483, in render_jinja_tmpl
    raise SaltRenderError("Jinja variable {}{}".format(exc, out), line, tmplstr)
salt.exceptions.SaltRenderError: Jinja variable 'supported' is undefined; line 15

---
[...]
      test.fail_without_changes:
        - name: "OS not supported!"
  {%- endif %}
{%- endif %}

{%- if supported %}    <======================
{%- if salt['pillar.get']('grafana:enabled', False) %}
{%- if salt['pillar.get']('mgr_server_is_uyuni', True) %}
  {% set product_name = 'Uyuni' %}
{%- else %}
  {% set product_name = 'SUSE Manager' %}
[...]
---
2024-08-05 13:34:07,712 [salt.state       :295 ][CRITICAL][24336] Rendering SLS 'base:grafana' failed: Jinja variable 'supported' is undefined; line 15

---
[...]
      test.fail_without_changes:
        - name: "OS not supported!"
  {%- endif %}
{%- endif %}

{%- if supported %}    <======================
{%- if salt['pillar.get']('grafana:enabled', False) %}
{%- if salt['pillar.get']('mgr_server_is_uyuni', True) %}
  {% set product_name = 'Uyuni' %}
{%- else %}
  {% set product_name = 'SUSE Manager' %}
[...]
---
```

**Comment by m-czernek** [comment]
Thank you for the bug report! We already saw this and created a fix in https://github.com/SUSE/salt-formulas/pull/222. The fix should be available in the next Uyuni release. I'm closing this bug as fixed, but feel free to add more comments here in case you have any questions.
