### ISSUE TITLE
Failed RHN registration after upgrade from Uyuni 2024.05 to 2024.07

### ISSUE THREAD

**Issue by mrstfn-sub** [uyuni-project/uyuni#9139]
### Problem description

After upgrade from 2024.05 to 2024.07: 
- unable to register a new client (oracle linux 6,7,8,9) through RHN
- unable to list repositories or use packages from Uyuni  for none of the existing RHN clients (Oracle Linux 6, 7, 8,9)

Error observed in both cases, in apache2 logs:` spacewalk.server.apacheRequest.UnknownXML: Invalid request received (class xmlrpc.up2date is not defined (function = login)) `

Salt clients are all clear.

### Steps to reproduce

**Registering a new Uyuni RHN client:** 
1.  rhnreg_ks --serverUrl=https://<my-uyuni-server>/XMLRPC --activationkey=<my-activation-key>
```
output: 

An error has occurred:
Error communicating with server. The message was:
Internal Server Error
```

**Using repositories for existing RHN client:** 
1. yum repoinfo

output: 

```
Loaded plugins: rhnplugin, ulninfo
There was an error communicating with ULN.
ULN Classic support will be disabled.
Error communicating with server. The message was:
Internal Server Error
repolist: 0
```

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2024.07-230900.219.1.uyuni3
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2024.07-230900.219.1.uyuni3.src
Upstream URL   : https://www.uyuni-project.org/
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

### Uyuni proxy version (if used)

```bash
package 'Uyuni-Proxy-release' not found.
No matching items found.
```

### Useful logs

```bash
/var/log/apache2/error_log  (for both cases: new client registration or yum repo info for an existing client)

Mon Aug 05 09:53:14.580163 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] Exception reported from uyuni
[Mon Aug 05 09:53:14.580210 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] Time: Mon Aug  5 09:53:14 2024
[Mon Aug 05 09:53:14.580216 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] Exception type <class 'spacewalk.server.apacheRequest.UnknownXML'>
[Mon Aug 05 09:53:14.580220 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] Exception while handling function <class 'spacewalk.server.apacheRequest.UnknownXML'>
[Mon Aug 05 09:53:14.580224 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] Request object information:
[Mon Aug 05 09:53:14.580228 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] URI: /XMLRPC
[Mon Aug 05 09:53:14.580231 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] Remote Host: [my_client_host]
[Mon Aug 05 09:53:14.580235 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] Server Name: [my_uyuni_server]:443
[Mon Aug 05 09:53:14.580239 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] Headers passed in:
[Mon Aug 05 09:53:14.580242 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tAccept-Encoding: identity
[Mon Aug 05 09:53:14.580246 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tCONTENT_LENGTH: 122
[Mon Aug 05 09:53:14.580250 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tCONTENT_TYPE: text/xml
[Mon Aug 05 09:53:14.580253 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tCONTEXT_DOCUMENT_ROOT: /usr/share/susemanager/www/htdocs
[Mon Aug 05 09:53:14.580264 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tCONTEXT_PREFIX: 
[Mon Aug 05 09:53:14.580268 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tDOCUMENT_ROOT: /usr/share/susemanager/www/htdocs
[Mon Aug 05 09:53:14.580272 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tGATEWAY_INTERFACE: CGI/1.1
[Mon Aug 05 09:53:14.580276 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tHTTP_ACCEPT_ENCODING: identity
[Mon Aug 05 09:53:14.580280 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tHTTP_HOST: [my_uyuni_server]
[Mon Aug 05 09:53:14.580293 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tHTTP_USER_AGENT: rhn.rpclib.py/2.5.65-4.el7
[Mon Aug 05 09:53:14.580297 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tHTTP_X_CLIENT_VERSION: 1
[Mon Aug 05 09:53:14.580300 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tHTTP_X_INFO: RPC Processor (C) Red Hat, Inc (version 2.5.65-4.el7)
[Mon Aug 05 09:53:14.580304 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tHTTP_X_RHN_CLIENT_CAPABILITY: caneatCheese(1)=1,packages.extended_profile(2)=1,reboot.reboot(1)=1,packages.verify(1)=1,packages.runTransaction(1)=1,packages.update(2)=2,packages.rollBack(1)=1
[Mon Aug 05 09:53:14.580308 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tHTTP_X_RHN_TRANSPORT_CAPABILITY: follow-redirects=3
[Mon Aug 05 09:53:14.580312 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tHTTP_X_TRANSPORT_INFO: Extended Capabilities Transport (C) Red Hat, Inc (version 2.5.65-4.el7)
[Mon Aug 05 09:53:14.580315 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tHTTP_X_UP2DATE_VERSION: 2.0.2-17.0.1.el7
[Mon Aug 05 09:53:14.580319 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tHost: [my_uyuni_server]
[Mon Aug 05 09:53:14.580323 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tPATH_INFO: 
[Mon Aug 05 09:53:14.580326 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tQUERY_STRING: 
[Mon Aug 05 09:53:14.580329 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tREMOTE_ADDR: 172.21.1.22
[Mon Aug 05 09:53:14.580333 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tREMOTE_PORT: 48251
[Mon Aug 05 09:53:14.580336 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tREQUEST_METHOD: POST
[Mon Aug 05 09:53:14.580340 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tREQUEST_SCHEME: https
[Mon Aug 05 09:53:14.580343 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tREQUEST_URI: /XMLRPC
[Mon Aug 05 09:53:14.580347 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tSCRIPT_FILENAME: /usr/share/rhn/wsgi/xmlrpc.py
[Mon Aug 05 09:53:14.580350 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tSCRIPT_NAME: /XMLRPC
[Mon Aug 05 09:53:14.580354 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tSCRIPT_URI: https://[my_uyuni_server]/XMLRPC
[Mon Aug 05 09:53:14.580358 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tSCRIPT_URL: /XMLRPC
[Mon Aug 05 09:53:14.580361 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tSERVER_ADDR: [my_uyuni_server_ip_address]
[Mon Aug 05 09:53:14.580365 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tSERVER_ADMIN: [no address given]
[Mon Aug 05 09:53:14.580368 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tSERVER_NAME: [my_uyuni_server]
[Mon Aug 05 09:53:14.580372 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tSERVER_PORT: 443
[Mon Aug 05 09:53:14.580376 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tSERVER_PROTOCOL: HTTP/1.1
[Mon Aug 05 09:53:14.580379 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tSERVER_SIGNATURE: 
[Mon Aug 05 09:53:14.580383 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tSERVER_SOFTWARE: Apache
[Mon Aug 05 09:53:14.580386 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tUser-Agent: rhn.rpclib.py/2.5.65-4.el7
[Mon Aug 05 09:53:14.580390 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tX-Client-Version: 1
[Mon Aug 05 09:53:14.580394 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tX-Info: RPC Processor (C) Red Hat, Inc (version 2.5.65-4.el7)
[Mon Aug 05 09:53:14.580398 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tX-RHN-Client-Capability: caneatCheese(1)=1,packages.extended_profile(2)=1,reboot.reboot(1)=1,packages.verify(1)=1,packages.runTransaction(1)=1,packages.update(2)=2,packages.rollBack(1)=1
[Mon Aug 05 09:53:14.580402 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tX-RHN-Transport-Capability: follow-redirects=3
[Mon Aug 05 09:53:14.580409 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tX-Transport-Info: Extended Capabilities Transport (C) Red Hat, Inc (version 2.5.65-4.el7)
[Mon Aug 05 09:53:14.580413 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tX-Up2Date-Version: 2.0.2-17.0.1.el7
[Mon Aug 05 09:53:14.580417 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tapache.version: (2, 4, 51)
[Mon Aug 05 09:53:14.580420 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tmod_wsgi.application_group: [my_uyuni_server]|/xmlrpc
[Mon Aug 05 09:53:14.580424 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tmod_wsgi.callable_object: application
[Mon Aug 05 09:53:14.580428 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tmod_wsgi.enable_sendfile: 0
[Mon Aug 05 09:53:14.580431 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tmod_wsgi.handler_script: 
[Mon Aug 05 09:53:14.580435 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tmod_wsgi.ignore_activity: 0
[Mon Aug 05 09:53:14.580439 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tmod_wsgi.listener_host: 
[Mon Aug 05 09:53:14.580442 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tmod_wsgi.listener_port: 443
[Mon Aug 05 09:53:14.580446 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tmod_wsgi.path_info: 
[Mon Aug 05 09:53:14.580450 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tmod_wsgi.process_group: 
[Mon Aug 05 09:53:14.580453 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tmod_wsgi.request_handler: wsgi-script
[Mon Aug 05 09:53:14.580457 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tmod_wsgi.request_id: hsQCKc+r89Q
[Mon Aug 05 09:53:14.580461 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tmod_wsgi.request_start: 1722862394328198
[Mon Aug 05 09:53:14.580465 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tmod_wsgi.script_name: /XMLRPC
[Mon Aug 05 09:53:14.580468 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tmod_wsgi.script_reloading: 1
[Mon Aug 05 09:53:14.580472 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tmod_wsgi.script_start: 1722862394388971
[Mon Aug 05 09:53:14.580476 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tmod_wsgi.thread_id: 0
[Mon Aug 05 09:53:14.580479 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tmod_wsgi.thread_requests: 0
[Mon Aug 05 09:53:14.580483 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tmod_wsgi.total_requests: 0
[Mon Aug 05 09:53:14.580487 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \tmod_wsgi.version: (4, 7, 1)
[Mon Aug 05 09:53:14.580490 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \twsgi.errors: <_io.TextIOWrapper name='<wsgi.errors>' encoding='utf-8'>
[Mon Aug 05 09:53:14.580494 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \twsgi.file_wrapper: <class 'mod_wsgi.FileWrapper'>
[Mon Aug 05 09:53:14.580498 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \twsgi.input: <mod_wsgi.Input object at 0x7fc60e9182d0>
[Mon Aug 05 09:53:14.580502 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \twsgi.input_terminated: True
[Mon Aug 05 09:53:14.580505 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \twsgi.multiprocess: True
[Mon Aug 05 09:53:14.580509 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \twsgi.multithread: False
[Mon Aug 05 09:53:14.580512 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \twsgi.run_once: False
[Mon Aug 05 09:53:14.580516 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \twsgi.url_scheme: https
[Mon Aug 05 09:53:14.580525 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] \twsgi.version: (1, 0)
[Mon Aug 05 09:53:14.580532 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] Extra information about this error:
[Mon Aug 05 09:53:14.580536 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] Response sent back to the caller:
[Mon Aug 05 09:53:14.580540 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] While running 'registration.welcome_message': caught
[Mon Aug 05 09:53:14.580560 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] <class 'spacewalk.server.apacheRequest.UnknownXML'> : Invalid request received (class xmlrpc.registration is not defined (function = welcome_message)).
[Mon Aug 05 09:53:14.580564 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] 
[Mon Aug 05 09:53:14.580567 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] 
[Mon Aug 05 09:53:14.580570 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] 
[Mon Aug 05 09:53:14.580574 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] Exception Handler Information
[Mon Aug 05 09:53:14.580577 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] Traceback (most recent call last):
[Mon Aug 05 09:53:14.580580 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251]   File "/usr/lib/python3.6/site-packages/spacewalk/server/apacheRequest.py", line 140, in call_function
[Mon Aug 05 09:53:14.580584 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251]     func = self.method_ref(method)
[Mon Aug 05 09:53:14.580587 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251]   File "/usr/lib/python3.6/site-packages/spacewalk/server/apacheRequest.py", line 525, in method_ref
[Mon Aug 05 09:53:14.580591 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251]     % (self.server, classname, funcname)
[Mon Aug 05 09:53:14.580594 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] spacewalk.server.apacheRequest.UnknownXML: Invalid request received (class xmlrpc.registration is not defined (function = welcome_message)).
[Mon Aug 05 09:53:14.580603 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] 
[Mon Aug 05 09:53:14.581650 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] mod_wsgi (pid=11471): Exception occurred processing WSGI script '/usr/share/rhn/wsgi/xmlrpc.py'.
[Mon Aug 05 09:53:14.582675 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] Traceback (most recent call last):
[Mon Aug 05 09:53:14.582707 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251]   File "/usr/lib/python3.6/site-packages/spacewalk/server/apacheRequest.py", line 140, in call_function
[Mon Aug 05 09:53:14.582715 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251]     func = self.method_ref(method)
[Mon Aug 05 09:53:14.582722 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251]   File "/usr/lib/python3.6/site-packages/spacewalk/server/apacheRequest.py", line 525, in method_ref
[Mon Aug 05 09:53:14.582726 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251]     % (self.server, classname, funcname)
[Mon Aug 05 09:53:14.582739 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] spacewalk.server.apacheRequest.UnknownXML: Invalid request received (class xmlrpc.registration is not defined (function = welcome_message)).
[Mon Aug 05 09:53:14.582752 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] 
[Mon Aug 05 09:53:14.582756 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] During handling of the above exception, another exception occurred:
[Mon Aug 05 09:53:14.582760 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] 
[Mon Aug 05 09:53:14.582766 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] Traceback (most recent call last):
[Mon Aug 05 09:53:14.582805 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251]   File "/usr/share/rhn/wsgi/xmlrpc.py", line 23, in application
[Mon Aug 05 09:53:14.582812 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251]     return wsgiHandler.handle(environ, start_response, "xmlrpc", "server.xmlrpc")
[Mon Aug 05 09:53:14.582819 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251]   File "/usr/share/rhn/wsgi/wsgiHandler.py", line 57, in handle
[Mon Aug 05 09:53:14.582823 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251]     ret = appServ(req)
[Mon Aug 05 09:53:14.582829 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251]   File "/usr/lib/python3.6/site-packages/spacewalk/server/apacheHandler.py", line 206, in handler
[Mon Aug 05 09:53:14.582842 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251]     ret = self._req_processor.process()
[Mon Aug 05 09:53:14.582848 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251]   File "/usr/lib/python3.6/site-packages/spacewalk/server/apacheRequest.py", line 575, in process
[Mon Aug 05 09:53:14.582852 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251]     return self.call_function(method, params)
[Mon Aug 05 09:53:14.582858 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251]   File "/usr/lib/python3.6/site-packages/spacewalk/server/apacheRequest.py", line 164, in call_function
[Mon Aug 05 09:53:14.582862 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251]     severity="notification",
[Mon Aug 05 09:53:14.582868 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251]   File "/usr/lib/python3.6/site-packages/spacewalk/common/rhnTB.py", line 196, in Traceback
[Mon Aug 05 09:53:14.582872 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251]     rhnMail.send(headers, outstring)
[Mon Aug 05 09:53:14.582878 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251]   File "/usr/lib/python3.6/site-packages/spacewalk/common/rhnMail.py", line 80, in send
[Mon Aug 05 09:53:14.582882 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251]     with smtplib.SMTP("localhost") as smtp:
[Mon Aug 05 09:53:14.582888 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251]   File "/usr/lib64/python3.6/smtplib.py", line 251, in __init__
[Mon Aug 05 09:53:14.582892 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251]     (code, msg) = self.connect(host, port)
[Mon Aug 05 09:53:14.582898 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251]   File "/usr/lib64/python3.6/smtplib.py", line 336, in connect
[Mon Aug 05 09:53:14.582902 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251]     self.sock = self._get_socket(host, port, self.timeout)
[Mon Aug 05 09:53:14.582908 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251]   File "/usr/lib64/python3.6/smtplib.py", line 307, in _get_socket
[Mon Aug 05 09:53:14.582912 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251]     self.source_address)
[Mon Aug 05 09:53:14.582918 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251]   File "/usr/lib64/python3.6/socket.py", line 724, in create_connection
[Mon Aug 05 09:53:14.582922 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251]     raise err
[Mon Aug 05 09:53:14.582928 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251]   File "/usr/lib64/python3.6/socket.py", line 713, in create_connection
[Mon Aug 05 09:53:14.582932 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251]     sock.connect(sa)
[Mon Aug 05 09:53:14.582941 2024] [wsgi:error] [pid 11471] [client 172.21.1.22:48251] ConnectionRefusedError: [Errno 111] Connection refused
[Mon Aug 05 09:53:14.583392 2024] [proxy_ajp:error] [pid 11471] [client 172.21.1.22:48251] AH00877: read zero bytes, expecting 122 bytes
```

### Additional information

both operations were working properly on 2024.05 version.

**Comment by rjmateus** [comment]
Are your clients registered as salt-minion or as traditional clients?

**Comment by mrstfn-sub** [comment]
Traditional Clients.

**Comment by rjmateus** [comment]
more information in here: https://www.uyuni-project.org/doc/2024.07/release-notes-uyuni-server.html#_removal_of_deprecated_functionalities

**Comment by mrstfn-sub** [comment]
Thanks for helping @rjmateus!
