### ISSUE TITLE
mgr-sync Connection timed out

### ISSUE THREAD

**Issue by consocio** [uyuni-project/uyuni#9148]
### Problem description

When I use in mgr-sync via CLI after a while responds with Network error: [Errno 110] Connection timed out. I have tried the following commands: 
mgr-sync refresh
mgr-sync list channels
mgr-sync add debian-12-pool-amd64

I am trying to add Debian 12 but I can’t, it is not shown to me in the web GUI wizard

### Steps to reproduce

1.
2.
3.
...

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2024.07-230900.219.1.uyuni3
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2024.07-230900.219.1.uyuni3.src
Upstream URL   : https://www.uyuni-project.org/
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

**Comment by consocio** [comment]
adding info 
mgr-sync -v -d 3 refresh
Network error: [Errno 110] Connection timed out
Traceback (most recent call last):
  File "/usr/sbin/mgr-sync", line 27, in <module>
    sys.exit(MgrSync().run(options))
  File "/usr/lib/python3.6/site-packages/spacewalk/susemanager/mgr_sync/mgr_sync.py", line 89, in run
    if self.conn.sync.master.hasMaster() and "refresh" not in vars(options):
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1166, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1279, in send_request
    self.send_content(connection, request_body)
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1309, in send_content
    connection.endheaders(request_body)
  File "/usr/lib64/python3.6/http/client.py", line 1286, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1046, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 984, in send
    self.connect()
  File "/usr/lib64/python3.6/http/client.py", line 1444, in connect
    super().connect()
  File "/usr/lib64/python3.6/http/client.py", line 956, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib64/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib64/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

**Comment by mcalmer** [comment]
For Debian 12 please use spacewalk-common-channels command when you use Uyuni.
That command and the Web UI is only working when you have a SUSE Manager Subscription in SCC
