### ISSUE TITLE
mgr_ssl_cert_setup.py authorityKeyIdentifier parse problem

### ISSUE THREAD

**Issue by dfaltum** [uyuni-project/uyuni#9163]
### Problem description

We have a problem with the mgr-ssl-cert-setup script in SUMA5. We want to change the certificates according to this guide: https://documentation.suse.com/suma/5.0/en/suse-manager/administration/ssl-certs-imported.html#_replace_certificates

The problem is that, the script fails with the following stack:

```
2024/08/12 13:41:16 -00:00: /usr/lib/python3.6/site-packages/certs/mgr_ssl_cert_setup.py.processCommandline(117) - ['/usr/bin/mgr-ssl-cert-setup', '-v', '-c', '-r', 'gold.crt', '-i', 'trustev3.crt', '-s', 'cert.crt', '-k', 'key.key']
2024/08/12 13:41:16 -00:00: /usr/lib/python3.6/site-packages/certs/mgr_ssl_cert_setup.py.writeError(715) -
ERROR: 'authorityKeyIdentifier'

2024/08/12 13:41:16 -00:00: /usr/lib/python3.6/site-packages/certs/mgr_ssl_cert_setup.py.writeError(716) - Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/certs/mgr_ssl_cert_setup.py", line 720, in main
    ret = _main() or 0
  File "/usr/lib/python3.6/site-packages/certs/mgr_ssl_cert_setup.py", line 686, in _main
    files_content.server_key,
  File "/usr/lib/python3.6/site-packages/certs/mgr_ssl_cert_setup.py", line 657, in getContainersSetup
    checks(server_key_content, server_cert_content, certData)
  File "/usr/lib/python3.6/site-packages/certs/mgr_ssl_cert_setup.py", line 639, in checks
    checkCompleteCAChain(server_cert_content, certData)
  File "/usr/lib/python3.6/site-packages/certs/mgr_ssl_cert_setup.py", line 421, in checkCompleteCAChain
    issuerKeyId = certData[serverCertHash]["authorityKeyIdentifier"]
KeyError: 'authorityKeyIdentifier'
```

### Steps to reproduce

1. Run mgr-ssl-cert-setup script within the container
2.
3.

### Uyuni version

```bash
suse/manager/5.0/x86_64/server:5.0.0
suse/manager/5.0/x86_64/server@sha256:e3ebcce36e7c67228fdf9cfd12f0c9b2a5502f9bda8cdaeb6a2e8cc17f4ec294
```

### Additional information

The /usr/lib/python3.6/site-packages/certs/mgr_ssl_cert_setup.py python script parses some openssl output. On SLES15SP4 (SUMA4) the openssl 1.1 gives an output like this:
```
openssl x509 -noout -subject -subject_hash -startdate -enddate -issuer -issuer_hash -modulus -ext "subjectKeyIdentifier,authorityKeyIdentifier" -in cert.crt
[...]
    keyid:69:02:D7:4F:EC:56:3F:D0:0C:1B:EB:8A:1D:6B:39:91:B8:C0:0F:52
```
On SLES15SP6 (SUMA5) the openssl 3.1 gives this output:
```
openssl x509 -noout -subject -subject_hash -startdate -enddate -issuer -issuer_hash -modulus -ext "subjectKeyIdentifier,authorityKeyIdentifier" -in cert.crt 
[...]
    69:02:D7:4F:EC:56:3F:D0:0C:1B:EB:8A:1D:6B:39:91:B8:C0:0F:52
```

So in the script we need to parse this line differently.

**Comment by dfaltum** [comment]
Solved with https://github.com/uyuni-project/uyuni/pull/9164
