### ISSUE TITLE
Failed to apply high state; "Error: Could not parse state file. Please check YAML syntax."

### ISSUE THREAD

**Issue by gabjef** [uyuni-project/uyuni#9194]
### Problem description

Failed to apply high state on Oracle Linux 9: `Error: Could not parse state file. Please check YAML syntax.`

### Steps to reproduce

1. Set high state From the GUI or via recurring action

### Uyuni version

```bash
Uyuni server version: 2024.05-230900.217.1.uyuni3
venv-salt-minion: venv-salt-minion-3006.0-32.17.uyuni
```

### Uyuni proxy version (if used)

```bash
N/A
```

### Useful logs

```bash
Error: Could not parse state file. Please check YAML syntax.
|
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/minion.py", line 1917, in _thread_return
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/minion.py", line 1876, in _execute_job_function
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1234, in run
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1249, in _run_as
      File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/executors/venv.py", line 24, in execute
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1234, in run
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1249, in _run_as
      File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/executors/direct_call.py", line 10, in execute
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1234, in run
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1249, in _run_as
      File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/modules/state.py", line 834, in apply_
      File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/modules/state.py", line 1200, in highstate
      File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/modules/state.py", line 103, in _set_retcode
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/context.py", line 78, in __getitem__
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 336, in __getitem__
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/utils/lazy.py", line 105, in __getitem__
    KeyError: 'state.check_result'
```
```


### Additional information

_No response_

**Comment by gabjef** [comment]
**Note that it appears high state _does appear to actually work_ in terms of what is being applied, but Uyuni is seeing a return error.**

**Comment by mcalmer** [comment]
Have you tried again with an up to date version of Uyuni server and venv-salt-minion. I think it could be fixed meanwhile
