### ISSUE TITLE
spacecmd doesn't work after migration to Uyuni container migration

### ISSUE THREAD

**Issue by ppanon2022** [uyuni-project/uyuni#9339]
### Problem description

I don't seem to be able to use spacecmd from within the container context with a config file. After running mgrctl term,

```
uyuni-server:~ # spacecmd
Welcome to spacecmd, a command-line interface to Spacewalk.

Type: 'help' for a list of commands
      'help <cmd>' for command-specific help
      'quit' to quit


ERROR: Failed to connect to http://<server.fqdn>/rpc/api
```

I do see some SELinux errors but they are for SEL context re-labeling, which seems to try to happen as a result of the spacecmd. It's possible it's misreporting the error. With no tcpdump packet capture available, it's not possible to be sure whether it's actually sending a packet or if it's very coarse-grained exception handling. It does take a long time to return the error.

```
/var/log/audit # audit2allow -a


#============= container_init_t ==============

#!!!! This avc is a constraint violation.  You would need to modify the attributes of either the source or target types to allow this access.
#Constraint rule:
#       constrain dir { create relabelfrom relabelto } ((u1 == u2 -Fail-)  or (t1 == can_change_object_identity -Fail-) ); Constraint DENIED

#       Possible cause is the source user (system_u) and target user (unconfined_u) are different.
#       Possible cause is the source level (s0:c303,c621) and target level (s0) are different.
allow container_init_t container_file_t:dir relabelfrom;

#!!!! This avc is a constraint violation.  You would need to modify the attributes of either the source or target types to allow this access.
#Constraint rule:
#       constrain file { create relabelfrom relabelto } ((u1 == u2 -Fail-)  or (t1 == can_change_object_identity -Fail-) ); Constraint DENIED

#       Possible cause is the source user (system_u) and target user (unconfined_u) are different.
#       Possible cause is the source level (s0:c303,c621) and target level (s0) are different.
```

While I could add a policy to allow the relabeling, but that seems like it would significantly reduce the security of the container.

### Steps to reproduce

1. Migrate Uyuni installation to container
2. Recreate spacecmd config file in /root/.spacecmd/config, including server, username, password, and nossl key-value pairs
3. Run spacecmd
...

### Uyuni version

```bash
Running 2024.08 container
```

### Useful logs

```bash
See description
```

**Comment by ppanon2022** [comment]
Attempting to telnet to port 80 on the host FQDN from within the container just hangs. Perhaps some sort of firewall rule, though there seems to be none on the host.

Attempting to use localhost to bypass any firewalling shows a redirect to uyuni-server.mgr.internal, but then trying to connect to uyuni-server.mgr.internal and do a get /pub shows the exact same 301 reply message.

uyuni-server:~ # telnet localhost 80
Trying ::1...
Connected to localhost.
Escape character is '^]'.
GET /pub
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="http://uyuni-server.mgr.internal/pub/">here</a>.</p>
</body></html>
Connection closed by foreign host.

**Comment by agraul** [comment]
It's not a firewall, it's the so-called "hairpin problem". By using the FQDN of the server from within the container, the network packets go container -> host -> container. This back-and-forth is the problem. 

Inside the container `localhost` should be used instead of the FQDN.

**Comment by ppanon2022** [comment]
localhost doesn't work for me either. You can see the results to that and using telnet to test the HTTP response for more detail in 
 [these replies](https://github.com/uyuni-project/uyuni/discussions/8816#discussioncomment-10902153) to the migration Github discussion

**Comment by ppanon2022** [comment]
Here's a thought that occurred to me and perhaps you can confirm if it could be an issue. We have two Uyuni servers. On one of them I set up sssd AD integration on the host Linux, and that's the one where connecting to localhost/loopback URLs from the container context fails. On the other system, the container localhost connections work, but trying to run the host sssd AD connection fails. Could there be a conflict somehow, where maybe sssd on the first server host is locking up some network resources and prevented the container from deploying properly somehow, and where the container being deployed correctly in the second case is somehow preventing sssd from running in that host?

If so, would disabling/purging sssd on the first host prior to upgrading the container to 2024.10 allow podman to fix the localhost network issue when deploying the update? What sort of interaction would be happening and is a container update close enough to a deployment that it could fix whatever may be broken for the localhost connections with the Uyuni 2024.08 server container deployment?

**Comment by ppanon2022** [comment]
Tried to upgrade to 2024.10 after removing the sssd packages from the host and got this error
# mgradm upgrade podman
12:04PM INF Welcome to mgradm
12:04PM INF Executing command: podman
12:04PM INF Computed image name is registry.opensuse.org/uyuni/server:latest
12:04PM INF Pull Policy is always. Presence of RPM image will be checked and if it's not present it will be pulled from registry
12:04PM INF Cannot find RPM image for registry.opensuse.org/uyuni/server:latest
12:04PM INF Running podman pull registry.opensuse.org/uyuni/server:latest
Trying to pull registry.opensuse.org/uyuni/server:latest...
Getting image source signatures
Copying blob a344d7b096ee done   |
Copying blob 642e3fc0d4ca done   |
Copying blob ba4705fe3f3b done   |
Copying config d78bb09cff done   |
Writing manifest to image destination
d78bb09cff782bfdae5724c727fac4393f5560b21cc437a26c30357cc5fb3e03
Error: cannot inspect podman values: cannot inspect data: cannot read config: While parsing config: line `carmd-nv-uyuni1.sierrawireless.local` doesn't match format

What config file would that come from and how could it not be correct? It seems like a pretty standard/legal hostname format.

**Comment by digdilem-work** [comment]
This may be a fix:  https://github.com/uyuni-project/uyuni/issues/9348#issuecomment-2437880738

**Comment by aric89** [comment]
I think this is related to my issue as well. It seems to me I'm getting a Cobbler config issue which isn't allowing taskomatic to get a CobblerToken.

This is from the rhn_taskomatic_daemon.log

> 2024-10-25 17:00:00,166 [DefaultQuartzScheduler_Worker-9] ERROR com.redhat.rhn.taskomatic.task.CobblerSyncTask - RuntimeExceptionError trying to sync to cobbler: We had an error trying to login.
com.redhat.rhn.manager.kickstart.cobbler.NoCobblerTokenException: We had an error trying to login.
        at com.redhat.rhn.manager.kickstart.cobbler.CobblerLoginCommand.login(CobblerLoginCommand.java:57) ~[rhn.jar:?]
        at com.redhat.rhn.frontend.integration.IntegrationService.authorize(IntegrationService.java:115) ~[rhn.jar:?]
        at com.redhat.rhn.frontend.integration.IntegrationService.getAuthToken(IntegrationService.java:69) ~[rhn.jar:?]
        at com.redhat.rhn.manager.kickstart.cobbler.CobblerCommand.<init>(CobblerCommand.java:61) ~[rhn.jar:?]
        at com.redhat.rhn.manager.kickstart.cobbler.CobblerCommand.<init>(CobblerCommand.java:82) ~[rhn.jar:?]
        at com.redhat.rhn.manager.kickstart.cobbler.CobblerDistroSyncCommand.<init>(CobblerDistroSyncCommand.java:48) ~[rhn.jar:?]
        at com.redhat.rhn.taskomatic.task.CobblerSyncTask.execute(CobblerSyncTask.java:85) ~[rhn.jar:?]
        at com.redhat.rhn.taskomatic.task.RhnJavaJob.execute(RhnJavaJob.java:56) ~[rhn.jar:?]
        at com.redhat.rhn.taskomatic.TaskoJob.doExecute(TaskoJob.java:240) ~[rhn.jar:?]
        at com.redhat.rhn.taskomatic.TaskoJob.runTemplate(TaskoJob.java:193) ~[rhn.jar:?]
        at com.redhat.rhn.taskomatic.TaskoJob.execute(TaskoJob.java:145) ~[rhn.jar:?]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.3.0.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) ~[quartz-2.3.0.jar:?]
Caused by: redstone.xmlrpc.XmlRpcFault: <class 'cobbler.cexceptions.CX'>:'login failed (taskomatic_user)'
        at redstone.xmlrpc.XmlRpcClient.handleResponse(XmlRpcClient.java:444) ~[redstone-xmlrpc-client-1.1_20071120.jar:?]
        at redstone.xmlrpc.XmlRpcClient.endCall(XmlRpcClient.java:376) ~[redstone-xmlrpc-client-1.1_20071120.jar:?]
        at redstone.xmlrpc.XmlRpcClient.invoke(XmlRpcClient.java:165) ~[redstone-xmlrpc-client-1.1_20071120.jar:?]
        at com.redhat.rhn.manager.kickstart.cobbler.CobblerXMLRPCHelper.invokeMethod(CobblerXMLRPCHelper.java:70) ~[rhn.jar:?]
        at com.redhat.rhn.manager.kickstart.cobbler.CobblerLoginCommand.login(CobblerLoginCommand.java:52) ~[rhn.jar:?]
        ... 12 more
2024-10-25 17:00:00,166 [DefaultQuartzScheduler_Worker-9] ERROR com.redhat.rhn.taskomatic.task.CobblerSyncTask - re-throwing exception since we havent yet.
2024-10-25 17:00:00,167 [DefaultQuartzScheduler_Worker-9] ERROR com.redhat.rhn.taskomatic.task.CobblerSyncTask - Executing a task threw an exception: com.redhat.rhn.manager.kickstart.cobbler.NoCobblerTokenException
com.redhat.rhn.manager.kickstart.cobbler.NoCobblerTokenException: We had an error trying to login.
        at com.redhat.rhn.manager.kickstart.cobbler.CobblerLoginCommand.login(CobblerLoginCommand.java:57) ~[rhn.jar:?]
        at com.redhat.rhn.frontend.integration.IntegrationService.authorize(IntegrationService.java:115) ~[rhn.jar:?]
        at com.redhat.rhn.frontend.integration.IntegrationService.getAuthToken(IntegrationService.java:69) ~[rhn.jar:?]
        at com.redhat.rhn.manager.kickstart.cobbler.CobblerCommand.<init>(CobblerCommand.java:61) ~[rhn.jar:?]
        at com.redhat.rhn.manager.kickstart.cobbler.CobblerCommand.<init>(CobblerCommand.java:82) ~[rhn.jar:?]
        at com.redhat.rhn.manager.kickstart.cobbler.CobblerDistroSyncCommand.<init>(CobblerDistroSyncCommand.java:48) ~[rhn.jar:?]
        at com.redhat.rhn.taskomatic.task.CobblerSyncTask.execute(CobblerSyncTask.java:85) ~[rhn.jar:?]
        at com.redhat.rhn.taskomatic.task.RhnJavaJob.execute(RhnJavaJob.java:56) ~[rhn.jar:?]
        at com.redhat.rhn.taskomatic.TaskoJob.doExecute(TaskoJob.java:240) ~[rhn.jar:?]
        at com.redhat.rhn.taskomatic.TaskoJob.runTemplate(TaskoJob.java:193) ~[rhn.jar:?]
        at com.redhat.rhn.taskomatic.TaskoJob.execute(TaskoJob.java:145) ~[rhn.jar:?]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.3.0.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) ~[quartz-2.3.0.jar:?]
Caused by: redstone.xmlrpc.XmlRpcFault: <class 'cobbler.cexceptions.CX'>:'login failed (taskomatic_user)'
        at redstone.xmlrpc.XmlRpcClient.handleResponse(XmlRpcClient.java:444) ~[redstone-xmlrpc-client-1.1_20071120.jar:?]
        at redstone.xmlrpc.XmlRpcClient.endCall(XmlRpcClient.java:376) ~[redstone-xmlrpc-client-1.1_20071120.jar:?]
        at redstone.xmlrpc.XmlRpcClient.invoke(XmlRpcClient.java:165) ~[redstone-xmlrpc-client-1.1_20071120.jar:?]
        at com.redhat.rhn.manager.kickstart.cobbler.CobblerXMLRPCHelper.invokeMethod(CobblerXMLRPCHelper.java:70) ~[rhn.jar:?]
        at com.redhat.rhn.manager.kickstart.cobbler.CobblerLoginCommand.login(CobblerLoginCommand.java:52) ~[rhn.jar:?]
        ... 12 more

**Comment by ppanon2022** [comment]
> This may be a fix: [#9348 (comment)](https://github.com/uyuni-project/uyuni/issues/9348#issuecomment-2437880738)

That was certainly a problem. Thank you very much for the pointer. After deleting the duplicate java.hostname and re-running the mgradm upgrade podman, I got much farther. I also got a lot of collation mismatch errors on the database portion of the upgrade.

```
2024-10-25 17:02:39.795 PDT   [50]LOG:  redirecting log output to logging collector process
2024-10-25 17:02:39.795 PDT   [50]HINT:  Future log output will appear in directory "log".
Schema update...
WARNING:  database "uyuni" has a collation version mismatch
DETAIL:  The database was created using collation version 2.31, but the operating system provides version 2.38.
HINT:  Rebuild all objects in this database that use the default collation and run ALTER DATABASE uyuni REFRESH COLLATION VERSION, or build PostgreSQL with the right library version.
report_db_host = localhost
WARNING:  database "reportdb" has a collation version mismatch
DETAIL:  The database was created using collation version 2.31, but the operating system provides version 2.38.
HINT:  Rebuild all objects in this database that use the default collation and run ALTER DATABASE reportdb REFRESH COLLATION VERSION, or build PostgreSQL with the right library version.
WARNING:  database "uyuni" has a collation version mismatch
...
INSERT 0 0
Stopping Postgresql...
```

I ran 
su postgresql
psql uyuni
REINDEX DATABASE uyuni;
ALTER DATABASE uyuni REFRESH COLLATION VERSION;
\c reportdb
REINDEX DATABASE reportdb;
ALTER DATABASE reportdb REFRESH COLLATION VERSION;

which should address that.
and then exited and reconnected to the reportdb database to do the same to that database.

**Comment by ppanon2022** [comment]
> I think this is related to my issue as well. It seems to me I'm getting a Cobbler config issue which isn't allowing taskomatic to get a CobblerToken.
> 
I agree, We're also seeing that, with the side effect that deleting and adding/registering systems doesn't work because the cobbler call fails. So this is a pretty serious issue because it breaks important functionality.

**Comment by aric89** [comment]
Has anyone heard any updates on this issue? I've had to decommission a few servers, and I'm not able to clean them up because of this bug.

**Comment by ppanon2022** [comment]
> Has anyone heard any updates on this issue? I've had to decommission a few servers, and I'm not able to clean them up because of this bug.

We've basically had to give up on this issue. We've got two Uyuni servers, with one affected and one not, and we're moving everything to the working one. 

My best guess at this point - even though there are no SELinux errors in the security log - is that it's an issue with either SELinux file settings or with cgroups. The server that isn't working was our first migrated one, and went through a couple of different aborted and deinstalled migrations before one appeared to succeed.

If that is the problem, then without knowing what exactly is the problem, the only solution I can think of is to do a DR type recovery, recovering the database and anything else from backups then letting the repos repopulate. It's not worth it to us to do so and easier to consolidate into the one server.

**Comment by aric89** [comment]
@digdilem-work @ppanon2022 

I've been troubleshooting this since last week and I've made some headway. I had to recreate the self-signed certificates for Uyuni to include the cnames for the containers. Once I did that I changed the spacecmd config to nossl=false which then allowed me to login with spacecmd inside the container. Also, I was able to test the /rpc/api with the curl command to verify that Apache was redirecting properly.

`curl -u username:password -Sks https://uyuni-server/rpc/api`

Also, I had to fix errors with Apache using httpd -t which I'm not sure were related or just info errors. For some reason, my Apache modules weren't loading correctly so I specified them in my httpd.conf as a global setting.

https://www.uyuni-project.org/uyuni-docs/en/uyuni/administration/ssl-certs-selfsigned.html

Ran this on the host against the container using mgrctl.

`mgrctl exec -ti -- rhn-ssl-tool --gen-server --dir="/root/ssl-build" --set-country="COUNTRY" \
--set-state="STATE" --set-city="CITY" --set-org="ORGANIZATION" \
--set-org-unit="ORGANIZATION UNIT" --set-email="name@example.com" \
--set-hostname="HOSTNAME FQDN" --set-cname="uyuni-server.mgr.internal" --set-cname="uyuni-server"`

This created a new directory under /root/ssl-build/%hostname%/

I copied the server.crt and server.key to /etc/pki/tls/certs/ and /etc/pki/tls/private respectively. Then I renamed the old spacewalk.crt and key to .bak and renamed the new server.crt & key to spacewalk.crt and spacewalk.key. Restarted Apache which loaded the new certificate. Once this was completed I was able to connect with Spacecmd as I mentioned in the first paragraph.



Unfortunately, this didn't fix my original issue of deleting servers/systems from the Web UI.

**Comment by aric89** [comment]
Following up on my last comment. After updating the certificate, I was able to get the Web UI to delete the servers!

I had to update the cobbler settings config from http://localhost to https://uyuni-server.

`vi /etc/cobbler/settings.yaml`

Update uyuni_authentication_endpoint: to https://uyuni-server

like so

`uyuni_authentication_endpoint: https://uyuni-server`

Run "cobbler check"

Restart Cobblerd "systemctl restart cobblerd"

Run "cobbler sync".

**Comment by ZsBT** [comment]
This is still the case with 2025.07, due to hairpin the container cannot reach the host on tcp/443. Using https://localhost obviously does not work as not included in cert AltName. Adding the FQDN to the host file is just a temporary solution, reboot overwrites the host file.

**Comment by aric89** [comment]
@ZsBT Did you try https://uyuni-server like in the comment up above?

**Comment by ZsBT** [comment]
> [@ZsBT](https://github.com/ZsBT) Did you try https://uyuni-server like in the comment up above?

sure; however as mentioned, the cert AltName does not have that AltName therefore spacecmd (and also curl) fails.
```
uyuni-server:~ # spacecmd user_list
ERROR: Failed to connect to https://uyuni-server/rpc/api
```

My workaround was to fall back to http and localhost in the ini file:

```
[spacecmd]
server=localhost
nossl=true
(...)
````

But of course this works in the uyuni-server container only.
