### ISSUE TITLE
mgr-websockify.service fails to start

### ISSUE THREAD

**Issue by juliogonzalez** [uyuni-project/uyuni#953]
Using master packages (Leap 15.0 as base OS):
```
● mgr-websockify.service - TCP to WebSocket proxy
   Loaded: loaded (/usr/lib/systemd/system/mgr-websockify.service; static; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2019-05-10 11:25:51 CEST; 2min 32s ago
  Process: 8831 ExecStart=/usr/bin/websockify --token-plugin JWTTokenApi --token-source /etc/rhn/websockify.key --cert /etc/apache2/ssl.crt/server.crt --key /etc/pki/tls/private/spacewalk.key 8050 (code=exited, status=1/FAILURE)
  Process: 8811 ExecStartPre=/usr/bin/sh -c grep secret_key /etc/rhn/rhn.conf | tr -d ' ' | cut -f2 -d '=' | perl -ne 's/([0-9a-f]{2})/print chr hex $1/gie' > /etc/rhn/websockify.key (code=exited, status=0/SUCCESS)
 Main PID: 8831 (code=exited, status=1/FAILURE)
```
It is not a problem with the certificates and keys:
```
uyuni-server:~ # ls /etc/rhn/websockify.key
/etc/rhn/websockify.key
uyuni-server:~ # ls /etc/apache2/ssl.crt/server.crt
/etc/apache2/ssl.crt/server.crt
uyuni-server:~ # ls /etc/pki/tls/private/spacewalk.key
/etc/pki/tls/private/spacewalk.key
```
But a problem with the python code:
```
uyuni-server:~ # /usr/bin/websockify --token-plugin JWTTokenApi --token-source /etc/rhn/websockify.key --cert /etc/apache2/ssl.crt/server.crt --key /etc/pki/tls/private/spacewalk.key 8050
Traceback (most recent call last):
  File "/usr/bin/websockify", line 11, in <module>
    load_entry_point('websockify==0.8.0', 'console_scripts', 'websockify')()
  File "/usr/lib/python3.6/site-packages/websockify/websocketproxy.py", line 511, in websockify_init
    token_plugin_cls = getattr(sys.modules[token_plugin_module], token_plugin_cls)
AttributeError: module 'websockify.token_plugins' has no attribute 'JWTTokenApi'
```
I can't reproduce when the base is SLE15SP1 and we use the packages from Devel:Galaxy:Manager:Head:
```● mgr-websockify.service - TCP to WebSocket proxy
   Loaded: loaded (/usr/lib/systemd/system/mgr-websockify.service; static; vendor preset: disabled)
   Active: active (running) since Thu 2019-05-09 23:58:45 CEST; 11h ago
 Main PID: 7770 (websockify)
    Tasks: 2 (limit: 4915)
   CGroup: /system.slice/mgr-websockify.service
           └─7770 /usr/bin/python3 /usr/bin/websockify --token-plugin JWTTokenApi --token-source /etc/rhn/websockify.key --cert /etc/apache2/ssl.crt/server.crt --key /etc/pki/tls/private/spacewalk.key 8050
```

**Comment by cbosdo** [comment]
The JWT patches for websockify have only been added to 15.1.

**Comment by juliogonzalez** [comment]
@cbosdo maybe you can submit them for 15.0 as well?

**Comment by juliogonzalez** [comment]
After talking to @cbosdo we decided to switch to 15.1 as next base OS for Uyuni.

https://en.opensuse.org/openSUSE:Roadmap

> openSUSE Leap 15.1 is planned to be released in May 2019, based on SLE 15 SP1.
