### ISSUE TITLE
AppStream duplicates in database prevent fetching list of stream's packages

### ISSUE THREAD

**Issue by santeri3700** [uyuni-project/uyuni#9538]
### Problem description
Accessing list of packages for certain AppStream module streams results in Error 500 when the database contains multiple AppStream IDs/rows for the same module and stream.

I have two independent Uyuni Servers with same Uyuni versions and channel, repository and reposync configurations. Both of them have the exact same AppStream modules corrupted while some are completely OK. The corruption seems to be specific to the streams so a module may have 2/3 of its streams corrupted while one is OK (e.g. container-tools or nodejs in my case).

I suspect this bug is related to some issues I've faced with installing/upgrading certain modular packages via Uyuni without CLM flattening. I don't have enough information about this yet but will provide it later when I've done more investigation on that part.

### Steps to reproduce
Not sure, but the two independent servers have been daily syncing the AlmaLinux AppStream repositories since before the new AppStream support was added.

An obvious way to see if any of the available streams are corrupted is to go to System -> Software -> AppStreams and try to click every link in the Streams column to see if you get error message "An error occurred while displaying the list of packages.".

The Web UI makes a GET request to "https://uyuni.server.fqdn/rhn/manager/api/appstreams/CHANNEL_ID/MODULE_NAME:STREAM_NAME/packages" which can also be manually accessed with a web browser or cURL (with authentication).

NOTE: The AppStreams tab is only visible on Systems which have been subscribed to a modular channel.

### Uyuni version
Both servers have originally been running the RPM version since 2022 and migrated from 2024.08 (RPM) to 2024.10 (Podman).
```
Repository     : @System
Name           : Uyuni-Server-release
Version        : 2024.10-241000.224.1.uyuni5
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : unknown
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2024.10-241000.224.1.uyuni5.src
```
```
# podman image inspect --format '{{.Id}}' 'registry.opensuse.org/uyuni/server'
d78bb09cff782bfdae5724c727fac4393f5560b21cc437a26c30357cc5fb3e03
```

### Useful logs

The following exception appears to rhn_web_api.log when trying to list packages in a corrupted stream from the Web UI. The result number matches the count of unique `suseappstream.id` values in the database per the module and stream.
```
[ajp-nio-0:0:0:0:0:0:0:1-8009-exec-139] ERROR spark.http.matching.GeneralError - 
org.hibernate.NonUniqueResultException: query did not return a unique result: 3
        at org.hibernate.query.internal.AbstractProducedQuery.uniqueElement(AbstractProducedQuery.java:1633) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
        at org.hibernate.query.internal.AbstractProducedQuery.uniqueResult(AbstractProducedQuery.java:1608) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
        at org.hibernate.query.criteria.internal.compile.CriteriaQueryTypeQueryAdapter.uniqueResult(CriteriaQueryTypeQueryAdapter.java:79) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
        at com.redhat.rhn.manager.appstreams.AppStreamsManager.findAppStream(AppStreamsManager.java:174) ~[rhn.jar:?]
        at com.suse.manager.webui.controllers.appstreams.AppStreamsController.getPackagesInModule(AppStreamsController.java:174) ~[rhn.jar:?]
        ...
```

### Additional information

Here are some comparisons from the two independent Uyuni Servers and their Appstream corruptions.

#### AlmaLinux 8 AppStream
- 389-ds:1.4 = **Corrupted** on both servers
- ant:1.10 = OK (both servers)
- container-tools:1.0 = OK (both servers)
- container-tools:2.0 = OK (both servers)
- container-tools:3.0 = OK (both servers)
- container-tools:4.0 = **Corrupted** on both servers
- container-tools:rhel8 = **Corrupted** on both servers
- maven:3.5 = OK (both servers)
- maven:3.6 = OK (both servers)
- maven:3.8 = OK (both servers)
(there are more but I'm too lazy to check)

#### AlmaLinux 9 AppStream
- maven:3.8 = OK (both servers)
- mariadb:10.11 = OK (both servers)
- nodejs:22 = OK (both servers)
- nodejs:20 = **Corrupted** on both servers
- nodejs:18 = **Corrupted** on both servers
- nginx:1.24 = **Corrupted** on both servers
- nginx:1.22 = **Corrupted** on both servers
- postgresql:16 = **Corrupted** on both servers
- postgresql:15 = **Corrupted** on both servers
- redis:7 = OK (both servers)
- ruby:3.3 = **Corrupted** on both servers
- ruby:3.1 = **Corrupted** on both servers

Here are some in-depth examples of OK and corrupted AppStream modules from the database.

#### Working AppStream module `mariadb:10.11` (found just one AppStream ID) in channel ID 291 (AlmaLinux 9 AppStream):
```
uyuni-server:/ # echo "SELECT * FROM suseappstream WHERE suseappstream.channel_id = 291 AND suseappstream.name = 'mariadb' AND suseappstream.stream = '10.11';" | spacewalk-sql --select-mode -

 id | channel_id |  name   | stream |       version       | context  |  arch  |            created            |           modified            
----+------------+---------+--------+---------------------+----------+--------+-------------------------------+-------------------------------
  1 |        291 | mariadb | 10.11  | 9040020240409185951 | 8cf767d6 | x86_64 | 2024-08-22 06:01:15.168098+00 | 2024-08-22 06:01:15.168098+00
(1 row)
```

#### Corrupted AppStream module `nginx:1.22` (found three different AppStream IDs) in channel ID 291 (AlmaLinux 9 AppStream):
```
uyuni-server:/ # echo "SELECT * FROM suseappstream WHERE suseappstream.channel_id = 291 AND suseappstream.name = 'nginx' AND suseappstream.stream = '1.22';" | spacewalk-sql --select-mode -

  id   | channel_id | name  | stream |       version       | context  |  arch  |            created            |           modified            
-------+------------+-------+--------+---------------------+----------+--------+-------------------------------+-------------------------------
 31791 |        291 | nginx | 1.22   | 9050020241004144401 | 8cf767d6 | x86_64 | 2024-11-19 07:03:05.745665+00 | 2024-11-19 07:03:05.745665+00
     3 |        291 | nginx | 1.22   | 9030020231108083939 | 8cf767d6 | x86_64 | 2024-08-22 06:01:15.168098+00 | 2024-08-22 06:01:15.168098+00
     4 |        291 | nginx | 1.22   | 9040020240724153833 | 8cf767d6 | x86_64 | 2024-08-22 06:01:15.168098+00 | 2024-08-22 06:01:15.168098+00
(3 rows)
```

I'll gladly provide more details and partial database dumps. I'm not sure what kind of information would be useful so please provide tips or queries for me to execute.

**Comment by santeri3700** [comment]
Great! Thanks for the fix and info. I'll wait for the next release and close this issue after confirming everything works as expected.
