### ISSUE TITLE
Uyuni should work without SCC credentials

### ISSUE THREAD

**Issue by juliogonzalez** [uyuni-project/uyuni#955]
Using master and Leap15.0, and launching mgr-sync-refresh without adding SCC credentials:
```
2019-05-10 12:28:18,043 [DefaultQuartzScheduler_Worker-8] ERROR com.redhat.rhn.taskomatic.task.MgrSyncRefresh - Error during mgr-sync refresh
com.redhat.rhn.manager.content.ContentSyncException: No SCC credentials found.
        at com.redhat.rhn.manager.content.ContentSyncManager.filterCredentials(ContentSyncManager.java:227)
        at com.redhat.rhn.manager.content.ContentSyncManager.getProducts(ContentSyncManager.java:241)
        at com.redhat.rhn.taskomatic.task.MgrSyncRefresh.execute(MgrSyncRefresh.java:97)
        at com.redhat.rhn.taskomatic.task.RhnJavaJob.execute(RhnJavaJob.java:88)
        at com.redhat.rhn.taskomatic.TaskoJob.execute(TaskoJob.java:199)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
```
Having Uyuni users without SUSE subscriptions is a valid scenario.

As a workaround until this is fixed, creating a SCC account without subscriptions should fix the issue.

**Comment by juliogonzalez** [comment]
This is maybe invalid.

It seems mgr-sync only works for SCC channels

Not really clear at the doc, but at https://opensource.suse.com/doc-susemanager/suse-manager/beta3/reference/admin/task-schedules.html I see:

> mgr-sync-refresh-default:
> the default time at which the start of synchronization with SUSE Customer Center (SCC) takes place (mgr-sync-refresh).

**Comment by juliogonzalez** [comment]
Closing this, and opening a bugzilla issue.

mgr-sync is not verbose in any case: it doesn't show that the process started when there are SCC credentials, it doesn't show it failed if there are not.
